import{listEvents,getEvent,saveEvent,deleteEvent,clearAllEvents,loadSettings,saveSettings}from'./storage.js';
import{sha256,stableStringify,deriveRoundSeed,seededShuffle}from'./crypto-utils.js';
import{normalizeParticipant,validateParticipants,parsePastedTable,digitCountFor,digitLabels,eligibleParticipants}from'./participants.js';
import{lockParticipantList,finalizeShuffle,verifyMapping}from'./shuffle-engine.js';

const XLSX_URL='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const refs={main:$('#mainView'),eventList:$('#eventList'),raceStage:$('#raceStage'),canvas:$('#raceCanvas'),digitSlots:$('#digitSlots'),raceRoundLabel:$('#raceRoundLabel'),raceCandidateInfo:$('#raceCandidateInfo'),raceCountdown:$('#raceCountdown'),raceWinner:$('#raceWinner'),raceRanking:$('#raceRanking'),raceStatus:$('#raceStatus'),startDigitBtn:$('#startDigitBtn'),resetSequenceBtn:$('#resetSequenceBtn'),toast:$('#toast')};
let events=[],current=null,currentView='overview',settings=loadSettings(),raceEngine=null,RaceEngineClass=null,toastTimer=null,shuffleTimer=null,raceMode='demo',raceAttempt=0;

init().catch(showError);
async function init(){
  bindGlobal();events=await listEvents();
  if(!events.length){current=createEvent('Sự kiện mẫu');current.participants=sampleParticipants(30);await saveEvent(current);events=[current]}
  const target=settings.lastEventId&&events.find(e=>e.id===settings.lastEventId);current=target||events[0];
  settings.lastEventId=current.id;saveSettings(settings);renderAll();
}
function bindGlobal(){
  $('#closeDrawBtn').onclick=closeToKanban;$('#exitRaceBtn').onclick=closeRaceStage;$('#newEventBtn').onclick=createNewEvent;
  $('#settingsBtn').onclick=()=>{$('#qualitySelect').value=settings.quality;$('#volumeInput').value=settings.volume;$('#settingsDialog').showModal()};
  $('#qualitySelect').onchange=e=>{settings.quality=e.target.value;saveSettings(settings)};$('#volumeInput').oninput=e=>{settings.volume=+e.target.value;saveSettings(settings);if(raceEngine)raceEngine.volume=settings.volume};
  $('#soundBtn').onclick=toggleSound;$('#raceSoundBtn').onclick=toggleSound;$('#fullscreenBtn').onclick=toggleFullscreen;
  $('#deleteDrawDataBtn').onclick=deleteAllDrawData;$('#startDigitBtn').onclick=runNextDigit;$('#resetSequenceBtn').onclick=resetSequence;
  $$('.md-nav button').forEach(btn=>btn.onclick=()=>{currentView=btn.dataset.view;renderAll()});
  window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!refs.raceStage.hidden)closeRaceStage()});
}
function createEvent(name='Sự kiện mới'){
  const now=new Date().toISOString();return{id:`event_${crypto.randomUUID?.()||Date.now()}`,name,createdAt:now,updatedAt:now,status:'draft',participants:[],digitCountManual:null,digitCount:1,shuffleCount:0,mapping:[],rounds:[],attempts:[],results:[],excludedParticipantIds:[],allowRepeatWinner:false,prizeName:'Giải may mắn',prizeDepartments:[],contributorSeed:'',trackVersion:'marblie-track-v1',physicsVersion:'rapier-0.19.3',gameVersion:'1.0.0'};
}
async function createNewEvent(){
  const name=prompt('Tên sự kiện mới:','Bốc thăm may mắn');if(!name?.trim())return;current=createEvent(name.trim());await saveEvent(current);events=await listEvents();settings.lastEventId=current.id;saveSettings(settings);currentView='overview';renderAll();
}
function sampleParticipants(count){return Array.from({length:count},(_,i)=>normalizeParticipant({'Mã người tham dự':`NV${String(i+1).padStart(3,'0')}`,'Họ và tên':`Người tham dự ${i+1}`,'Phòng ban':`Phòng ${(i%5)+1}`,'Đủ điều kiện tham gia':'Có'},i));}
function renderAll(){renderEventList();renderNav();renderView();syncSoundButtons()}
function renderEventList(){refs.eventList.innerHTML=events.map(e=>`<button class="md-event-item ${e.id===current?.id?'active':''}" data-id="${esc(e.id)}"><span><strong>${esc(e.name)}</strong><small>${statusLabel(e.status)} · ${(e.participants||[]).length} người</small></span><span>›</span></button>`).join('');refs.eventList.querySelectorAll('button').forEach(b=>b.onclick=async()=>{current=await getEvent(b.dataset.id);settings.lastEventId=current.id;saveSettings(settings);renderAll()})}
function renderNav(){$$('.md-nav button').forEach(btn=>btn.classList.toggle('active',btn.dataset.view===currentView))}
function renderView(){if(!current){refs.main.innerHTML='<div class="md-card">Chưa có sự kiện.</div>';return}const fn={overview:renderOverview,participants:renderParticipants,shuffle:renderShuffle,race:renderRace,results:renderResults,verify:renderVerify}[currentView]||renderOverview;fn()}
function head(title,desc,actions=''){return`<div class="view-head"><div><div class="md-eyebrow">${esc(current.name)}</div><h2>${title}</h2><p>${desc}</p></div><div class="view-actions">${actions}</div></div>`}
function renderOverview(){
  const eligible=eligibleParticipants(current).length;const validation=validateParticipants(current.participants||[]);
  refs.main.innerHTML=head('Tổng quan sự kiện','Chuẩn bị danh sách, khóa dữ liệu, xáo chính thức rồi mới chạy đường đua.',`<button id="saveOverview" class="md-primary-btn">Lưu thông tin</button><button id="deleteEvent" class="md-danger-btn">Xóa sự kiện</button>`)+`
  <div class="md-grid">
    <section class="md-card half"><h3>Thông tin sự kiện</h3><div class="md-form-grid"><label class="md-field"><span>Tên sự kiện</span><input id="eventName" value="${escAttr(current.name)}"></label><label class="md-field"><span>Tên giải hiện tại</span><input id="prizeName" value="${escAttr(current.prizeName||'Giải may mắn')}"></label><label class="md-field"><span>Số chữ số</span><select id="digitCount"><option value="auto">Tự động</option>${[1,2,3,4,5,6].map(n=>`<option value="${n}" ${current.digitCountManual===n?'selected':''}>${n} chữ số</option>`).join('')}</select></label></div><label class="md-field" style="margin-top:10px"><span>Phòng ban được tham gia giải (ngăn cách bằng dấu phẩy; để trống = tất cả)</span><input id="prizeDepartments" value="${escAttr((current.prizeDepartments||[]).join(', '))}" placeholder="Ví dụ: Kế toán, Nhân sự"></label><label class="md-field" style="margin-top:10px"><span>Chuỗi đóng góp từ người tham dự (không bắt buộc)</span><input id="contributorSeed" value="${escAttr(current.contributorSeed||'')}" placeholder="Có thể ghép ba chuỗi do ba người nhập"></label><label style="display:flex;gap:8px;margin-top:12px"><input id="allowRepeat" type="checkbox" ${current.allowRepeatWinner?'checked':''}> Cho phép một người trúng nhiều giải</label></section>
    <section class="md-card half"><h3>Trạng thái</h3><div class="status-pill ${current.status==='draft'?'warn':''}">${statusLabel(current.status)}</div><p>Danh sách hợp lệ: <strong>${validation.eligibleCount}</strong> / ${validation.total}. Mã bốc thăm dự kiến dùng <strong>${current.digitCountManual||digitCountFor(Math.max(1,eligible))}</strong> chữ số, quay từ hàng cao nhất xuống hàng thấp nhất.</p>${current.participantListHash?`<div class="hash-box">SHA-256 danh sách: ${current.participantListHash}</div>`:''}</section>
    <section class="md-card third"><div class="stat">${eligible}</div><p>Người đủ điều kiện</p></section><section class="md-card third"><div class="stat">${current.shuffleCount||0}</div><p>Lần bấm xáo chính thức</p></section><section class="md-card third"><div class="stat">${current.results?.length||0}</div><p>Kết quả đã công bố</p></section>
    <section class="md-card"><h3>Quy trình minh bạch</h3><p>Danh sách được hash trước khi xáo. Người quản trò có thể bấm xáo nhiều lần để trình diễn, nhưng mapping chính thức chỉ được tạo một lần khi bấm <strong>Khóa kết quả xáo</strong>. Cuộc đua dùng 10 viên giống nhau và cảm biến đích xác định chữ số thắng.</p></section>
  </div>`;
  $('#saveOverview').onclick=async()=>{const oldContributor=current.contributorSeed||'',oldDigits=current.digitCountManual;current.name=$('#eventName').value.trim()||'Sự kiện';current.prizeName=$('#prizeName').value.trim()||'Giải may mắn';current.prizeDepartments=$('#prizeDepartments').value.split(',').map(x=>x.trim()).filter(Boolean);current.digitCountManual=$('#digitCount').value==='auto'?null:+$('#digitCount').value;current.contributorSeed=$('#contributorSeed').value.trim();current.allowRepeatWinner=$('#allowRepeat').checked;if((oldContributor!==current.contributorSeed||oldDigits!==current.digitCountManual)&&current.status!=='draft')invalidateOfficialData();await persist('Đã lưu thông tin sự kiện.')};
  $('#deleteEvent').onclick=async()=>{if(!confirm(`Xóa sự kiện “${current.name}”? Dữ liệu Kanban không bị ảnh hưởng.`))return;await deleteEvent(current.id);events=await listEvents();current=events[0]||createEvent();if(!events.length){await saveEvent(current);events=[current]}renderAll()};
}
function renderParticipants(){
  const validation=validateParticipants(current.participants||[]);const locked=['list_locked','shuffled','ready','running','completed'].includes(current.status);
  refs.main.innerHTML=head('Người tham dự','Tải Excel mẫu, upload danh sách hoặc dán trực tiếp từ Excel.',`<a class="md-secondary-btn" href="samples/Danh_sach_nguoi_tham_du_mau.xlsx" download>Tải Excel mẫu</a><button id="validateBtn" class="md-secondary-btn">Kiểm tra dữ liệu</button>${locked?'<button id="unlockListBtn" class="md-danger-btn">Mở khóa danh sách</button>':'<button id="lockListBtn" class="md-primary-btn">Khóa danh sách</button>'}`)+`
  <div class="md-grid"><section class="md-card half"><h3>Nhập bằng Excel/CSV</h3><label class="dropzone" id="participantDrop" ${locked?'aria-disabled="true" style="opacity:.55;pointer-events:none"':''}><strong>Browse hoặc kéo thả Excel/CSV</strong><span>XLSX, XLS, XLSM hoặc CSV. Tệp không được tải lên máy chủ.</span><input id="participantFile" type="file" accept=".xlsx,.xls,.xlsm,.csv" hidden></label></section>
  <section class="md-card half"><h3>Nhập hoặc dán trực tiếp</h3><textarea id="pasteParticipants" class="md-field" ${locked?'disabled':''} style="width:100%;min-height:88px" placeholder="Mã[TAB]Họ và tên[TAB]Phòng ban\nNV001[TAB]Nguyễn Văn A[TAB]Kế toán"></textarea><div class="md-toolbar"><button id="appendPaste" class="md-secondary-btn" ${locked?'disabled':''}>Thêm dữ liệu đã dán</button><button id="addTenRows" class="md-secondary-btn" ${locked?'disabled':''}>＋ 10 dòng trống</button><button id="clearParticipants" class="md-danger-btn" ${locked?'disabled':''}>Xóa danh sách</button></div></section>
  <section class="md-card"><div class="md-toolbar"><span class="status-pill ${validation.valid?'':'warn'}">${validation.valid?'Dữ liệu hợp lệ':`${validation.errors.length} lỗi cần sửa`}</span><span>${validation.eligibleCount} người đủ điều kiện / ${validation.total} dòng</span><span style="margin-left:auto"><input id="participantSearch" placeholder="Tìm tên, mã, phòng ban" style="padding:8px;border:1px solid var(--line);border-radius:9px"></span></div><div id="participantTableHost"></div></section></div>`;
  renderParticipantTable('');
  $('#participantDrop').onclick=()=>$('#participantFile').click();$('#participantFile').onchange=e=>importParticipantFile(e.target.files[0]);
  bindDrop($('#participantDrop'),file=>importParticipantFile(file));
  $('#appendPaste').onclick=async()=>{const rows=parsePastedTable($('#pasteParticipants').value);if(!rows.length)return showToast('Chưa có dữ liệu để thêm.');current.participants.push(...rows);current.status='draft';await persist(`Đã thêm ${rows.length} người.`)};
  $('#addTenRows').onclick=async()=>{const start=current.participants.length;current.participants.push(...Array.from({length:10},(_,i)=>normalizeParticipant({'Mã người tham dự':`P${String(start+i+1).padStart(4,'0')}`,'Họ và tên':'','Đủ điều kiện tham gia':'Có'},start+i)));await persist('Đã thêm 10 dòng trống.')};
  $('#clearParticipants').onclick=async()=>{if(!confirm('Xóa toàn bộ danh sách người tham dự của sự kiện này?'))return;current.participants=[];invalidateOfficialData();await persist('Đã xóa danh sách.')};
  $('#validateBtn').onclick=()=>{const v=validateParticipants(current.participants);showToast(v.valid?`Dữ liệu hợp lệ: ${v.eligibleCount} người.`:`Còn ${v.errors.length} lỗi.`);renderParticipants()};
  if($('#lockListBtn'))$('#lockListBtn').onclick=async()=>{const v=validateParticipants(current.participants);if(!v.valid)return showError(new Error('Hãy sửa toàn bộ lỗi trước khi khóa danh sách.'));if(!confirm(`Khóa ${v.eligibleCount} người hợp lệ? Sau khi khóa, mọi chỉnh sửa sẽ làm mất hiệu lực mapping cũ.`))return;await lockParticipantList(current);await persist('Đã khóa danh sách và tạo mã cam kết seed.')};
  if($('#unlockListBtn'))$('#unlockListBtn').onclick=async()=>{if(!confirm('Mở khóa sẽ làm mất hiệu lực hash, seed, mapping và các lượt quay đang chuẩn bị. Tiếp tục?'))return;invalidateOfficialData();await persist('Đã mở khóa danh sách. Hãy khóa lại trước khi chạy chính thức.')};
  $('#participantSearch').oninput=e=>renderParticipantTable(e.target.value);
}
function renderParticipantTable(query=''){
  const host=$('#participantTableHost');if(!host)return;const q=query.trim().toLowerCase();const rows=(current.participants||[]).map((p,index)=>({p,index})).filter(({p})=>!q||`${p.participantId} ${p.name} ${p.department}`.toLowerCase().includes(q));
  host.innerHTML=`<div class="participant-table-wrap"><table class="participant-table"><thead><tr><th>#</th><th>Mã</th><th>Họ và tên</th><th>Phòng ban</th><th>Chức danh</th><th>Đủ điều kiện</th><th></th></tr></thead><tbody>${rows.map(({p,index})=>`<tr data-index="${index}" class="${p._errors?.length?'row-error':''}"><td>${index+1}</td><td><input data-k="participantId" value="${escAttr(p.participantId)}" ${current.status!=='draft'?'disabled':''}></td><td><input data-k="name" value="${escAttr(p.name)}" ${current.status!=='draft'?'disabled':''}></td><td><input data-k="department" value="${escAttr(p.department)}" ${current.status!=='draft'?'disabled':''}></td><td><input data-k="title" value="${escAttr(p.title||'')}" ${current.status!=='draft'?'disabled':''}></td><td><input data-k="eligible" type="checkbox" ${p.eligible?'checked':''} ${current.status!=='draft'?'disabled':''}></td><td><button class="md-mini-btn remove-row" type="button" ${current.status!=='draft'?'disabled':''}>×</button></td></tr>`).join('')}</tbody></table></div>`;
  host.querySelectorAll('input').forEach(input=>input.onchange=async()=>{const tr=input.closest('tr'),p=current.participants[+tr.dataset.index],k=input.dataset.k;p[k]=input.type==='checkbox'?input.checked:input.value;invalidateOfficialData();await saveEvent(current)});
  host.querySelectorAll('.remove-row').forEach(btn=>btn.onclick=async()=>{current.participants.splice(+btn.closest('tr').dataset.index,1);invalidateOfficialData();await persist('Đã xóa một dòng.')});
}
async function importParticipantFile(file){
  if(!file)return;try{const XLSX=await ensureXlsx(),data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array',cellDates:true});const sheet=wb.Sheets[wb.SheetNames.includes('DANH_SACH_THAM_DU')?'DANH_SACH_THAM_DU':wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(sheet,{defval:''});current.participants=rows.map(normalizeParticipant);invalidateOfficialData();await persist(`Đã đọc ${rows.length} dòng từ ${file.name}.`)}catch(e){showError(e)}}
function invalidateOfficialData(){if(current.status!=='draft')current.status='draft';current.participantListHash='';current.baseSeed='';current.baseSeedCommitment='';current.mapping=[];current.mappingHash='';current.rounds=[];current.winningCode=''}
function renderShuffle(){
  const locked=['list_locked','shuffled','ready','running','completed'].includes(current.status);const mapped=current.mapping?.length;
  refs.main.innerHTML=head('Xáo và gán mã','Tên chạy trực quan để trình diễn; mapping chính thức chỉ xuất hiện sau khi khóa.',`<button id="trialShuffle" class="md-secondary-btn">Xáo thử</button><button id="officialShuffle" class="md-primary-btn" ${!locked||mapped?'disabled':''}>Xáo chính thức</button><button id="finalizeShuffle" class="md-primary-btn" ${!locked||mapped?'disabled':''}>Khóa kết quả xáo</button>`)+`
  <div class="md-grid"><section class="md-card"><div class="md-toolbar"><span class="status-pill">Đã xáo chính thức: ${current.shuffleCount||0} lần</span>${mapped?'<span class="status-pill">Mapping đã khóa</span>':'<span class="status-pill warn">Chưa công bố mapping</span>'}</div><div id="shuffleStage" class="shuffle-stage"><div id="shuffleCloud" class="shuffle-cloud">${shuffleNameHtml()}</div></div></section>
  <section class="md-card half"><h3>Cam kết trước khi xáo</h3>${current.baseSeedCommitment?`<p>Seed thật chưa được dùng để hiển thị mapping trung gian. Chỉ hash được công bố trước:</p><div class="hash-box">${current.baseSeedCommitment}</div>`:'<div class="inline-note">Hãy khóa danh sách người tham dự trước.</div>'}</section>
  <section class="md-card half"><h3>Quy tắc</h3><p>Mỗi lần bấm <strong>Xáo chính thức</strong> chỉ tăng bộ đếm và chạy animation. Khi bấm <strong>Khóa kết quả xáo</strong>, hệ thống mới tạo thứ tự cuối từ seed + số lần xáo + hash danh sách.</p></section>
  ${mapped?`<section class="md-card"><h3>Mapping mã số chính thức</h3><div class="mapping-list">${current.mapping.map(m=>`<div class="mapping-item"><span class="mapping-code">${m.code}</span><span><strong>${esc(m.name)}</strong><small>${esc(m.participantId)} · ${esc(m.department||'')}</small></span></div>`).join('')}</div></section>`:''}</div>`;
  $('#trialShuffle').onclick=()=>animateShuffle(false);$('#officialShuffle').onclick=async()=>{current.shuffleCount=(current.shuffleCount||0)+1;await saveEvent(current);animateShuffle(true);renderEventList();setTimeout(()=>{if(currentView==='shuffle')renderAll()},1700)};
  $('#finalizeShuffle').onclick=async()=>{if(!current.shuffleCount){if(!confirm('Chưa bấm xáo chính thức lần nào. Vẫn khóa mapping với số lần xáo bằng 0?'))return}await finalizeShuffle(current);await persist('Đã khóa mapping và gán mã số.')};
}
function shuffleNameHtml(){const list=eligibleParticipants(current).slice(0,80);return list.length?list.map((p,i)=>`<span class="shuffle-name" style="--dx:${(i%7-3)*3}px;--dy:${(i%5-2)*3}px;--rot:${(i%9-4)*2}deg">${esc(p.name)}</span>`).join(''):'<span>Chưa có danh sách hợp lệ.</span>'}
function animateShuffle(official){const stage=$('#shuffleStage'),cloud=$('#shuffleCloud');if(!stage||!cloud)return;stage.classList.add('running');const names=eligibleParticipants(current).map(p=>p.name);let frames=0;clearInterval(shuffleTimer);shuffleTimer=setInterval(()=>{const sample=[...names].sort(()=>Math.random()-.5).slice(0,Math.min(80,names.length));cloud.innerHTML=sample.map((n,i)=>`<span class="shuffle-name" style="--dx:${(Math.random()*40-20).toFixed(0)}px;--dy:${(Math.random()*30-15).toFixed(0)}px;--rot:${(Math.random()*18-9).toFixed(0)}deg">${esc(n)}</span>`).join('');if(++frames>12){clearInterval(shuffleTimer);stage.classList.remove('running');cloud.innerHTML=official?'<strong>Đã ghi nhận một lần xáo. Mapping vẫn chưa được công bố.</strong>':shuffleNameHtml()}},110)}
function getDigitCount(){return current.digitCountManual||current.digitCount||digitCountFor(Math.max(1,eligibleParticipants(current).length));}
function renderRace(){
  const ready=current.mapping?.length>0;const count=getDigitCount();const labels=digitLabels(count);
  refs.main.innerHTML=head('Đường đua 3D','Mỗi lượt thả 10 viên số 0–9; quay từ hàng cao nhất đến hàng đơn vị.',`<button id="demoRaceBtn" class="md-secondary-btn">Chạy thử</button><button id="officialRaceBtn" class="md-primary-btn" ${ready?'':'disabled'}>Chạy chính thức</button>`)+`
  <div class="md-grid"><section class="md-card half"><h3>Cấu hình lượt quay</h3><p>Số người hợp lệ: <strong>${eligibleParticipants(current).length}</strong>. Số chữ số: <strong>${count}</strong>. Thứ tự: ${labels.join(' → ')}.</p><label style="display:flex;gap:8px"><input id="allowRepeatRace" type="checkbox" ${current.allowRepeatWinner?'checked':''}> Cho phép người đã thắng tiếp tục tham gia giải sau</label></section><section class="md-card half"><h3>Điều kiện chạy chính thức</h3>${ready?'<div class="status-pill">Đã khóa mapping</div><p>Hash danh sách, seed, số lần xáo và mapping đã sẵn sàng.</p>':'<div class="inline-note">Phải khóa danh sách và khóa kết quả xáo trước khi chạy chính thức.</div>'}</section>
  <section class="md-card"><div class="race-preview"><canvas id="previewCanvas"></canvas><div class="race-preview-overlay"><div><strong>Marblie Track v1</strong><div>Rapier 3D · 10 viên giống nhau · cảm biến đích</div></div><button id="previewLoadBtn" class="md-primary-btn">Xem đường đua</button></div></div></section></div>`;
  $('#demoRaceBtn').onclick=()=>openRace('demo');$('#officialRaceBtn').onclick=()=>openRace('official');$('#previewLoadBtn').onclick=()=>previewTrack();
}
async function createRaceEngine(canvas,options){
  if(!RaceEngineClass){const mod=await import('./race-engine.js');RaceEngineClass=mod.MarbleRaceEngine;}
  return new RaceEngineClass(canvas,options);
}
async function previewTrack(){try{const canvas=$('#previewCanvas');if(raceEngine)raceEngine.destroy();raceEngine=await createRaceEngine(canvas,{quality:settings.quality,volume:settings.volume,sound:false});await raceEngine.prepare('preview-track');showToast('Đã tải đường đua mẫu.')}catch(e){showError(e)}}
async function openRace(mode){
  if(mode==='official'){if(!current.mapping?.length)return showError(new Error('Chưa có mapping chính thức.'));const typed=prompt('Gõ CHAY CHINH THUC để khóa cấu hình và bắt đầu:','');if(typed!=='CHAY CHINH THUC')return}
  raceMode=mode;raceAttempt=mode==='official'?((current.results?.length||0)*100000+(current.attempts?.length||0)):Date.now();current.digitCount=getDigitCount();current.rounds=[];current.currentPrefix='';current.winningCode='';current.status=mode==='official'?'running':current.status;
  if(mode==='official')await saveEvent(current);refs.raceStage.hidden=false;document.body.style.overflow='hidden';$('#raceModeBadge').textContent=mode==='official'?'CHẠY CHÍNH THỨC':'CHẠY THỬ';$('#raceEventName').textContent=current.name;refs.raceWinner.hidden=true;refs.resetSequenceBtn.hidden=true;refs.startDigitBtn.hidden=false;refs.startDigitBtn.disabled=false;refs.startDigitBtn.textContent='Bắt đầu lượt đầu tiên';
  setupDigitSlots();updateRaceCandidateInfo();refs.raceStatus.textContent='Sẵn sàng. Bấm Bắt đầu lượt để thả 10 viên.';
  if(raceEngine)raceEngine.destroy();raceEngine=await createRaceEngine(refs.canvas,{quality:settings.quality,volume:settings.volume,sound:settings.sound});
  try{await raceEngine.prepare(await deriveRoundSeed(current,0,raceAttempt))}catch(e){closeRaceStage();showError(new Error('Không tải được Three.js/Rapier. Hãy kiểm tra Internet ở lần mở đầu tiên. '+e.message))}
}
function setupDigitSlots(){const count=getDigitCount();const labels=digitLabels(count);refs.digitSlots.innerHTML=Array.from({length:count},(_,i)=>`<div class="digit-slot ${i===0?'active':''}" title="${labels[i]}">?</div>`).join('');refs.raceRoundLabel.textContent=labels[0]||'Chữ số'}
async function runNextDigit(){
  if(!raceEngine||raceEngine.running)return;const count=current.digitCount||1,index=current.rounds.length;if(index>=count)return;refs.startDigitBtn.disabled=true;refs.raceWinner.hidden=true;refs.raceRanking.innerHTML='';
  const seed=await deriveRoundSeed(current,index,raceAttempt);const slots=$$('.digit-slot');slots.forEach((s,i)=>s.classList.toggle('active',i===index));const labels=digitLabels(count);refs.raceRoundLabel.textContent=labels[index];
  try{const result=await raceEngine.run({seed,onCountdown:n=>{refs.raceCountdown.hidden=n===0;refs.raceCountdown.textContent=n||''},onUpdate:order=>{refs.raceRanking.innerHTML=order.slice(0,5).map((r,i)=>`<div class="rank-row"><span>${i+1}. Viên ${r.digit}</span><span>${r.finished?'Đích':r.z.toFixed(1)}</span></div>`).join('')},onStatus:t=>refs.raceStatus.textContent=t,onFinish:r=>showDigitWinner(r,index,seed)});return result}catch(e){refs.raceStatus.textContent=e.message;refs.startDigitBtn.disabled=false;refs.startDigitBtn.textContent='Quay lại lượt này'}
}
async function showDigitWinner(result,index,seed){
  const round={index,label:digitLabels(current.digitCount)[index],seed,winner:result.winner,finishOrder:result.finishOrder,duration:result.duration,createdAt:new Date().toISOString()};current.rounds.push(round);current.currentPrefix=current.rounds.map(r=>r.winner).join('');
  const slots=$$('.digit-slot');slots[index].textContent=result.winner;slots[index].classList.remove('active');slots[index].classList.add('done');if(index+1<slots.length)slots[index+1].classList.add('active');
  refs.raceWinner.innerHTML=`<span>Chữ số chiến thắng</span><b>${result.winner}</b><small>${round.label} · ${result.finishOrder[0]?.time?.toFixed(3)||'—'} giây</small>`;refs.raceWinner.hidden=false;updateRaceCandidateInfo();await saveEvent(current);
  if(current.rounds.length<current.digitCount){refs.startDigitBtn.disabled=false;refs.startDigitBtn.textContent=`Bắt đầu ${digitLabels(current.digitCount)[current.rounds.length]}`;refs.raceStatus.textContent='Đã ghi nhận chữ số. Sẵn sàng cho lượt tiếp theo.';return}
  await completeSequence();
}
async function completeSequence(){
  const code=current.rounds.map(r=>r.winner).join('');current.winningCode=code;const match=current.mapping?.find(m=>m.code===code);
  if(raceMode==='demo'&&!current.mapping?.length){refs.raceWinner.innerHTML=`<span>Kết quả chạy thử</span><b>${code}</b><small>Chưa có mapping chính thức nên không công bố người thắng.</small>`;refs.raceWinner.hidden=false;refs.startDigitBtn.hidden=true;refs.raceStatus.textContent='Kết quả chỉ dùng để kiểm tra đường đua, không lưu giải thưởng.';return}
  const alreadyWon=match&&!current.allowRepeatWinner&&(current.excludedParticipantIds||[]).includes(match.participantId);
  const wrongDepartment=match&&(current.prizeDepartments||[]).length&&!current.prizeDepartments.some(d=>d.toLowerCase()===String(match.department||'').toLowerCase());
  const ineligible=alreadyWon||wrongDepartment;
  if(!match||ineligible){current.attempts=current.attempts||[];current.attempts.push({attempt:raceAttempt,code,rounds:structuredClone(current.rounds),status:alreadyWon?'excluded_winner':wrongDepartment?'department_not_eligible':'empty_code',createdAt:new Date().toISOString()});await saveEvent(current);refs.raceWinner.innerHTML=`<span>${alreadyWon?'Người đã trúng':wrongDepartment?'Sai phạm vi phòng ban':'Mã trống'}</span><b>${code}</b><small>${alreadyWon?'Mã thuộc người không còn đủ điều kiện cho giải này.':wrongDepartment?'Mã thuộc người ngoài phạm vi phòng ban của giải.':'Mã chưa được cấp.'} Quy định yêu cầu quay lại toàn bộ chuỗi.</small>`;refs.resetSequenceBtn.hidden=false;refs.startDigitBtn.hidden=true;refs.raceStatus.textContent=alreadyWon?`Mã ${code} thuộc người đã trúng và không được trúng lại. Quay lại toàn bộ chuỗi.`:wrongDepartment?`Mã ${code} không thuộc phòng ban được tham gia giải. Quay lại toàn bộ chuỗi.`:`Mã ${code} không thuộc danh sách hợp lệ. Không dùng modulo và không sửa riêng chữ số cuối.`;return}
  const result={id:`result_${Date.now()}`,prizeName:current.prizeName||'Giải may mắn',code,participantId:match.participantId,name:match.name,department:match.department,rounds:structuredClone(current.rounds),attempt:raceAttempt,createdAt:new Date().toISOString(),mode:raceMode};
  if(raceMode==='official'){current.results=current.results||[];current.results.push(result);if(!current.allowRepeatWinner)current.excludedParticipantIds=[...new Set([...(current.excludedParticipantIds||[]),match.participantId])];current.status='completed';await saveEvent(current)}
  refs.raceWinner.innerHTML=`<span>${esc(result.prizeName)}</span><b>${code}</b><strong>${esc(match.name)}</strong><small>${esc(match.participantId)} · ${esc(match.department||'')}</small>`;refs.raceWinner.hidden=false;refs.startDigitBtn.hidden=true;refs.raceStatus.textContent=raceMode==='official'?'Kết quả chính thức đã được lưu.':'Kết quả chạy thử, không ghi vào danh sách giải thưởng.';showToast(`Mã ${code}: ${match.name}`)
}
async function resetSequence(){raceAttempt++;current.rounds=[];current.currentPrefix='';current.winningCode='';setupDigitSlots();refs.raceWinner.hidden=true;refs.resetSequenceBtn.hidden=true;refs.startDigitBtn.hidden=false;refs.startDigitBtn.disabled=false;refs.startDigitBtn.textContent='Bắt đầu lại từ hàng cao nhất';updateRaceCandidateInfo();await saveEvent(current);await raceEngine.prepare(await deriveRoundSeed(current,0,raceAttempt));refs.raceStatus.textContent='Đã tạo seed mới cho toàn bộ chuỗi.'}
function updateRaceCandidateInfo(){const prefix=current.currentPrefix||'';if(!current.mapping?.length){refs.raceCandidateInfo.textContent='Chế độ thử nghiệm: chưa có mapping chính thức.';return}const candidates=current.mapping.filter(m=>m.code.startsWith(prefix)&&((current.allowRepeatWinner||!(current.excludedParticipantIds||[]).includes(m.participantId)))&&(!(current.prizeDepartments||[]).length||current.prizeDepartments.some(d=>d.toLowerCase()===String(m.department||'').toLowerCase())));refs.raceCandidateInfo.textContent=prefix?`Tiền tố ${prefix}: còn ${candidates.length} người có khả năng trúng.`:`${candidates.length} người đang có cơ hội.`}
function closeRaceStage(){refs.raceStage.hidden=true;document.body.style.overflow='';raceEngine?.stop();renderAll()}
function renderResults(){const rows=[...(current.results||[])].reverse();refs.main.innerHTML=head('Kết quả','Lưu lịch sử giải thưởng và xuất biên bản kiểm chứng.',`<button id="exportResultsExcel" class="md-secondary-btn">Xuất Excel</button><button id="printResults" class="md-secondary-btn">In / lưu PDF</button>`)+`<div class="md-grid"><section class="md-card"><div class="result-list">${rows.length?rows.map(r=>`<div class="result-row"><span class="result-code">${r.code}</span><span><strong>${esc(r.name)}</strong><small>${esc(r.participantId)} · ${esc(r.department||'')}<br>${esc(r.prizeName)}</small></span><time>${formatDate(r.createdAt)}</time></div>`).join(''):'<div class="inline-note">Chưa có kết quả chính thức.</div>'}</div></section></div>`;$('#exportResultsExcel').onclick=exportResultsExcel;$('#printResults').onclick=printResultReport}
async function exportResultsExcel(){const XLSX=await ensureXlsx(),rows=(current.results||[]).map((r,i)=>({STT:i+1,'Tên giải':r.prizeName,'Mã trúng':r.code,'Mã người tham dự':r.participantId,'Họ và tên':r.name,'Phòng ban':r.department,'Thời điểm':r.createdAt}));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'KET_QUA');XLSX.writeFile(wb,`${safeName(current.name)}_ket_qua.xlsx`)}
function printResultReport(){const win=open('','_blank');win.document.write(`<html><head><meta charset="utf-8"><title>Biên bản ${esc(current.name)}</title><style>body{font-family:Arial;padding:40px}h1{color:#173a30}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccc;padding:8px;text-align:left}</style></head><body><h1>BIÊN BẢN KẾT QUẢ MARBLE DRAW</h1><p>Sự kiện: <b>${esc(current.name)}</b></p><p>Hash danh sách: ${esc(current.participantListHash||'—')}</p><table><tr><th>Giải</th><th>Mã</th><th>Người thắng</th><th>Phòng ban</th><th>Thời điểm</th></tr>${(current.results||[]).map(r=>`<tr><td>${esc(r.prizeName)}</td><td>${r.code}</td><td>${esc(r.name)} (${esc(r.participantId)})</td><td>${esc(r.department||'')}</td><td>${formatDate(r.createdAt)}</td></tr>`).join('')}</table><script>print()<\/script></body></html>`);win.document.close()}
function renderVerify(){refs.main.innerHTML=head('Xác minh','Kiểm tra hash, mapping và xuất toàn bộ dữ liệu cần thiết để đối chiếu.',`<button id="verifyMappingBtn" class="md-secondary-btn">Kiểm tra mapping</button><button id="exportVerification" class="md-primary-btn">Xuất verification.json</button>`)+`<div class="md-grid"><section class="md-card half"><h3>Dữ liệu đã khóa</h3><p>Phiên bản game: ${esc(current.gameVersion)}<br>Đường đua: ${esc(current.trackVersion)}<br>Vật lý: ${esc(current.physicsVersion)}<br>Số lần xáo: ${current.shuffleCount||0}</p><div class="hash-box">Danh sách: ${current.participantListHash||'—'}</div><div class="hash-box" style="margin-top:8px">Mapping: ${current.mappingHash||'—'}</div></section><section class="md-card half"><h3>Seed commitment</h3><p>Hash được công bố trước khi mapping xuất hiện:</p><div class="hash-box">${current.baseSeedCommitment||'—'}</div>${current.mapping?.length?`<p>Seed đã công bố sau khi khóa mapping:</p><div class="hash-box">${current.baseSeed||'—'}</div>`:''}</section><section class="md-card"><h3>Kiểm tra phân bổ 10.000 seed</h3><p>Phép kiểm tra nhanh này xác minh mỗi chữ số xuất hiện ở mỗi vị trí xuất phát với tần suất gần đồng đều. Benchmark vật lý đầy đủ cần chạy riêng trên máy dùng cho sự kiện.</p><button id="seedBenchmarkBtn" class="md-secondary-btn">Chạy 10.000 lượt phân bổ</button><div id="benchmarkResult"></div></section></div>`;$('#verifyMappingBtn').onclick=async()=>showToast(await verifyMapping(current)?'Mapping khớp seed và số lần xáo.':'Mapping không khớp hoặc chưa được khóa.');$('#exportVerification').onclick=exportVerification;$('#seedBenchmarkBtn').onclick=runSeedBenchmark}
async function exportVerification(){const payload=verificationPayload();downloadJson(payload,`${safeName(current.name)}_verification.json`)}
function verificationPayload(){return{formatVersion:1,eventId:current.id,eventName:current.name,participantListHash:current.participantListHash,trackHash:current.trackHash||null,trackVersion:current.trackVersion,physicsConfigHash:current.physicsConfigHash||null,physicsVersion:current.physicsVersion,mappingHash:current.mappingHash,baseSeedCommitment:current.baseSeedCommitment,revealedBaseSeed:current.mapping?.length?current.baseSeed:null,shuffleCount:current.shuffleCount,digitCount:current.digitCount,digitOrder:digitLabels(current.digitCount),mapping:current.mapping,attempts:current.attempts,results:current.results,gameVersion:current.gameVersion,exportedAt:new Date().toISOString()}}
async function runSeedBenchmark(){const host=$('#benchmarkResult');host.innerHTML='<p>Đang chạy…</p>';const counts=Array.from({length:10},()=>Array(10).fill(0));for(let i=0;i<10000;i++){const order=await seededShuffle([...Array(10).keys()],`${current.baseSeed||'benchmark'}|position|${i}`);order.forEach((digit,pos)=>counts[digit][pos]++);if(i%500===0)await nextFrame()}const maxDev=Math.max(...counts.flat().map(n=>Math.abs(n-1000)/1000));host.innerHTML=`<div class="inline-note">Đã kiểm tra 100.000 lượt gán chữ số-vị trí. Độ lệch lớn nhất so với kỳ vọng 1.000 lần/vị trí: <strong>${(maxDev*100).toFixed(2)}%</strong>.</div>`}
async function persist(message){await saveEvent(current);events=await listEvents();current=events.find(e=>e.id===current.id)||current;renderAll();if(message)showToast(message)}
function statusLabel(s){return({draft:'Bản nháp',list_locked:'Danh sách đã khóa',shuffled:'Mapping đã khóa',ready:'Sẵn sàng',running:'Đang chạy',completed:'Đã hoàn thành',invalidated:'Đã mất hiệu lực'})[s]||s||'Bản nháp'}
function toggleSound(){settings.sound=!settings.sound;saveSettings(settings);if(raceEngine)raceEngine.sound=settings.sound;syncSoundButtons()}
function syncSoundButtons(){$('#soundBtn').classList.toggle('active',settings.sound);$('#raceSoundBtn').classList.toggle('active',settings.sound);$('#soundBtn').textContent=$('#raceSoundBtn').textContent=settings.sound?'♪':'∅'}
async function toggleFullscreen(){if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.()}
function closeToKanban(){raceEngine?.destroy();if(parent!==window)parent.postMessage({type:'marble-draw-close'},'*');else location.href='../index.html'}
async function deleteAllDrawData(){const backup=confirm('Bạn có muốn xuất backup Marble Draw trước khi xóa không?');if(backup)downloadJson({events,settings,exportedAt:new Date().toISOString()},'Marble_Draw_backup.json');const typed=prompt('Gõ chính xác OK để xóa toàn bộ dữ liệu Marble Draw. Dữ liệu Kanban không bị ảnh hưởng.','');if(typed!=='OK')return;await clearAllEvents();location.reload()}
async function ensureXlsx(){if(globalThis.XLSX)return globalThis.XLSX;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=XLSX_URL;s.onload=resolve;s.onerror=()=>reject(new Error('Không tải được thư viện SheetJS.'));document.head.appendChild(s)});return globalThis.XLSX}
function bindDrop(el,handler){el.ondragover=e=>{e.preventDefault();el.style.filter='brightness(.95)'};el.ondragleave=()=>el.style.filter='';el.ondrop=e=>{e.preventDefault();el.style.filter='';handler(e.dataTransfer.files[0])}}
function downloadJson(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function showToast(msg){clearTimeout(toastTimer);refs.toast.textContent=msg;refs.toast.classList.add('show');toastTimer=setTimeout(()=>refs.toast.classList.remove('show'),2500)}
function showError(err){console.error(err);showToast(err?.message||String(err))}
function formatDate(v){const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('vi-VN'):'—'}
function safeName(s){return String(s||'file').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'_').replace(/^_+|_+$/g,'')||'file'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c])}
function escAttr(v){return esc(v).replace(/`/g,'&#96;')}
function nextFrame(){return new Promise(r=>requestAnimationFrame(r))}
