(()=>{
'use strict';
const $=s=>document.querySelector(s), app=$('#app');
const META_KEY='tlv_meta_v1', SLOT_KEY=i=>`tlv_slot_${i}_v1`;
const GOODS=[
 {id:'thep',name:'Thép',base:18,icon:'▰'}, {id:'nhienlieu',name:'Nhiên liệu',base:24,icon:'◆'},
 {id:'linhkien',name:'Linh kiện',base:42,icon:'⌘'}, {id:'luongthuc',name:'Lương thực',base:12,icon:'◒'},
 {id:'duocpham',name:'Dược phẩm',base:55,icon:'✚'}, {id:'maymoc',name:'Máy móc',base:68,icon:'⚙'},
 {id:'nong-san',name:'Nông sản',base:15,icon:'✿'}, {id:'khoangsan',name:'Khoáng sản',base:30,icon:'⬟'},
 {id:'hanglanh',name:'Hàng lạnh',base:46,icon:'❄'}, {id:'dientu',name:'Điện tử',base:75,icon:'▣'}
];
const PORTS=[
 {id:'saigon',name:'Trạm Sài Gòn',type:'Thương mại',prod:{dientu:13,duocpham:8},cons:{luongthuc:14,nhienlieu:10,khoangsan:5}},
 {id:'cuulong',name:'Cảng Cửu Long',type:'Nông nghiệp',prod:{'nong-san':18,luongthuc:14},cons:{maymoc:7,nhienlieu:8,dientu:4}},
 {id:'haivan',name:'Cảng Hải Vân',type:'Trung chuyển',prod:{},cons:{thep:8,nhienlieu:8,luongthuc:8}},
 {id:'taynguyen',name:'Khu mỏ Tây Nguyên',type:'Khai khoáng',prod:{khoangsan:19,thep:8},cons:{luongthuc:11,maymoc:8,duocpham:5}},
 {id:'binhduong',name:'Khu công nghiệp Bình Dương',type:'Công nghiệp',prod:{maymoc:13,linhkien:12},cons:{thep:15,nhienlieu:12,khoangsan:10}},
 {id:'phuquoc',name:'Cảng Phú Quốc',type:'Dịch vụ',prod:{hanglanh:12,'nong-san':7},cons:{duocpham:7,dientu:9,luongthuc:8}},
 {id:'halong',name:'Cảng Hạ Long',type:'Đóng tàu',prod:{thep:9,maymoc:7},cons:{linhkien:12,nhienlieu:11,khoangsan:6}},
 {id:'dalat',name:'Trạm Đà Lạt',type:'Nông nghiệp công nghệ',prod:{'nong-san':12,hanglanh:10},cons:{maymoc:5,dientu:6,nhienlieu:5}}
];
const ROUTES={saigon:{cuulong:2,binhduong:1,phuquoc:3,dalat:2},cuulong:{saigon:2,phuquoc:2,haivan:4},haivan:{cuulong:4,taynguyen:3,halong:4,binhduong:3},taynguyen:{haivan:3,binhduong:2,dalat:2},binhduong:{saigon:1,haivan:3,taynguyen:2,dalat:2},phuquoc:{saigon:3,cuulong:2},halong:{haivan:4},dalat:{saigon:2,taynguyen:2,binhduong:2}};
const COMPANIES=[
 {id:'namphuong',name:'Vận tải Nam Phương',style:'an toàn',risk:.25}, {id:'giaphat',name:'Thương nghiệp Gia Phát',style:'đầu cơ',risk:.65},
 {id:'haidang',name:'Hải Đăng Logistics',style:'hợp đồng',risk:.4}, {id:'truongson',name:'Vận tải Trường Sơn',style:'tuyến khó',risk:.75},
 {id:'minhlong',name:'Công ty Minh Long',style:'mở rộng nhanh',risk:.8}, {id:'cuulongcorp',name:'Tập đoàn Cửu Long',style:'quy mô lớn',risk:.35},
 {id:'hungvuong',name:'Vận tải Hùng Vương',style:'tàu nhanh',risk:.55}, {id:'daithanh',name:'Thương mại Đại Thành',style:'gom hàng giá thấp',risk:.5}
];
const ORIGINS=[
 {id:'canbang',name:'Người mới lập nghiệp',desc:'Cân bằng, dễ làm quen.',cash:180,debt:0,cap:50,rep:0,unlock:0},
 {id:'vanta',name:'Gia đình làm vận tải',desc:'Tàu lớn hơn nhưng có khoản vay ban đầu.',cash:150,debt:80,cap:75,rep:5,unlock:2},
 {id:'nganhang',name:'Cựu nhân viên ngân hàng',desc:'Vốn ít hơn nhưng hạn mức vay tốt.',cash:120,debt:0,cap:50,rep:8,unlock:4},
 {id:'chobuon',name:'Dân buôn lâu năm',desc:'Biết thị trường tốt hơn, vốn vừa phải.',cash:160,debt:0,cap:45,rep:-3,unlock:6},
 {id:'taytrang',name:'Tay trắng',desc:'Khởi đầu khó, ít vốn nhưng điểm sự nghiệp nhận được cao hơn.',cash:80,debt:0,cap:35,rep:0,unlock:10}
];
const SHIP_TYPES=[
 {id:'anbinh',name:'An Bình',cap:50,speed:1,cost:150,maint:2},
 {id:'haiau',name:'Hải Âu',cap:38,speed:2,cost:210,maint:3},
 {id:'songhong',name:'Sông Hồng',cap:90,speed:1,cost:330,maint:5},
 {id:'bachdang',name:'Bạch Đằng',cap:65,speed:1,cost:285,maint:4}
];
const EVENT_TEMPLATES={
 market:[
  ['Nhà máy tăng ca','Khu công nghiệp {port} nhận đơn hàng lớn. Nhu cầu {good} tăng trong vài ngày.','boostDemand'],
  ['Hàng về dồn dập','Nhiều tàu cùng đưa {good} tới {port}. Giá có thể giảm nhanh.','floodSupply'],
  ['Thiếu hàng cục bộ','Kho {good} tại {port} đang xuống thấp. Các thương nhân bắt đầu gom hàng.','shortage'],
  ['Đơn hàng bất ngờ','Một khách lớn cần lượng {good} đáng kể tại {port}.','boostDemand']
 ],
 transport:[
  ['Tuyến vận chuyển ùn','Tuyến tới {port} đang đông, tàu có thể chậm thêm một ngày.','routeDelay'],
  ['Trạm tiếp nhiên liệu bảo trì','Chi phí vận hành trong vài ngày tới tăng nhẹ.','fuelUp'],
  ['Mở luồng ưu tiên','Cảng {port} mở luồng ưu tiên tạm thời, tàu đến đây đi nhanh hơn.','routeBoost']
 ],
 staff:[
  ['Nhân viên xin tăng lương','Đội vận hành đề nghị tăng phụ cấp. Nếu đồng ý, tinh thần sẽ tốt hơn.','staffRaise'],
  ['Mâu thuẫn trong đội','Hai nhân viên tranh cãi về cách xếp lịch tàu.','staffConflict'],
  ['Người giỏi xin việc','Một điều phối viên có kinh nghiệm muốn gia nhập công ty.','hireTalent']
 ],
 ship:[
  ['Máy tàu nóng bất thường','Một tàu đang hoạt động báo nhiệt độ máy cao.','shipHeat'],
  ['Kiểm tra kỹ thuật','Cảng yêu cầu kiểm tra một tàu trước khi rời bến.','inspection'],
  ['Khoang hàng cần sửa','Bộ phận khoang hàng xuống cấp, chưa nguy hiểm nhưng có thể tốn thêm phí.','cargoRepair']
 ],
 business:[
  ['Khách hàng lớn tìm đến','Một doanh nghiệp muốn ký hợp đồng giao hàng ngắn hạn.','specialContract'],
  ['Đề nghị hợp tác','Một hãng vận tải nhỏ muốn chia tuyến và chia lợi nhuận.','partnership'],
  ['Khách chậm thanh toán','Một khoản phải thu bị chậm, dòng tiền có thể căng vài ngày.','latePay']
 ],
 social:[
  ['Lễ hội lớn','Lượng người và hàng tăng mạnh tại {port}; lương thực và hàng lạnh được hỏi mua nhiều.','festival'],
  ['Dịch bệnh theo mùa','Nhu cầu dược phẩm tại {port} tăng nhanh.','medicineDemand'],
  ['Đình công kho bãi','Một phần kho tại {port} tạm dừng hoạt động.','strike']
 ],
 government:[
  ['Giảm phí cảng','Chính quyền {port} giảm phí vận chuyển tạm thời để kích cầu.','portSubsidy'],
  ['Siết kiểm tra','Hàng hóa qua {port} bị kiểm tra kỹ hơn trong vài ngày.','tightInspect'],
  ['Trợ giá nhiên liệu','Một gói hỗ trợ mới làm chi phí nhiên liệu giảm nhẹ.','fuelDown'],
  ['Tăng thuế hàng công nghiệp','Thuế máy móc và điện tử tăng tạm thời.','industrialTax']
 ],
 underground:[
  ['Lời mời kín','Một người lạ đề nghị vận chuyển lô hàng không khai báo với tiền công cao.','smuggleOffer'],
  ['Mua tin nội bộ','Có người chào bán thông tin về đơn hàng lớn sắp tới.','buyIntel'],
  ['Môi giới mờ ám','Một môi giới hứa giúp ưu tiên dỡ hàng nếu trả phí riêng.','bribeOffer']
 ],
 personal:[
  ['Bạn cũ liên lạc','Một người bạn cũ đang làm ở kho hàng muốn giới thiệu anh với khách mới.','oldFriend'],
  ['Nhân viên gặp khó','Một nhân viên xin ứng trước lương vì việc gia đình.','advanceSalary'],
  ['Chuyện vui trên tàu','Một chú mèo lạc vào khoang hàng và được cả đội giữ lại làm “linh vật”.','catMascot']
 ],
 competitor:[
  ['Đối thủ gom hàng','{company} đang mua mạnh {good}. Chưa rõ họ biết điều gì.','aiAccumulation'],
  ['Đối thủ mở tuyến','{company} vừa đưa thêm tàu vào {port}.','aiExpansion'],
  ['Đối thủ bán tháo','{company} bất ngờ bán lượng hàng lớn để lấy tiền mặt.','aiSelloff'],
  ['Hãng nhỏ gặp khó','Một hãng vận tải nhỏ đang rao bán tàu do thiếu tiền.','cheapShip']
 ],
 world:[
  ['Khủng hoảng năng lượng','Nhiều khu vực cùng thiếu nhiên liệu. Giá vận chuyển có nguy cơ tăng kéo dài.','energyCrisis'],
  ['Suy giảm kinh tế','Đơn hàng dân dụng giảm, doanh nghiệp bắt đầu thận trọng hơn.','recession'],
  ['Bùng nổ đầu tư','Các khu công nghiệp đồng loạt mở rộng sản xuất.','boom'],
  ['Khủng hoảng tín dụng','Ngân hàng bắt đầu siết cho vay. Công ty nợ nhiều sẽ chịu áp lực.','creditCrisis']
 ]
};
let meta=loadMeta(), state=null, slot=1, tab='tongquan', selectedShipId=null, selectedPort='saigon', modal=null;
function loadMeta(){try{return JSON.parse(localStorage.getItem(META_KEY))||defaultMeta()}catch{return defaultMeta()}}
function defaultMeta(){return{version:1,runs:0,bankruptcies:0,wins:0,totalDays:0,careerPoints:0,bestNetWorth:0,unlockedOrigins:['canbang'],discoveredEvents:[],history:[]}}
function saveMeta(){localStorage.setItem(META_KEY,JSON.stringify(meta))}
function loadSlot(i){try{return JSON.parse(localStorage.getItem(SLOT_KEY(i)))}catch{return null}}
function save(){if(!state)return;state.updatedAt=Date.now();localStorage.setItem(SLOT_KEY(slot),JSON.stringify(state))}
function eraseSlot(i){localStorage.removeItem(SLOT_KEY(i))}
function money(v){const sign=v<0?'-':'';v=Math.abs(v);return sign+(v>=1000?(v/1000).toLocaleString('vi-VN',{maximumFractionDigits:2})+' tỷ':v.toLocaleString('vi-VN',{maximumFractionDigits:1})+' tr')}
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a} function pick(a){return a[Math.floor(Math.random()*a.length)]}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function gname(id){return GOODS.find(g=>g.id===id)?.name||id} function pname(id){return PORTS.find(p=>p.id===id)?.name||id}
function netWorth(s=state){return s.cash-s.debt+s.ships.reduce((x,sh)=>x+(SHIP_TYPES.find(t=>t.id===sh.type)?.cost||100)*.65,0)+Object.values(s.warehouses||{}).reduce((a,w)=>a+Object.values(w).reduce((x,y)=>x+y.qty*(GOODS.find(g=>g.id===y.good)?.base||0),0),0)}
function makeWorld(){const markets={};for(const p of PORTS){markets[p.id]={};for(const g of GOODS){const bias=(p.prod[g.id]||0)-(p.cons[g.id]||0);const stock=clamp(80+bias*3+rnd(-20,20),20,160);markets[p.id][g.id]={stock,price:Math.max(4,g.base*(1+(70-stock)/120)+rnd(-2,2)),trend:0,history:[]}}}return markets}
function createState(name,originId){const o=ORIGINS.find(x=>x.id===originId)||ORIGINS[0];const ship={id:'ship1',name:'An Bình 01',type:'anbinh',cap:o.cap,port:'saigon',dest:null,eta:0,cargo:[],condition:100};return{version:1,company:name||'Hoài Phát Logistics',origin:originId,day:1,cash:o.cash,debt:o.debt,creditLimit:originId==='nganhang'?300:180,reputation:o.rep,morale:70,staff:4,monthlySalary:10,ships:[ship],markets:makeWorld(),contracts:[],acceptedContracts:[],events:[],scheduled:[],news:[],journal:[],ai:COMPANIES.map(c=>({...c,cash:rnd(500,1800),fleet:rnd(2,7),health:100})),effects:[],warehouses:{},stats:{revenue:0,profit:0,trades:0,contractsDone:0,maxShips:1,bestDayProfit:0},createdAt:Date.now(),updatedAt:Date.now(),status:'playing'} }
function pushLog(text,type='info'){state.journal.unshift({day:state.day,text,type});state.journal=state.journal.slice(0,250)}
function toast(msg){const old=$('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
function startScreen(){state=null;const slots=[1,2,3].map(i=>({i,s:loadSlot(i)}));app.innerHTML=`<div class="shell"><div class="slot-wrap"><div class="hero"><div class="brand-mark" style="margin:auto">TL</div><h1>Thương Lộ Việt</h1><p>Chiến thuật kinh tế theo ngày · Mỗi lựa chọn tạo ra một lịch sử khác nhau</p></div><div class="career">${careerCard('Hành trình',meta.runs)}${careerCard('Ngày đã chơi',meta.totalDays)}${careerCard('Điểm sự nghiệp',meta.careerPoints)}${careerCard('Tài sản kỷ lục',money(meta.bestNetWorth))}</div><div class="grid3">${slots.map(({i,s})=>slotCard(i,s)).join('')}</div><div class="card" style="margin-top:12px"><div class="row between"><div><h3>Tiến trình chung</h3><div class="muted mini">Mở khóa thêm cách khởi đầu và thử thách. Không cộng tiền trực tiếp vào ván mới.</div></div><div class="tag">${meta.unlockedOrigins.length}/${ORIGINS.length} kiểu khởi đầu</div></div><div class="unlock-list" style="margin-top:10px">${ORIGINS.map(o=>`<span class="tag ${meta.unlockedOrigins.includes(o.id)?'':'warn'}">${meta.unlockedOrigins.includes(o.id)?'✓':'🔒'} ${o.name}</span>`).join('')}</div></div><div class="footer-note">Game lưu riêng trong trình duyệt, không dùng dữ liệu KanBan.</div></div></div>`;document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>openSlot(+b.dataset.load));document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>newRunModal(+b.dataset.new));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const i=+b.dataset.delete;if(confirm('Xóa hành trình ở ô lưu này? Tiến trình sự nghiệp chung vẫn được giữ.')){eraseSlot(i);startScreen()}})}
function careerCard(a,b){return`<div class="stat"><span>${a}</span><b>${b}</b></div>`}
function slotCard(i,s){if(!s)return`<div class="card slot empty"><div><span class="tag">Ô lưu ${i}</span><h3>Chưa có hành trình</h3><p class="muted">Tạo một công ty mới và bắt đầu từ Ngày 1.</p></div><button class="btn primary" data-new="${i}">Tạo hành trình mới</button></div>`;return`<div class="card slot"><div><span class="tag">Ô lưu ${i}</span><h3>${esc(s.company)}</h3><div class="big">Ngày ${s.day}</div><p class="muted">${ORIGINS.find(o=>o.id===s.origin)?.name||'Hành trình'} · ${s.status==='playing'?'Đang kinh doanh':'Đã kết thúc'}</p><div class="mini">Tài sản ước tính: <b>${money(netWorth(s))}</b></div></div><div class="slot-actions"><button class="btn primary" data-load="${i}">${s.status==='playing'?'Tiếp tục':'Xem lại'}</button><button class="btn danger" data-delete="${i}">Xóa</button></div></div>`}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function newRunModal(i){modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-card"><h2>Tạo hành trình mới</h2><p class="muted">Mỗi ô lưu là một thế giới riêng. Các mở khóa thuộc Hồ sơ sự nghiệp dùng chung.</p><div class="form-grid"><label>Tên công ty<input id="companyName" class="input" value="Hoài Phát Logistics" maxlength="40"></label><label>Kiểu khởi đầu<select id="originSelect" class="select">${ORIGINS.filter(o=>meta.unlockedOrigins.includes(o.id)).map(o=>`<option value="${o.id}">${o.name}</option>`).join('')}</select></label></div><div id="originInfo" class="option-cards" style="margin:12px 0">${ORIGINS.map(o=>`<div class="origin ${meta.unlockedOrigins.includes(o.id)?'':'locked'}"><b>${meta.unlockedOrigins.includes(o.id)?'':'🔒 '}${o.name}</b><span class="mini muted">${o.desc}</span></div>`).join('')}</div><div class="row between"><button class="btn" id="cancelNew">Hủy</button><button class="btn primary" id="createNew">Bắt đầu Ngày 1</button></div></div>`;document.body.appendChild(modal);$('#cancelNew').onclick=()=>modal.remove();$('#createNew').onclick=()=>{const name=$('#companyName').value.trim()||'Hoài Phát Logistics';const origin=$('#originSelect').value;slot=i;state=createState(name,origin);selectedShipId='ship1';selectedPort='saigon';save();modal.remove();renderGame()}}
function openSlot(i){const s=loadSlot(i);if(!s)return;slot=i;state=s;selectedShipId=state.ships[0]?.id;selectedPort=state.ships[0]?.port||'saigon';tab='tongquan';renderGame()}
function renderGame(){if(!state){startScreen();return}const playable=state.status==='playing';app.innerHTML=`<div class="shell"><div class="top"><div class="content"><div class="top-row"><div class="brand"><div class="brand-mark">TL</div><div><h1>${esc(state.company)}</h1><small>${ORIGINS.find(o=>o.id===state.origin)?.name||''} · Ô lưu ${slot}</small></div></div><div class="top-actions"><span class="day-pill">Ngày ${state.day}</span><button class="btn ghost" id="backSlots">3 ô lưu</button>${playable?`<button class="btn primary next-btn" id="nextDay">QUA NGÀY →</button>`:''}</div></div><div class="stats">${stat('Tiền mặt',money(state.cash),state.cash<0?'down':'')}${stat('Tài sản',money(netWorth()),'')}${stat('Nợ',money(state.debt),state.debt>state.cash?'down':'')}${stat('Danh tiếng',state.reputation,'')}${stat('Tàu',state.ships.length,'')}${stat('Nhân viên',state.staff,'')}</div><div class="nav">${[['tongquan','Tổng quan'],['thitruong','Thị trường'],['tautuyen','Tàu & tuyến'],['hopdong','Hợp đồng'],['tintuc','Tin tức'],['taichinh','Tài chính'],['doithu','Đối thủ'],['nhatky','Nhật ký']].map(x=>`<button data-tab="${x[0]}" class="${tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</div></div></div><main class="content">${renderTab()}</main></div>`;$('#backSlots').onclick=()=>{save();startScreen()};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderGame()});if(playable)$('#nextDay').onclick=nextDay;bindTab();if(state.events?.length)showPendingEvent()}
function stat(a,b,c=''){return`<div class="stat"><span>${a}</span><b class="${c}">${b}</b></div>`}
function renderTab(){if(tab==='thitruong')return marketView();if(tab==='tautuyen')return fleetView();if(tab==='hopdong')return contractView();if(tab==='tintuc')return newsView();if(tab==='taichinh')return financeView();if(tab==='doithu')return rivalsView();if(tab==='nhatky')return journalView();return overviewView()}
function overviewView(){const brief=buildBrief();return`<div class="grid"><div class="card"><div class="screen-title"><div><h2>Bản tin sáng · Ngày ${state.day}</h2><div class="muted mini">Chỉ những việc đáng chú ý để anh quyết định trước khi qua ngày.</div></div><span class="tag">${brief.length} việc</span></div><div class="brief">${brief.map(x=>`<div class="brief-item"><strong>${x.title}</strong><span class="muted">${x.text}</span></div>`).join('')||'<div class="goodbox">Hôm nay khá yên. Anh có thể kiểm tra thị trường, điều tàu hoặc qua ngày.</div>'}</div></div><div><div class="card"><h2>Việc đang chạy</h2>${state.ships.map(shipMini).join('')}<div class="tooltip-note">Tàu đang đi vẫn tiếp tục di chuyển khi bấm Qua ngày.</div></div><div class="card" style="margin-top:12px"><h2>Tình hình nhanh</h2>${riskSummary()}</div></div></div>`}
function buildBrief(){const out=[];state.news.slice(0,4).forEach(n=>out.push({title:n.title,text:n.text}));const due=state.acceptedContracts.filter(c=>c.status==='active').sort((a,b)=>a.deadline-b.deadline)[0];if(due)out.push({title:'Hợp đồng sắp tới hạn',text:`${due.title} còn ${Math.max(0,due.deadline-state.day)} ngày, thưởng ${money(due.reward)}.`});const low=state.ships.find(s=>s.condition<55);if(low)out.push({title:'Tàu cần chú ý',text:`${low.name} chỉ còn ${Math.round(low.condition)}% tình trạng kỹ thuật.`});if(state.debt>state.creditLimit*.7)out.push({title:'Nợ đang cao',text:`Dư nợ ${money(state.debt)} đang gần hạn mức ${money(state.creditLimit)}.`});return out.slice(0,7)}
function riskSummary(){const cash=state.cash<50?'Dòng tiền mỏng':state.cash>300?'Dòng tiền khỏe':'Dòng tiền bình thường';const debt=state.debt>250?'Nợ cao':state.debt>100?'Nợ vừa':'Nợ thấp';return`<div class="brief"><div class="brief-item"><b>${cash}</b><div class="mini muted">Tiền mặt hiện có ${money(state.cash)}</div></div><div class="brief-item"><b>${debt}</b><div class="mini muted">Nợ ${money(state.debt)} / hạn mức ${money(state.creditLimit)}</div></div><div class="brief-item"><b>Thị trường đang ${state.effects.some(e=>e.type==='recession')?'chậm lại':state.effects.some(e=>e.type==='boom')?'sôi động':'ổn định'}</b><div class="mini muted">Hãy xem Tin tức trước khi gom hàng lớn.</div></div></div>`}
function shipMini(s){return`<div class="ship"><div class="row between"><b>${s.name}</b><span class="tag">${s.dest?`Đang tới ${pname(s.dest)}`:pname(s.port)}</span></div><div class="mini muted">Khoang ${cargoQty(s)}/${s.cap} · Tình trạng ${Math.round(s.condition)}%</div>${s.dest?`<div class="progress" style="margin-top:7px"><i style="width:${Math.max(10,100-(s.eta*22))}%"></i></div><div class="mini muted">Còn khoảng ${s.eta} ngày</div>`:''}</div>`}
function cargoQty(s){return s.cargo.reduce((a,c)=>a+c.qty,0)}
function marketView(){const ship=state.ships.find(s=>s.id===selectedShipId)||state.ships[0];if(ship&&!ship.dest)selectedPort=ship.port;const m=state.markets[selectedPort];return`<div class="card"><div class="screen-title"><div><h2>Thị trường · ${pname(selectedPort)}</h2><div class="muted mini">Giá thay đổi theo hàng tồn, sản xuất, nhu cầu, đối thủ và sự kiện.</div></div><div class="market-controls"><select id="marketPort" class="select">${PORTS.map(p=>`<option value="${p.id}" ${p.id===selectedPort?'selected':''}>${p.name}</option>`).join('')}</select><select id="marketShip" class="select">${state.ships.map(s=>`<option value="${s.id}" ${s.id===selectedShipId?'selected':''}>${s.name}</option>`).join('')}</select></div></div>${ship&&ship.port!==selectedPort?`<div class="notice">${ship.name} đang ở ${pname(ship.port)} nên chỉ xem được giá ở đây, chưa thể mua/bán tại ${pname(selectedPort)}.</div>`:''}<div style="overflow:auto"><table class="table"><thead><tr><th>Hàng</th><th class="num">Giá</th><th class="num">Tồn</th><th>Xu hướng</th><th class="num">Trên tàu</th><th>Giao dịch</th></tr></thead><tbody>${GOODS.map(g=>{const x=m[g.id],qty=ship?.cargo.find(c=>c.good===g.id)?.qty||0;return`<tr><td><b>${g.icon} ${g.name}</b></td><td class="num">${money(x.price)}</td><td class="num">${Math.round(x.stock)}</td><td class="${x.trend>1?'up':x.trend<-1?'down':''}">${x.trend>1?'▲ tăng':x.trend<-1?'▼ giảm':'• ổn'}</td><td class="num">${qty}</td><td><div class="row"><input class="input" style="width:70px" type="number" min="1" value="10" data-qty="${g.id}"><button class="btn" data-buy="${g.id}" ${!ship||ship.dest||ship.port!==selectedPort?'disabled':''}>Mua</button><button class="btn" data-sell="${g.id}" ${!ship||ship.dest||ship.port!==selectedPort||qty<=0?'disabled':''}>Bán</button></div></td></tr>`}).join('')}</tbody></table></div></div>`}
function fleetView(){const ship=state.ships.find(s=>s.id===selectedShipId)||state.ships[0];return`<div class="grid"><div class="card"><h2>Đội tàu</h2>${state.ships.map(s=>`<button class="ship ${s.id===ship?.id?'selected':''}" style="display:block;width:100%;text-align:left" data-ship="${s.id}"><div class="row between"><b>${s.name}</b><span>${s.dest?'Đang đi':'Đang đậu'}</span></div><div class="mini muted">${s.dest?`${pname(s.port)} → ${pname(s.dest)} · còn ${s.eta} ngày`:pname(s.port)} · Khoang ${cargoQty(s)}/${s.cap} · Máy ${Math.round(s.condition)}%</div></button>`).join('')}<button class="btn" id="buyShip">Mua thêm tàu</button></div><div class="card"><h2>Điều tàu</h2>${ship?routePanel(ship):'<div class="muted">Chưa có tàu.</div>'}</div></div>`}
function routePanel(s){if(s.dest)return`<div class="notice"><b>${s.name}</b> đang trên đường tới ${pname(s.dest)}.<br>Còn ${s.eta} ngày. Hàng trên tàu: ${cargoQty(s)}/${s.cap}.</div>`;const links=ROUTES[s.port]||{};return`<div class="ship selected"><b>${s.name}</b><div class="mini muted">Đang ở ${pname(s.port)} · Sức chở ${s.cap} · Tình trạng ${Math.round(s.condition)}%</div></div><h3>Chọn nơi đến</h3><div class="brief">${Object.entries(links).map(([p,d])=>`<div class="brief-item row between"><div><b>${pname(p)}</b><div class="mini muted">Khoảng ${Math.max(1,Math.ceil(d/(SHIP_TYPES.find(t=>t.id===s.type)?.speed||1)))} ngày</div></div><button class="btn primary" data-travel="${p}">Khởi hành</button></div>`).join('')}</div><div class="tooltip-note">Khởi hành ngay. Tàu chỉ di chuyển khi bấm Qua ngày.</div>`}
function contractView(){generateContractsIfNeeded();return`<div class="grid"><div class="card"><h2>Hợp đồng đang làm</h2>${state.acceptedContracts.filter(c=>c.status==='active').map(contractCard).join('')||'<div class="muted">Chưa có hợp đồng đang làm.</div>'}</div><div class="card"><h2>Cơ hội mới</h2>${state.contracts.map(c=>`<div class="contract"><div class="row between"><b>${c.title}</b><span class="tag">${c.deadline-state.day} ngày</span></div><div class="mini muted">Giao ${c.qty} ${gname(c.good)} tới ${pname(c.dest)} · Thưởng ${money(c.reward)}</div><button class="btn primary" data-accept="${c.id}" style="margin-top:8px">Nhận hợp đồng</button></div>`).join('')||'<div class="muted">Hôm nay chưa có hợp đồng mới.</div>'}</div></div>`}
function contractCard(c){const delivered=deliveredAt(c.dest,c.good);return`<div class="contract"><div class="row between"><b>${c.title}</b><span class="tag ${c.deadline-state.day<=2?'bad':'warn'}">Còn ${Math.max(0,c.deadline-state.day)} ngày</span></div><div class="mini muted">Cần ${c.qty} ${gname(c.good)} tại ${pname(c.dest)} · Có sẵn ở đó: ${delivered}</div><div class="row" style="margin-top:8px"><button class="btn primary" data-deliver="${c.id}">Giao hàng</button><span class="mini">Thưởng ${money(c.reward)}</span></div></div>`}
function newsView(){return`<div class="grid"><div class="card"><h2>Tin mới</h2><div class="log">${state.news.map(n=>`<div class="log-item"><div class="row between"><b>${n.title}</b><span class="tag ${n.kind==='Tin đồn'?'warn':n.kind==='Cảnh báo'?'bad':'info'}">${n.kind||'Tin tức'}</span></div><div class="mini muted">Ngày ${n.day} · ${n.text}</div></div>`).join('')||'<div class="muted">Chưa có tin mới.</div>'}</div></div><div class="card"><h2>Tác động đang còn hiệu lực</h2>${state.effects.map(e=>`<div class="brief-item"><b>${effectName(e.type)}</b><div class="mini muted">Còn ${e.days} ngày</div></div>`).join('')||'<div class="goodbox">Không có biến động lớn kéo dài.</div>'}</div></div>`}
function financeView(){return`<div class="grid"><div class="card"><h2>Tài chính</h2><div class="brief"><div class="brief-item row between"><span>Tiền mặt</span><b>${money(state.cash)}</b></div><div class="brief-item row between"><span>Dư nợ</span><b>${money(state.debt)}</b></div><div class="brief-item row between"><span>Hạn mức</span><b>${money(state.creditLimit)}</b></div><div class="brief-item row between"><span>Tài sản ước tính</span><b>${money(netWorth())}</b></div><div class="brief-item row between"><span>Lương mỗi 30 ngày</span><b>${money(state.monthlySalary)}</b></div></div></div><div class="card"><h2>Vay & trả nợ</h2><p class="muted mini">Lãi vay được tính mỗi 30 ngày. Vay giúp mở rộng nhanh nhưng dễ phá sản khi thị trường xấu.</p><div class="row"><input id="loanAmt" class="input" type="number" min="10" step="10" value="50"><button class="btn primary" id="borrowBtn">Vay</button><button class="btn" id="repayBtn">Trả nợ</button></div><div class="tooltip-note">Có thể vay tối đa phần hạn mức còn lại. Mức cơ bản: khoảng 2% mỗi tháng.</div></div></div>`}
function rivalsView(){return`<div class="card"><h2>Các hãng đang hoạt động</h2><p class="muted mini">Họ dùng cùng thị trường, có thể gom hàng, bán tháo, mở rộng hoặc phá sản.</p>${state.ai.map(c=>`<div class="company"><div><b>${c.name}</b><div class="mini muted">Phong cách: ${c.style} · Đội tàu khoảng ${c.fleet}</div></div><div class="num"><b>${money(c.cash)}</b><div class="mini ${c.health<40?'down':'muted'}">Sức khỏe ${Math.round(c.health)}%</div></div></div>`).join('')}</div>`}
function journalView(){return`<div class="card"><div class="screen-title"><div><h2>Nhật ký hành trình</h2><div class="muted mini">Ghi lại các quyết định và biến cố đáng nhớ.</div></div><button class="btn danger" id="retireBtn">Kết thúc hành trình</button></div><div class="log">${state.journal.map(j=>`<div class="log-item"><b>Ngày ${j.day}</b> · ${esc(j.text)}</div>`).join('')||'<div class="muted">Chưa có ghi chép.</div>'}</div></div>`}
function bindTab(){if(tab==='thitruong'){const p=$('#marketPort'),s=$('#marketShip');p.onchange=()=>{selectedPort=p.value;renderGame()};s.onchange=()=>{selectedShipId=s.value;renderGame()};document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>trade(b.dataset.buy,1));document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>trade(b.dataset.sell,-1))}if(tab==='tautuyen'){document.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>{selectedShipId=b.dataset.ship;renderGame()});document.querySelectorAll('[data-travel]').forEach(b=>b.onclick=()=>travel(b.dataset.travel));const bs=$('#buyShip');if(bs)bs.onclick=buyShipModal}if(tab==='hopdong'){document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>acceptContract(b.dataset.accept));document.querySelectorAll('[data-deliver]').forEach(b=>b.onclick=()=>deliverContract(b.dataset.deliver))}if(tab==='taichinh'){const br=$('#borrowBtn'),rp=$('#repayBtn');if(br)br.onclick=()=>loan(1);if(rp)rp.onclick=()=>loan(-1)}if(tab==='nhatky'){const r=$('#retireBtn');if(r)r.onclick=()=>finishRun(false,'Anh chủ động dừng hành trình để bắt đầu một chiến lược mới.')}}
function trade(good,dir){const ship=state.ships.find(s=>s.id===selectedShipId)||state.ships[0];if(!ship||ship.dest||ship.port!==selectedPort)return;const q=Math.max(1,+document.querySelector(`[data-qty="${good}"]`)?.value||1),mk=state.markets[selectedPort][good];if(dir>0){const room=ship.cap-cargoQty(ship),qty=Math.min(q,room,Math.floor(mk.stock),Math.floor(state.cash/mk.price));if(qty<=0)return toast('Không đủ tiền, hàng hoặc chỗ trống.');state.cash-=qty*mk.price;mk.stock-=qty;let c=ship.cargo.find(x=>x.good===good);if(c)c.qty+=qty;else ship.cargo.push({good,qty,avg:mk.price});state.stats.trades++;pushLog(`Mua ${qty} ${gname(good)} tại ${pname(selectedPort)} giá ${money(mk.price)}/đv.`)}else{const c=ship.cargo.find(x=>x.good===good);const qty=Math.min(q,c?.qty||0);if(qty<=0)return;const rev=qty*mk.price;state.cash+=rev;mk.stock+=qty;state.stats.revenue+=rev;state.stats.trades++;c.qty-=qty;if(c.qty<=0)ship.cargo=ship.cargo.filter(x=>x!==c);pushLog(`Bán ${qty} ${gname(good)} tại ${pname(selectedPort)} thu ${money(rev)}.`)}save();renderGame()}
function travel(dest){const s=state.ships.find(x=>x.id===selectedShipId);if(!s||s.dest)return;const d=ROUTES[s.port]?.[dest];if(!d)return;const speed=SHIP_TYPES.find(t=>t.id===s.type)?.speed||1;s.dest=dest;s.eta=Math.max(1,Math.ceil(d/speed));pushLog(`${s.name} rời ${pname(s.port)} đi ${pname(dest)}, dự kiến ${s.eta} ngày.`);save();renderGame()}
function buyShipModal(){const available=SHIP_TYPES.filter(t=>t.id==='anbinh'||meta.careerPoints>=3||t.id==='haiau');modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-card"><h2>Mua tàu</h2><p class="muted">Tàu mới xuất hiện tại Trạm Sài Gòn. Không có loại tàu tốt nhất; mỗi loại hợp một cách chơi.</p>${available.map(t=>`<div class="brief-item row between"><div><b>${t.name}</b><div class="mini muted">Khoang ${t.cap} · Tốc độ ${t.speed} · Bảo trì ${money(t.maint)}/tháng</div></div><button class="btn primary" data-buyship="${t.id}" ${state.cash<t.cost?'disabled':''}>${money(t.cost)}</button></div>`).join('')}<button class="btn" id="closeModal" style="margin-top:10px">Đóng</button></div>`;document.body.appendChild(modal);$('#closeModal').onclick=()=>modal.remove();modal.querySelectorAll('[data-buyship]').forEach(b=>b.onclick=()=>{const t=SHIP_TYPES.find(x=>x.id===b.dataset.buyship);if(state.cash<t.cost)return;state.cash-=t.cost;const n=state.ships.length+1;state.ships.push({id:'ship'+Date.now(),name:`${t.name} ${String(n).padStart(2,'0')}`,type:t.id,cap:t.cap,port:'saigon',dest:null,eta:0,cargo:[],condition:100});state.stats.maxShips=Math.max(state.stats.maxShips,state.ships.length);pushLog(`Mua tàu ${t.name} với giá ${money(t.cost)}.`);save();modal.remove();renderGame()})}
function generateContractsIfNeeded(){if(state.contracts.length>=3)return;while(state.contracts.length<3){const good=pick(GOODS).id,dest=pick(PORTS).id,qty=rnd(18,60),reward=qty*(state.markets[dest][good].price||20)*rnd(13,18)/10;state.contracts.push({id:'c'+Date.now()+Math.random(),title:`Giao ${gname(good)} cho ${pname(dest)}`,good,dest,qty,reward,deadline:state.day+rnd(5,12)})}save()}
function acceptContract(id){const i=state.contracts.findIndex(c=>c.id===id);if(i<0)return;if(state.acceptedContracts.filter(c=>c.status==='active').length>=3)return toast('Tối đa 3 hợp đồng đang làm.');const c=state.contracts.splice(i,1)[0];c.status='active';state.acceptedContracts.push(c);pushLog(`Nhận hợp đồng: ${c.title}.`);save();renderGame()}
function deliveredAt(port,good){return state.ships.filter(s=>!s.dest&&s.port===port).reduce((a,s)=>a+(s.cargo.find(c=>c.good===good)?.qty||0),0)}
function deliverContract(id){const c=state.acceptedContracts.find(x=>x.id===id&&x.status==='active');if(!c)return;let remain=c.qty;for(const s of state.ships.filter(s=>!s.dest&&s.port===c.dest)){const x=s.cargo.find(z=>z.good===c.good);if(!x)continue;const take=Math.min(remain,x.qty);x.qty-=take;remain-=take;if(x.qty<=0)s.cargo=s.cargo.filter(z=>z!==x);if(remain<=0)break}if(remain>0)return toast(`Còn thiếu ${remain} ${gname(c.good)} tại ${pname(c.dest)}.`);c.status='done';state.cash+=c.reward;state.reputation+=3;state.stats.contractsDone++;state.stats.revenue+=c.reward;pushLog(`Hoàn thành ${c.title}, nhận ${money(c.reward)}.`,'good');save();renderGame()}
function loan(dir){const amt=Math.max(10,+$('#loanAmt').value||50);if(dir>0){const room=state.creditLimit-state.debt;if(room<=0)return toast('Đã hết hạn mức vay.');const take=Math.min(amt,room);state.debt+=take;state.cash+=take;pushLog(`Vay thêm ${money(take)}.`)}else{const pay=Math.min(amt,state.debt,Math.max(0,state.cash));if(pay<=0)return;state.debt-=pay;state.cash-=pay;pushLog(`Trả nợ ${money(pay)}.`)}save();renderGame()}
function nextDay(){if(state.events.length)return showPendingEvent();const before=state.cash;state.day++;meta.totalDays++;processEffects();processMarkets();processShips();processAI();processContracts();processScheduled();processMonthly();maybeEvent();state.news=state.news.slice(0,20);const dayProfit=state.cash-before;state.stats.bestDayProfit=Math.max(state.stats.bestDayProfit,dayProfit);meta.bestNetWorth=Math.max(meta.bestNetWorth,netWorth());saveMeta();save();if(checkBankruptcy())return;renderGame()}
function processEffects(){for(const e of state.effects)e.days--;state.effects=state.effects.filter(e=>e.days>0)}
function processMarkets(){const recession=state.effects.some(e=>e.type==='recession'),boom=state.effects.some(e=>e.type==='boom'),energy=state.effects.some(e=>e.type==='energyCrisis');for(const p of PORTS){for(const g of GOODS){const m=state.markets[p.id][g.id],prod=p.prod[g.id]||0,cons=p.cons[g.id]||0;const demandMul=recession ? .78 : (boom ? 1.25 : 1);m.stock=clamp(m.stock+prod*(.75+Math.random()*.5)-cons*demandMul*(.75+Math.random()*.5),3,240);let scarcity=(80-m.stock)/90;let eventAdj=0;for(const e of state.effects){if(e.port&&e.port!==p.id)continue;if(e.good&&e.good!==g.id)continue;if(e.type==='boostDemand'||e.type==='shortage')eventAdj+=.18;if(e.type==='floodSupply')eventAdj-=.2;if(e.type==='festival'&&(g.id==='luongthuc'||g.id==='hanglanh'))eventAdj+=.22;if(e.type==='medicineDemand'&&g.id==='duocpham')eventAdj+=.3;if(e.type==='industrialTax'&&(g.id==='maymoc'||g.id==='dientu'))eventAdj+=.14;if(e.type==='energyCrisis'&&g.id==='nhienlieu')eventAdj+=.35}if(energy&&g.id==='nhienlieu')eventAdj+=.28;const target=Math.max(3,g.base*(1+scarcity+eventAdj));const old=m.price;m.price=Math.max(3,old*.58+target*.42+rnd(-1,1));m.trend=m.price-old;m.history.push(m.price);if(m.history.length>30)m.history.shift()}}}
function processShips(){for(const s of state.ships){if(s.dest){s.eta--;s.condition=clamp(s.condition-(.4+Math.random()*.8),5,100);if(s.eta<=0){s.port=s.dest;s.dest=null;s.eta=0;state.news.unshift({day:state.day,title:`${s.name} đã tới nơi`,text:`Tàu đã cập ${pname(s.port)} với ${cargoQty(s)} đơn vị hàng.`,kind:'Vận hành'});pushLog(`${s.name} cập ${pname(s.port)}.`)}}}}
function processAI(){for(const c of state.ai){if(c.health<=0)continue;const p=pick(PORTS),g=pick(GOODS),m=state.markets[p.id][g.id];const qty=rnd(5,30);if(Math.random()<.55){const cost=qty*m.price;if(c.cash>cost){c.cash-=cost;m.stock=Math.max(2,m.stock-qty)}}else{c.cash+=qty*m.price*.9;m.stock=Math.min(240,m.stock+qty)}c.cash-=c.fleet*.35;c.health=clamp(50+c.cash/25-c.fleet*3,0,100);if(c.cash<0||c.health<=3){c.health=0;state.news.unshift({day:state.day,title:`${c.name} ngừng hoạt động`,text:'Hãng này không còn đủ tiền để duy trì đội tàu và rút khỏi thị trường.',kind:'Cảnh báo'});pushLog(`${c.name} phá sản. Thị trường mất đi một đối thủ.`)}}}
function processContracts(){for(const c of state.acceptedContracts.filter(x=>x.status==='active'))if(state.day>c.deadline){c.status='failed';state.reputation-=5;state.cash-=Math.min(20,Math.max(0,state.cash*.05));pushLog(`Hợp đồng ${c.title} bị trễ và thất bại.`,'bad');state.news.unshift({day:state.day,title:'Hợp đồng thất bại',text:`${c.title} đã quá hạn. Danh tiếng bị giảm.`,kind:'Cảnh báo'})}state.contracts=state.contracts.filter(c=>c.deadline>=state.day);if(Math.random()<.35&&state.contracts.length<4)generateContractsIfNeeded()}
function processScheduled(){const due=state.scheduled.filter(x=>x.day<=state.day);state.scheduled=state.scheduled.filter(x=>x.day>state.day);for(const x of due){state.news.unshift({day:state.day,title:x.title,text:x.text,kind:x.kind||'Tin tức'});if(x.effect)state.effects.push(x.effect);pushLog(x.text)}}
function processMonthly(){if(state.day%30!==0)return;const interest=state.debt*(state.effects.some(e=>e.type==='creditCrisis') ? .035 : .02),maint=state.ships.reduce((a,s)=>a+(SHIP_TYPES.find(t=>t.id===s.type)?.maint||2),0);const total=state.monthlySalary+interest+maint;state.cash-=total;pushLog(`Cuối tháng: lương ${money(state.monthlySalary)}, lãi vay ${money(interest)}, bảo trì ${money(maint)}.`);state.news.unshift({day:state.day,title:'Chốt chi phí tháng',text:`Tổng chi định kỳ ${money(total)}.`,kind:'Tài chính'})}
function maybeEvent(){const chance=Math.min(.82,.4+state.day/1200);if(Math.random()>chance)return;let groups=['market','transport','staff','ship','business','social','government','personal','competitor'];if(state.day>40)groups.push('underground');if(state.day>80&&Math.random()<.16)groups.push('world');const group=pick(groups),tpl=pick(EVENT_TEMPLATES[group]),port=pick(PORTS),good=pick(GOODS),company=pick(state.ai.filter(c=>c.health>0)||state.ai);const title=tpl[0],text=tpl[1].replace('{port}',port.name).replace('{good}',good.name).replace('{company}',company?.name||'một đối thủ'),code=tpl[2];const ev=buildEvent(group,title,text,code,{port:port.id,good:good.id,company:company?.id});state.events.push(ev);meta.discoveredEvents=[...new Set([...meta.discoveredEvents,code])];saveMeta()}
function buildEvent(group,title,text,code,ctx){const base={id:'e'+Date.now()+Math.random(),group,title,text,code,ctx,choices:[]};const C=(label,desc,action)=>({label,desc,action});switch(code){case'boostDemand':case'shortage':base.choices=[C('Theo dõi thêm','Không tốn tiền, chưa chắc cơ hội còn lâu.','watch'),C('Mua tin chi tiết','Chi 5 triệu để biết rõ hơn tình hình.','intel')];break;case'floodSupply':base.choices=[C('Bán sớm hàng đang có','Nếu đang giữ mặt hàng này, ưu tiên giảm rủi ro.','sellSignal'),C('Chờ giá xuống','Không làm gì lúc này.','watch')];break;case'staffRaise':base.choices=[C('Tăng phụ cấp','Chi phí tháng tăng 2 triệu, tinh thần tốt hơn.','raise'),C('Từ chối','Giữ chi phí nhưng tinh thần giảm.','refuseRaise')];break;case'hireTalent':base.choices=[C('Tuyển ngay','Tốn 12 triệu và tăng chi phí lương 3 triệu/tháng.','hire'),C('Không tuyển','Giữ bộ máy gọn.','none')];break;case'shipHeat':case'cargoRepair':case'inspection':base.choices=[C('Sửa ngay','Chi 10 triệu, giữ tàu ổn định.','repair'),C('Tạm thời bỏ qua','Không tốn tiền nhưng tàu xuống cấp hơn.','ignoreRepair')];break;case'specialContract':base.choices=[C('Nhận cơ hội','Tạo một hợp đồng thưởng cao.','newContract'),C('Từ chối','Không gánh thêm việc.','none')];break;case'smuggleOffer':base.choices=[C('Nhận việc','Nhận 45 triệu nhưng danh tiếng giảm và có rủi ro bị phạt.','smuggle'),C('Từ chối','Không kiếm tiền nhưng giữ uy tín.','refuseSmuggle')];break;case'buyIntel':base.choices=[C('Mua tin 8 triệu','Có cơ hội biết sớm một biến động giá.','buyIntel'),C('Không mua','Tiết kiệm tiền.','none')];break;case'advanceSalary':base.choices=[C('Cho ứng 5 triệu','Tinh thần nhân viên tăng.','advance'),C('Từ chối','Không mất tiền nhưng tinh thần giảm nhẹ.','noneMorale')];break;case'catMascot':base.choices=[C('Giữ lại làm linh vật','Tinh thần +3.','cat'),C('Gửi về cảng','Không ảnh hưởng.','none')];break;case'cheapShip':base.choices=[C('Xem xét mua','Có thể mua một tàu An Bình cũ giá 95 triệu.','cheapShip'),C('Bỏ qua','Giữ tiền mặt.','none')];break;case'energyCrisis':case'recession':case'boom':case'creditCrisis':base.choices=[C('Điều chỉnh kế hoạch','Ghi nhận biến cố và tự thay đổi chiến lược.','worldAccept')];break;default:base.choices=[C('Chấp nhận tình hình','Không can thiệp trực tiếp.','watch'),C('Chủ động xử lý','Chi một khoản nhỏ để giảm rủi ro.','mitigate')]}return base}
function showPendingEvent(){if(!state?.events?.length)return;const ev=state.events[0];if(document.querySelector('.modal'))return;modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-card event ${['world','ship'].includes(ev.group)?'urgent':''}"><div class="row between"><span class="tag">${eventGroupName(ev.group)}</span><span class="mini muted">Ngày ${state.day}</span></div><h2 style="margin-top:8px">${ev.title}</h2><p>${ev.text}</p><div class="choice">${ev.choices.map((c,i)=>`<button data-choice="${i}"><b>${c.label}</b><div class="mini muted">${c.desc}</div></button>`).join('')}</div></div>`;document.body.appendChild(modal);modal.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>resolveEvent(ev,+b.dataset.choice))}
function resolveEvent(ev,i){const ch=ev.choices[i];applyEventAction(ch.action,ev);pushLog(`${ev.title}: ${ch.label}.`);state.news.unshift({day:state.day,title:ev.title,text:`${ev.text} Quyết định: ${ch.label}.`,kind:eventGroupName(ev.group)});state.events.shift();save();modal.remove();modal=null;if(state.events.length)showPendingEvent();else renderGame()}
function applyEventAction(a,ev){const ctx=ev.ctx||{};switch(a){case'intel':state.cash-=5;state.reputation+=1;state.scheduled.push({day:state.day+1,title:'Tin xác nhận',text:`Nguồn tin cho biết ${gname(ctx.good)} tại ${pname(ctx.port)} có khả năng tiếp tục tăng giá trong vài ngày.`,kind:'Tin đồn',effect:{type:'boostDemand',good:ctx.good,port:ctx.port,days:4}});break;case'raise':state.monthlySalary+=2;state.morale+=8;break;case'refuseRaise':state.morale-=8;break;case'hire':if(state.cash>=12){state.cash-=12;state.staff++;state.monthlySalary+=3;state.morale+=4}break;case'repair':state.cash-=10;state.ships.forEach(s=>s.condition=clamp(s.condition+12,0,100));break;case'ignoreRepair':state.ships.forEach(s=>s.condition=clamp(s.condition-8,0,100));break;case'newContract':generateContractsIfNeeded();if(state.contracts[0])state.contracts[0].reward*=1.3;break;case'smuggle':state.cash+=45;state.reputation-=10;if(Math.random()<.25){state.scheduled.push({day:state.day+rnd(2,6),title:'Bị kiểm tra lại',text:'Chuyến hàng kín trước đây bị phát hiện dấu hiệu bất thường. Công ty bị phạt 35 triệu.',kind:'Cảnh báo',effect:null});state.cash-=35}break;case'buyIntel':if(state.cash>=8){state.cash-=8;state.scheduled.push({day:state.day+1,title:'Tin từ môi giới',text:`Một đơn hàng lớn có thể làm giá ${gname(ctx.good)} tại ${pname(ctx.port)} tăng.`,kind:'Tin đồn',effect:{type:'boostDemand',good:ctx.good,port:ctx.port,days:5}})}break;case'advance':state.cash-=5;state.morale+=6;break;case'noneMorale':state.morale-=3;break;case'cat':state.morale+=3;break;case'cheapShip':if(state.cash>=95){state.cash-=95;state.ships.push({id:'ship'+Date.now(),name:`An Bình Cũ ${state.ships.length+1}`,type:'anbinh',cap:45,port:'saigon',dest:null,eta:0,cargo:[],condition:68});state.stats.maxShips=Math.max(state.stats.maxShips,state.ships.length)}break;case'worldAccept':state.effects.push({type:ev.code,days:rnd(25,55)});break;case'mitigate':state.cash-=4;state.reputation+=1;break;case'watch':if(['boostDemand','shortage','floodSupply','festival','medicineDemand','strike','fuelUp','fuelDown','industrialTax'].includes(ev.code))state.effects.push({type:ev.code,port:ctx.port,good:ctx.good,days:rnd(3,8)});break;default:break}}
function eventGroupName(g){return({market:'Thị trường',transport:'Vận chuyển',staff:'Nhân viên',ship:'Tàu',business:'Kinh doanh',social:'Xã hội',government:'Chính sách',underground:'Đề nghị mờ ám',personal:'Cá nhân',competitor:'Đối thủ',world:'Biến cố lớn'})[g]||'Sự kiện'}
function effectName(t){return({boostDemand:'Nhu cầu tăng',shortage:'Thiếu hàng',floodSupply:'Hàng về nhiều',festival:'Lễ hội',medicineDemand:'Nhu cầu dược phẩm',strike:'Đình công',fuelUp:'Chi phí nhiên liệu tăng',fuelDown:'Nhiên liệu được hỗ trợ',industrialTax:'Thuế hàng công nghiệp',energyCrisis:'Khủng hoảng năng lượng',recession:'Suy giảm kinh tế',boom:'Bùng nổ đầu tư',creditCrisis:'Khủng hoảng tín dụng'})[t]||t}
function checkBankruptcy(){const nw=netWorth();if(state.cash<-80||nw<-120||state.debt>state.creditLimit+20){finishRun(true,'Công ty không còn đủ khả năng thanh toán và buộc phải dừng hoạt động.');return true}if(state.day>=500&&nw>=5000){finishRun(false,'Công ty đã đạt quy mô lớn và hoàn thành một hành trình thành công.',true);return true}return false}
function finishRun(bankrupt,reason,win=false){if(!state||state.status!=='playing')return;state.status=bankrupt?'bankrupt':win?'won':'retired';meta.runs++;if(bankrupt)meta.bankruptcies++;if(win)meta.wins++;const score=Math.max(1,Math.floor(state.day/40)+Math.floor(Math.max(0,netWorth())/500)+(state.origin==='taytrang'?3:0)+(win?8:0));meta.careerPoints+=score;meta.bestNetWorth=Math.max(meta.bestNetWorth,netWorth());meta.history.unshift({company:state.company,day:state.day,net:netWorth(),result:state.status,score});meta.history=meta.history.slice(0,50);for(const o of ORIGINS)if(meta.careerPoints>=o.unlock&&!meta.unlockedOrigins.includes(o.id))meta.unlockedOrigins.push(o.id);saveMeta();save();modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-card"><span class="tag ${bankrupt?'bad':''}">${bankrupt?'PHÁ SẢN':win?'HOÀN THÀNH':'KẾT THÚC'}</span><h2 style="margin-top:8px">Tổng kết ${state.company}</h2><p>${reason}</p><div class="grid3"><div class="stat"><span>Số ngày</span><b>${state.day}</b></div><div class="stat"><span>Tài sản cuối</span><b>${money(netWorth())}</b></div><div class="stat"><span>Điểm sự nghiệp</span><b>+${score}</b></div></div><div class="brief" style="margin-top:10px"><div class="brief-item">Giao dịch: <b>${state.stats.trades}</b> · Hợp đồng hoàn thành: <b>${state.stats.contractsDone}</b></div><div class="brief-item">Nhiều tàu nhất: <b>${state.stats.maxShips}</b> · Danh tiếng cuối: <b>${state.reputation}</b></div></div><p class="muted mini">Điểm sự nghiệp mở thêm kiểu khởi đầu và lựa chọn mới, nhưng không cộng tiền trực tiếp cho ván sau.</p><button class="btn primary" id="toSlots">Về 3 ô lưu</button></div>`;document.body.appendChild(modal);$('#toSlots').onclick=()=>{modal.remove();startScreen()}}
startScreen();
})();
