(()=>{
'use strict';
const app=document.querySelector('#app');
const $=s=>document.querySelector(s);
const META_KEY='tlv_meta_v2';
const SLOT_KEY=i=>`tlv_slot_${i}_v2`;
const GOODS=[
{id:'thep',name:'Thép',base:18,group:'công nghiệp'},
{id:'nhienlieu',name:'Nhiên liệu',base:24,group:'năng lượng'},
{id:'linhkien',name:'Linh kiện',base:42,group:'công nghiệp'},
{id:'luongthuc',name:'Lương thực',base:12,group:'dân sinh'},
{id:'duocpham',name:'Dược phẩm',base:55,group:'dân sinh'},
{id:'maymoc',name:'Máy móc',base:68,group:'công nghiệp'},
{id:'nongsan',name:'Nông sản',base:15,group:'nông nghiệp'},
{id:'khoangsan',name:'Khoáng sản',base:30,group:'nguyên liệu'},
{id:'hanglanh',name:'Hàng lạnh',base:46,group:'dịch vụ'},
{id:'dientu',name:'Điện tử',base:75,group:'công nghệ'}
];
const PORTS=[
{id:'saigon',name:'Trạm Sài Gòn',type:'Thương mại',prod:{dientu:13,duocpham:8},cons:{luongthuc:14,nhienlieu:10,khoangsan:5}},
{id:'cuulong',name:'Cảng Cửu Long',type:'Nông nghiệp',prod:{nongsan:18,luongthuc:14},cons:{maymoc:7,nhienlieu:8,dientu:4}},
{id:'haivan',name:'Cảng Hải Vân',type:'Trung chuyển',prod:{},cons:{thep:8,nhienlieu:8,luongthuc:8}},
{id:'taynguyen',name:'Khu mỏ Tây Nguyên',type:'Khai khoáng',prod:{khoangsan:19,thep:8},cons:{luongthuc:11,maymoc:8,duocpham:5}},
{id:'binhduong',name:'Khu công nghiệp Bình Dương',type:'Công nghiệp',prod:{maymoc:13,linhkien:12},cons:{thep:15,nhienlieu:12,khoangsan:10}},
{id:'phuquoc',name:'Cảng Phú Quốc',type:'Dịch vụ',prod:{hanglanh:12,nongsan:7},cons:{duocpham:7,dientu:9,luongthuc:8}},
{id:'halong',name:'Cảng Hạ Long',type:'Đóng tàu',prod:{thep:9,maymoc:7},cons:{linhkien:12,nhienlieu:11,khoangsan:6}},
{id:'dalat',name:'Trạm Đà Lạt',type:'Nông nghiệp công nghệ',prod:{nongsan:12,hanglanh:10},cons:{maymoc:5,dientu:6,nhienlieu:5}}
];
const ROUTES={saigon:{cuulong:2,binhduong:1,phuquoc:3,dalat:2},cuulong:{saigon:2,phuquoc:2,haivan:4},haivan:{cuulong:4,taynguyen:3,halong:4,binhduong:3},taynguyen:{haivan:3,binhduong:2,dalat:2},binhduong:{saigon:1,haivan:3,taynguyen:2,dalat:2},phuquoc:{saigon:3,cuulong:2},halong:{haivan:4},dalat:{saigon:2,taynguyen:2,binhduong:2}};
const RIVALS=[
{id:'namphuong',name:'Vận tải Nam Phương',style:'safe',styleLabel:'an toàn'},
{id:'giaphat',name:'Thương nghiệp Gia Phát',style:'spec',styleLabel:'đầu cơ'},
{id:'haidang',name:'Hải Đăng Logistics',style:'contract',styleLabel:'hợp đồng'},
{id:'truongson',name:'Vận tải Trường Sơn',style:'risk',styleLabel:'tuyến khó'},
{id:'minhlong',name:'Công ty Minh Long',style:'growth',styleLabel:'mở rộng nhanh'},
{id:'cuulongcorp',name:'Tập đoàn Cửu Long',style:'heavy',styleLabel:'quy mô lớn'},
{id:'hungvuong',name:'Vận tải Hùng Vương',style:'fast',styleLabel:'tàu nhanh'},
{id:'daithanh',name:'Thương mại Đại Thành',style:'value',styleLabel:'gom hàng giá thấp'}
];
const ORIGINS=[
{id:'canbang',name:'Người mới lập nghiệp',desc:'Cân bằng, dễ làm quen.',cash:180,debt:0,credit:180,shipType:'anbinh',rep:0,unlock:0},
{id:'vantai',name:'Gia đình làm vận tải',desc:'Có tàu lớn hơn nhưng đi cùng khoản vay ban đầu.',cash:150,debt:80,credit:220,shipType:'songhong',rep:5,unlock:3},
{id:'nganhang',name:'Cựu nhân viên ngân hàng',desc:'Tiền đầu thấp hơn nhưng hạn mức vay tốt.',cash:120,debt:0,credit:320,shipType:'anbinh',rep:8,unlock:6},
{id:'chobuon',name:'Dân buôn lâu năm',desc:'Nhìn giá nhanh hơn, nhận tin đồn tốt hơn.',cash:160,debt:0,credit:160,shipType:'haiau',rep:-2,unlock:10},
{id:'taytrang',name:'Tay trắng',desc:'Khó nhất, ít vốn nhưng điểm sự nghiệp nhận thêm.',cash:80,debt:0,credit:120,shipType:'anbinh',rep:0,unlock:16}
];
const SHIP_TYPES=[
{id:'anbinh',name:'An Bình',cap:50,speed:1,cost:150,maint:2,fuel:1},
{id:'haiau',name:'Hải Âu',cap:38,speed:2,cost:210,maint:3,fuel:1.1},
{id:'songhong',name:'Sông Hồng',cap:90,speed:1,cost:330,maint:5,fuel:1.8},
{id:'bachdang',name:'Bạch Đằng',cap:65,speed:1,cost:285,maint:4,fuel:1.3}
];
const FACILITIES=[
{id:'warehouse',name:'Kho thường',cost:90,upkeep:2,desc:'Lưu tối đa 120 đơn vị hàng tại cảng này.'},
{id:'cold',name:'Kho lạnh',cost:130,upkeep:3,desc:'Hàng lạnh và dược phẩm giữ giá tốt hơn.'},
{id:'fuel',name:'Trạm nhiên liệu',cost:150,upkeep:3,desc:'Giảm chi phí di chuyển, có thể tạo thêm thu nhập nhỏ.'}
];
const HELP={
next:'Qua ngày sẽ làm cho toàn bộ thế giới chạy tiếp 1 ngày: tàu di chuyển, giá thay đổi, đối thủ hành động, hợp đồng giảm hạn, sự kiện mới có thể xuất hiện.',
market:'Giá thay đổi theo tồn kho, nhu cầu, đối thủ và sự kiện. Tồn kho thấp thường kéo giá lên.',
fleet:'Tàu chỉ thực sự đến nơi khi bạn bấm Qua ngày. Mỗi tàu có sức chở, tốc độ và chi phí khác nhau.',
contracts:'Hợp đồng đem dòng tiền ổn định nhưng có hạn chót. Nếu trễ, bạn mất danh tiếng và có thể bị phạt.',
finance:'Nợ giúp mở rộng nhanh nhưng dễ làm bạn vỡ dòng tiền. Hãy theo dõi tiền mặt và chi phí cuối tháng.',
facilities:'Cơ sở mở ra chiến thuật dài hơi: tích hàng chờ giá, bảo quản hàng lạnh hoặc giảm chi phí nhiên liệu.',
rivals:'Mỗi đối thủ có cách chơi riêng. Họ cùng mua bán trong một thị trường và có thể mở rộng hoặc phá sản.',
characters:'Nhân vật có lịch sử riêng. Quyết định của bạn có thể làm họ trung thành hơn, nghỉ việc hoặc giúp bạn mở cơ hội mới.',
collection:'Bộ sưu tập lưu những gì bạn đã gặp qua nhiều hành trình, giống tiến trình ngoài ván. Nó mở thêm cách bắt đầu nhưng không cho tiền trực tiếp.'
};
let state=null,meta=loadMeta(),slot=1,tab='tongquan',selectedPort='saigon',selectedShipId=null,modal=null;

function defaultMeta(){return {version:2,runs:0,wins:0,bankruptcies:0,totalDays:0,careerPoints:0,bestNetWorth:0,unlockedOrigins:['canbang'],discoveredEvents:[],discoveredChains:[],discoveredFacilities:[],discoveredCharacters:[],endings:[],history:[]};}
function loadMeta(){try{return Object.assign(defaultMeta(),JSON.parse(localStorage.getItem(META_KEY)||'{}'));}catch{return defaultMeta();}}
function saveMeta(){localStorage.setItem(META_KEY,JSON.stringify(meta));}
function loadSlot(i){try{return JSON.parse(localStorage.getItem(SLOT_KEY(i)));}catch{return null;}}
function save(){if(!state)return;state.updatedAt=Date.now();localStorage.setItem(SLOT_KEY(slot),JSON.stringify(state));}
function eraseSlot(i){localStorage.removeItem(SLOT_KEY(i));}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a;}
function pick(a){return a[Math.floor(Math.random()*a.length)];}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function money(v){const sign=v<0?'-':''; v=Math.abs(v); return sign + (v>=1000 ? (v/1000).toLocaleString('vi-VN',{maximumFractionDigits:2})+' tỷ' : v.toLocaleString('vi-VN',{maximumFractionDigits:1})+' tr');}
const pname=id=>PORTS.find(p=>p.id===id)?.name||id;
const gname=id=>GOODS.find(g=>g.id===id)?.name||id;
const sdef=id=>SHIP_TYPES.find(s=>s.id===id);
function tip(text){return `<span class="help" title="${esc(text)}">ⓘ</span>`;}
function ensureMetaArray(key,val){if(!meta[key].includes(val)){meta[key].push(val); saveMeta();}}

function createMarkets(){const markets={};
 for(const p of PORTS){markets[p.id]={};
  for(const g of GOODS){const bias=(p.prod[g.id]||0)-(p.cons[g.id]||0); const stock=clamp(80+bias*3+rnd(-15,18),20,180); const price=Math.max(4,g.base*(1+(70-stock)/120)+rnd(-2,2)); markets[p.id][g.id]={stock,price,trend:0,history:[price]};}
 }
 return markets;
}
function createCharacters(){
 return [
  {id:'char1',name:'Nguyễn Minh Tuấn',role:'Thuyền trưởng',trait:'cẩn thận',loyalty:64,mood:66,story:['Gia nhập công ty từ ngày 1.']},
  {id:'char2',name:'Lê Thanh Mai',role:'Phân tích thị trường',trait:'giỏi số liệu',loyalty:58,mood:65,story:['Phụ trách đọc giá và tin đồn ban đầu.']},
  {id:'char3',name:'Trần Quốc Huy',role:'Người mua hàng',trait:'nhanh nhạy',loyalty:55,mood:61,story:['Thường đi chợ giá tốt cho công ty.']},
  {id:'char4',name:'Phạm Bảo Ngân',role:'Điều phối',trait:'gọn gàng',loyalty:60,mood:64,story:['Giữ lịch tàu và hồ sơ hợp đồng.']}
 ];
}
function createAI(){return RIVALS.map(r=>({
 ...r,cash:rnd(600,1800),fleet:rnd(2,6),reputation:rnd(5,35),health:100,focus:pick(GOODS).id,lastAction:'Đang theo dõi thị trường',debt:r.style==='growth'?rnd(80,180):0,facilities:r.style==='heavy'?rnd(1,3):0
}));}
function createState(company,originId){const origin=ORIGINS.find(o=>o.id===originId)||ORIGINS[0]; const type=origin.shipType; const shipType=sdef(type);
 const firstShip={id:'ship1',name:`${shipType.name} 01`,type,port:'saigon',dest:null,eta:0,cargo:{},condition:100};
 return {version:2,status:'playing',company:company||'Hoài Phát Logistics',origin:origin.id,day:1,cash:origin.cash,debt:origin.debt,creditLimit:origin.credit,reputation:origin.rep,morale:70,staff:4,monthlySalary:10,
 ships:[firstShip],markets:createMarkets(),contracts:[],acceptedContracts:[],events:[],scheduled:[],news:[],journal:[],effects:[],facilities:{},intel:{rumors:[],forecasts:[]},characters:createCharacters(),ai:createAI(),
 stats:{revenue:0,profit:0,trades:0,contractsDone:0,maxShips:1,bestDayProfit:0,maxCash:origin.cash},createdAt:Date.now(),updatedAt:Date.now(),activeChains:[]};
}
function migrateState(s){if(!s) return null; if(s.version===2) return s; return null;}
function cargoQty(ship){return Object.values(ship.cargo||{}).reduce((a,b)=>a+b,0);}
function freeCap(ship){return (sdef(ship.type)?.cap||ship.cap||50)-cargoQty(ship);}
function getFacility(portId){if(!state.facilities[portId]) state.facilities[portId]={owned:[],stock:{}}; return state.facilities[portId];}
function warehouseCapacity(portId){const f=getFacility(portId); return f.owned.includes('warehouse')?120+(f.owned.includes('cold')?40:0):0;}
function warehouseQty(portId){const stock=getFacility(portId).stock; return Object.values(stock).reduce((a,b)=>a+b,0);}
function addCharacterStory(id,text){const c=state.characters.find(x=>x.id===id); if(c){c.story.unshift(`Ngày ${state.day}: ${text}`); c.story=c.story.slice(0,12);} }
function pushLog(text,type='info'){state.journal.unshift({day:state.day,text,type}); state.journal=state.journal.slice(0,250);}
function pushNews(title,text,kind='Tin tức'){state.news.unshift({day:state.day,title,text,kind}); state.news=state.news.slice(0,40);}
function toast(msg){const old=$('.toast'); if(old) old.remove(); const el=document.createElement('div'); el.className='toast'; el.textContent=msg; document.body.appendChild(el); setTimeout(()=>el.remove(),2200);}
function netWorth(s=state){
 const ships=(s.ships||[]).reduce((a,x)=>a+(sdef(x.type)?.cost||100)*0.68,0);
 const cargo=(s.ships||[]).reduce((a,sh)=>a+Object.entries(sh.cargo||{}).reduce((q,[gid,qty])=>q+qty*((GOODS.find(g=>g.id===gid)?.base)||0),0),0);
 const storage=Object.entries(s.facilities||{}).reduce((a,[pid,f])=>a+Object.entries(f.stock||{}).reduce((q,[gid,qty])=>q+qty*((GOODS.find(g=>g.id===gid)?.base)||0),0),0);
 const facs=Object.values(s.facilities||{}).reduce((a,f)=>a+((f.owned||[]).length*70),0);
 return s.cash - s.debt + ships + cargo + storage + facs;
}

function startScreen(){state=null; const slots=[1,2,3].map(i=>({i,s:migrateState(loadSlot(i))}));
 app.innerHTML=`<div class="shell"><div class="slot-wrap"><div class="hero"><div class="brand-mark" style="margin:auto">TL</div><h1>Thương Lộ Việt</h1><p>Game chiến thuật kinh tế theo ngày · Mỗi hành trình là một câu chuyện khác nhau</p></div>
 <div class="career">${careerCard('Hành trình',meta.runs)}${careerCard('Ngày đã chơi',meta.totalDays)}${careerCard('Điểm sự nghiệp',meta.careerPoints)}${careerCard('Tài sản kỷ lục',money(meta.bestNetWorth))}</div>
 <div class="grid3">${slots.map(({i,s})=>slotCard(i,s)).join('')}</div>
 <div class="card" style="margin-top:12px"><div class="row between"><div><h3>Bộ sưu tập & mở khóa ${tip(HELP.collection)}</h3><div class="muted mini">Giống tiến trình ngoài ván: bạn gặp càng nhiều sự kiện, chuỗi và kiểu chơi thì càng mở thêm lựa chọn.</div></div><div class="tag">${meta.unlockedOrigins.length}/${ORIGINS.length} kiểu khởi đầu</div></div>
 <div class="unlock-list" style="margin-top:10px">${ORIGINS.map(o=>`<span class="tag ${meta.unlockedOrigins.includes(o.id)?'':'warn'}">${meta.unlockedOrigins.includes(o.id)?'✓':'🔒'} ${o.name}</span>`).join('')}</div>
 <div class="mini muted" style="margin-top:10px">Đã gặp: ${meta.discoveredEvents.length} loại sự kiện · ${meta.discoveredChains.length} chuỗi dài · ${meta.discoveredFacilities.length} cơ sở · ${meta.discoveredCharacters.length} nhân vật đặc biệt</div>
 </div>
 <div class="footer-note">Game lưu riêng trong trình duyệt và không dùng dữ liệu KanBan.</div></div></div>`;
 document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>openSlot(+b.dataset.load));
 document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>newRunModal(+b.dataset.new));
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const i=+b.dataset.delete; if(confirm('Xóa hành trình ở ô lưu này? Tiến trình chung vẫn được giữ.')){eraseSlot(i); startScreen();}});
}
function careerCard(a,b){return `<div class="stat"><span>${a}</span><b>${b}</b></div>`;}
function slotCard(i,s){if(!s)return `<div class="card slot empty"><div><span class="tag">Ô lưu ${i}</span><h3>Chưa có hành trình</h3><p class="muted">Tạo công ty mới và bắt đầu từ Ngày 1.</p></div><button class="btn primary" data-new="${i}">Tạo hành trình mới</button></div>`;
 return `<div class="card slot"><div><span class="tag">Ô lưu ${i}</span><h3>${esc(s.company)}</h3><div class="big">Ngày ${s.day}</div><p class="muted">${ORIGINS.find(o=>o.id===s.origin)?.name||'Hành trình'} · ${s.status==='playing'?'Đang kinh doanh':'Đã kết thúc'}</p><div class="mini">Tài sản ước tính: <b>${money(netWorth(s))}</b></div></div><div class="slot-actions"><button class="btn primary" data-load="${i}">${s.status==='playing'?'Tiếp tục':'Xem lại'}</button><button class="btn danger" data-delete="${i}">Xóa</button></div></div>`;}
function newRunModal(i){openModal(`<div class="modal-card"><h2>Tạo hành trình mới</h2><p class="muted">Mỗi ô lưu là một thế giới riêng. Mở khóa ngoài ván được dùng chung cho cả 3 ô lưu.</p><div class="form-grid"><label>Tên công ty<input id="companyName" class="input" value="Hoài Phát Logistics" maxlength="40"></label><label>Kiểu khởi đầu<select id="originSelect" class="select">${ORIGINS.filter(o=>meta.unlockedOrigins.includes(o.id)).map(o=>`<option value="${o.id}">${o.name}</option>`).join('')}</select></label></div><div class="option-cards" style="margin:12px 0">${ORIGINS.map(o=>`<div class="origin ${meta.unlockedOrigins.includes(o.id)?'':'locked'}"><b>${meta.unlockedOrigins.includes(o.id)?'':'🔒 '}${o.name}</b><span class="mini muted">${o.desc}</span><span class="mini muted">Mở ở ${o.unlock} điểm sự nghiệp</span></div>`).join('')}</div><div class="row between"><button class="btn" id="cancelNew">Hủy</button><button class="btn primary" id="createNew">Bắt đầu Ngày 1</button></div></div>`);
 $('#cancelNew').onclick=closeModal; $('#createNew').onclick=()=>{slot=i; state=createState($('#companyName').value.trim()||'Hoài Phát Logistics',$('#originSelect').value); selectedShipId=state.ships[0].id; selectedPort=state.ships[0].port; tab='tongquan'; generateContractsIfNeeded(); refreshIntel(); save(); closeModal(); renderGame();};
}
function openSlot(i){const s=migrateState(loadSlot(i)); if(!s) return; slot=i; state=s; selectedShipId=state.ships[0]?.id; selectedPort=state.ships[0]?.port||'saigon'; tab='tongquan'; renderGame();}

function renderGame(){if(!state) return startScreen(); const playable=state.status==='playing'; const statusText=state.status==='playing'?'Đang chơi':state.status==='won'?'Đã hoàn thành':state.status==='bankrupt'?'Đã phá sản':'Đã kết thúc';
 app.innerHTML=`<div class="shell"><div class="top"><div class="content"><div class="top-row"><div class="brand"><div class="brand-mark">TL</div><div><h1>${esc(state.company)}</h1><small>${ORIGINS.find(o=>o.id===state.origin)?.name||''} · Ô lưu ${slot} · ${statusText}</small></div></div><div class="top-actions"><span class="day-pill" title="Mọi thứ trong game chỉ chạy tiếp khi bạn bấm Qua ngày.">Ngày ${state.day}</span><button class="btn ghost" id="backSlots">3 ô lưu</button>${playable?`<button class="btn primary next-btn" id="nextDay" title="${esc(HELP.next)}">QUA NGÀY →</button>`:''}</div></div>
 <div class="stats">${stat('Tiền mặt',money(state.cash),state.cash<0?'down':'')}${stat('Tài sản',money(netWorth()))}${stat('Nợ',money(state.debt),state.debt>state.cash?'down':'')}${stat('Danh tiếng',state.reputation)}${stat('Tàu',state.ships.length)}${stat('Nhân viên',state.staff)}</div>
 <div class="nav">${[['tongquan','Tổng quan'],['thitruong','Thị trường'],['tautuyen','Tàu & tuyến'],['hopdong','Hợp đồng'],['taichinh','Tài chính'],['doithu','Đối thủ'],['nhanvat','Nhân vật'],['coso','Cơ sở'],['thuthap','Thu thập'],['nhatky','Nhật ký']].map(x=>`<button data-tab="${x[0]}" class="${tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</div></div></div>
 <main class="content">${renderTab()}</main></div>`;
 $('#backSlots').onclick=()=>{save(); startScreen();};
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab; renderGame();});
 if(playable) $('#nextDay').onclick=nextDay;
 bindTab();
 if(state.events.length) showPendingEvent();
}
function stat(a,b,c=''){return `<div class="stat"><span>${a}</span><b class="${c}">${b}</b></div>`;}
function renderTab(){switch(tab){case'thitruong':return marketView(); case'tautuyen':return fleetView(); case'hopdong':return contractView(); case'taichinh':return financeView(); case'doithu':return rivalsView(); case'nhanvat':return charactersView(); case'coso':return facilitiesView(); case'thuthap':return collectionView(); case'nhatky':return journalView(); default:return overviewView();}}
function buildBrief(){const brief=[]; for(const r of state.intel.rumors.slice(0,2)) brief.push({title:'Tin đồn',text:r.text}); for(const f of state.intel.forecasts.slice(0,2)) brief.push({title:`Dự báo ${gname(f.good)}`,text:`${pname(f.port)} · ${f.direction>0?'có thể tăng':'có thể giảm'} ${Math.abs(f.direction)}% trong ${f.days} ngày · độ tin ${f.confidence}%`}); if(state.acceptedContracts.some(c=>c.status==='active'&&c.deadline-state.day<=3)) brief.push({title:'Hợp đồng gần hạn',text:'Bạn có hợp đồng còn dưới 3 ngày. Nên ưu tiên giao hàng.'}); if(state.debt>state.creditLimit*0.7) brief.push({title:'Nợ đang cao',text:'Khoảng đệm vay không còn nhiều. Hãy theo dõi dòng tiền.'}); if(state.effects.length) brief.push({title:'Biến động đang chạy',text:state.effects.slice(0,3).map(e=>effectName(e.type)).join(' · ')}); return brief.slice(0,6);}
function overviewView(){const brief=buildBrief(); return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>Bản tin sáng · Ngày ${state.day}</h2><div class="muted mini">Chỉ những việc đáng chú ý để <b>bạn</b> quyết định trước khi qua ngày.</div></div><span class="tag">${brief.length} việc</span></div><div class="brief">${brief.map(x=>`<div class="brief-item"><strong>${x.title}</strong><span class="muted">${x.text}</span></div>`).join('')||'<div class="goodbox">Hôm nay khá yên. Bạn có thể kiểm tra thị trường, điều tàu hoặc qua ngày.</div>'}</div></div>
 <div><div class="card"><h2>Việc đang chạy ${tip(HELP.fleet)}</h2>${state.ships.map(shipMini).join('')}<div class="tooltip-note">Tàu đang đi sẽ tiếp tục di chuyển khi bạn bấm Qua ngày.</div></div>
 <div class="card" style="margin-top:12px"><h2>Tình hình nhanh</h2>${riskSummary()}</div></div></div>
 <div class="grid" style="margin-top:12px"><div class="card"><h2>Tin đồn & dự báo ${tip('Tin đồn chỉ là gợi ý. Dự báo tốt giúp bạn quyết định sớm hơn nhưng không đảm bảo đúng tuyệt đối.')}</h2>${intelSnippet()}</div><div class="card"><h2>Chuỗi đang chạy</h2>${chainSnippet()}</div></div>`;}
function shipMini(s){return `<div class="ship"><div class="row between"><b>${s.name}</b><span class="tag">${pname(s.dest||s.port)}</span></div><div class="mini muted">Khoang ${cargoQty(s)}/${sdef(s.type)?.cap||50} · Tình trạng ${Math.round(s.condition)}%</div>${s.dest?`<div class="mini muted">Đang đi tới ${pname(s.dest)} · còn ${s.eta} ngày</div>`:`<div class="mini muted">Đang neo tại ${pname(s.port)}</div>`}</div>`;}
function riskSummary(){
 const boxes=[];
 boxes.push(state.cash<0?`<div class="badbox"><b>Dòng tiền căng</b><div class="mini">Tiền mặt hiện còn ${money(state.cash)}.</div></div>`:`<div class="goodbox"><b>Dòng tiền ổn</b><div class="mini">Tiền mặt hiện có ${money(state.cash)}.</div></div>`);
 boxes.push(state.debt>state.creditLimit*.7?`<div class="notice"><b>Nợ khá cao</b><div class="mini">Nợ ${money(state.debt)} / hạn mức ${money(state.creditLimit)}.</div></div>`:`<div class="goodbox"><b>Nợ đang an toàn</b><div class="mini">Nợ ${money(state.debt)} / hạn mức ${money(state.creditLimit)}.</div></div>`);
 boxes.push(state.effects.length?`<div class="notice"><b>Thị trường đang biến động</b><div class="mini">${state.effects.slice(0,3).map(e=>effectName(e.type)).join(' · ')}</div></div>`:`<div class="goodbox"><b>Thị trường khá ổn định</b><div class="mini">Hãy xem tin đồn và dự báo trước khi gom hàng lớn.</div></div>`);
 return boxes.join('');
}
function intelSnippet(){return `<div class="brief">${state.intel.rumors.slice(0,3).map(r=>`<div class="brief-item"><strong>${r.title}</strong><span class="muted">${r.text}</span><div class="mini muted">Độ tin ${r.confidence}% · còn giá trị khoảng ${r.days} ngày</div></div>`).join('')||'<div class="mini muted">Chưa có tin đồn nổi bật.</div>'}${state.intel.forecasts.slice(0,3).map(f=>`<div class="brief-item"><strong>${gname(f.good)} tại ${pname(f.port)}</strong><span class="muted">${f.direction>0?'Có khả năng tăng':'Có khả năng giảm'} ${Math.abs(f.direction)}% trong ${f.days} ngày.</span><div class="mini muted">Độ tin ${f.confidence}%</div></div>`).join('')}</div>`;}
function chainSnippet(){return state.activeChains.length?`<div class="brief">${state.activeChains.map(c=>`<div class="brief-item"><strong>${c.name}</strong><span class="muted">${c.summary}</span><div class="mini muted">Bước ${c.stage}/${c.totalStages} · theo dõi thêm ${c.nextIn} ngày</div></div>`).join('')}</div>`:`<div class="mini muted">Chưa có chuỗi dài nào đang theo dõi. Các quyết định lớn của bạn có thể tự mở ra chuỗi sự kiện 5–30 ngày.</div>`;}

function marketView(){const ship=state.ships.find(s=>s.id===selectedShipId)||state.ships[0]; const portId=selectedPort||ship?.port||'saigon'; const f=getFacility(portId); const current=state.markets[portId]; return `<div class="card"><div class="screen-title"><div><h2>Thị trường ${tip(HELP.market)}</h2><div class="muted mini">Chọn cảng để xem giá. Nếu tàu của bạn đang đứng tại đó, bạn có thể mua bán trực tiếp.</div></div><span class="tag">${pname(portId)}</span></div>
 <div class="market-controls"><label class="mini muted">Cảng <select id="marketPort" class="select">${PORTS.map(p=>`<option value="${p.id}" ${p.id===portId?'selected':''}>${p.name}</option>`).join('')}</select></label><label class="mini muted">Tàu <select id="marketShip" class="select">${state.ships.map(s=>`<option value="${s.id}" ${s.id===ship?.id?'selected':''}>${s.name}</option>`).join('')}</select></label></div>
 <div class="mini muted" style="margin:8px 0">${ship&&ship.port===portId&&!ship.dest?'Tàu đang có mặt tại cảng này và có thể giao dịch.':'Tàu chưa đứng tại cảng này nên bạn chỉ xem giá tham khảo được.'}</div>
 <table class="table"><thead><tr><th>Hàng</th><th class="num">Giá</th><th class="num">Tồn</th><th class="num">Xu hướng</th><th>Dự báo</th><th>Thao tác</th></tr></thead><tbody>${GOODS.map(g=>marketRow(g,current[g.id],ship,portId)).join('')}</tbody></table>
 ${f.owned.includes('warehouse')?warehousePanel(portId,ship):`<div class="notice" style="margin-top:10px">Bạn chưa có kho tại ${pname(portId)}. Mua trong tab <b>Cơ sở</b> nếu muốn tích hàng chờ giá.</div>`}
 </div>`;}
function marketRow(g,m,ship,portId){const trend=m.trend>0?`▲ ${m.trend.toFixed(1)}`:m.trend<0?`▼ ${Math.abs(m.trend).toFixed(1)}`:'—'; const canTrade=ship&&ship.port===portId&&!ship.dest; const rum=state.intel.forecasts.find(f=>f.port===portId&&f.good===g.id); const warehouse=getFacility(portId); const wqty=warehouse.stock[g.id]||0; const cargo=(ship?.cargo[g.id]||0); return `<tr><td><b>${g.name}</b><div class="mini muted">${g.group}</div></td><td class="num kpi">${money(m.price)}</td><td class="num">${Math.round(m.stock)}</td><td class="num ${m.trend>0?'up':m.trend<0?'down':''}">${trend}</td><td>${rum?`<span class="tag ${rum.direction>0?'':'warn'}">${rum.direction>0?'↑':'↓'} ${Math.abs(rum.direction)}% · ${rum.confidence}%</span>`:'<span class="mini muted">Chưa rõ</span>'}</td><td>${canTrade?`<div class="row"><button class="btn" data-buy="${g.id}">Mua 1</button><button class="btn" data-sell="${g.id}">Bán 1</button>${warehouse.owned.includes('warehouse')?`<button class="btn" data-store="${g.id}" ${cargo<1?'disabled':''}>Gửi kho</button><button class="btn" data-pick="${g.id}" ${wqty<1||freeCap(ship)<1?'disabled':''}>Lấy kho</button>`:''}</div><div class="mini muted">Tàu: ${cargo} · Kho: ${wqty}</div>`:`<span class="mini muted">Tàu chưa đứng tại đây</span>`}</td></tr>`;}
function warehousePanel(portId,ship){const f=getFacility(portId); return `<div class="card" style="margin-top:12px;background:var(--panel2)"><h3>Kho tại ${pname(portId)} ${tip('Kho giúp bạn tách việc mua hàng khỏi việc vận chuyển. Bạn có thể gom hàng trước, chờ giá đẹp rồi mới lấy lên tàu.')}</h3><div class="mini muted">Sức chứa ${warehouseQty(portId)}/${warehouseCapacity(portId)}</div><div class="unlock-list" style="margin-top:8px">${GOODS.filter(g=>(f.stock[g.id]||0)>0).map(g=>`<span class="tag">${g.name}: ${f.stock[g.id]}</span>`).join('')||'<span class="mini muted">Kho đang trống.</span>'}</div></div>`;}

function fleetView(){const ship=state.ships.find(s=>s.id===selectedShipId)||state.ships[0]; return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>Tàu & tuyến ${tip(HELP.fleet)}</h2><div class="muted mini">Chọn một tàu rồi điều động tuyến mới. Tàu đang đi sẽ tiếp tục qua từng ngày.</div></div><button class="btn" id="buyShip">Mua tàu</button></div>${state.ships.map(s=>shipCard(s)).join('')}</div><div class="card">${ship?routePanel(ship):'<div class="mini muted">Chưa có tàu.</div>'}</div></div>`;}
function shipCard(s){return `<div class="ship ${s.id===selectedShipId?'selected':''}"><div class="row between"><div><b>${s.name}</b><div class="mini muted">${sdef(s.type)?.name} · sức chở ${sdef(s.type)?.cap||50}</div></div><button class="btn" data-ship="${s.id}">Chọn</button></div><div class="mini muted">Vị trí: ${pname(s.port)}${s.dest?` → ${pname(s.dest)} (còn ${s.eta} ngày)`:''}</div><div class="mini muted">Hàng: ${cargoQty(s)} · Tình trạng ${Math.round(s.condition)}%</div><div class="progress"><i style="width:${Math.round(s.condition)}%"></i></div></div>`;}
function routePanel(ship){const routes=Object.entries(ROUTES[ship.port]||{}); return `<h2>${ship.name}</h2><div class="mini muted">Neo tại ${pname(ship.port)} · Hàng ${cargoQty(ship)}/${sdef(ship.type)?.cap||50} · Tình trạng ${Math.round(ship.condition)}%</div>${ship.dest?`<div class="notice" style="margin-top:10px">Tàu đang đi tới ${pname(ship.dest)} và còn ${ship.eta} ngày.</div>`:`<div class="brief" style="margin-top:12px">${routes.map(([dest,days])=>`<div class="brief-item"><strong>${pname(dest)}</strong><span class="muted">Thời gian ${Math.ceil(days/(sdef(ship.type)?.speed||1))} ngày · chi phí nhiên liệu khoảng ${money(travelFuelCost(ship,dest))}</span><div class="row" style="margin-top:6px"><button class="btn" data-travel="${dest}">Đi tuyến này</button></div></div>`).join('')||'<div class="mini muted">Tuyến đang tạm trống.</div>'}</div>`}`;}
function travelFuelCost(ship,dest){const days=Math.ceil((ROUTES[ship.port]?.[dest]||1)/(sdef(ship.type)?.speed||1)); const hasFuel=getFacility(ship.port).owned.includes('fuel'); let cost=days*(sdef(ship.type)?.fuel||1)*8; if(hasFuel) cost*=0.8; if(state.effects.some(e=>e.type==='energyCrisis')) cost*=1.3; return Math.round(cost);}

function contractView(){return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>Hợp đồng mở ${tip(HELP.contracts)}</h2><div class="muted mini">Nhận hợp đồng phù hợp với tuyến và sức chở của bạn.</div></div><button class="btn" id="refreshContracts">Làm mới</button></div>${state.contracts.length?state.contracts.map(contractCard).join(''):'<div class="mini muted">Hiện chưa có hợp đồng phù hợp. Bấm làm mới hoặc chờ qua ngày.</div>'}</div><div class="card"><h2>Hợp đồng đang chạy</h2>${state.acceptedContracts.length?state.acceptedContracts.map(activeContractCard).join(''):'<div class="mini muted">Bạn chưa nhận hợp đồng nào.</div>'}</div></div>`;}
function contractCard(c){return `<div class="contract"><div class="row between"><b>${c.title}</b><span class="tag">Thưởng ${money(c.reward)}</span></div><div class="mini muted">${pname(c.from)} → ${pname(c.to)} · ${gname(c.good)} x${c.qty} · hạn đến ngày ${c.deadline}</div><div class="row" style="margin-top:8px"><button class="btn primary" data-accept="${c.id}">Nhận hợp đồng</button></div></div>`;}
function activeContractCard(c){return `<div class="contract"><div class="row between"><b>${c.title}</b><span class="tag ${c.status==='active'?'':'warn'}">${c.status==='active'?'Đang chạy':c.status}</span></div><div class="mini muted">${pname(c.from)} → ${pname(c.to)} · ${gname(c.good)} x${c.qty} · hạn đến ngày ${c.deadline}</div><div class="mini muted">Trạng thái giao: ${c.loaded?'Đã lấy hàng':'Chưa lấy hàng'} · ${c.delivered||0}/${c.qty}</div><div class="row" style="margin-top:8px">${c.status==='active'?`<button class="btn" data-loadcontract="${c.id}">Lấy hàng</button><button class="btn" data-deliver="${c.id}">Giao hàng</button>`:''}</div></div>`;}

function financeView(){const monthInterest=state.debt*(state.effects.some(e=>e.type==='creditCrisis')?0.035:0.02); const monthMaint=state.ships.reduce((a,s)=>a+(sdef(s.type)?.maint||2),0)+Object.values(state.facilities).reduce((a,f)=>a+(f.owned||[]).reduce((x,id)=>x+(FACILITIES.find(ff=>ff.id===id)?.upkeep||0),0),0); return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>Tài chính ${tip(HELP.finance)}</h2><div class="muted mini">Vay giúp mở rộng nhanh nhưng cũng dễ làm mất kiểm soát dòng tiền.</div></div></div><div class="brief"><div class="brief-item"><strong>Tiền mặt</strong><span class="muted">${money(state.cash)}</span></div><div class="brief-item"><strong>Nợ hiện tại</strong><span class="muted">${money(state.debt)} / hạn mức ${money(state.creditLimit)}</span></div><div class="brief-item"><strong>Chi phí cuối tháng ước tính</strong><span class="muted">Lương ${money(state.monthlySalary)} · Lãi ${money(monthInterest)} · Bảo trì & cơ sở ${money(monthMaint)}</span></div></div><div class="row" style="margin-top:12px"><input id="loanAmt" class="input" value="50"><button class="btn" id="borrowBtn">Vay thêm</button><button class="btn" id="repayBtn">Trả nợ</button></div></div>
 <div class="card"><h2>Báo cáo nhanh</h2><div class="brief">${reportLine('Doanh thu cộng dồn',money(state.stats.revenue))}${reportLine('Số giao dịch',state.stats.trades)}${reportLine('Hợp đồng hoàn thành',state.stats.contractsDone)}${reportLine('Lợi nhuận ngày tốt nhất',money(state.stats.bestDayProfit))}${reportLine('Tiền mặt cao nhất',money(state.stats.maxCash))}</div></div></div>`;}
function reportLine(a,b){return `<div class="brief-item"><strong>${a}</strong><span class="muted">${b}</span></div>`;}

function rivalsView(){return `<div class="card"><div class="screen-title"><div><h2>Đối thủ ${tip(HELP.rivals)}</h2><div class="muted mini">Họ cùng chịu luật kinh tế như bạn. Một số sẽ liều, một số thích an toàn, một số săn hợp đồng.</div></div></div>${state.ai.map(aiCard).join('')}</div>`;}
function aiCard(ai){return `<div class="company"><div><b>${ai.name}</b><div class="mini muted">Phong cách: ${ai.styleLabel} · Tàu ${ai.fleet} · Tập trung ${gname(ai.focus)}</div><div class="mini muted">Hành động gần đây: ${ai.lastAction}</div></div><div><div class="kpi ${ai.health<25?'down':'up'}">${money(ai.cash)}</div><div class="mini muted">Sức khỏe ${Math.round(ai.health)}%</div></div></div>`;}

function charactersView(){return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>Nhân vật ${tip(HELP.characters)}</h2><div class="muted mini">Mỗi người có tính cách và lịch sử riêng. Quyết định của bạn sẽ dần thay đổi họ.</div></div></div>${state.characters.map(characterCard).join('')}</div><div class="card"><h2>Nhân vật đặc biệt đã gặp</h2>${meta.discoveredCharacters.length?`<div class="unlock-list">${meta.discoveredCharacters.map(n=>`<span class="tag">${n}</span>`).join('')}</div>`:'<div class="mini muted">Bạn chưa gặp nhân vật đặc biệt nào.</div>'}<div class="card" style="margin-top:12px;background:var(--panel2)"><h3>Gợi ý</h3><div class="mini muted">Các chuỗi dài như đình công, tin nội bộ, khủng hoảng hoặc cơ hội đầu tư có thể tạo ra gương mặt mới và làm thay đổi lịch sử của nhân vật hiện tại.</div></div></div></div>`;}
function characterCard(c){return `<div class="ship"><div class="row between"><div><b>${c.name}</b><div class="mini muted">${c.role} · ${c.trait}</div></div><span class="tag">Trung thành ${c.loyalty}</span></div><div class="mini muted">Tinh thần ${c.mood}</div><div class="progress"><i style="width:${clamp(c.mood,0,100)}%"></i></div><div class="brief" style="margin-top:8px">${c.story.slice(0,4).map(t=>`<div class="mini muted">• ${t}</div>`).join('')}</div></div>`;}

function facilitiesView(){return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>Cơ sở kinh doanh ${tip(HELP.facilities)}</h2><div class="muted mini">Mỗi cảng có thể là một mắt xích trong chiến lược dài hạn của bạn.</div></div></div>${PORTS.map(portFacilityCard).join('')}</div><div class="card"><h2>Tác động chiến thuật</h2><div class="brief">${FACILITIES.map(f=>`<div class="brief-item"><strong>${f.name}</strong><span class="muted">${f.desc}</span><div class="mini muted">Giá mua ${money(f.cost)} · phí duy trì ${money(f.upkeep)}/tháng</div></div>`).join('')}</div></div></div>`;}
function portFacilityCard(p){const f=getFacility(p.id); return `<div class="contract"><div class="row between"><div><b>${p.name}</b><div class="mini muted">${p.type}</div></div><span class="tag">${(f.owned||[]).length} cơ sở</span></div><div class="unlock-list" style="margin:6px 0">${f.owned.length?f.owned.map(id=>`<span class="tag">${FACILITIES.find(x=>x.id===id)?.name}</span>`).join(' '):'<span class="mini muted">Chưa có cơ sở nào.</span>'}</div><div class="row">${FACILITIES.map(fc=>f.owned.includes(fc.id)?`<button class="btn" disabled>Đã có ${fc.name}</button>`:`<button class="btn" data-buyfac="${p.id}:${fc.id}">Mua ${fc.name}</button>`).join('')}</div></div>`;}

function collectionView(){return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>Thu thập & mở khóa ${tip(HELP.collection)}</h2><div class="muted mini">Phần này đi theo bạn qua nhiều hành trình, giống kiểu Collection trong game roguelike.</div></div></div><div class="brief">${reportLine('Loại sự kiện đã gặp',`${meta.discoveredEvents.length}`)}${reportLine('Chuỗi dài đã mở',`${meta.discoveredChains.length}`)}${reportLine('Nhân vật đặc biệt',`${meta.discoveredCharacters.length}`)}${reportLine('Cơ sở từng xây',`${meta.discoveredFacilities.length}`)}${reportLine('Kiểu khởi đầu đã mở',`${meta.unlockedOrigins.length}/${ORIGINS.length}`)}</div><div class="card" style="margin-top:12px;background:var(--panel2)"><h3>Chuỗi đã khám phá</h3><div class="unlock-list">${meta.discoveredChains.length?meta.discoveredChains.map(x=>`<span class="tag">${x}</span>`).join(' '):'<span class="mini muted">Chưa có chuỗi nào được mở.</span>'}</div></div></div><div class="card"><h2>Lịch sử hành trình</h2>${meta.history.length?meta.history.slice(0,10).map(h=>`<div class="company"><div><b>${esc(h.company)}</b><div class="mini muted">${h.result==='won'?'Hoàn thành':h.result==='bankrupt'?'Phá sản':'Kết thúc'} · ${h.day} ngày</div></div><div><div class="kpi">${money(h.net)}</div><div class="mini muted">+${h.score} điểm</div></div></div>`).join(''):'<div class="mini muted">Chưa có hành trình nào kết thúc.</div>'}</div></div>`;}

function journalView(){return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>Nhật ký gần đây</h2><div class="muted mini">Lưu lại giao dịch, sự kiện và quyết định của bạn.</div></div>${state.status==='playing'?'<button class="btn" id="retireBtn">Kết thúc hành trình</button>':''}</div><div class="log">${state.journal.map(j=>`<div class="log-item"><div class="mini muted">Ngày ${j.day}</div><div>${j.text}</div></div>`).join('')||'<div class="mini muted">Chưa có ghi chép.</div>'}</div></div><div class="card"><h2>Tin tức</h2><div class="log">${state.news.map(n=>`<div class="log-item"><div class="row between"><b>${n.title}</b><span class="tag info">${n.kind}</span></div><div class="mini muted">Ngày ${n.day}</div><div>${n.text}</div></div>`).join('')||'<div class="mini muted">Chưa có tin tức.</div>'}</div></div></div>`;}

function bindTab(){
 if(tab==='thitruong'){
  $('#marketPort').onchange=e=>{selectedPort=e.target.value; renderGame();};
  $('#marketShip').onchange=e=>{selectedShipId=e.target.value; renderGame();};
  document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>trade(b.dataset.buy,1));
  document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>trade(b.dataset.sell,-1));
  document.querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>moveWarehouse(b.dataset.store,true));
  document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>moveWarehouse(b.dataset.pick,false));
 }
 if(tab==='tautuyen'){
  document.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>{selectedShipId=b.dataset.ship; renderGame();});
  document.querySelectorAll('[data-travel]').forEach(b=>b.onclick=()=>travel(b.dataset.travel));
  const bs=$('#buyShip'); if(bs) bs.onclick=buyShipModal;
 }
 if(tab==='hopdong'){
  const rf=$('#refreshContracts'); if(rf) rf.onclick=()=>{generateContractsIfNeeded(true); save(); renderGame();};
  document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>acceptContract(b.dataset.accept));
  document.querySelectorAll('[data-loadcontract]').forEach(b=>b.onclick=()=>loadContractGoods(b.dataset.loadcontract));
  document.querySelectorAll('[data-deliver]').forEach(b=>b.onclick=()=>deliverContract(b.dataset.deliver));
 }
 if(tab==='taichinh'){
  const br=$('#borrowBtn'),rp=$('#repayBtn'); if(br) br.onclick=()=>loan(1); if(rp) rp.onclick=()=>loan(-1);
 }
 if(tab==='coso'){
  document.querySelectorAll('[data-buyfac]').forEach(b=>b.onclick=()=>{const [p,f]=b.dataset.buyfac.split(':'); buyFacility(p,f);});
 }
 if(tab==='nhatky'){
  const r=$('#retireBtn'); if(r) r.onclick=()=>finishRun(false,'Bạn chủ động dừng hành trình để thử một chiến lược mới.');
 }
}

function trade(goodId,dir){const ship=state.ships.find(s=>s.id===selectedShipId); if(!ship||ship.dest||ship.port!==selectedPort) return toast('Tàu phải đứng đúng cảng mới giao dịch được.'); const market=state.markets[selectedPort][goodId]; if(dir>0){ if(freeCap(ship)<1) return toast('Khoang tàu đã đầy.'); if(state.cash<market.price) return toast('Tiền mặt không đủ.'); if(market.stock<1) return toast('Cảng đang hết hàng.'); state.cash-=market.price; ship.cargo[goodId]=(ship.cargo[goodId]||0)+1; market.stock-=1; state.stats.revenue-=0; pushLog(`Mua 1 ${gname(goodId)} tại ${pname(selectedPort)} với giá ${money(market.price)}.`);}
 else{ if((ship.cargo[goodId]||0)<1) return toast('Tàu không có mặt hàng này.'); const price=market.price*((getFacility(selectedPort).owned.includes('cold')&&(goodId==='hanglanh'||goodId==='duocpham'))?1.08:1); state.cash+=price; ship.cargo[goodId]-=1; if(ship.cargo[goodId]<=0) delete ship.cargo[goodId]; market.stock+=1; state.stats.revenue+=price; state.stats.profit+=price; pushLog(`Bán 1 ${gname(goodId)} tại ${pname(selectedPort)} với giá ${money(price)}.`);} state.stats.trades++; state.stats.maxCash=Math.max(state.stats.maxCash,state.cash); refreshIntel(); save(); renderGame();}
function moveWarehouse(goodId,toWarehouse){const ship=state.ships.find(s=>s.id===selectedShipId); const fac=getFacility(selectedPort); if(!fac.owned.includes('warehouse')) return; fac.stock[goodId]=fac.stock[goodId]||0; if(toWarehouse){ if((ship.cargo[goodId]||0)<1) return toast('Tàu không có hàng này.'); if(warehouseQty(selectedPort)>=warehouseCapacity(selectedPort)) return toast('Kho đã đầy.'); ship.cargo[goodId]--; if(ship.cargo[goodId]<=0) delete ship.cargo[goodId]; fac.stock[goodId]++; pushLog(`Gửi 1 ${gname(goodId)} vào kho tại ${pname(selectedPort)}.`); }
 else{ if((fac.stock[goodId]||0)<1) return toast('Kho không có hàng này.'); if(freeCap(ship)<1) return toast('Tàu đã đầy.'); fac.stock[goodId]--; if(fac.stock[goodId]<=0) delete fac.stock[goodId]; ship.cargo[goodId]=(ship.cargo[goodId]||0)+1; pushLog(`Lấy 1 ${gname(goodId)} từ kho tại ${pname(selectedPort)} lên tàu.`);} save(); renderGame();}
function travel(dest){const ship=state.ships.find(s=>s.id===selectedShipId); if(!ship||ship.dest) return; const route=ROUTES[ship.port]?.[dest]; if(!route) return toast('Không có tuyến này.'); const days=Math.ceil(route/(sdef(ship.type)?.speed||1)); const fuel=Math.round(travelFuelCost(ship,dest)); if(state.cash<fuel) return toast('Không đủ tiền nhiên liệu.'); state.cash-=fuel; ship.dest=dest; ship.eta=days; pushLog(`${ship.name} rời ${pname(ship.port)} đi ${pname(dest)}. Chi phí nhiên liệu ${money(fuel)}.`); save(); renderGame();}
function buyShipModal(){openModal(`<div class="modal-card"><h2>Mua tàu mới</h2><div class="brief">${SHIP_TYPES.map(t=>`<div class="brief-item"><strong>${t.name}</strong><span class="muted">Sức chở ${t.cap} · tốc độ ${t.speed} · bảo trì ${money(t.maint)}/tháng</span><div class="row" style="margin-top:8px"><button class="btn primary" data-buyship="${t.id}">Mua với giá ${money(t.cost)}</button></div></div>`).join('')}</div><div class="row" style="margin-top:12px"><button class="btn" id="closeShipBuy">Đóng</button></div></div>`); $('#closeShipBuy').onclick=closeModal; document.querySelectorAll('[data-buyship]').forEach(b=>b.onclick=()=>{buyShip(b.dataset.buyship);});}
function buyShip(type){const t=sdef(type); if(state.cash<t.cost) return toast('Tiền mặt chưa đủ mua tàu này.'); state.cash-=t.cost; const id='ship'+Date.now(); state.ships.push({id,name:`${t.name} ${String(state.ships.length+1).padStart(2,'0')}`,type,port:'saigon',dest:null,eta:0,cargo:{},condition:100}); state.stats.maxShips=Math.max(state.stats.maxShips,state.ships.length); pushLog(`Mua tàu mới ${t.name}.`); closeModal(); save(); renderGame();}

function generateContractsIfNeeded(force=false){if(!force && state.contracts.length>=4) return; if(force) state.contracts=[]; while(state.contracts.length<4){const from=pick(PORTS); const to=pick(PORTS.filter(p=>p.id!==from.id)); const good=pick(GOODS); const qty=rnd(8,28); const dist=ROUTES[from.id]?.[to.id]||rnd(2,5); const reward=Math.round((good.base*qty)*(1.3+dist/4)); state.contracts.push({id:'ct'+Date.now()+Math.random(),title:`Chuyến ${gname(good.id)} ${from.name.split(' ').pop()} → ${to.name.split(' ').pop()}`,from:from.id,to:to.id,good:good.id,qty,reward,deadline:state.day+dist+rnd(3,7)});}}
function acceptContract(id){const idx=state.contracts.findIndex(c=>c.id===id); if(idx<0) return; const c=state.contracts.splice(idx,1)[0]; c.status='active'; c.loaded=false; c.delivered=0; state.acceptedContracts.push(c); pushLog(`Nhận hợp đồng ${c.title}.`); save(); renderGame();}
function loadContractGoods(id){const c=state.acceptedContracts.find(x=>x.id===id&&x.status==='active'); if(!c) return; const ship=state.ships.find(s=>!s.dest&&s.port===c.from&&freeCap(s)>=c.qty); if(!ship) return toast('Không có tàu phù hợp đang đứng tại cảng xuất phát.'); const market=state.markets[c.from][c.good]; if(market.stock<c.qty) return toast('Cảng xuất phát không đủ hàng để bốc đủ hợp đồng.'); for(let i=0;i<c.qty;i++){ship.cargo[c.good]=(ship.cargo[c.good]||0)+1; market.stock--;}
 c.loaded=true; c.shipId=ship.id; pushLog(`Bốc ${c.qty} ${gname(c.good)} cho hợp đồng ${c.title}.`); save(); renderGame();}
function deliverContract(id){const c=state.acceptedContracts.find(x=>x.id===id&&x.status==='active'); if(!c||!c.loaded) return toast('Hợp đồng chưa lấy hàng.'); const ship=state.ships.find(s=>s.id===c.shipId); if(!ship||ship.dest||ship.port!==c.to) return toast('Tàu của hợp đồng chưa tới cảng nhận.'); if((ship.cargo[c.good]||0)<c.qty) return toast('Hàng trên tàu không đủ.'); ship.cargo[c.good]-=c.qty; if(ship.cargo[c.good]<=0) delete ship.cargo[c.good]; c.delivered=c.qty; c.status='done'; state.cash+=c.reward; state.reputation+=4; state.stats.contractsDone++; state.stats.revenue+=c.reward; pushLog(`Hoàn thành ${c.title}, nhận ${money(c.reward)}.`); pushNews('Hợp đồng hoàn thành',`${c.title} đã được giao đúng hạn.`, 'Kinh doanh'); save(); renderGame();}
function loan(dir){const amt=Math.max(10,+$('#loanAmt').value||50); if(dir>0){const room=state.creditLimit-state.debt; if(room<=0) return toast('Đã hết hạn mức vay.'); const take=Math.min(amt,room); state.debt+=take; state.cash+=take; pushLog(`Vay thêm ${money(take)}.`);} else {const pay=Math.min(amt,state.debt,Math.max(0,state.cash)); if(pay<=0) return toast('Không đủ tiền để trả nợ.'); state.debt-=pay; state.cash-=pay; pushLog(`Trả nợ ${money(pay)}.`);} save(); renderGame();}
function buyFacility(portId,facId){const fac=getFacility(portId); if(fac.owned.includes(facId)) return; const def=FACILITIES.find(f=>f.id===facId); if(state.cash<def.cost) return toast('Tiền mặt chưa đủ mua cơ sở này.'); state.cash-=def.cost; fac.owned.push(facId); ensureMetaArray('discoveredFacilities',def.name); pushLog(`Xây ${def.name} tại ${pname(portId)}.`); if(facId==='warehouse') pushNews('Mở kho mới',`Bạn vừa mở ${def.name} tại ${pname(portId)}. Từ nay có thể gom hàng chờ giá.`, 'Kinh doanh'); save(); renderGame();}

function nextDay(){if(state.events.length) return showPendingEvent(); const before=state.cash; state.day++; meta.totalDays++; processEffects(); processMarkets(); processShips(); processFacilities(); processAI(); processContracts(); processScheduled(); processMonthly(); processCharacters(); refreshIntel(); maybeEvent(); updateActiveChains(); state.stats.bestDayProfit=Math.max(state.stats.bestDayProfit,state.cash-before); state.stats.maxCash=Math.max(state.stats.maxCash,state.cash); meta.bestNetWorth=Math.max(meta.bestNetWorth,netWorth()); saveMeta(); save(); if(checkBankruptcy()) return; renderGame();}
function processEffects(){for(const e of state.effects) e.days--; state.effects=state.effects.filter(e=>e.days>0);} 
function processMarkets(){const recession=state.effects.some(e=>e.type==='recession'),boom=state.effects.some(e=>e.type==='boom'),energy=state.effects.some(e=>e.type==='energyCrisis'); for(const p of PORTS){for(const g of GOODS){const m=state.markets[p.id][g.id], prod=p.prod[g.id]||0, cons=p.cons[g.id]||0; const demandMul=recession?0.78:(boom?1.25:1); m.stock=clamp(m.stock+prod*(0.7+Math.random()*0.55)-cons*demandMul*(0.7+Math.random()*0.55),3,260); let eventAdj=0; for(const e of state.effects){if(e.port&&e.port!==p.id) continue; if(e.good&&e.good!==g.id) continue; if(['boostDemand','shortage','festival','medicineDemand'].includes(e.type)) eventAdj+=0.18; if(e.type==='floodSupply') eventAdj-=0.2; if(e.type==='industrialTax'&&(g.id==='maymoc'||g.id==='dientu')) eventAdj+=0.15; if(e.type==='energyCrisis'&&g.id==='nhienlieu') eventAdj+=0.35; if(e.type==='fuelDown'&&g.id==='nhienlieu') eventAdj-=0.15;}
 const scarcity=(78-m.stock)/90; if(energy && g.id==='nhienlieu') eventAdj+=0.25; const target=Math.max(3,g.base*(1+scarcity+eventAdj)); const old=m.price; m.price=Math.max(3,old*0.58+target*0.42+rnd(-1,1)); m.trend=m.price-old; m.history.push(m.price); if(m.history.length>30) m.history.shift();}}
}
function processShips(){for(const s of state.ships){ if(s.dest){s.eta--; s.condition=clamp(s.condition-(0.4+Math.random()*0.8),5,100); if(s.eta<=0){s.port=s.dest; s.dest=null; s.eta=0; pushNews(`${s.name} đã tới nơi`,`${s.name} vừa cập ${pname(s.port)} với ${cargoQty(s)} đơn vị hàng.`, 'Vận hành'); pushLog(`${s.name} cập ${pname(s.port)}.`); if(s.condition<40) pushNews('Tàu cần bảo trì',`${s.name} đã xuống tình trạng ${Math.round(s.condition)}%. Bạn nên theo dõi.`, 'Cảnh báo'); } } }}
function processFacilities(){for(const p of Object.keys(state.facilities)){const fac=state.facilities[p]; if(fac.owned.includes('fuel')){const income=rnd(1,4); state.cash+=income; if(Math.random()<0.15) pushNews('Trạm nhiên liệu có doanh thu',`Trạm nhiên liệu tại ${pname(p)} mang lại thêm ${money(income)}.`, 'Kinh doanh');}}
}
function processAI(){for(const c of state.ai){if(c.health<=0) continue; const port=pick(PORTS); let good=pick(GOODS); const m=state.markets[port.id][good.id]; const cheap=GOODS.map(g=>({g,score:state.markets[port.id][g.id].price/g.base})).sort((a,b)=>a.score-b.score)[0].g; const hot=GOODS.map(g=>({g,score:state.markets[port.id][g.id].trend})).sort((a,b)=>b.score-a.score)[0].g; if(c.style==='value') good=cheap; if(c.style==='spec') good=hot; if(c.style==='contract') good=pick([GOODS.find(g=>g.id==='luongthuc'),GOODS.find(g=>g.id==='duocpham'),GOODS.find(g=>g.id==='hanglanh')]); if(c.style==='heavy') good=pick([GOODS.find(g=>g.id==='thep'),GOODS.find(g=>g.id==='khoangsan'),GOODS.find(g=>g.id==='maymoc')]);
 const market=state.markets[port.id][good.id]; const qty=rnd(c.style==='heavy'?12:6,c.style==='heavy'?32:24); const buyScore=market.stock<85 || market.trend>0 || c.style==='value'; let action=''; if(buyScore && c.cash>market.price*qty*0.8){ const cost=qty*market.price; c.cash-=cost; market.stock=Math.max(2,market.stock-qty); action=`gom ${qty} ${good.name} tại ${port.name}`; }
 else { const revenue=qty*market.price*(c.style==='spec'?1.06:0.92); c.cash+=revenue; market.stock=Math.min(260,market.stock+qty); action=`bán ${qty} ${good.name} tại ${port.name}`; }
 if(c.style==='growth'&&Math.random()<0.28){ c.debt+=20; c.cash+=20; action+=' · vay thêm để mở rộng'; }
 if(c.style==='fast'&&Math.random()<0.18){ c.reputation+=1; action+=' · nhận tuyến gấp'; }
 c.cash-=c.fleet*(c.style==='heavy'?0.55:0.35); c.health=clamp(58+c.cash/28-c.fleet*3-c.debt*0.03,0,100); c.lastAction=action;
 if(c.cash<0||c.health<=3){ c.health=0; pushNews(`${c.name} ngừng hoạt động`,'Hãng này không còn đủ tiền để duy trì đội tàu và đã rút khỏi thị trường.','Cảnh báo'); pushLog(`${c.name} phá sản. Thị trường bớt đi một đối thủ.`); }
 else if(Math.random()<0.04){ pushNews('Động thái của đối thủ',`${c.name} vừa ${action}.`, 'Đối thủ'); }
 }}
function processContracts(){for(const c of state.acceptedContracts.filter(x=>x.status==='active')) if(state.day>c.deadline){ c.status='failed'; state.reputation-=5; const fine=Math.min(25,Math.max(6,state.cash*0.05)); state.cash-=fine; pushLog(`Hợp đồng ${c.title} bị trễ và thất bại.`,'bad'); pushNews('Hợp đồng thất bại',`${c.title} đã quá hạn. Bạn bị giảm danh tiếng và mất ${money(fine)}.`, 'Cảnh báo'); }
 state.contracts=state.contracts.filter(c=>c.deadline>=state.day); if(Math.random()<0.35&&state.contracts.length<4) generateContractsIfNeeded(); }
function processScheduled(){const due=state.scheduled.filter(x=>x.day<=state.day); state.scheduled=state.scheduled.filter(x=>x.day>state.day); for(const x of due){ if(x.chain){resolveChainStep(x); continue;} if(x.effect) state.effects.push(x.effect); if(x.rumor) state.intel.rumors.unshift(x.rumor); pushNews(x.title,x.text,x.kind||'Tin tức'); pushLog(x.text); }}
function processMonthly(){if(state.day%30!==0) return; const interest=state.debt*(state.effects.some(e=>e.type==='creditCrisis')?0.035:0.02); const shipMaint=state.ships.reduce((a,s)=>a+(sdef(s.type)?.maint||2),0); const facCost=Object.values(state.facilities).reduce((a,f)=>a+(f.owned||[]).reduce((x,id)=>x+(FACILITIES.find(ff=>ff.id===id)?.upkeep||0),0),0); const total=state.monthlySalary+interest+shipMaint+facCost; state.cash-=total; pushLog(`Cuối tháng: lương ${money(state.monthlySalary)}, lãi vay ${money(interest)}, bảo trì ${money(shipMaint)} và cơ sở ${money(facCost)}.`); pushNews('Chốt chi phí tháng',`Tổng chi định kỳ ${money(total)}.`, 'Tài chính');}
function processCharacters(){for(const c of state.characters){ c.mood=clamp(c.mood+rnd(-2,2)+(state.morale>70?1:0),20,95); if(state.day%20===0 && Math.random()<0.18){ c.loyalty=clamp(c.loyalty+rnd(-1,3),25,95); addCharacterStory(c.id,'Có thêm kinh nghiệm sau nhiều chuyến đi.'); }}}
function refreshIntel(){state.intel.rumors=(state.intel.rumors||[]).filter(r=>--r.days>0).slice(0,8); state.intel.forecasts=[]; for(const port of PORTS){const candidates=GOODS.map(g=>({good:g.id,port:port.id,trend:state.markets[port.id][g.id].trend,stock:state.markets[port.id][g.id].stock})).sort((a,b)=>Math.abs(b.trend)-Math.abs(a.trend)).slice(0,1); for(const c of candidates){const conf=clamp(45+Math.round(Math.abs(c.trend)*8)+(state.origin==='chobuon'?10:0),45,88); state.intel.forecasts.push({port:c.port,good:c.good,direction:Math.max(-25,Math.min(25,Math.round((state.markets[c.port][c.good].trend/state.markets[c.port][c.good].price)*100*10))),confidence:conf,days:rnd(2,5)});} }
 state.intel.forecasts=state.intel.forecasts.slice(0,6);
 if(Math.random()<0.35){const port=pick(PORTS), good=pick(GOODS); const dir=Math.random()<0.6?1:-1; const rumor={title:`Tin ở ${port.name}`,text:`Có nguồn cho rằng ${gname(good.id)} tại ${port.name} ${dir>0?'có thể tăng giá':'có thể hạ giá'} trong ít ngày tới.`,confidence:rnd(48,state.origin==='chobuon'?86:78),days:rnd(3,6)}; state.intel.rumors.unshift(rumor); state.intel.rumors=state.intel.rumors.slice(0,8);} }

function maybeEvent(){const chance=Math.min(0.88,0.42+state.day/1000); if(Math.random()>chance) return; const pool=['market','transport','staff','ship','business','social','government','personal','competitor']; if(state.day>35) pool.push('underground'); if(state.day>80&&Math.random()<0.18) pool.push('world'); if(Math.random()<0.16) return startChainEvent(); const group=pick(pool); const port=pick(PORTS), good=pick(GOODS), rival=pick(state.ai.filter(c=>c.health>0)); const map={
 market:['Nhu cầu tăng nhanh','Nhu cầu {good} tại {port} đang tăng.','boostDemand'],
 transport:['Tuyến đang ùn','Tuyến tới {port} đang đông, tàu có thể chậm thêm một ngày.','routeDelay'],
 staff:['Nhân viên xin tăng phụ cấp','Đội vận hành muốn điều chỉnh phụ cấp để bám việc lâu hơn.','staffRaise'],
 ship:['Máy tàu nóng bất thường','Một tàu báo nhiệt độ máy tăng.','shipHeat'],
 business:['Khách lớn tìm đến','Một doanh nghiệp muốn thử hợp tác ngắn hạn với công ty của bạn.','specialContract'],
 social:['Lễ hội địa phương','Lượng người và hàng tăng mạnh tại {port}.','festival'],
 government:['Siết kiểm tra','Hàng hóa qua {port} bị kiểm tra kỹ hơn vài ngày.','tightInspect'],
 personal:['Bạn cũ liên lạc','Một người bạn cũ ở kho hàng muốn giới thiệu <b>bạn</b> với khách mới.','oldFriend'],
 competitor:['Đối thủ gom hàng','{company} đang mua mạnh {good}. Chưa rõ họ biết điều gì.','aiAccumulation'],
 underground:['Mua tin nội bộ','Có người chào bán thông tin về đơn hàng lớn sắp tới.','buyIntel'],
 world:['Khủng hoảng năng lượng','Nhiều khu vực cùng thiếu nhiên liệu. Giá vận chuyển có nguy cơ tăng kéo dài.','energyCrisis']
 };
 const [titleTpl,textTpl,code]=map[group]; const title=titleTpl; const text=textTpl.replace('{port}',port.name).replace('{good}',good.name).replace('{company}',rival?.name||'một đối thủ'); const ev=buildEvent(group,title,text,code,{port:port.id,good:good.id,company:rival?.id}); state.events.push(ev); ensureMetaArray('discoveredEvents',code);}
function buildEvent(group,title,text,code,ctx){const C=(label,desc,action)=>({label,desc,action}); const base={id:'e'+Date.now()+Math.random(),group,title,text,code,ctx,choices:[]}; switch(code){case'boostDemand': base.choices=[C('Theo dõi thêm','Không tốn tiền nhưng chưa chắc cơ hội còn lâu.','watch'),C('Mua tin chi tiết','Chi 5 triệu để tăng chất lượng dự báo.','intel')]; break; case'staffRaise': base.choices=[C('Tăng phụ cấp','Chi phí tháng tăng 2 triệu, tinh thần đội tốt hơn.','raise'),C('Từ chối','Giữ chi phí nhưng tinh thần giảm.','refuseRaise')]; break; case'shipHeat': base.choices=[C('Sửa ngay','Chi 10 triệu để giữ tàu ổn định.','repair'),C('Tạm bỏ qua','Không tốn tiền nhưng tàu xuống cấp hơn.','ignoreRepair')]; break; case'specialContract': base.choices=[C('Nhận cơ hội','Tạo một hợp đồng thưởng cao.','newContract'),C('Từ chối','Không nhận thêm việc.','none')]; break; case'buyIntel': base.choices=[C('Mua tin 8 triệu','Có cơ hội biết sớm một biến động giá.','buyIntel'),C('Không mua','Tiết kiệm tiền.','none')]; break; case'oldFriend': base.choices=[C('Nhận lời giới thiệu','Có thể mở thêm chuỗi khách hàng.', 'oldFriendYes'),C('Để sau','Không thay đổi lúc này.','none')]; break; case'energyCrisis': base.choices=[C('Điều chỉnh kế hoạch','Ghi nhận biến cố và tự đổi chiến lược.','worldAccept')]; break; default: base.choices=[C('Chấp nhận tình hình','Không can thiệp trực tiếp.','watch'),C('Chủ động xử lý','Chi một khoản nhỏ để giảm rủi ro.','mitigate')]; }
 return base;}
function showPendingEvent(){if(!state.events.length || document.querySelector('.modal')) return; const ev=state.events[0]; openModal(`<div class="modal-card event ${['world','ship'].includes(ev.group)?'urgent':''}"><div class="row between"><span class="tag">${eventGroupName(ev.group)}</span><span class="mini muted">Ngày ${state.day}</span></div><h2 style="margin-top:8px">${ev.title}</h2><p>${ev.text}</p><div class="choice">${ev.choices.map((c,i)=>`<button data-choice="${i}"><b>${c.label}</b><div class="mini muted">${c.desc}</div></button>`).join('')}</div></div>`); document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>resolveEvent(ev,+b.dataset.choice));}
function resolveEvent(ev,i){const ch=ev.choices[i]; applyEventAction(ch.action,ev); pushLog(`${ev.title}: ${ch.label}.`); pushNews(ev.title,`${ev.text} Quyết định: ${ch.label}.`,eventGroupName(ev.group)); state.events.shift(); save(); closeModal(); if(state.events.length) showPendingEvent(); else renderGame();}
function applyEventAction(a,ev){const ctx=ev.ctx||{}; switch(a){case'intel': state.cash-=5; state.reputation+=1; state.intel.forecasts.unshift({port:ctx.port,good:ctx.good,direction:rnd(8,18),confidence:rnd(68,90),days:rnd(3,5)}); break; case'raise': state.monthlySalary+=2; state.morale=clamp(state.morale+8,0,100); state.characters.forEach(c=>c.mood=clamp(c.mood+5,0,100)); break; case'refuseRaise': state.morale=clamp(state.morale-8,0,100); state.characters[0]&&addCharacterStory(state.characters[0].id,'Không vui vì phụ cấp không được tăng.'); break; case'repair': state.cash-=10; state.ships.forEach(s=>s.condition=clamp(s.condition+12,0,100)); break; case'ignoreRepair': state.ships.forEach(s=>s.condition=clamp(s.condition-10,0,100)); break; case'newContract': generateContractsIfNeeded(true); if(state.contracts[0]) state.contracts[0].reward=Math.round(state.contracts[0].reward*1.3); break; case'buyIntel': if(state.cash>=8){ state.cash-=8; state.scheduled.push({day:state.day+1,title:'Tin từ môi giới',text:`Một đơn hàng lớn có thể làm giá ${gname(ctx.good)} tại ${pname(ctx.port)} tăng.`,kind:'Tin đồn',effect:{type:'boostDemand',good:ctx.good,port:ctx.port,days:5},rumor:{title:`Nguồn kín ở ${pname(ctx.port)}`,text:`${gname(ctx.good)} có thể tăng mạnh tại ${pname(ctx.port)}.`,confidence:rnd(60,85),days:5}});} break; case'worldAccept': state.effects.push({type:ev.code,days:rnd(25,55)}); break; case'mitigate': state.cash-=4; state.reputation+=1; break; case'watch': if(['boostDemand','festival'].includes(ev.code)) state.effects.push({type:ev.code,port:ctx.port,good:ctx.good,days:rnd(3,8)}); break; case'oldFriendYes': createSpecialCharacter('Đỗ Hải Nam','Khách hàng đầu mối','Giới thiệu khách lớn đầu tiên'); state.scheduled.push({day:state.day+4,title:'Khách hàng từ bạn cũ',text:'Mối quen mới muốn thử một hợp đồng lớn hơn bình thường.',kind:'Cá nhân',chain:{type:'oldFriendChain',stage:2,name:'Mối quen từ bạn cũ',summary:'Theo dõi khả năng biến thành khách lớn.',totalStages:3}}); startOrUpdateChain('Mối quen từ bạn cũ','Đang chờ khách mới phản hồi.',1,3,4); break; default: break;}}
function eventGroupName(g){return ({market:'Thị trường',transport:'Vận chuyển',staff:'Nhân viên',ship:'Tàu',business:'Kinh doanh',social:'Xã hội',government:'Chính sách',underground:'Đề nghị mờ ám',personal:'Cá nhân',competitor:'Đối thủ',world:'Biến cố lớn'})[g]||'Sự kiện';}
function effectName(t){return ({boostDemand:'Nhu cầu tăng',festival:'Lễ hội',medicineDemand:'Dược phẩm tăng',floodSupply:'Hàng về nhiều',shortage:'Thiếu hàng',industrialTax:'Thuế công nghiệp',energyCrisis:'Khủng hoảng năng lượng',recession:'Suy giảm kinh tế',boom:'Bùng nổ đầu tư',creditCrisis:'Khủng hoảng tín dụng'})[t]||t;}

function startChainEvent(){const choices=[startFuelChain,startStrikeChain,startRivalChain,startInspectionChain]; pick(choices)();}
function startOrUpdateChain(name,summary,stage,total,nextIn){const found=state.activeChains.find(c=>c.name===name); if(found){found.summary=summary; found.stage=stage; found.totalStages=total; found.nextIn=nextIn;} else state.activeChains.push({name,summary,stage,totalStages:total,nextIn}); ensureMetaArray('discoveredChains',name);}
function updateActiveChains(){state.activeChains.forEach(c=>c.nextIn=Math.max(0,c.nextIn-1)); state.activeChains=state.activeChains.filter(c=>c.stage<c.totalStages||c.nextIn>0);}
function createSpecialCharacter(name,role,story){if(!state.characters.some(c=>c.name===name)){state.characters.push({id:'sp'+Date.now()+Math.random(),name,role,trait:'đặc biệt',loyalty:62,mood:68,story:[story]}); ensureMetaArray('discoveredCharacters',name);} }
function resolveChainStep(item){const c=item.chain; if(c.type==='fuelChain'){ if(c.stage===2){ pushNews('Giá nhiên liệu tăng mạnh',`Căng thẳng kéo dài khiến nhiên liệu tăng rõ rệt trên nhiều cảng.`, 'Biến cố lớn'); state.effects.push({type:'energyCrisis',days:rnd(8,16)}); startOrUpdateChain(c.name,'Khủng hoảng đang lan rộng. Hãy kiểm soát chi phí vận chuyển.',2,3,8); state.scheduled.push({day:state.day+rnd(8,16),title:'Nguồn cung dần hồi lại',text:'Khủng hoảng năng lượng đang hạ nhiệt. Giá nhiên liệu có thể bớt căng.',kind:'Biến cố lớn',chain:{type:'fuelChain',stage:3,name:c.name}}); }
 else if(c.stage===3){ pushNews('Khủng hoảng năng lượng hạ nhiệt','Nguồn cung dần trở lại. Những ai tích được tiền mặt trong giai đoạn khó sẽ có lợi thế.', 'Biến cố lớn'); startOrUpdateChain(c.name,'Chuỗi đã kết lại, thị trường dần bình thường.',3,3,0); }
 }
 if(c.type==='strikeChain'){ if(c.stage===2){ pushNews('Đình công lan rộng',`Đội kho bãi tại ${pname(c.port)} đình công thật sự. Hàng bị trễ rõ rệt trong khoảng 5–10 ngày.`, 'Xã hội'); state.effects.push({type:'shortage',port:c.port,days:rnd(5,10)}); startOrUpdateChain(c.name,'Cảng đang tắc nghẽn do đình công.',2,3,7); state.scheduled.push({day:state.day+rnd(6,10),title:'Đình công kết thúc',text:`Cảng ${pname(c.port)} dần hoạt động lại, nhưng lượng hàng bị dồn có thể làm giá đảo chiều.`,kind:'Xã hội',effect:{type:'floodSupply',port:c.port,days:4},chain:{type:'strikeChain',stage:3,name:c.name,port:c.port}}); }
 else if(c.stage===3){ pushNews('Lượng hàng đổ về','Sau đình công, nhiều chuyến cùng cập cảng khiến một số giá có thể rơi nhanh.', 'Thị trường'); startOrUpdateChain(c.name,'Chuỗi đã kết thúc nhưng giá còn dư chấn ngắn hạn.',3,3,0); }
 }
 if(c.type==='rivalChain'){ if(c.stage===2){ const ai=state.ai.find(x=>x.id===c.rival); if(ai&&ai.health>0){ pushNews('Đối thủ mở đợt phá giá',`${ai.name} bắt đầu bán thấp ở ${pname(c.port)} để giành khách.`, 'Đối thủ'); state.effects.push({type:'floodSupply',port:c.port,good:c.good,days:rnd(5,9)}); startOrUpdateChain(c.name,'Đối thủ đang ép giá trong ngắn hạn.',2,3,6); state.scheduled.push({day:state.day+rnd(6,9),title:'Đối thủ hụt hơi',text:`${ai.name} đang đuối dòng tiền sau đợt phá giá. Đây có thể là lúc bạn phản công.`,kind:'Đối thủ',chain:{type:'rivalChain',stage:3,name:c.name,rival:c.rival,port:c.port,good:c.good}}); }
 } else if(c.stage===3){ const ai=state.ai.find(x=>x.id===c.rival); if(ai&&ai.health>0){ ai.cash-=rnd(20,60); ai.health=clamp(ai.health-rnd(4,12),0,100); pushNews('Đối thủ hụt hơi',`${ai.name} bắt đầu yếu đi sau đợt cạnh tranh giá.`, 'Đối thủ'); } startOrUpdateChain(c.name,'Chuỗi cạnh tranh đã lắng xuống.',3,3,0);}
 }
 if(c.type==='inspectionChain'){ if(c.stage===2){ pushNews('Đợt kiểm tra mở rộng',`Cơ quan quản lý mở rộng kiểm tra tại ${pname(c.port)}. Hàng công nghiệp và điện tử bị soi kỹ hơn.`, 'Chính sách'); state.effects.push({type:'industrialTax',port:c.port,days:rnd(5,8)}); startOrUpdateChain(c.name,'Đợt kiểm tra đang làm giá hàng công nghiệp biến động.',2,3,5); state.scheduled.push({day:state.day+rnd(5,8),title:'Đợt kiểm tra kết thúc',text:`Thủ tục tại ${pname(c.port)} dần trở lại bình thường.`,kind:'Chính sách',chain:{type:'inspectionChain',stage:3,name:c.name,port:c.port}}); } else if(c.stage===3){ pushNews('Đợt kiểm tra kết thúc',`Thủ tục tại ${pname(c.port)} đã dần trở lại bình thường.`, 'Chính sách'); startOrUpdateChain(c.name,'Chuỗi kiểm tra đã kết thúc.',3,3,0); }
 }
 if(c.type==='oldFriendChain' && c.stage===2){ generateContractsIfNeeded(true); if(state.contracts[0]){state.contracts[0].reward=Math.round(state.contracts[0].reward*1.4); pushNews('Mối khách đầu tiên',`Nhờ mối quen từ bạn cũ, bạn nhận được cơ hội hợp đồng giá tốt hơn bình thường.`, 'Cá nhân'); startOrUpdateChain(c.name,'Mối quen đang mang về khách đầu tiên.',2,3,5); state.scheduled.push({day:state.day+5,title:'Khách quay lại',text:'Khách mới hài lòng và muốn xem bạn có thể hợp tác dài hơn không.',kind:'Cá nhân',chain:{type:'oldFriendChain',stage:3,name:c.name}});} } else if(c.type==='oldFriendChain' && c.stage===3){ pushNews('Khách quay lại','Mối khách mới đã bắt đầu quay lại đều hơn. Bạn vừa xây được một quan hệ làm ăn dài hơi.', 'Cá nhân'); startOrUpdateChain(c.name,'Chuỗi khách hàng mới đã chốt xong.',3,3,0);} 
 }
function startFuelChain(){const ev={id:'chain'+Date.now(),group:'world',title:'Dấu hiệu thiếu nhiên liệu',text:'Một số cảng báo lượng nhiên liệu về chậm bất thường. Nếu kéo dài, chi phí vận chuyển có thể tăng mạnh.',code:'fuelChain',choices:[{label:'Giữ thêm tiền mặt',desc:'Bớt vay và thận trọng hơn trong vài ngày tới.','action':'fuelSafe'},{label:'Đặt cược gom nhiên liệu',desc:'Bạn chọn mua dần nhiên liệu ở những nơi còn rẻ.','action':'fuelBet'}],ctx:{}}; state.events.push(ev); ensureMetaArray('discoveredEvents','fuelChainPrompt');}
function startStrikeChain(){const port=pick(PORTS); const ev={id:'chain'+Date.now(),group:'social',title:'Tiếng xì xào ở kho bãi',text:`Nhân viên kho tại ${port.name} đang than phiền về khối lượng công việc. Nếu bị bỏ qua, họ có thể đình công trong 5–10 ngày tới.`,code:'strikeChain',choices:[{label:'Chuẩn bị né cảng này',desc:'Bạn chưa can thiệp nhưng chủ động theo dõi giá.','action':'strikeWatch'},{label:'Chủ động làm quen đầu mối',desc:'Chi 6 triệu để có thông tin sớm và dễ xoay sở hơn.','action':'strikeIntel'}],ctx:{port:port.id}}; state.events.push(ev); ensureMetaArray('discoveredEvents','strikeChainPrompt');}
function startRivalChain(){const ai=pick(state.ai.filter(a=>a.health>0)); const port=pick(PORTS); const good=pick(GOODS); const ev={id:'chain'+Date.now(),group:'competitor',title:'Đối thủ âm thầm gom hàng',text:`${ai.name} đang âm thầm gom ${good.name} quanh ${port.name}. Có thể họ sắp tạo một đợt ép giá hoặc chuẩn bị hợp đồng lớn.`,code:'rivalChain',choices:[{label:'Quan sát và chờ',desc:'Bạn chưa hành động, chỉ lưu ý diễn biến tiếp theo.','action':'rivalWatch'},{label:'Đi trước một bước',desc:'Chi 7 triệu để lấy thông tin sâu hơn về kế hoạch của họ.','action':'rivalIntel'}],ctx:{port:port.id,good:good.id,rival:ai.id}}; state.events.push(ev); ensureMetaArray('discoveredEvents','rivalChainPrompt');}
function startInspectionChain(){const port=pick(PORTS); const ev={id:'chain'+Date.now(),group:'government',title:'Tin hành lang về đợt kiểm tra',text:`Có nguồn nói ${port.name} sắp có đợt kiểm tra thủ tục hàng hóa. Nếu đúng, giá một số hàng công nghiệp có thể biến động trong 5–8 ngày tới.`,code:'inspectionChain',choices:[{label:'Ghi nhận và thận trọng',desc:'Bạn chưa tốn tiền nhưng chấp nhận độ mơ hồ.','action':'inspectWatch'},{label:'Mua tin chính xác hơn',desc:'Chi 5 triệu để biết rõ mốc thời gian.','action':'inspectIntel'}],ctx:{port:port.id}}; state.events.push(ev); ensureMetaArray('discoveredEvents','inspectionChainPrompt');}
const originalApplyEventAction=applyEventAction;
applyEventAction=function(a,ev){const ctx=ev.ctx||{}; if(a==='fuelSafe'){ state.reputation+=1; state.scheduled.push({day:state.day+rnd(5,9),title:'Chuỗi thiếu nhiên liệu tiếp diễn',text:'Dấu hiệu thiếu nhiên liệu chuyển thành biến động thật sự.',kind:'Biến cố lớn',chain:{type:'fuelChain',stage:2,name:'Khủng hoảng năng lượng âm ỉ'}}); startOrUpdateChain('Khủng hoảng năng lượng âm ỉ','Bạn đang giữ thế thủ và chờ diễn biến.',1,3,rnd(5,9)); return; }
 if(a==='fuelBet'){ const qty=5; const ship=state.ships.find(s=>!s.dest&&s.port===selectedPort)||state.ships.find(s=>!s.dest); if(ship&&freeCap(ship)>=qty){ for(let i=0;i<qty;i++){const mk=state.markets[ship.port]['nhienlieu']; if(state.cash>=mk.price && mk.stock>0){state.cash-=mk.price; ship.cargo.nhienlieu=(ship.cargo.nhienlieu||0)+1; mk.stock--;}} } state.scheduled.push({day:state.day+rnd(5,9),title:'Chuỗi thiếu nhiên liệu tiếp diễn',text:'Dấu hiệu thiếu nhiên liệu chuyển thành biến động thật sự.',kind:'Biến cố lớn',chain:{type:'fuelChain',stage:2,name:'Khủng hoảng năng lượng âm ỉ'}}); startOrUpdateChain('Khủng hoảng năng lượng âm ỉ','Bạn đã đặt cược gom nhiên liệu từ sớm.',1,3,rnd(5,9)); return; }
 if(a==='strikeWatch'){ state.scheduled.push({day:state.day+rnd(5,10),title:'Đình công bùng ra',text:'Căng thẳng kho bãi đã bùng ra thành đình công.',kind:'Xã hội',chain:{type:'strikeChain',stage:2,name:'Đình công kho bãi',port:ctx.port}}); startOrUpdateChain('Đình công kho bãi',`Bạn đang theo dõi rủi ro tại ${pname(ctx.port)}.`,1,3,rnd(5,10)); return; }
 if(a==='strikeIntel'){ state.cash-=6; state.intel.rumors.unshift({title:`Tin nội bộ ${pname(ctx.port)}`,text:`Khả năng đình công tại ${pname(ctx.port)} là khá cao.`,confidence:rnd(70,88),days:6}); state.scheduled.push({day:state.day+rnd(5,8),title:'Đình công bùng ra',text:'Căng thẳng kho bãi đã bùng ra thành đình công.',kind:'Xã hội',chain:{type:'strikeChain',stage:2,name:'Đình công kho bãi',port:ctx.port}}); startOrUpdateChain('Đình công kho bãi',`Bạn đã mua tin và chuẩn bị trước cho rủi ro ở ${pname(ctx.port)}.`,1,3,rnd(5,8)); return; }
 if(a==='rivalWatch'){ state.scheduled.push({day:state.day+rnd(4,8),title:'Đối thủ ra đòn',text:'Đối thủ bắt đầu chiến lược mới trên thị trường.',kind:'Đối thủ',chain:{type:'rivalChain',stage:2,name:'Cuộc đua với đối thủ',rival:ctx.rival,port:ctx.port,good:ctx.good}}); startOrUpdateChain('Cuộc đua với đối thủ','Bạn đang theo dõi đối thủ trước khi phản ứng.',1,3,rnd(4,8)); return; }
 if(a==='rivalIntel'){ state.cash-=7; state.intel.rumors.unshift({title:'Tin về đối thủ',text:`${state.ai.find(x=>x.id===ctx.rival)?.name||'Đối thủ'} có vẻ sắp đánh mạnh vào ${gname(ctx.good)} ở ${pname(ctx.port)}.`,confidence:rnd(72,90),days:5}); state.scheduled.push({day:state.day+rnd(4,6),title:'Đối thủ ra đòn',text:'Đối thủ bắt đầu chiến lược mới trên thị trường.',kind:'Đối thủ',chain:{type:'rivalChain',stage:2,name:'Cuộc đua với đối thủ',rival:ctx.rival,port:ctx.port,good:ctx.good}}); startOrUpdateChain('Cuộc đua với đối thủ','Bạn đã lấy tin sâu hơn về kế hoạch của đối thủ.',1,3,rnd(4,6)); return; }
 if(a==='inspectWatch'){ state.scheduled.push({day:state.day+rnd(5,8),title:'Đợt kiểm tra mở rộng',text:'Tin hành lang hóa ra là thật.',kind:'Chính sách',chain:{type:'inspectionChain',stage:2,name:'Đợt kiểm tra diện rộng',port:ctx.port}}); startOrUpdateChain('Đợt kiểm tra diện rộng',`Bạn đang chờ xem ${pname(ctx.port)} có thật sự bị soi kỹ không.`,1,3,rnd(5,8)); return; }
 if(a==='inspectIntel'){ state.cash-=5; state.scheduled.push({day:state.day+rnd(4,6),title:'Đợt kiểm tra mở rộng',text:'Tin hành lang hóa ra là thật.',kind:'Chính sách',chain:{type:'inspectionChain',stage:2,name:'Đợt kiểm tra diện rộng',port:ctx.port}}); state.intel.rumors.unshift({title:`Lịch kiểm tra ${pname(ctx.port)}`,text:`Khả năng cao đợt kiểm tra sẽ xảy ra trong vài ngày tới.`,confidence:rnd(72,88),days:5}); startOrUpdateChain('Đợt kiểm tra diện rộng',`Bạn đã mua tin rõ hơn về ${pname(ctx.port)}.`,1,3,rnd(4,6)); return; }
 return originalApplyEventAction(a,ev);
};

function checkBankruptcy(){const nw=netWorth(); if(state.cash<-100||nw<-120||state.debt>state.creditLimit+30){finishRun(true,'Công ty không còn đủ khả năng thanh toán và buộc phải dừng hoạt động.'); return true;} if(state.day>=500&&nw>=5000){finishRun(false,'Công ty đã đạt quy mô lớn và hoàn thành một hành trình thành công.',true); return true;} return false;}
function finishRun(bankrupt,reason,win=false){if(!state||state.status!=='playing') return; state.status=bankrupt?'bankrupt':win?'won':'retired'; meta.runs++; if(bankrupt) meta.bankruptcies++; if(win) meta.wins++; const score=Math.max(1,Math.floor(state.day/35)+Math.floor(Math.max(0,netWorth())/450)+(state.origin==='taytrang'?4:0)+(win?10:0)); meta.careerPoints+=score; meta.bestNetWorth=Math.max(meta.bestNetWorth,netWorth()); meta.history.unshift({company:state.company,day:state.day,net:netWorth(),result:state.status,score}); meta.history=meta.history.slice(0,60); if(win) ensureMetaArray('endings','Hành trình thành công'); if(bankrupt) ensureMetaArray('endings','Phá sản'); for(const o of ORIGINS){if(meta.careerPoints>=o.unlock && !meta.unlockedOrigins.includes(o.id)) meta.unlockedOrigins.push(o.id);} saveMeta(); save(); openModal(`<div class="modal-card"><span class="tag ${bankrupt?'bad':''}">${bankrupt?'PHÁ SẢN':win?'HOÀN THÀNH':'KẾT THÚC'}</span><h2 style="margin-top:8px">Tổng kết ${esc(state.company)}</h2><p>${reason}</p><div class="grid3"><div class="stat"><span>Số ngày</span><b>${state.day}</b></div><div class="stat"><span>Tài sản cuối</span><b>${money(netWorth())}</b></div><div class="stat"><span>Điểm sự nghiệp</span><b>+${score}</b></div></div><div class="brief" style="margin-top:10px"><div class="brief-item">Giao dịch: <b>${state.stats.trades}</b> · Hợp đồng hoàn thành: <b>${state.stats.contractsDone}</b></div><div class="brief-item">Nhiều tàu nhất: <b>${state.stats.maxShips}</b> · Danh tiếng cuối: <b>${state.reputation}</b></div><div class="brief-item">Chuỗi đã mở trong ván này: <b>${meta.discoveredChains.length}</b> · Nhân vật đặc biệt đã gặp: <b>${meta.discoveredCharacters.length}</b></div></div><p class="muted mini">Điểm sự nghiệp mở thêm kiểu khởi đầu và lựa chọn mới, nhưng không cộng tiền trực tiếp cho hành trình sau.</p><button class="btn primary" id="toSlots">Về 3 ô lưu</button></div>`); $('#toSlots').onclick=()=>{closeModal(); startScreen();};}

function openModal(html){closeModal(); modal=document.createElement('div'); modal.className='modal'; modal.innerHTML=html; document.body.appendChild(modal);} 
function closeModal(){if(modal){modal.remove(); modal=null;}}

startScreen();
})();
