import {SAVE_KEY,LEGACY_SAVE_KEY,SAVE_VERSION,MAX_PLOTS,INITIAL_PLOTS,INITIAL_GOLD,INITIAL_WAREHOUSE,MATERIAL_CONFIG,CROP_CONFIG,SPEED_UPGRADES,DIAMOND_RECIPE_CONFIG,VILLA_CONFIG,WEATHER_CONFIG,HELP_CONFIG} from './config.js?v=2.0.0';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cropById=Object.fromEntries(CROP_CONFIG.map(c=>[c.id,c]));
const fmt=n=>Math.floor(n||0).toLocaleString('vi-VN');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const now=()=>Date.now();
const hour=3600000;
let selectedAction='harvest', selectedCrop='carrot', soundOn=false, tickTimer=null;
const emptyMaterials=()=>Object.fromEntries(Object.keys(MATERIAL_CONFIG).map(k=>[k,0]));
const emptyCrops=()=>Object.fromEntries(CROP_CONFIG.map(c=>[c.id,{normal:0,fresh:0,premium:0}]));
function newPlot(i){return {id:i,cropId:null,plantedAt:0,wateredAt:0,diseaseAt:0,deadAt:0,deadReason:'',treatedAt:0}}
function defaultState(){return {version:SAVE_VERSION,createdAt:now(),lastSeen:now(),gold:INITIAL_GOLD,diamonds:0,exp:0,level:1,warehouse:{capacity:INITIAL_WAREHOUSE,crops:emptyCrops(),materials:emptyMaterials()},plots:Array.from({length:MAX_PLOTS},(_,i)=>newPlot(i)),unlockedPlotCount:INITIAL_PLOTS,speedLevel:0,orders:[null,null,null],orderCooldown:[0,0,0],house:{built:{},styles:{roof:'red',fence:'wood',path:'stone'}},tutorial:{step:0,seenDiamond:false},stats:{harvested:0,orders:0,sold:0,cropsPlanted:0,diamondsMade:0},achievements:{},lastWeatherKey:'',lastSavedAt:0};}
let state=defaultState();
function save(){state.lastSeen=now();state.lastSavedAt=state.lastSeen;localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
function load(){const raw=localStorage.getItem(SAVE_KEY);if(raw){try{const v=JSON.parse(raw);state=migrateV2(v);return}catch(e){console.warn(e)}}migrateLegacy();}
function migrateV2(v){const base=defaultState();const s={...base,...v,warehouse:{...base.warehouse,...(v.warehouse||{})},house:{...base.house,...(v.house||{}),styles:{...base.house.styles,...(v.house?.styles||{})}},stats:{...base.stats,...(v.stats||{})},tutorial:{...base.tutorial,...(v.tutorial||{})}};s.warehouse.crops={...emptyCrops(),...(v.warehouse?.crops||{})};s.warehouse.materials={...emptyMaterials(),...(v.warehouse?.materials||{})};s.plots=Array.from({length:MAX_PLOTS},(_,i)=>({...newPlot(i),...(v.plots?.[i]||{})}));s.version=2;return s}
function migrateLegacy(){const raw=localStorage.getItem(LEGACY_SAVE_KEY);state=defaultState();if(!raw)return;try{const old=JSON.parse(raw);state.gold=Math.max(INITIAL_GOLD,Math.min(Number(old.gold)||INITIAL_GOLD,25000));state.unlockedPlotCount=clamp(old.unlockedPlotCount||INITIAL_PLOTS,INITIAL_PLOTS,MAX_PLOTS);const map={carrot:'carrot',potato:'potato',corn:'corn',strawberry:'strawberry',watermelon:'watermelon',pumpkin:'pumpkin',diamond:'blueberry'};(old.plots||[]).slice(0,MAX_PLOTS).forEach((p,i)=>{if(p?.cropType&&map[p.cropType])state.plots[i]={...newPlot(i),cropId:map[p.cropType],plantedAt:p.startTime||now(),wateredAt:p.startTime||now()}});showInfo('Đã chuyển dữ liệu Farm cũ','Farm V2 đã giữ lại Vàng, diện tích đất và các cây còn nhận diện được. Economy mới dùng Kho/EXP/Vật liệu/Kim Cương nên một số nâng cấp cũ không chuyển trực tiếp.');save()}catch(e){console.warn('Không migration được Farm cũ',e)}}
function expNeed(level){return 80+level*45+Math.floor(level*level*4)}
function addExp(n){state.exp+=n;let up=0;while(state.exp>=expNeed(state.level)){state.exp-=expNeed(state.level);state.level++;up++}if(up){toast(`🎉 Lên Cấp ${state.level}!`);checkAchievements();renderAll()}}
function speedMult(){return SPEED_UPGRADES[state.speedLevel]?.mult||1}
function cropUnits(){let n=0;for(const q of Object.values(state.warehouse.crops))n+=q.normal+q.fresh+q.premium;return n}
function materialUnits(){return Object.values(state.warehouse.materials).reduce((a,b)=>a+b,0)}
function warehouseUsed(){return cropUnits()+Math.ceil(materialUnits()/10)}
function warehouseFree(){return Math.max(0,state.warehouse.capacity-warehouseUsed())}
function getWeather(){const key=Math.floor(now()/(6*hour));const idx=Math.abs((key*17+11)%WEATHER_CONFIG.length);return {key:String(key),...WEATHER_CONFIG[idx]}}
function weatherSync(){const w=getWeather();if(state.lastWeatherKey!==w.key){if(w.id==='rain'){for(const p of state.plots)if(p.cropId&&!p.deadAt)p.wateredAt=now();toast('🌧️ Trời mưa: cây trên ruộng đã được tưới.')}state.lastWeatherKey=w.key;save()}return w}
function careStatus(p,t=now()){if(!p.cropId)return {id:'empty',label:'Đất trống'};if(p.deadAt)return {id:'dead',label:'Đã chết'};const c=cropById[p.cropId],w=getWeather(),hours=(t-(p.wateredAt||p.plantedAt))/hour*w.waterFactor;const safe=18+(1-c.waterNeed)*9;if(hours>safe+42)return {id:'dead',label:'Chết vì thiếu nước',dead:true,reason:`Thiếu nước quá lâu (${Math.floor(hours)} giờ).`};if(hours>safe+30)return {id:'disease',label:'Bệnh nặng',disease:true};if(hours>safe+18)return {id:'weak',label:'Suy yếu',disease:true};if(hours>safe+8)return {id:'dry',label:'Khô'};if(hours>safe)return {id:'slightly',label:'Hơi khô'};return {id:'good',label:'Đủ nước'}}
function growthProgress(p,t=now()){if(!p.cropId||p.deadAt)return 0;const c=cropById[p.cropId],w=getWeather();return clamp((t-p.plantedAt)/(c.growMin*60000)*speedMult()*w.growth,0,1)}
function syncPlotHealth(){let changed=false;for(const p of state.plots){if(!p.cropId||p.deadAt)continue;const s=careStatus(p);if(s.dead){p.deadAt=now();p.deadReason=s.reason;changed=true}else if(s.disease&&!p.diseaseAt){p.diseaseAt=now();changed=true}}if(changed)save()}
function qualityFor(p){const s=careStatus(p),w=getWeather();let score=.66+w.quality;if(s.id==='slightly')score-=.08;if(s.id==='dry')score-=.20;if(s.id==='weak'||s.id==='disease')score-=.35;if(p.diseaseAt)score-=.12;score=clamp(score,.1,.98);return score>.83?'premium':score>.52?'fresh':'normal'}
function qualityName(q){return q==='premium'?'Hảo hạng':q==='fresh'?'Tươi':'Thường'}
function cropQty(id){const q=state.warehouse.crops[id];return q.normal+q.fresh+q.premium}
function takeCrop(id,count){let left=count,q=state.warehouse.crops[id];for(const k of ['normal','fresh','premium']){const use=Math.min(q[k],left);q[k]-=use;left-=use;if(!left)break}return left===0}
function hasCosts({gold=0,diamond=0,materials={},crops={}}={}){if(state.gold<gold||state.diamonds<diamond)return false;for(const [k,v] of Object.entries(materials))if((state.warehouse.materials[k]||0)<v)return false;for(const [k,v] of Object.entries(crops))if(cropQty(k)<v)return false;return true}
function spendCosts(cost){if(!hasCosts(cost))return false;state.gold-=cost.gold||0;state.diamonds-=cost.diamond||0;for(const [k,v] of Object.entries(cost.materials||{}))state.warehouse.materials[k]-=v;for(const [k,v] of Object.entries(cost.crops||{}))takeCrop(k,v);return true}
function addMaterial(id,n){state.warehouse.materials[id]=(state.warehouse.materials[id]||0)+n}
function formatDuration(ms){if(ms<=0)return 'Sẵn sàng';const m=Math.ceil(ms/60000);if(m<60)return `${m} phút`;const h=Math.floor(m/60),mm=m%60;return `${h}g ${mm}p`}
function seeded(seed){let x=Math.sin(seed)*10000;return x-Math.floor(x)}
function marketInfo(c){const period=Math.floor(now()/(6*hour)),r=seeded(period*101+c.level*17+c.id.length*13),mult=.75+r*.5;return {mult,price:Math.max(1,Math.round(c.basePrice*mult)),trend:mult>1.08?'↑ Giá tốt':mult<.92?'↓ Giá thấp':'→ Ổn định'}}
function materialExchangeCost(id){const keys=['carrot','potato','corn','tomato','cabbage','strawberry','pumpkin','watermelon'];const crop=keys[Object.keys(MATERIAL_CONFIG).indexOf(id)%keys.length];return {crop,qty:10+Object.keys(MATERIAL_CONFIG).indexOf(id)*2}}
function levelCropPool(){return CROP_CONFIG.filter(c=>c.level<=state.level)}
function generateOrder(slot){const pool=levelCropPool();const seed=Math.floor(now()/60000)+slot*91+state.stats.orders*13;const lines=1+Math.floor(seeded(seed)*Math.min(3,pool.length));const req={};for(let i=0;i<lines;i++){const c=pool[Math.floor(seeded(seed+i*31)*pool.length)];req[c.id]=(req[c.id]||0)+Math.max(3,Math.round((6+c.level*.7)*(0.8+seeded(seed+i*55)*.8)))}let value=0;for(const [id,q] of Object.entries(req))value+=cropById[id].basePrice*q;const mats=Object.keys(MATERIAL_CONFIG),mat=mats[Math.floor(seeded(seed+777)*Math.min(mats.length,Math.max(2,Math.floor(state.level/2)+2)))];return {id:`o-${slot}-${now()}`,customer:['Quán Bếp Xanh','Cô Lan hàng xóm','Nhà hàng Sân Vườn','Bếp Trường Mầm Non','Tiệm Nước Mát'][Math.floor(seeded(seed+8)*5)],title:['Giỏ rau hôm nay','Đơn bếp gia đình','Chuyến hàng buổi chiều','Đặt hàng cuối tuần'][Math.floor(seeded(seed+9)*4)],req,gold:Math.round(value*(1.2+seeded(seed+2)*.25)),exp:Math.max(8,Math.round(value/18)),material:{id:mat,qty:1+Math.floor(seeded(seed+3)*3)}}}
function ensureOrders(){let changed=false;for(let i=0;i<3;i++){if(!state.orders[i]&&now()>=(state.orderCooldown[i]||0)){state.orders[i]=generateOrder(i);changed=true}}if(changed)save()}
function completeOrder(i){const o=state.orders[i];if(!o)return;for(const [id,q] of Object.entries(o.req))if(cropQty(id)<q)return guide('Chưa thể giao đơn',`Bạn chưa đủ ${cropById[id].name}. Hiện có ${cropQty(id)}, cần ${q}.`,['Trồng thêm nông sản còn thiếu.','Kiểm tra Kho trước khi giao.']);const cropCost=Object.fromEntries(Object.entries(o.req));if(!spendCosts({crops:cropCost}))return;state.gold+=o.gold;addExp(o.exp);addMaterial(o.material.id,o.material.qty);state.stats.orders++;state.orders[i]=null;state.orderCooldown[i]=now()+(8+Math.floor(Math.random()*12))*60000;toast(`✅ Giao đơn thành công · +${fmt(o.gold)} Vàng`);checkAchievements();save();renderAll()}
function discardOrder(i){if(!state.orders[i])return;state.orders[i]=null;state.orderCooldown[i]=now()+(12+Math.floor(Math.random()*18))*60000;save();renderOrders();toast('Đã bỏ đơn. Đơn mới sẽ xuất hiện sau thời gian chờ.','warning')}
function plant(i,id){const c=cropById[id],p=state.plots[i];if(!c||c.level>state.level)return guide('Chưa mở khóa',`${c?.name||'Cây này'} mở khóa ở Cấp ${c?.level||'?'}.`,['Hoàn thành đơn hàng và thu hoạch để nhận EXP.']);if(p.cropId)return;if(state.gold<c.seedCost)return guide('Chưa đủ Vàng',`Bạn cần thêm ${fmt(c.seedCost-state.gold)} Vàng để mua hạt ${c.name}.`,['Bán nông sản trong Chợ.','Hoàn thành đơn hàng.']);state.gold-=c.seedCost;state.plots[i]={...newPlot(i),cropId:id,plantedAt:now(),wateredAt:now()};state.stats.cropsPlanted++;save();renderAll();toast(`Đã gieo ${c.name}.`)}
function harvest(i){const p=state.plots[i];if(!p.cropId||p.deadAt)return;if(growthProgress(p)<1)return toast('Cây chưa trưởng thành.','warning');const c=cropById[p.cropId];if(warehouseFree()<c.yield)return guide('Kho đã đầy',`Kho hiện có ${warehouseUsed()}/${state.warehouse.capacity} chỗ. Cần ít nhất ${c.yield} chỗ để thu hoạch ${c.name}.`,['Bán bớt nông sản.','Giao đơn hàng.','Đổi nông sản lấy vật liệu.','Dùng 1 Kim Cương để mở thêm 5 chỗ.']);const q=qualityFor(p);state.warehouse.crops[c.id][q]+=c.yield;state.stats.harvested+=c.yield;addExp(c.exp);state.plots[i]=newPlot(i);toast(`🧺 +${c.yield} ${c.name} (${qualityName(q)})`);checkAchievements();save();renderAll()}
function water(i){const p=state.plots[i];if(!p.cropId||p.deadAt)return;p.wateredAt=now();toast('💧 Đã tưới cây.');save();renderFarm()}
function cure(i){const p=state.plots[i];if(!p.cropId||p.deadAt)return;const status=careStatus(p);if(!status.disease&&!p.diseaseAt)return toast('Cây chưa có dấu hiệu bệnh.');if(state.warehouse.materials.fertilizer>0)state.warehouse.materials.fertilizer--;else if(state.gold>=35)state.gold-=35;else return guide('Chưa thể chăm bệnh','Bạn cần 1 Phân hữu cơ hoặc 35 Vàng.',['Hoàn thành đơn hàng để nhận vật liệu.','Đổi nông sản lấy Phân hữu cơ.']);p.diseaseAt=0;p.treatedAt=now();p.wateredAt=now();toast('🌿 Cây đã được chăm và tưới lại.');save();renderAll()}
function clearDead(i){const p=state.plots[i];if(!p.deadAt)return;p.cropId=null;p.deadAt=0;p.deadReason='';p.plantedAt=0;p.wateredAt=0;p.diseaseAt=0;save();renderFarm();toast('Đã dọn cây chết.')}
function handlePlot(i){if(i>=state.unlockedPlotCount)return guide('Ô đất chưa mở','Bạn cần mở rộng ruộng trước.',['Vào Nâng cấp → Mở thêm đất.']);const p=state.plots[i];if(selectedAction==='water')return water(i);if(selectedAction==='cure')return cure(i);if(selectedAction==='clear')return clearDead(i);if(selectedAction==='harvest'&&p.cropId)return harvest(i);if(!p.cropId){if(selectedAction==='plant')return plant(i,selectedCrop);return toast('Chọn một loại hạt giống để gieo vào ô đất trống.','warning')}if(growthProgress(p)>=1)return harvest(i);toast('Cây đang lớn. Bạn có thể tưới nếu đất bắt đầu khô.','warning')}
function waterAll(){const living=state.plots.filter((p,i)=>i<state.unlockedPlotCount&&p.cropId&&!p.deadAt);if(!living.length)return toast('Không có cây cần tưới.');living.forEach(p=>p.wateredAt=now());save();renderFarm();toast(`💧 Đã tưới ${living.length} ô.`)}
function sellCrop(id,n){const available=cropQty(id),qty=n==='all'?available:Math.min(n,available);if(!qty)return;const c=cropById[id],m=marketInfo(c);takeCrop(id,qty);const gold=qty*m.price;state.gold+=gold;state.stats.sold+=qty;save();renderAll();toast(`💰 Bán ${qty} ${c.name} · +${fmt(gold)} Vàng`)}
function exchangeMaterial(id){const {crop,qty}=materialExchangeCost(id);if(cropQty(crop)<qty)return guide('Chưa đủ nông sản',`Cần ${qty} ${cropById[crop].name} để đổi 2 ${MATERIAL_CONFIG[id].name}.`,[`Hiện có: ${cropQty(crop)}.`]);takeCrop(crop,qty);addMaterial(id,2);save();renderAll();toast(`Đổi được 2 ${MATERIAL_CONFIG[id].name}.`)}
function expandWarehouse(){if(state.diamonds<1)return guide('Bạn chưa đủ Kim Cương','Kim Cương không mua bằng Vàng.',['Đổi nông sản + vật liệu ở Nâng cấp.','Hoàn thành thành tựu.']);const before=state.warehouse.capacity;if(!confirm(`Kho hiện tại: ${before}\nSau nâng cấp: ${before+5}\nDùng 1 Kim Cương?`))return;state.diamonds--;state.warehouse.capacity+=5;save();renderAll();toast('📦 Kho đã mở thêm 5 chỗ.')}
function craftDiamond(id){const r=DIAMOND_RECIPE_CONFIG.find(x=>x.id===id);if(!r||state.level<r.level)return;if(!hasCosts({crops:r.crops,materials:r.materials}))return guide('Chưa đủ nguyên liệu','Bạn chưa đủ nông sản hoặc vật liệu cho công thức này.',['Kiểm tra Kho.','Hoàn thành đơn hàng để nhận vật liệu.']);spendCosts({crops:r.crops,materials:r.materials});state.diamonds+=r.diamond;state.stats.diamondsMade+=r.diamond;save();checkAchievements();renderAll();toast(`💎 Nhận ${r.diamond} Kim Cương!`)}
function upgradeSpeed(){const next=SPEED_UPGRADES[state.speedLevel+1];if(!next)return toast('Đã đạt cấp tốc độ tối đa.');if(state.diamonds<next.cost)return guide('Chưa đủ Kim Cương',`Nâng tốc độ Cấp ${next.level} cần ${next.cost} Kim Cương.`,['Ưu tiên giữa Kho, Tốc độ và Nhà Vườn.']);if(!confirm(`Dùng ${next.cost} Kim Cương để tăng tốc độ cây lên ${Math.round(next.mult*100)}%?`))return;state.diamonds-=next.cost;state.speedLevel++;save();renderAll();toast('⚡ Tốc độ tăng trưởng đã được nâng vĩnh viễn.')}
function expandLand(){if(state.unlockedPlotCount>=MAX_PLOTS)return toast('Đã mở toàn bộ đất.');const step=state.unlockedPlotCount-INITIAL_PLOTS,cost=180+step*85,wood=Math.floor(step/3);if(!hasCosts({gold:cost,materials:{wood}}))return guide('Chưa thể mở đất',`Cần ${fmt(cost)} Vàng${wood?` và ${wood} Gỗ`:''}.`,['Hoàn thành đơn hàng để nhận Vàng và vật liệu.']);spendCosts({gold:cost,materials:{wood}});state.unlockedPlotCount++;save();renderAll();toast('🚩 Đã mở thêm 1 ô đất.')}
function buildVilla(id){const b=VILLA_CONFIG.find(x=>x.id===id);if(!b||state.house.built[id])return;if(state.level<b.level)return guide('Chưa đủ cấp',`${b.name} mở xây từ Cấp ${b.level}.`,['Tích lũy EXP từ thu hoạch và đơn hàng.']);const cost={gold:b.gold,diamond:b.diamond,materials:b.materials};if(!hasCosts(cost))return guide('Chưa đủ nguyên liệu',`Bạn chưa đủ tài nguyên để xây ${b.name}.`,['Kiểm tra Vàng, Kim Cương và vật liệu.','Mỗi hạng mục là mục tiêu dài hạn; không cần xây ngay.']);if(!confirm(`Xây “${b.name}”?`))return;spendCosts(cost);state.house.built[id]=true;addExp(15+b.level);save();checkAchievements();renderAll();toast(`🏡 Đã xây ${b.name}.`)}
const ACH=[
{id:'h100',name:'Mùa vụ đầu tiên',desc:'Thu hoạch 100 nông sản',test:s=>s.stats.harvested>=100,reward:{exp:80,material:['wood',3]}},
{id:'o20',name:'Người giao hàng',desc:'Hoàn thành 20 đơn',test:s=>s.stats.orders>=20,reward:{exp:120,diamond:1}},
{id:'d1',name:'Kim Cương đầu tiên',desc:'Tự đổi được Kim Cương',test:s=>s.stats.diamondsMade>=1,reward:{exp:70,material:['glass',2]}},
{id:'l10',name:'Nông dân Cấp 10',desc:'Đạt Cấp 10',test:s=>s.level>=10,reward:{diamond:1}},
{id:'v10',name:'Nhà Vườn 25%',desc:'Xây 10 hạng mục',test:s=>Object.keys(s.house.built).length>=10,reward:{diamond:1}},
{id:'v20',name:'Nhà Vườn 50%',desc:'Xây 20 hạng mục',test:s=>Object.keys(s.house.built).length>=20,reward:{diamond:1}},
{id:'v30',name:'Nhà Vườn 75%',desc:'Xây 30 hạng mục',test:s=>Object.keys(s.house.built).length>=30,reward:{diamond:2}},
{id:'v40',name:'Nhà Vườn hoàn chỉnh',desc:'Xây đủ 40 hạng mục',test:s=>Object.keys(s.house.built).length>=40,reward:{diamond:3}}
];
function checkAchievements(){for(const a of ACH){if(state.achievements[a.id]||!a.test(state))continue;state.achievements[a.id]=true;if(a.reward.exp)state.exp+=a.reward.exp;if(a.reward.diamond)state.diamonds+=a.reward.diamond;if(a.reward.material)addMaterial(a.reward.material[0],a.reward.material[1]);toast(`🏆 Thành tựu: ${a.name}`)}save()}
function renderAll(){weatherSync();syncPlotHealth();ensureOrders();renderStatus();renderFarm();renderWarehouse();renderOrders();renderMarket();renderVilla();renderUpgrade();renderAchievements();renderHelp();renderTutorial()}
function renderStatus(){const w=getWeather();$('#goldStat').textContent=fmt(state.gold);$('#diamondStat').textContent=fmt(state.diamonds);$('#levelStat').textContent=state.level;$('#expStat').textContent=`${fmt(state.exp)}/${fmt(expNeed(state.level))}`;$('#warehouseStat').textContent=`${warehouseUsed()}/${state.warehouse.capacity}`;$('#weatherStat').textContent=`${w.icon} ${w.name}`}
function renderSeedButtons(){const host=$('#seedList');host.innerHTML=CROP_CONFIG.map(c=>`<button class="seed-btn ${selectedCrop===c.id?'active':''} ${c.level>state.level?'locked':''}" data-crop="${c.id}" ${c.level>state.level?'disabled':''}><span class="seed-icon">${cropSymbol(c)}</span><span><b>${c.name}</b><small>Cấp ${c.level} · ${fmt(c.seedCost)}G · ${formatDuration(c.growMin*60000)}</small></span></button>`).join('');host.querySelectorAll('[data-crop]').forEach(b=>b.onclick=()=>{selectedCrop=b.dataset.crop;selectedAction='plant';setActiveAction();renderSeedButtons()})}
function setActiveAction(){$$('.action-btn').forEach(b=>b.classList.toggle('active',b.dataset.action===selectedAction));const names={harvest:'Thu hoạch',water:'Tưới',cure:'Chăm bệnh',clear:'Dọn cây chết',plant:`Gieo ${cropById[selectedCrop]?.name||''}`};$('#selectedActionText').textContent=`Đang chọn: ${names[selectedAction]}`}
function renderFarm(){renderSeedButtons();setActiveAction();const host=$('#plotGrid');host.innerHTML='';for(let i=0;i<MAX_PLOTS;i++){const p=state.plots[i],locked=i>=state.unlockedPlotCount,el=document.createElement('button');el.className=`plot ${locked?'locked':''}`;el.dataset.i=i;el.innerHTML=`<canvas width="160" height="160"></canvas>${locked?'<span class="plot-badge">🔒</span>':''}<div class="plot-meta"><span></span><span></span></div>`;el.onclick=()=>handlePlot(i);host.appendChild(el);drawPlot(el.querySelector('canvas'),p,locked);const meta=el.querySelectorAll('.plot-meta span');if(locked){meta[0].textContent='Chưa mở';meta[1].textContent=''}else if(!p.cropId){meta[0].textContent='Đất trống';meta[1].textContent=''}else{const c=cropById[p.cropId],st=careStatus(p),prog=growthProgress(p);meta[0].textContent=c.name;meta[1].textContent=p.deadAt?'Đã chết':prog>=1?'Thu hoạch':`${Math.round(prog*100)}%`;const badge=el.querySelector('.plot-badge')||document.createElement('span');badge.className='plot-badge';badge.textContent=p.deadAt?'☠️':st.disease?'⚠️':st.id==='dry'||st.id==='slightly'?'💧':prog>=1?'✨':'';if(badge.textContent&&!badge.parentNode)el.appendChild(badge)}}}
function cropSymbol(c){return c.shape==='root'?'🌱':c.shape==='corn'?'🌽':c.shape==='berry'?'🍓':c.shape==='melon'?'🍈':c.shape==='vine'?'🍇':c.shape==='tree'?'🌳':c.shape==='cactus'?'🌵':'🌿'}
function drawPlot(canvas,p,locked){const x=canvas.getContext('2d'),W=canvas.width,H=canvas.height;x.clearRect(0,0,W,H);if(locked){x.fillStyle='#dfe7e1';x.fillRect(0,0,W,H);x.fillStyle='#b9c8bf';for(let i=0;i<5;i++){x.fillRect(10+i*31,20,18,110)}return}const wet=p.cropId?clamp(1-(now()-(p.wateredAt||p.plantedAt))/(40*hour),0,1):.5;const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,wet>.4?'#7b5b3c':'#9d754d');g.addColorStop(1,'#5b422e');x.fillStyle=g;x.fillRect(0,0,W,H);x.strokeStyle='rgba(255,255,255,.08)';for(let i=15;i<W;i+=28){x.beginPath();x.moveTo(i,0);x.lineTo(i-10,H);x.stroke()}if(!p.cropId)return;const c=cropById[p.cropId],prog=growthProgress(p),st=careStatus(p),stage=p.deadAt?4:prog<.18?0:prog<.50?1:prog<.90?2:3;drawCrop(x,c,stage,st,p.deadAt);if(prog<1&&!p.deadAt){x.fillStyle='rgba(255,255,255,.88)';x.fillRect(12,H-17,W-24,6);x.fillStyle='#59bd8c';x.fillRect(12,H-17,(W-24)*prog,6)}}
function drawCrop(ctx,c,stage,st,dead){ctx.save();ctx.translate(80,83);if(dead){ctx.globalAlpha=.55;ctx.filter='grayscale(1)'}const scale=[.35,.58,.78,1,1][stage];ctx.scale(scale,scale);ctx.lineCap='round';ctx.strokeStyle=dead?'#6d604d':c.colors[0];ctx.fillStyle=dead?'#7e715d':c.colors[0];ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(0,45);ctx.lineTo(0,-15);ctx.stroke();for(const side of [-1,1]){ctx.beginPath();ctx.ellipse(side*17,-6,19,9,side*.5,0,Math.PI*2);ctx.fill()}ctx.fillStyle=dead?'#756658':c.colors[1];if(stage>=2){if(['root','berry','corn','melon','pine','vine','tree','cactus'].includes(c.shape)){const count=c.shape==='berry'||c.shape==='vine'?5:c.shape==='tree'?4:2;for(let i=0;i<count;i++){const a=(i/count)*Math.PI*2-Math.PI/2,rx=c.shape==='tree'?28:22,ry=c.shape==='tree'?18:20;ctx.beginPath();ctx.ellipse(Math.cos(a)*rx,Math.sin(a)*ry+2,c.shape==='root'?10:9,c.shape==='root'?14:9,0,0,Math.PI*2);ctx.fill()}}else{for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse((i-1.5)*10,-12+Math.abs(i-1.5)*4,17,11,i*.4,0,Math.PI*2);ctx.fill()}}}if(st.disease&&!dead){ctx.fillStyle='#f4c04f';for(let i=0;i<4;i++){ctx.beginPath();ctx.arc(-22+i*14,-8+(i%2)*11,3.2,0,Math.PI*2);ctx.fill()}}ctx.restore()}
function renderWarehouse(){const used=warehouseUsed();$('#warehouseUsage').textContent=`Đã dùng ${used}/${state.warehouse.capacity} · Còn ${warehouseFree()} chỗ`;$('#warehouseCrops').innerHTML=CROP_CONFIG.filter(c=>cropQty(c.id)>0).map(c=>{const q=state.warehouse.crops[c.id];return `<div class="list-row"><div><b>${c.name}</b><div class="muted">Thường ${q.normal} · Tươi ${q.fresh} · Hảo hạng ${q.premium}</div></div><b>${cropQty(c.id)}</b></div>`}).join('')||'<p class="muted">Kho chưa có nông sản.</p>';$('#materialsList').innerHTML=Object.entries(MATERIAL_CONFIG).map(([id,m])=>`<div class="material">${m.icon} <b>${m.name}</b><div>${fmt(state.warehouse.materials[id])}</div></div>`).join('')}
function renderOrders(){ensureOrders();$('#ordersList').innerHTML=state.orders.map((o,i)=>{if(!o){const left=Math.max(0,state.orderCooldown[i]-now());return `<div class="order-card"><h3>Đang chờ đơn mới</h3><p class="muted">Đơn mới sau ${formatDuration(left)}</p></div>`}return `<div class="order-card"><h3>${o.customer}</h3><div class="muted">${o.title}</div>${Object.entries(o.req).map(([id,q])=>`<div class="req-line"><span>${cropById[id].name}</span><b>${cropQty(id)}/${q}</b></div>`).join('')}<div class="reward">💰 ${fmt(o.gold)} · EXP ${fmt(o.exp)} · ${MATERIAL_CONFIG[o.material.id].icon} ${o.material.qty} ${MATERIAL_CONFIG[o.material.id].name}</div><div class="row-actions"><button class="mini-btn" data-discard="${i}">Bỏ đơn</button><button class="primary-btn" data-complete="${i}">Giao đơn</button></div></div>`}).join('');$$('[data-complete]').forEach(b=>b.onclick=()=>completeOrder(+b.dataset.complete));$$('[data-discard]').forEach(b=>b.onclick=()=>discardOrder(+b.dataset.discard))}
function renderMarket(){$('#marketList').innerHTML=CROP_CONFIG.filter(c=>cropQty(c.id)>0).map(c=>{const m=marketInfo(c);return `<div class="list-row"><div><b>${c.name}</b><div class="muted">Có ${cropQty(c.id)} · ${m.trend} · ${fmt(m.price)}G/đv</div></div><div class="row-actions"><button class="mini-btn" data-sell="${c.id}:1">Bán 1</button><button class="mini-btn" data-sell="${c.id}:10">Bán 10</button><button class="mini-btn" data-sell="${c.id}:all">Bán hết</button></div></div>`}).join('')||'<p class="muted">Chưa có nông sản để bán.</p>';$$('[data-sell]').forEach(b=>b.onclick=()=>{const [id,n]=b.dataset.sell.split(':');sellCrop(id,n==='all'?'all':+n)});$('#materialExchange').innerHTML=Object.entries(MATERIAL_CONFIG).map(([id,m])=>{const x=materialExchangeCost(id);return `<div class="list-row"><div>${m.icon} <b>${m.name}</b><div class="muted">${x.qty} ${cropById[x.crop].name} → 2 ${m.name}</div></div><button class="mini-btn" data-mex="${id}">Đổi</button></div>`}).join('');$$('[data-mex]').forEach(b=>b.onclick=()=>exchangeMaterial(b.dataset.mex))}
function renderVilla(){const built=Object.keys(state.house.built).length;$('#villaProgress').textContent=`${built}/40 hạng mục · ${Math.round(built/40*100)}%`;$('#villaList').innerHTML=VILLA_CONFIG.map(b=>`<div class="build-row ${state.house.built[b.id]?'built':''}"><b>${state.house.built[b.id]?'✓ ':''}${b.name}</b><div class="muted">${b.category} · Cấp ${b.level}</div><div class="cost">${fmt(b.gold)}G · ${b.diamond}💎 · ${Object.entries(b.materials).map(([k,v])=>`${MATERIAL_CONFIG[k].name} ${v}`).join(' · ')}</div>${state.house.built[b.id]?'':`<button class="mini-btn" data-build="${b.id}">Xây</button>`}</div>`).join('');$$('[data-build]').forEach(b=>b.onclick=()=>buildVilla(b.dataset.build));$('#roofStyle').value=state.house.styles.roof;$('#fenceStyle').value=state.house.styles.fence;$('#pathStyle').value=state.house.styles.path;drawVilla()}
function drawVilla(){const c=$('#villaCanvas'),x=c.getContext('2d'),built=state.house.built,s=state.house.styles;x.clearRect(0,0,c.width,c.height);const sky=x.createLinearGradient(0,0,0,520);sky.addColorStop(0,'#cfeee8');sky.addColorStop(.55,'#eaf6d5');sky.addColorStop(1,'#92c67d');x.fillStyle=sky;x.fillRect(0,0,900,520);x.fillStyle=s.path==='brick'?'#bd805d':s.path==='gravel'?'#d6c7aa':'#b9b5a8';x.beginPath();x.moveTo(380,520);x.lineTo(420,315);x.lineTo(560,315);x.lineTo(650,520);x.fill();if(built.villa_1||built.villa_2||built.villa_3){x.fillStyle='#f4e7cf';x.fillRect(330,190,280,170);x.fillStyle='#d9b691';x.fillRect(350,205,240,145)}if(built.villa_4){x.fillStyle=s.roof==='blue'?'#547b9c':s.roof==='wood'?'#8a603d':'#b74d43';x.beginPath();x.moveTo(300,200);x.lineTo(470,90);x.lineTo(640,200);x.closePath();x.fill()}if(built.villa_5){x.fillStyle='#765438';x.fillRect(450,275,55,85)}if(built.villa_6){x.fillStyle='#aee3ed';for(const px of [380,535]){x.fillRect(px,235,45,40);x.strokeStyle='#fff';x.strokeRect(px,235,45,40)}}if(built.villa_11||built.villa_12){x.strokeStyle=s.fence==='white'?'#f8f5eb':s.fence==='stone'?'#a3a59c':'#8c633d';x.lineWidth=12;x.beginPath();x.moveTo(70,410);x.lineTo(290,410);x.moveTo(660,410);x.lineTo(840,410);x.stroke()}if(built.villa_18||built.villa_33){x.fillStyle='#6bb6c3';x.beginPath();x.ellipse(150,365,95,46,0,0,Math.PI*2);x.fill()}if(built.villa_31){x.strokeStyle='#826348';x.lineWidth=12;x.beginPath();x.moveTo(760,330);x.lineTo(760,190);x.stroke();x.fillStyle='#f2eee2';for(let i=0;i<4;i++){x.save();x.translate(760,190);x.rotate(i*Math.PI/2);x.fillRect(0,-8,72,16);x.restore()}}const trees=[15,20,34,39,40];trees.forEach((n,i)=>{if(built[`villa_${n}`]){x.fillStyle='#6d563d';x.fillRect(90+i*145,270+(i%2)*35,12,70);x.fillStyle=['#4e9a55','#65aa5d','#4c8f4d'][i%3];x.beginPath();x.arc(96+i*145,255+(i%2)*35,38,0,Math.PI*2);x.fill()}});x.fillStyle='rgba(31,89,59,.55)';x.font='700 26px system-ui';x.fillText(`Nhà Vườn ${Math.round(Object.keys(built).length/40*100)}%`,24,42)}
function renderUpgrade(){const cur=SPEED_UPGRADES[state.speedLevel],next=SPEED_UPGRADES[state.speedLevel+1];$('#speedUpgrade').innerHTML=`<div class="upgrade-box"><b>⚡ Tốc độ cây: ${Math.round(cur.mult*100)}%</b><p class="muted">Nâng cấp vĩnh viễn, chỉ dùng Kim Cương.</p>${next?`<button id="speedBtn" class="primary-btn">Lên ${Math.round(next.mult*100)}% · ${next.cost} 💎</button>`:'<b>Đã tối đa</b>'}</div>`;if($('#speedBtn'))$('#speedBtn').onclick=upgradeSpeed;const step=state.unlockedPlotCount-INITIAL_PLOTS,cost=180+step*85,wood=Math.floor(step/3);$('#landUpgrade').innerHTML=`<b>🚩 Diện tích: ${state.unlockedPlotCount}/${MAX_PLOTS} ô</b><p class="muted">Mở đất dùng Vàng${wood?' + Gỗ':''}, không dùng Kim Cương.</p><button id="landBtn" class="primary-btn" ${state.unlockedPlotCount>=MAX_PLOTS?'disabled':''}>Mở 1 ô · ${fmt(cost)}G${wood?` · ${wood} Gỗ`:''}</button>`;$('#landBtn').onclick=expandLand;$('#diamondRecipes').innerHTML=DIAMOND_RECIPE_CONFIG.map(r=>`<div class="recipe"><b>${r.name}</b><div class="muted">Mở từ Cấp ${r.level} · Nhận ${r.diamond} 💎</div><div class="cost">${Object.entries(r.crops).map(([id,q])=>`${cropById[id].name} ${q}`).join(' · ')} · ${Object.entries(r.materials).map(([id,q])=>`${MATERIAL_CONFIG[id].name} ${q}`).join(' · ')}</div><button class="mini-btn" data-craft="${r.id}" ${state.level<r.level?'disabled':''}>Đổi</button></div>`).join('');$$('[data-craft]').forEach(b=>b.onclick=()=>craftDiamond(b.dataset.craft))}
function renderAchievements(){$('#achievementsList').innerHTML=ACH.map(a=>`<div class="achievement ${state.achievements[a.id]?'done':''}"><b>${state.achievements[a.id]?'🏆':'○'} ${a.name}</b><div>${a.desc}</div></div>`).join('')}
function renderHelp(){$('#helpList').innerHTML=Object.entries(HELP_CONFIG).map(([k,arr])=>`<details><summary>${({start:'Bắt đầu chơi',crop:'Trồng cây',water:'Tưới nước',disease:'Bệnh cây',warehouse:'Kho',orders:'Đơn hàng',diamond:'Kim Cương',villa:'Nhà Vườn',speed:'Nâng cấp tốc độ',material:'Vật liệu',weather:'Thời tiết',dead:'Vì sao cây chết?'})[k]}</summary><ul>${arr.map(v=>`<li>${v}</li>`).join('')}</ul></details>`).join('')}
function renderTutorial(){const b=$('#tutorialBanner'),step=state.tutorial.step||0;if(step>=5){b.hidden=true;return}const t=[['Bước 1/5','Chọn Cà rốt trong danh sách hạt giống.'],['Bước 2/5','Chạm vào ô đất trống để gieo hạt.'],['Bước 3/5','Cây vẫn lớn khi bạn đóng Farm; không cần ngồi chờ.'],['Bước 4/5','Khi cây chín, thu hoạch để đưa nông sản vào Kho.'],['Bước 5/5','Mở Chợ hoặc Đơn hàng để biến nông sản thành Vàng, EXP và vật liệu.']][step];b.hidden=false;b.innerHTML=`<div><b>${t[0]}</b><div>${t[1]}</div></div><button id="tutorialNext" class="mini-btn">Tiếp</button>`;$('#tutorialNext').onclick=()=>{state.tutorial.step++;save();renderTutorial()}}
function offlineSummary(previous){if(!previous)return;const elapsed=now()-previous;if(elapsed<30*60000)return;syncPlotHealth();ensureOrders();let ready=0,dry=0,disease=0,dead=0;for(const p of state.plots){if(!p.cropId)continue;if(p.deadAt)dead++;else{const s=careStatus(p);if(growthProgress(p)>=1)ready++;if(s.id==='dry'||s.id==='slightly')dry++;if(s.disease)disease++}}const lines=[];if(ready)lines.push(`${ready} cây đã trưởng thành.`);if(dry)lines.push(`${dry} cây đang thiếu nước.`);if(disease)lines.push(`${disease} cây có dấu hiệu bệnh.`);if(dead)lines.push(`${dead} cây đã chết.`);if(lines.length)showInfo('Trong thời gian bạn vắng mặt',`<ul class="offline-list">${lines.map(x=>`<li>${x}</li>`).join('')}</ul>${dead?'<p>Bạn có thể chạm cây chết để xem nguyên nhân, sau đó chọn “Dọn cây chết”.</p>':''}`)}
function guide(title,message,suggestions=[]){showInfo(title,`<p>${message}</p>${suggestions.length?`<b>Bạn có thể:</b><ul>${suggestions.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}`)}
function showInfo(title,body){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;$('#infoDialog').showModal()}
function toast(msg,type=''){const t=$('#toast');t.textContent=msg;t.className=`toast ${type}`;t.hidden=false;clearTimeout(t._tm);t._tm=setTimeout(()=>t.hidden=true,2600)}
function switchTab(id){$$('.farm-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${id}`));if(id==='villa')drawVilla()}
function bind(){$('#backBtn').onclick=()=>parent.postMessage({type:'farm-game-close'},'*');$('#soundBtn').onclick=()=>{soundOn=!soundOn;$('#soundBtn').textContent=soundOn?'♫':'♪'};$('#helpQuickBtn').onclick=()=>switchTab('help');$('#farmNav').onclick=e=>{const b=e.target.closest('[data-tab]');if(b)switchTab(b.dataset.tab)};$$('.action-btn').forEach(b=>b.onclick=()=>{selectedAction=b.dataset.action;setActiveAction();renderSeedButtons()});$('#waterAllBtn').onclick=waterAll;$('#expandWarehouseBtn').onclick=expandWarehouse;$('#dialogClose').onclick=$('#dialogOk').onclick=()=>$('#infoDialog').close();['roof','fence','path'].forEach(k=>$(`#${k}Style`).onchange=e=>{state.house.styles[k]=e.target.value;save();drawVilla()})}
function init(){const previous=(()=>{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')?.lastSeen||0}catch{return 0}})();load();bind();weatherSync();syncPlotHealth();ensureOrders();renderAll();offlineSummary(previous);save();tickTimer=setInterval(()=>{syncPlotHealth();ensureOrders();renderStatus();renderFarm();renderOrders()},15000);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();else renderAll()});window.addEventListener('beforeunload',save)}
init();
