(() => {
  'use strict';
  const D=GAME_DATA, SAVE_PREFIX='dai_luc_nghe_nghiep_demo_slot_', ACTIVE_SLOT_KEY='dai_luc_nghe_nghiep_active_slot', LEGACY_SAVE_KEY='dai_luc_nghe_nghiep_demo_v1', SPEED_KEY='dai_luc_nghe_nghiep_speed_x3_enabled';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const now=()=>Date.now(), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rand=(a,b)=>Math.random()*(b-a)+a, randint=(a,b)=>Math.floor(rand(a,b+1));
  let activeSlot=clamp(parseInt(localStorage.getItem(ACTIVE_SLOT_KEY)||'1',10)||1,1,3), speedX3=localStorage.getItem(SPEED_KEY)==='1';
  const gameSpeed=()=>speedX3?3:1, scaledWait=ms=>Math.max(250,Math.round(ms/gameSpeed()));
  const saveKey=(slot=activeSlot)=>SAVE_PREFIX+slot, welcomeKey=(slot=activeSlot)=>SAVE_PREFIX+slot+'_welcomed';
  if(!localStorage.getItem(saveKey(1))&&localStorage.getItem(LEGACY_SAVE_KEY)){localStorage.setItem(saveKey(1),localStorage.getItem(LEGACY_SAVE_KEY));localStorage.removeItem(LEGACY_SAVE_KEY);localStorage.setItem(ACTIVE_SLOT_KEY,'1');activeSlot=1;}
  const fmt=n=>Math.floor(Number(n)||0).toLocaleString('vi-VN');
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const durationText=ms=>{let s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;return h?`${h}g ${m}p ${s}s`:m?`${m}p ${s}s`:`${s}s`;};
  const xpNeed=l=>Math.round(34*Math.pow(1.42,l-1));
  const item=id=>D.items[id], skill=id=>D.skills[id], allActions=()=>Object.values(D.actions).flat(), actionById=id=>allActions().find(a=>a.id===id);
  const actionSkill=id=>Object.entries(D.actions).find(([,arr])=>arr.some(a=>a.id===id))?.[0];

  function initialState(){
    const skills={};Object.keys(D.skills).forEach(id=>skills[id]={level:1,xp:0,unlocked:!!D.skills[id].startUnlocked});
    const prices={};Object.values(D.items).forEach(it=>prices[it.id]={price:it.basePrice,prev:it.basePrice,updatedAt:now()});
    return {version:D.version,createdAt:now(),lastSeen:now(),coins:0,inventory:{},skills,mastery:{},currentAction:null,activeView:'gathering',logTab:'all',logs:[],mails:[],prices,
      flags:{marketUnlocked:false,quickSold:0,marketSold:0,mailIntro:false},tutorialStep:0,zones:{starter:true},zoneEligibleNotified:{},selectedAction:'g_pebble',marketTickAt:now(),transactionCount:0,
      stats:{produced:{},sold:{},bought:{}},sideQuests:[],questNextAt:0,questSerial:0,inventoryTab:'bag',equipment:{weapon:null}};
  }
  function loadState(){
    try{
      const raw=localStorage.getItem(saveKey()); if(!raw)return initialState();
      const old=JSON.parse(raw),base=initialState();
      const s={...base,...old,flags:{...base.flags,...(old.flags||{})},skills:{...base.skills,...(old.skills||{})},prices:{...base.prices,...(old.prices||{})},stats:{...base.stats,...(old.stats||{})},zoneEligibleNotified:{...(old.zoneEligibleNotified||{})},equipment:{...base.equipment,...(old.equipment||{})}};
      Object.keys(D.skills).forEach(id=>s.skills[id]={...base.skills[id],...(s.skills[id]||{})});
      Object.values(D.items).forEach(it=>{if(!s.prices[it.id])s.prices[it.id]={price:it.basePrice,prev:it.basePrice,updatedAt:now()};});
      if((old.version||1)<2){
        s.version=2;s.zones={starter:true};s.zoneEligibleNotified={};s.sideQuests=[];s.questNextAt=0;s.questSerial=0;s.stats={produced:{},sold:{},bought:{}};
        const legacy={blade:{to:'steel',mul:2},handle:{to:'hardwood',mul:2},iron_sword_1:{to:'iron_sword',mul:1}};
        Object.entries({...s.inventory}).forEach(([id,q])=>{if(D.items[id])return;const m=legacy[id];delete s.inventory[id];if(m)s.inventory[m.to]=(s.inventory[m.to]||0)+q*m.mul;});
      }
      if((old.version||1)<3){s.version=3;s.inventoryTab='bag';s.equipment={weapon:null};Object.values(D.items).forEach(it=>s.prices[it.id]={price:it.basePrice,prev:it.basePrice,updatedAt:now()});if((s.inventory?.iron_sword||0)>0&&s.skills.combat?.unlocked)s.equipment.weapon='iron_sword';}
      Object.keys(s.inventory||{}).forEach(id=>{if(!D.items[id])delete s.inventory[id];});
      if(s.equipment?.weapon&&(!(s.inventory?.[s.equipment.weapon]>0)||!D.items[s.equipment.weapon]?.combat))s.equipment.weapon=null;
      if(s.currentAction&&!actionById(s.currentAction.actionId))s.currentAction=null;
      if(!D.skills[s.activeView] && !['market','map','mail'].includes(s.activeView))s.activeView='gathering';
      return s;
    }catch(e){console.warn(e);return initialState();}
  }
  let state=loadState(),lastRender=0,offlineReport=null;
  function save(){state.version=D.version;state.lastSeen=now();pruneMails();try{localStorage.setItem(saveKey(),JSON.stringify(state));}catch(e){}}
  function log(text,type='all'){state.logs.unshift({at:now(),text,type});if(state.logs.length>180)state.logs.length=180;}
  function sendMail(title,body,type='system'){const t=now();state.mails.unshift({id:'m_'+t+'_'+Math.random().toString(36).slice(2,7),title,body,type,createdAt:t,expiresAt:t+D.mailLifetimeMs,read:false});toast('Có thư mới',title,'good');}
  function pruneMails(){const t=now();state.mails=(state.mails||[]).filter(m=>m.expiresAt>t);}
  function unreadCount(){pruneMails();return state.mails.filter(m=>!m.read).length;}
  function totalLevel(){return Object.values(state.skills).filter(s=>s.unlocked).reduce((n,s)=>n+s.level,0);}
  function invQty(id){return state.inventory[id]||0;}
  function addItem(id,q){if(q<=0)return;state.inventory[id]=(state.inventory[id]||0)+q;}
  function removeItem(id,q){if(invQty(id)<q)return false;state.inventory[id]-=q;if(state.inventory[id]<=0)delete state.inventory[id];return true;}
  function addCoins(n,visual=true){state.coins=Math.max(0,state.coins+n);if(visual&&n)moneyFloat(n);}
  function incStat(group,id,q){state.stats[group]=state.stats[group]||{};state.stats[group][id]=(state.stats[group][id]||0)+q;}
  function addXP(skillId,amount){const s=state.skills[skillId];if(!s?.unlocked)return;s.xp+=amount;while(s.xp>=xpNeed(s.level)){s.xp-=xpNeed(s.level);s.level++;log(`${skill(skillId).name} đạt cấp ${s.level}.`,'unlock');sendMail(`${skill(skillId).name} đạt Lv${s.level}`,`Cấp nghề mới đã đạt. Hãy kiểm tra những vật liệu, công thức hoặc khu vực vừa đủ điều kiện.`,'progress');checkUnlockNotices();checkZoneEligibility();checkMarketUnlock();}}

  function reqStatus(req){
    if(!req)return{ok:true,lines:[]};const lines=[];
    if(req.skill){const ss=state.skills[req.skill],cur=ss?.unlocked?ss.level:0;lines.push({type:'skill',skillId:req.skill,label:`${skill(req.skill).name} Lv${req.level}`,cur,need:req.level,ok:!!ss?.unlocked&&cur>=req.level});}
    if(req.skills)Object.entries(req.skills).forEach(([sid,lvl])=>{const ss=state.skills[sid],cur=ss?.unlocked?ss.level:0;lines.push({type:'skill',skillId:sid,label:`${skill(sid).name} Lv${lvl}`,cur,need:lvl,ok:!!ss?.unlocked&&cur>=lvl});});
    if(req.totalLevel){const cur=totalLevel();lines.push({type:'total',label:`Tổng cấp ${req.totalLevel}`,cur,need:req.totalLevel,ok:cur>=req.totalLevel});}
    if(req.coins){lines.push({type:'coins',label:`${fmt(req.coins)} xu`,cur:state.coins,need:req.coins,ok:state.coins>=req.coins});}
    if(req.item){const cur=invQty(req.item);lines.push({type:'item',itemId:req.item,label:`${req.qty} ${item(req.item).name}`,cur,need:req.qty,ok:cur>=req.qty});}
    return{ok:lines.every(x=>x.ok),lines};
  }
  function missingText(line){const d=Math.max(0,line.need-line.cur);if(line.type==='coins')return `Bạn còn thiếu ${fmt(d)} xu`;if(line.type==='item')return `Bạn còn thiếu ${fmt(d)} ${item(line.itemId).name}`;if(line.type==='skill')return `Bạn còn thiếu ${fmt(d)} cấp ${skill(line.skillId).name}`;if(line.type==='total')return `Bạn còn thiếu ${fmt(d)} tổng cấp`;return 'Bạn chưa đủ điều kiện';}
  function showMissing(rs,anchor){const miss=rs.lines.filter(x=>!x.ok);if(!miss.length)return;popupFloat(missingText(miss[0]),anchor,'missing');toast('Chưa đủ điều kiện',miss.map(missingText).join(' · '),'warn');}
  function canUnlockSkill(id){return reqStatus(skill(id).unlock);}
  function payUnlock(req){if(req.coins)addCoins(-req.coins);if(req.item&&req.consumeItem!==false)removeItem(req.item,req.qty);}
  function unlockSkill(id,anchor){const s=skill(id),st=state.skills[id];if(st.unlocked)return;const rs=canUnlockSkill(id);if(!rs.ok){showMissing(rs,anchor);return;}payUnlock(s.unlock);st.unlocked=true;state.activeView=id;if(id==='combat')ensureWeaponEquipped();state.flags['unlockNotice_'+id]=true;log(`Đã mở khóa nghề ${s.name}.`,'unlock');sendMail(`Đã mở khóa ${s.name}`,`Nghề ${s.name} đã sẵn sàng. 12 nội dung của nghề sẽ mở dần theo cấp.`,'unlock');checkTutorial();ensureSideQuests();render(true);save();}
  function checkUnlockNotices(){Object.values(D.skills).forEach(s=>{if(state.skills[s.id].unlocked||state.flags['unlockNotice_'+s.id])return;if(canUnlockSkill(s.id).ok){state.flags['unlockNotice_'+s.id]=true;sendMail(`Có thể mở khóa ${s.name}`,`Đã đủ điều kiện: ${s.unlockText}. Chọn nghề ở menu trái để tự mở khóa.`,'unlock');log(`${s.name} đã đủ điều kiện mở khóa.`,'unlock');}});}
  function checkMarketUnlock(){if(state.flags.marketUnlocked)return;if(totalLevel()>=5){state.flags.marketUnlocked=true;sendMail('Chợ Trời đã mở','Các thương nhân bắt đầu mua bán ở Chợ Trời. Giá thay đổi theo cung cầu mô phỏng và tiếp tục cập nhật khi quay lại game.','unlock');log('Chợ Trời đã mở.','unlock');}}
  function checkZoneEligibility(){D.zones.forEach(z=>{if(z.startUnlocked||state.zones[z.id]||state.zoneEligibleNotified[z.id])return;const rs=reqStatus(z.unlock);if(rs.ok){state.zoneEligibleNotified[z.id]=true;sendMail(`Có thể khám phá: ${z.name}`,`Đã đủ điều kiện để khám phá ${z.name}. Vào Bản đồ và bấm “Khám phá”.`,'unlock');log(`${z.name} đã đủ điều kiện khám phá.`,'unlock');}});}
  function exploreZone(id,anchor){const z=D.zones.find(x=>x.id===id);if(!z||state.zones[id])return;const rs=reqStatus(z.unlock);if(!rs.ok){showMissing(rs,anchor);return;}state.zones[id]=true;log(`Đã khám phá ${z.name}.`,'unlock');sendMail(`Đã khám phá ${z.name}`,`${z.name} đã chính thức được mở trên bản đồ.`,'unlock');render(true);save();}

  function bestToolBonus(skillId){let specific=0,global=0;Object.entries(state.inventory).forEach(([id,q])=>{if(q<=0)return;const t=item(id)?.tool;if(!t)return;if(t.skill==='all')global=Math.max(global,t.speed||0);if(t.skill===skillId)specific=Math.max(specific,t.speed||0);});return clamp(specific+global,0,.45);}
  function weaponItems(){return Object.values(D.items).filter(it=>it.combat?.slot==='weapon').sort((a,b)=>(a.combat.requiredLevel||1)-(b.combat.requiredLevel||1));}
  function canEquipWeapon(id){const it=item(id);return !!it?.combat&&it.combat.slot==='weapon'&&invQty(id)>0&&!!state.skills.combat?.unlocked&&state.skills.combat.level>=(it.combat.requiredLevel||1);}
  function ensureWeaponEquipped(){if(state.equipment?.weapon&&canEquipWeapon(state.equipment.weapon))return state.equipment.weapon;const best=weaponItems().filter(it=>canEquipWeapon(it.id)).sort((a,b)=>(b.combat.attack||0)-(a.combat.attack||0))[0];state.equipment=state.equipment||{weapon:null};state.equipment.weapon=best?.id||null;return state.equipment.weapon;}
  function combatStats(){const lv=state.skills.combat?.unlocked?state.skills.combat.level:0,wid=ensureWeaponEquipped(),w=wid?item(wid):null,c=w?.combat||{};return{level:lv,weapon:w,attack:Math.round(10+lv*2.6+(c.attack||0)),attackSpeed:c.attackSpeed||1,crit:c.crit||0,armorPen:c.armorPen||0};}
  function combatDps(a){const st=combatStats(),def=Math.max(0,a.enemy?.defense||0),effectiveDef=def*(1-st.armorPen),mit=100/(100+effectiveDef),critFactor=1+st.crit*.65;return Math.max(1,st.attack*st.attackSpeed*mit*critFactor);}
  function combatDuration(a){const dps=combatDps(a),hp=Math.max(1,a.enemy?.hp||100);return Math.max(1800,Math.round((hp/dps+1.2)*1000));}
  function equipmentEffectText(id){const it=item(id),c=it?.combat;if(!c)return '';return `Yêu cầu Chiến đấu Lv${c.requiredLevel||1} · Công +${c.attack||0} · Tốc đánh ${Number(c.attackSpeed||1).toFixed(2)}x · Crit ${Math.round((c.crit||0)*100)}% · Xuyên giáp ${Math.round((c.armorPen||0)*100)}%`;}
  function equipWeapon(id,anchor){const it=item(id);if(!it?.combat)return;if(invQty(id)<=0){toast('Chưa sở hữu',`Cần chế tạo ${it.name} trước.`,'warn');return;}if(!state.skills.combat?.unlocked){toast('Chưa mở Chiến đấu','Hãy mở nghề Chiến đấu trước khi trang bị vũ khí.','warn');return;}const need=it.combat.requiredLevel||1;if(state.skills.combat.level<need){toast('Chưa đủ cấp',`${it.name} yêu cầu Chiến đấu Lv${need}.`,'warn');return;}state.equipment.weapon=id;if(state.currentAction?.skillId==='combat')state.currentAction.duration=actionDuration('combat',actionById(state.currentAction.actionId));popupFloat(`Trang bị ${it.name}`,anchor,'reward');render(true);save();}
  function actionDuration(skillId,a){const base=skillId==='combat'?combatDuration(a):Math.max(900,Math.round(a.duration*(1-bestToolBonus(skillId))));return Math.max(300,Math.round(base/gameSpeed()));}
  function actionAvailable(skillId,a){return !!state.skills[skillId]?.unlocked&&state.skills[skillId].level>=a.level;}
  function canProcess(a){if(a.inputs)for(const[id,q]of Object.entries(a.inputs))if(invQty(id)<q)return false;if(a.coinCost&&state.coins<a.coinCost)return false;return true;}
  function consumeInputs(a,offline=false){if(a.inputs)Object.entries(a.inputs).forEach(([id,q])=>removeItem(id,q));if(a.coinCost)addCoins(-a.coinCost,!offline);}
  function inputText(inputs){if(!inputs)return 'Không cần nguyên liệu';return Object.entries(inputs).map(([id,q])=>`${q} ${item(id).name}`).join(' + ');}
  function outputText(outputs){return Object.entries(outputs||{}).map(([id,r])=>`${r[0]===r[1]?r[0]:r[0]+'–'+r[1]} ${item(id).name}`).join(' + ');}
  function toolEffectText(outputId){const it=item(outputId); if(!it?.tool) return ''; const t=it.tool; const pct=Math.round((t.speed||0)*100); const sampleSkills=t.skill==='all'?['gathering','mining','woodcutting','smelting']:[t.skill]; const samples=[]; sampleSkills.forEach(sid=>{ const first=(D.actions[sid]||[])[0]; if(!first) return; const base=Math.round(first.duration)/1000; const reduced=Math.round(first.duration*(1-(t.speed||0)))/1000; samples.push(`${first.name.replace(/^Nhặt /,'').replace(/^Thu thập /,'').replace(/^Khai /,'').replace(/^Đốn /,'').replace(/^Luyện /,'')}: ${base.toFixed(1)}s→${reduced.toFixed(1)}s`); }); const skillName=t.skill==='all'?'mọi nghề sản xuất':skill(t.skill).name; return `Hiệu ứng: giảm ${pct}% thời gian ${skillName}${samples.length?` · Ví dụ ${samples.slice(0, t.skill==='all'?2:1).join(' · ')}`:''}`; }
  function completeCycle(skillId,a,{offline=false}={}){
    if(!canProcess(a))return false;consumeInputs(a,offline);const gained={};
    for(const[id,r]of Object.entries(a.outputs||{})){let q=randint(r[0],r[1]);const m=state.mastery[a.masteryKey]||0;if(q>0&&Math.random()<Math.min(.18,m/4000))q++;if(q>0){addItem(id,q);incStat('produced',id,q);gained[id]=(gained[id]||0)+q;}}
    let cr=0;if(a.coinReward){cr=randint(a.coinReward[0],a.coinReward[1]);addCoins(cr,!offline);}addXP(skillId,a.xp);state.mastery[a.masteryKey]=(state.mastery[a.masteryKey]||0)+1;
    if(!offline)log(`${a.name}: ${Object.entries(gained).map(([id,q])=>`${q} ${item(id).name}`).join(', ')||'hoàn thành'}${cr?` · +${cr} xu`:''}.`,'activity');
    return{gained,coins:cr,xp:a.xp};
  }
  function startAction(skillId,actionId){const a=actionById(actionId);if(!a||!actionAvailable(skillId,a))return;if(skillId==='combat'&&!ensureWeaponEquipped()){toast('Chưa có vũ khí','Hãy vào tab Trang bị và trang bị một vũ khí phù hợp.','warn');return;}if(!canProcess(a)){toast('Thiếu nguyên liệu','Kiểm tra Túi đồ để biết nguyên liệu cần cho lượt sản xuất.','warn');return;}state.currentAction={skillId,actionId,startedAt:now(),duration:actionDuration(skillId,a)};state.selectedAction=actionId;log(`Bắt đầu: ${a.name}.`,'activity');checkTutorial();render(true);save();}
  function stopAction(reason='Đã dừng hành động.'){if(state.currentAction){log(reason,'activity');state.currentAction=null;render(true);save();}}
  function mergeGain(dst,src){Object.entries(src||{}).forEach(([id,q])=>dst[id]=(dst[id]||0)+q);}
  function processOnline(){const ca=state.currentAction;if(!ca)return;const a=actionById(ca.actionId);if(!a){state.currentAction=null;return;}const dur=ca.duration||actionDuration(ca.skillId,a);let cycles=Math.floor((now()-ca.startedAt)/dur);if(cycles<=0)return;cycles=Math.min(cycles,100);let changed=false,agg={};for(let i=0;i<cycles;i++){const res=completeCycle(ca.skillId,a);if(!res){stopAction('Hoạt động tự dừng vì thiếu nguyên liệu hoặc xu.');toast('Hoạt động đã dừng','Không đủ nguyên liệu cho lượt tiếp theo.','warn');return;}mergeGain(agg,res.gained);ca.startedAt+=dur;changed=true;}if(changed){resourceFloat(agg,a.id);checkUnlockNotices();checkZoneEligibility();checkMarketUnlock();checkSideQuests();checkTutorial();ensureSideQuests();render(true);save();}}
  function simulateOffline(){pruneMails();const t=now(),delta=Math.max(0,t-(state.lastSeen||t));if(delta<8000||!state.currentAction){state.lastSeen=t;return;}const ca=state.currentAction,a=actionById(ca.actionId);if(!a){state.currentAction=null;state.lastSeen=t;return;}const capped=Math.min(delta,D.offlineCapMs),dur=ca.duration||actionDuration(ca.skillId,a),partial=Math.max(0,(state.lastSeen||t)-ca.startedAt),total=Math.min(partial+capped,D.offlineCapMs+dur);let cycles=Math.floor(total/dur),done=0,coins=0,xp=0,gained={};cycles=Math.min(cycles,50000);for(let i=0;i<cycles;i++){if(!canProcess(a))break;const res=completeCycle(ca.skillId,a,{offline:true});if(!res)break;done++;coins+=res.coins;xp+=res.xp;mergeGain(gained,res.gained);}const rem=total-done*dur;ca.startedAt=t-Math.max(0,Math.min(rem,dur-1));if(done<cycles&&!canProcess(a))state.currentAction=null;state.lastSeen=t;updateMarketOffline(capped);if(done>0){offlineReport={duration:capped,cycles:done,action:a.name,gained,coins,xp};log(`Offline ${durationText(capped)}: hoàn thành ${done} lượt ${a.name}.`,'activity');}checkUnlockNotices();checkZoneEligibility();checkMarketUnlock();checkSideQuests();checkTutorial();ensureSideQuests();}

  function updateMarketOffline(ms){if(!state.flags.marketUnlocked)return;const steps=Math.min(48,Math.floor(ms/scaledWait(15*60*1000)));for(let i=0;i<steps;i++)marketTick(false);}
  function marketTick(doRender=true){if(!state.flags.marketUnlocked)return;Object.values(D.items).forEach(it=>{const p=state.prices[it.id]||{price:it.basePrice,prev:it.basePrice};p.prev=p.price;const bs=D.npcProfiles.map(n=>n.bias[it.id]||1),d=bs.reduce((a,b)=>a+b,0)/bs.length,anchor=it.basePrice*d,pull=(anchor-p.price)*.12,noise=rand(-.055,.055)*it.basePrice;p.price=Math.max(1,Math.round((p.price+pull+noise)*10)/10);p.updatedAt=now();state.prices[it.id]=p;});state.marketTickAt=now();if(doRender){const tradable=Object.values(D.items).filter(it=>isItemKnown(it.id));if(tradable.length){const it=tradable[randint(0,tradable.length-1)],interested=[...D.npcProfiles].sort((a,b)=>(b.bias[it.id]||1)-(a.bias[it.id]||1)),buyer=interested[0],seller=interested.at(-1),qty=randint(4,24),px=Math.round(state.prices[it.id].price);log(`${buyer.name} mua ${qty} ${it.name} quanh mức ${px} xu; ${seller.name} đang bán tích cực.`,'economy');}render(true);save();}}
  function marketQuote(id){const it=item(id),p=state.prices[id]?.price||it.basePrice,buyers=D.npcProfiles.map(n=>({n,score:n.bias[id]||1})).sort((a,b)=>b.score-a.score),sellers=[...buyers].sort((a,b)=>a.score-b.score),buy=Math.max(1,Math.round(p*(.91+Math.min(.10,(buyers[0].score-1)*.35)))),sell=Math.max(buy+1,Math.round(p*(1.08+Math.max(-.04,(sellers[0].score-1)*.20))));return{buy,sell,buyer:buyers[0].n,seller:sellers[0].n};}
  function marketSell(id,qty){qty=Math.max(1,Math.floor(qty));const have=invQty(id);if(!state.flags.marketUnlocked||have<=0)return;const reserve=state.equipment?.weapon===id?1:0,sellable=Math.max(0,have-reserve);if(sellable<=0){toast('Đang trang bị','Hãy đổi hoặc tháo vũ khí trước khi bán món cuối cùng.','warn');return;}qty=Math.min(qty,sellable);const q=marketQuote(id),total=q.buy*qty;removeItem(id,qty);addCoins(total);incStat('sold',id,qty);state.flags.marketSold+=qty;state.transactionCount++;state.prices[id].prev=state.prices[id].price;state.prices[id].price=Math.max(1,state.prices[id].price*(1-Math.min(.06,qty/1000)));log(`Bán ${qty} ${item(id).name} cho ${q.buyer.name}: +${fmt(total)} xu.`,'economy');checkTutorial();render(true);save();}
  function marketBuy(id,qty){qty=Math.max(1,Math.floor(qty));if(!state.flags.marketUnlocked)return;const q=marketQuote(id),total=q.sell*qty;if(state.coins<total){popupFloat(`Bạn còn thiếu ${fmt(total-state.coins)} xu`,$(`[data-mbuy="${id}"]`),'missing');return;}addCoins(-total);addItem(id,qty);incStat('bought',id,qty);state.transactionCount++;state.prices[id].prev=state.prices[id].price;state.prices[id].price*=1+Math.min(.07,qty/900);log(`Mua ${qty} ${item(id).name} từ ${q.seller.name}: -${fmt(total)} xu.`,'economy');render(true);save();}
  function quickSell(id,qty){const have=invQty(id);if(have<=0)return;qty=Math.max(1,Math.floor(qty));const reserve=state.equipment?.weapon===id?1:0,sellable=Math.max(0,have-reserve);if(sellable<=0){toast('Đang trang bị','Hãy đổi hoặc tháo vũ khí trước khi bán món cuối cùng.','warn');return;}qty=Math.min(qty,sellable);const unit=Math.max(1,Math.round((state.prices[id]?.price||item(id).basePrice)*.9)),total=unit*qty;removeItem(id,qty);addCoins(total);incStat('sold',id,qty);state.flags.quickSold+=qty;log(`Bán nhanh ${qty} ${item(id).name}: +${fmt(total)} xu.`,'economy');checkUnlockNotices();checkMarketUnlock();checkTutorial();render(true);save();}

  function isItemKnown(id){if(invQty(id)>0||(state.stats.produced?.[id]||0)>0)return true;for(const[sid,arr]of Object.entries(D.actions)){const a=arr.find(x=>x.outputs&&id in x.outputs);if(a&&actionAvailable(sid,a))return true;}return false;}
  function itemUses(id){const uses=[];Object.entries(D.actions).forEach(([sid,arr])=>arr.forEach(a=>{if(a.inputs?.[id])uses.push(`${skill(sid).name}: ${a.name}`);}));Object.values(D.skills).forEach(s=>{if(s.unlock?.item===id)uses.push(`Mở khóa nghề ${s.name}`);});D.zones.forEach(z=>{if(z.unlock?.item===id)uses.push(`Khám phá ${z.name}`);});return uses;}
  function itemAdvice(id){const it=item(id),uses=itemUses(id);if(it.tool)return `Nên giữ: ${toolEffectText(id)}.`;
    if(it.combat)return `Trang bị chiến đấu: ${equipmentEffectText(id)}.`;
    if(it.equipment)return 'Nên giữ ít nhất 1 món: có thể là điều kiện mở nội dung hoặc dùng cho chiến đấu.';
    if(uses.length>=2)return 'Nên giữ một lượng dự phòng: vật phẩm có nhiều công thức hoặc điều kiện sử dụng.';
    if(uses.length===1)return 'Có thể bán phần dư, nhưng nên giữ đủ cho công thức/điều kiện đang cần.';
    return 'Hiện chủ yếu dùng để bán lấy xu hoặc hoàn thành nhiệm vụ phụ; có thể xuất hiện công thức mới về sau.';}

  const tutorialSteps=[
    {title:'Bước 1 · Bắt đầu',text:'Mở Thu nhặt, chọn Đá vụn và bắt đầu. Thanh hành động tự lặp; mỗi lượt hoàn thành sẽ hiện vật phẩm vừa nhận.',done:()=> (state.mastery.pebble||0)>=1},
    {title:'Bước 2 · Tích tài nguyên',text:'Thu nhặt đến khi có ít nhất 5 Đá vụn. Rê chuột vào vật phẩm trong Túi đồ để xem nên bán hay giữ.',done:()=>invQty('pebble')>=5},
    {title:'Bước 3 · Kiếm xu',text:'Trong Túi đồ có các mức Bán 1 / 10 / 50 / Tất cả và ô nhập số lượng tùy chọn. Hãy bán ít nhất 5 món.',done:()=>state.flags.quickSold>=5},
    {title:'Bước 4 · Tăng cấp',text:'Tiếp tục Thu nhặt tới Lv3. 12 tài nguyên của mỗi nghề luôn hiện, nhưng nội dung chưa mở sẽ tối và mang tên ???.',done:()=>state.skills.gathering.level>=3},
    {title:'Bước 5 · Mở Khai khoáng',text:'Chọn Khai khoáng. Nếu còn thiếu điều kiện, bấm Mở khóa để game báo chính xác phần còn thiếu.',done:()=>state.skills.mining.unlocked},
    {title:'Bước 6 · Khai khoáng',text:'Khai ít nhất 5 Quặng đồng. Thời gian tài nguyên cao cấp tăng dần; dụng cụ chế tạo về sau sẽ rút ngắn thời gian.',done:()=> (state.stats.produced.copper_ore||0)>=5},
    {title:'Bước 7 · Chợ Trời',text:'Đưa Tổng cấp lên 5 để mở Chợ Trời. Thương nhân mua bán và làm giá biến động ngay cả khi game đóng.',done:()=>state.flags.marketUnlocked},
    {title:'Bước 8 · Nhiệm vụ phụ',text:'Theo dõi 1–2 nhiệm vụ phụ cạnh Mục tiêu tiếp theo. Hoàn thành sẽ có thư nhắc và nhận thêm xu.',done:()=>state.flags.sideQuestClaimed>0},
    {title:'Bước 9 · Mở rộng',text:'Mở Đốn gỗ, sau đó tích Quặng sắt + xu để mở Luyện kim. Các khu vực trên Bản đồ chỉ được tính là khám phá sau khi tự bấm Khám phá.',done:()=>state.skills.smelting.unlocked},
    {title:'Đã quen hệ thống cơ bản',text:'Từ đây có thể tự chọn hướng: khai thác, sản xuất, buôn bán, chế tạo dụng cụ hoặc tiến tới Chiến đấu.',done:()=>false}
  ];
  function checkTutorial(){while(state.tutorialStep<tutorialSteps.length-1&&tutorialSteps[state.tutorialStep].done()){const old=tutorialSteps[state.tutorialStep];state.tutorialStep++;sendMail(`Hoàn thành ${old.title}`,`Bước tiếp theo: ${tutorialSteps[state.tutorialStep].title}.`,'guide');log(`Hướng dẫn chuyển sang: ${tutorialSteps[state.tutorialStep].title}.`,'unlock');}}

  function questProgress(q){return Math.max(0,(state.stats.produced?.[q.itemId]||0)-q.startProduced);}
  function questCandidates(){let c=[];['gathering','mining','woodcutting','smelting','crafting','combat'].forEach(sid=>{if(!state.skills[sid]?.unlocked)return;D.actions[sid].forEach(a=>{if(!actionAvailable(sid,a))return;const id=Object.keys(a.outputs||{})[0];if(id)c.push({sid,a,itemId:id});});});return c;}
  function generateQuest(){const activeIds=new Set(state.sideQuests.map(q=>q.itemId)),c=questCandidates().filter(x=>!activeIds.has(x.itemId));if(!c.length)return false;const preferred=c.filter(x=>['gathering','mining','woodcutting'].includes(x.sid)),pool=preferred.length&&Math.random()<.75?preferred:c,pick=pool[randint(0,pool.length-1)],it=item(pick.itemId),qty=randint(6,14)+Math.max(0,Math.floor(state.skills[pick.sid].level/3)),reward=Math.max(20,Math.round(it.basePrice*qty*(.65+Math.random()*.25)));state.questSerial=(state.questSerial||0)+1;state.sideQuests.push({id:'q'+state.questSerial,itemId:pick.itemId,skillId:pick.sid,qty,reward,startProduced:state.stats.produced?.[pick.itemId]||0,createdAt:now(),notified:false,claimed:false});state.questNextAt=now()+scaledWait(D.questCooldownMs);return true;}
  function ensureSideQuests(){state.sideQuests=state.sideQuests||[];if(state.sideQuests.length>=2||now()<(state.questNextAt||0))return;generateQuest();}
  function checkSideQuests(){(state.sideQuests||[]).forEach(q=>{if(q.notified||questProgress(q)<q.qty)return;q.notified=true;sendMail(`Hoàn thành nhiệm vụ phụ`,`${item(q.itemId).name}: đã đủ ${q.qty}. Phần thưởng ${fmt(q.reward)} xu đang chờ nhận.`,'quest');log(`Nhiệm vụ phụ hoàn thành: ${q.qty} ${item(q.itemId).name}.`,'unlock');});}
  function claimQuest(id,anchor){const q=state.sideQuests.find(x=>x.id===id);if(!q||questProgress(q)<q.qty)return;addCoins(q.reward);state.flags.sideQuestClaimed=(state.flags.sideQuestClaimed||0)+1;popupFloat(`+${fmt(q.reward)} xu thưởng`,anchor,'reward');state.sideQuests=state.sideQuests.filter(x=>x.id!==id);state.questNextAt=Math.max(state.questNextAt||0,now()+scaledWait(D.questCooldownMs));checkTutorial();render(true);save();}

  function currentGoal(){const locked=Object.values(D.skills).sort((a,b)=>a.order-b.order).find(s=>!state.skills[s.id].unlocked);if(!locked)return{name:'Phát triển tự do',lines:[{label:'Tất cả nghề demo đã mở',cur:1,need:1,ok:true}]};return{name:`Mở ${locked.name}`,lines:reqStatus(locked.unlock).lines,skill:locked};}
  function reqProgress(req){const r=reqStatus(req);return r.lines.length?r.lines.reduce((s,l)=>s+clamp(l.cur/l.need,0,1),0)/r.lines.length:1;}
  function renderGoal(){const g=currentGoal();return `<div class="goal-card"><div class="goal-title">Mục tiêu tiếp theo</div><div class="goal-name">${esc(g.name)}</div><div class="goal-lines">${g.lines.slice(0,4).map(l=>`<div class="goal-line"><span>${esc(l.label)}</span><b>${l.ok?'✓':`${fmt(l.cur)}/${fmt(l.need)}`}</b></div>`).join('')}</div></div>`;}
  function renderSideQuests(){ensureSideQuests();const qs=state.sideQuests||[];return `<div class="quest-card"><div class="goal-title">Nhiệm vụ phụ</div>${qs.length?qs.map(q=>{const p=Math.min(q.qty,questProgress(q)),done=p>=q.qty;return `<div class="quest-row"><div><b>${esc(item(q.itemId).name)}</b><span>Thu được ${fmt(p)}/${fmt(q.qty)} · thưởng ${fmt(q.reward)} xu</span></div>${done?`<button class="gold-btn btn-sm" data-claimquest="${q.id}">Nhận</button>`:`<div class="quest-mini progress small"><i style="width:${p/q.qty*100}%"></i></div>`}</div>`;}).join(''):`<div class="quest-wait">Nhiệm vụ mới sẽ xuất hiện sau một khoảng nghỉ.</div>`}</div>`;}
  function renderObjectives(){return `<div class="objective-stack">${renderGoal()}${renderSideQuests()}</div>`;}

  function render(force=false){if(!force&&now()-lastRender<150)return;lastRender=now();pruneMails();$('#app').innerHTML=`<div class="app-shell">${renderTop()}<div class="main-grid">${renderSidebar()}<main class="center">${renderCenter()}</main>${renderInventory()}</div>${renderBottom()}</div>`;bindEvents();updateProgressDom();}
  function renderTop(){const ca=state.currentAction,a=ca?actionById(ca.actionId):null,unread=unreadCount();return `<header class="topbar"><div class="brand"><div class="brand-mark">◆</div><div>Đại Lục Nghề Nghiệp<div class="brand-sub">Bản demo single-player</div></div></div><div class="action-strip" id="current-action-strip"><div class="action-head"><div class="action-name">${a?`<img src="${a.icon}">${esc(a.name)}`:'Chưa có hành động đang chạy'}</div><div class="action-meta" id="action-time">${a?durationText(ca.duration):'Chọn một nghề để bắt đầu'}</div></div><div class="progress"><i id="action-progress"></i></div></div><div class="top-actions"><button class="kanban-back-btn" data-action="backKanban" title="Trở về KanBan">← KanBan</button><div class="coin-box" id="coin-box"><img src="assets/coin.svg"><strong>${fmt(state.coins)}</strong><span>xu</span></div><div class="top-stat">Tổng cấp<b>${totalLevel()}</b></div><div class="top-stat slot-indicator">Slot<b>${activeSlot}/3</b></div>${speedX3?'<div class="speed-test-badge" title="Giftcode đang bật: tốc độ ×3">×3</div>':''}<button class="icon-btn" data-view="mail" title="Hòm thư"><img src="assets/mail.svg">${unread?`<span class="badge">${unread}</span>`:''}</button><button class="icon-btn" data-action="saveMenu" title="Lưu / Giftcode / Slot">☰</button></div></header>`;}
  function renderSidebar(){const util=[{id:'market',name:'Chợ Trời',icon:'assets/market.svg',locked:!state.flags.marketUnlocked,sub:state.flags.marketUnlocked?'Đang hoạt động':'Mở ở Tổng cấp 5'},{id:'map',name:'Bản đồ',icon:'assets/map.svg',locked:false,sub:`${Object.values(state.zones).filter(Boolean).length}/${D.zones.length} khu vực`}],uhtml=util.map(x=>`<div class="nav-item ${state.activeView===x.id?'active':''} ${x.locked?'locked':''}" data-view="${x.id}"><img src="${x.icon}"><div><div class="nav-name">${x.locked?'🔒 ':''}${x.name}</div><div class="lockline">${x.sub}</div></div></div>`).join(''),skills=Object.values(D.skills).sort((a,b)=>a.order-b.order).map(s=>{const st=state.skills[s.id],pct=st.unlocked?clamp(st.xp/xpNeed(st.level)*100,0,100):reqProgress(s.unlock)*100;return `<div class="nav-item ${state.activeView===s.id?'active':''} ${!st.unlocked?'locked':''}" data-view="${s.id}"><img src="${s.icon}"><div><div class="nav-name">${!st.unlocked?'🔒 ':''}${s.name}</div>${!st.unlocked?`<div class="lockline">${esc(s.unlockText||'Chưa mở')}</div>`:''}</div><div class="nav-level">${st.unlocked?`Lv${st.level}`:''}</div><div class="nav-xp progress small ${!st.unlocked?'unlock':''}"><i style="width:${pct}%"></i></div></div>`;}).join('');return `<aside class="sidebar"><div class="sidebar-head">Khám phá</div><div class="nav-group">${uhtml}</div><div class="divider"></div><div class="sidebar-head">Nghề nghiệp</div><div class="nav-group">${skills}</div></aside>`;}
  function renderCenter(){const v=state.activeView;if(D.skills[v])return renderSkill(v);if(v==='market')return renderMarket();if(v==='map')return renderMap();if(v==='mail')return renderMail();return renderSkill('gathering');}
  function primaryOutput(a){return Object.keys(a.outputs||{})[0];}
  function rarityBadge(id){const r=D.rarityMeta[item(id).rarity];return `<span class="rarity-badge rarity-${item(id).rarity}">${esc(r.name)}</span>`;}
  function renderSkill(skillId){const s=skill(skillId),st=state.skills[skillId];if(!st.unlocked)return renderUnlockSkill(skillId);const bonus=bestToolBonus(skillId);return `<div class="page-head"><div><div class="page-title">${esc(s.name)} · Lv${st.level}</div><div class="page-sub">XP ${fmt(st.xp)} / ${fmt(xpNeed(st.level))} · ${bonus?`Dụng cụ đang giảm tổng cộng ${Math.round(bonus*100)}% thời gian.`:'12 nội dung mở dần theo cấp nghề.'}</div></div>${renderObjectives()}</div><div class="section-card"><div class="section-title">Tiến độ nghề</div><div class="progress"><i style="width:${clamp(st.xp/xpNeed(st.level)*100,0,100)}%"></i></div></div><div class="card-grid">${(D.actions[skillId]||[]).map(a=>renderActionCard(skillId,a)).join('')}</div><div class="start-row">${state.currentAction?`<button class="danger" data-action="stop">Dừng hành động hiện tại</button>`:'<span class="page-sub">Chọn một thẻ đã mở để bắt đầu.</span>'}</div>`;}
  function renderActionCard(skillId,a){const unlocked=actionAvailable(skillId,a),active=state.currentAction?.actionId===a.id,m=state.mastery[a.masteryKey]||0,pid=primaryOutput(a),dur=actionDuration(skillId,a),bonus=bestToolBonus(skillId),outItem=item(pid);let effect='';if(skillId==='crafting'&&outItem?.tool)effect=toolEffectText(pid);else if(skillId==='crafting'&&outItem?.combat)effect=equipmentEffectText(pid);else if(skillId==='crafting'&&outItem?.equipment)effect='Hiệu ứng: '+(outItem.description||'Trang bị dùng cho mở khóa hoặc chiến đấu.');else if(skillId==='combat'){const st=combatStats(),dps=combatDps(a);effect=`Sát thương ước tính ${dps.toFixed(1)} DPS · Công ${st.attack} · HP địch ${fmt(a.enemy?.hp||0)} · Thủ ${fmt(a.enemy?.defense||0)}`;}if(!unlocked)return `<div class="action-card locked" data-locked-action="${a.id}"><img src="${a.icon}"><h3>???</h3><div class="req">Mở ở ${skill(skillId).name} Lv${a.level}</div><div class="recipe">Nội dung chưa khám phá</div><div class="mastery"><div class="progress small"><i style="width:0%"></i></div></div><div class="lock-cover">🔒 Lv${a.level}</div></div>`;return `<div class="action-card ${active?'selected':''} rarity-frame-${item(pid).rarity}" data-start="${a.id}" data-skill="${skillId}"><img src="${a.icon}"><h3>${esc(a.name)}</h3>${rarityBadge(pid)}<div class="req">${(dur/1000).toFixed(1)} giây/lượt · +${a.xp} XP${skillId!=='combat'&&bonus?` · -${Math.round(bonus*100)}% thời gian`:''}</div><div class="recipe">${a.inputs?`Cần: ${esc(inputText(a.inputs))}`:`Nhận: ${esc(outputText(a.outputs))}`}</div>${effect?`<div class="effect-note">${esc(effect)}</div>`:''}<div class="mastery"><div class="mastery-row"><span>Thành thạo</span><span>${fmt(m)} lượt</span></div><div class="progress small"><i style="width:${(m%50)/50*100}%"></i></div></div></div>`;}
  function renderInventory(){const entries=Object.entries(state.inventory).filter(([,q])=>q>0),val=entries.reduce((sum,[id,q])=>sum+(state.prices[id]?.price||item(id).basePrice)*q,0),tab=state.inventoryTab||'bag';let body='';if(tab==='equipment')body=renderEquipmentPanel();else if(tab==='skills')body=renderSkillSummary();else body=`<div class="inv-search"><input id="inv-filter" placeholder="Lọc vật phẩm..."></div><div class="inv-summary"><span>${entries.length} loại vật phẩm</span><span>Giá trị <b>${fmt(val)} xu</b></span></div><div class="inventory-list">${entries.length?entries.sort((a,b)=>D.rarityMeta[item(b[0]).rarity].rank-D.rarityMeta[item(a[0]).rarity].rank).map(([id,q])=>renderInvItem(id,q)).join(''):'<div class="empty">Túi đồ đang trống.<br>Hãy bắt đầu Thu nhặt.</div>'}</div>`;return `<aside class="inventory-panel"><div class="tabs"><div class="tab ${tab==='bag'?'active':''}" data-invtab="bag">Túi đồ</div><div class="tab ${tab==='equipment'?'active':''}" data-invtab="equipment">Trang bị</div><div class="tab ${tab==='skills'?'active':''}" data-invtab="skills">Kỹ năng</div></div>${body}</aside>`;}
  function renderEquipmentPanel(){const st=combatStats(),weapons=weaponItems();return `<div class="equipment-pane"><div class="equip-current"><div class="section-title">Vũ khí đang dùng</div>${st.weapon?`<div class="equip-current-card rarity-frame-${st.weapon.rarity}"><img src="${st.weapon.icon}"><div><b>${esc(st.weapon.name)}</b><span>${esc(equipmentEffectText(st.weapon.id))}</span></div></div>`:'<div class="empty">Chưa trang bị vũ khí.</div>'}<div class="combat-statline"><span>Công <b>${fmt(st.attack)}</b></span><span>Tốc đánh <b>${st.attackSpeed.toFixed(2)}x</b></span><span>Crit <b>${Math.round(st.crit*100)}%</b></span><span>Xuyên giáp <b>${Math.round(st.armorPen*100)}%</b></span></div></div><div class="equipment-list"><div class="section-title">Tiến trình mở trang bị</div>${weapons.map(it=>{const own=invQty(it.id),need=it.combat.requiredLevel||1,levelOk=state.skills.combat?.unlocked&&state.skills.combat.level>=need,craftNeed=it.requiredCraftingLevel||4,equipped=state.equipment?.weapon===it.id;return `<div class="equipment-row ${levelOk?'':'locked'} rarity-frame-${it.rarity}"><img src="${it.icon}"><div class="equipment-row-main"><b>${esc(it.name)}</b><span>Chế tác Lv${craftNeed} · Sử dụng từ Chiến đấu Lv${need}</span><small>${esc(equipmentEffectText(it.id))}</small></div><div class="equipment-owned">${own?`×${fmt(own)}`:'Chưa có'}</div>${equipped?'<span class="equipped-badge">Đang dùng</span>':own&&levelOk?`<button class="gold-btn btn-sm" data-equipweapon="${it.id}">Trang bị</button>`:`<span class="equip-lock">${!levelOk?`🔒 Lv${need}`:'Cần chế tạo'}</span>`}</div>`;}).join('')}</div></div>`;}
  function renderSkillSummary(){return `<div class="skill-summary">${Object.values(D.skills).sort((a,b)=>a.order-b.order).map(sk=>{const x=state.skills[sk.id];return `<div class="skill-summary-row ${x.unlocked?'':'locked'}"><img src="${sk.icon}"><div><b>${esc(sk.name)}</b><span>${x.unlocked?`Lv${x.level} · XP ${fmt(x.xp)}/${fmt(xpNeed(x.level))}`:esc(sk.unlockText||'Chưa mở')}</span></div></div>`;}).join('')}</div>`;}
  function renderInvItem(id,q){const it=item(id),p=Math.round(state.prices[id]?.price||it.basePrice),uses=itemUses(id),useText=uses.length?uses.slice(0,4).join(' · '):'Chưa có công thức bắt buộc trong bản demo hiện tại.',equipBtn=it.combat?`<button class="secondary btn-sm" data-equipweapon="${id}">Trang bị</button>`:'';return `<div class="inv-item rarity-frame-${it.rarity}" data-inv-name="${esc(it.name.toLowerCase())}"><img src="${it.icon}"><div><div class="inv-item-name">${esc(it.name)} ${rarityBadge(id)}</div><div class="inv-item-meta">${esc(it.group)} · Giá tham chiếu ${fmt(p)} xu</div></div><div class="inv-item-qty">×${fmt(q)}</div><div class="inv-actions sell-controls">${equipBtn}<button class="secondary btn-sm" data-quick="${id}" data-qty="1">1</button><button class="secondary btn-sm" data-quick="${id}" data-qty="10">10</button><button class="secondary btn-sm" data-quick="${id}" data-qty="50">50</button><button class="secondary btn-sm" data-quick="${id}" data-qty="${q}">Tất cả</button><input class="sell-custom" type="number" min="1" max="${q}" value="1" id="qs_${id}"><button class="gold-btn btn-sm" data-qcustom="${id}">Bán</button></div><div class="inv-tooltip"><div class="tt-title">${esc(it.name)} · ${esc(D.rarityMeta[it.rarity].name)}</div><div>${esc(it.description||'Vật phẩm trong thế giới.')}</div>${it.combat?`<div><b>Yêu cầu trang bị:</b> Chiến đấu Lv${it.combat.requiredLevel||1}</div>`:''}<div><b>Dùng cho:</b> ${esc(useText)}</div><div><b>Gợi ý:</b> ${esc(itemAdvice(id))}</div><div><b>Giá bán nhanh hiện tại:</b> khoảng ${fmt(p*.9)} xu/món.</div></div></div>`;}
  function renderMarket(){if(!state.flags.marketUnlocked)return `<div class="page-head"><div><div class="page-title">Chợ Trời</div><div class="page-sub">Chợ Trời mở khi Tổng cấp đạt 5.</div></div>${renderObjectives()}</div><div class="section-card"><div class="unlock-name">🔒 Chợ Trời chưa mở</div><div class="unlock-desc">Tiếp tục tăng cấp các nghề đầu tiên.</div><div class="progress unlock"><i style="width:${clamp(totalLevel()/5*100,0,100)}%"></i></div></div>`;const known=Object.values(D.items).filter(it=>isItemKnown(it.id)),rows=known.map(it=>{const p=state.prices[it.id],q=marketQuote(it.id),trend=p.price-p.prev,cls=trend>.01?'price-up':trend<-.01?'price-down':'price-flat',arrow=trend>.01?'▲':trend<-.01?'▼':'•',have=invQty(it.id);return `<div class="market-row rarity-frame-${it.rarity}"><img src="${it.icon}"><div><div class="m-name">${esc(it.name)} ${rarityBadge(it.id)}</div><div class="m-sub">${esc(q.buyer.name)} mua · ${esc(q.seller.name)} bán · Có ${fmt(have)}</div></div><div><div class="m-sub">Thương nhân mua</div><b class="price-up">${fmt(q.buy)} xu</b></div><div><div class="m-sub">Thương nhân bán</div><b>${fmt(q.sell)} xu</b></div><div><div class="m-sub">Xu hướng</div><b class="${cls}">${arrow} ${Number(p.price).toFixed(1)}</b></div><div class="market-action"><div class="preset-row"><button data-mpreset="${it.id}" data-qty="1">1</button><button data-mpreset="${it.id}" data-qty="10">10</button><button data-mpreset="${it.id}" data-qty="50">50</button><button data-mpreset="${it.id}" data-qty="${Math.max(1,have)}">Tất cả</button></div><div class="trade-row"><input type="number" min="1" value="1" id="mq_${it.id}"><button class="secondary btn-sm" data-msell="${it.id}">Bán</button><button class="gold-btn btn-sm" data-mbuy="${it.id}">Mua</button></div></div></div>`;}).join('');return `<div class="page-head"><div><div class="page-title">Chợ Trời</div><div class="page-sub">Chỉ hiển thị vật phẩm đã biết. Thương nhân tự mua bán và điều chỉnh giá kể cả khi quay lại game.</div></div>${renderObjectives()}</div><div class="section-card"><div class="section-title">Thương nhân đang hoạt động</div><div class="npc-strip">${D.npcProfiles.map(n=>`<div class="npc-chip"><b>${esc(n.name)}</b> · ${esc(n.role)}</div>`).join('')}</div></div><div class="market-table">${rows||'<div class="empty">Chưa khám phá vật phẩm nào để giao dịch.</div>'}</div>`;}

  function renderMap(){return `<div class="page-head"><div><div class="page-title">Bản đồ</div><div class="page-sub">12 khu vực luôn hiện. Chỉ Trấn Khởi Đầu mở sẵn; khu vực khác phải tự bấm Khám phá khi đủ điều kiện.</div></div>${renderObjectives()}</div><div class="map-grid">${D.zones.map(z=>{const open=!!state.zones[z.id],rs=reqStatus(z.unlock),eligible=!open&&rs.ok;return `<div class="zone-card ${open?'open':eligible?'eligible':'locked'}"><img src="${z.icon}"><div class="zone-name">${open?'':eligible?'◇ ':'🔒 '}${esc(z.name)}</div><div class="zone-desc">${esc(z.description)}</div><div class="zone-req">${open?'Đã khám phá':eligible?'Đã đủ điều kiện':esc(z.unlockText)}</div>${eligible?`<button class="gold-btn btn-sm zone-btn" data-explore="${z.id}">Khám phá</button>`:''}</div>`;}).join('')}</div>`;}
  function renderMail(){pruneMails();return `<div class="page-head"><div><div class="page-title">Hòm thư</div><div class="page-sub">Thông báo tự xóa sau 2 ngày thực tế. Có thể chủ động xóa toàn bộ bất cứ lúc nào.</div></div>${renderObjectives()}</div><div class="mail-toolbar"><span>${state.mails.length} thư · ${unreadCount()} chưa đọc</span><div class="mail-tools"><button class="secondary btn-sm" data-action="readAll">Đánh dấu đã đọc</button><button class="danger btn-sm" data-action="clearMails">Xóa toàn bộ thư</button></div></div><div class="mail-list">${state.mails.length?state.mails.map(m=>`<div class="mail-item ${m.read?'':'unread'}" data-mail="${m.id}"><div class="mail-top"><div class="mail-title">${esc(m.title)}</div><div class="mail-time">${new Date(m.createdAt).toLocaleString('vi-VN')}</div></div><div class="mail-body">${esc(m.body)}</div><div class="mail-expire">Tự xóa sau ${durationText(m.expiresAt-now())}</div></div>`).join(''):'<div class="empty">Không có thư.</div>'}</div>`;}
  function renderBottom(){const step=tutorialSteps[state.tutorialStep]||tutorialSteps.at(-1),filtered=state.logs.filter(l=>state.logTab==='all'||l.type===state.logTab).slice(0,60);return `<footer class="bottom"><div class="log-panel"><div class="log-tabs">${[['all','Tất cả'],['economy','Kinh tế'],['unlock','Mở khóa'],['activity','Hoạt động']].map(([id,n])=>`<div class="log-tab ${state.logTab===id?'active':''}" data-logtab="${id}">${n}</div>`).join('')}</div><div class="logs">${filtered.length?filtered.map(l=>`<div><time>${new Date(l.at).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time>${esc(l.text)}</div>`).join(''):'<div>Nhật ký sẽ ghi lại các hoạt động quan trọng.</div>'}</div></div><div class="guide"><div class="guide-title">Hướng dẫn khám phá</div><div class="guide-step">${esc(step.title)}</div><div class="guide-text">${esc(step.text)}</div><div class="guide-progress progress small"><i style="width:${Math.min(100,state.tutorialStep/(tutorialSteps.length-1)*100)}%"></i></div><div class="guide-footer"><span>${Math.min(state.tutorialStep+1,tutorialSteps.length)}/${tutorialSteps.length}</span><span>${state.tutorialStep>=tutorialSteps.length-1?'Tự do khám phá':'Tự chuyển bước khi hoàn thành'}</span></div></div></footer>`;}

  function bindEvents(){
    $$('[data-view]').forEach(el=>el.onclick=()=>{state.activeView=el.dataset.view;render(true);save();});
    $$('[data-start]').forEach(el=>el.onclick=()=>startAction(el.dataset.skill,el.dataset.start));
    $$('[data-unlock]').forEach(el=>el.onclick=()=>unlockSkill(el.dataset.unlock,el));
    $$('[data-explore]').forEach(el=>el.onclick=()=>exploreZone(el.dataset.explore,el));
    $$('[data-quick]').forEach(el=>el.onclick=e=>{e.stopPropagation();quickSell(el.dataset.quick,Number(el.dataset.qty));});
    $$('[data-qcustom]').forEach(el=>el.onclick=()=>quickSell(el.dataset.qcustom,Number($('#qs_'+el.dataset.qcustom)?.value||1)));
    $$('[data-msell]').forEach(el=>el.onclick=()=>marketSell(el.dataset.msell,Number($('#mq_'+el.dataset.msell)?.value||1)));
    $$('[data-mbuy]').forEach(el=>el.onclick=()=>marketBuy(el.dataset.mbuy,Number($('#mq_'+el.dataset.mbuy)?.value||1)));
    $$('[data-mpreset]').forEach(el=>el.onclick=()=>{const inp=$('#mq_'+el.dataset.mpreset);if(inp)inp.value=el.dataset.qty;});
    $$('[data-claimquest]').forEach(el=>el.onclick=()=>claimQuest(el.dataset.claimquest,el));
    $$('[data-invtab]').forEach(el=>el.onclick=()=>{state.inventoryTab=el.dataset.invtab;render(true);save();});
    $$('[data-equipweapon]').forEach(el=>el.onclick=e=>{e.stopPropagation();equipWeapon(el.dataset.equipweapon,el);});
    $$('[data-logtab]').forEach(el=>el.onclick=()=>{state.logTab=el.dataset.logtab;render(true);});
    $$('[data-mail]').forEach(el=>el.onclick=()=>{const m=state.mails.find(x=>x.id===el.dataset.mail);if(m){m.read=true;render(true);save();}});
    const f=$('#inv-filter');if(f)f.oninput=()=>{$$('.inv-item').forEach(x=>x.style.display=x.dataset.invName.includes(f.value.toLowerCase())?'grid':'none');};
    $$('[data-action]').forEach(el=>{const a=el.dataset.action;if(a==='stop')el.onclick=()=>stopAction();if(a==='readAll')el.onclick=()=>{state.mails.forEach(m=>m.read=true);render(true);save();};if(a==='clearMails')el.onclick=()=>{if(confirm('Xóa toàn bộ thư hiện có?')){state.mails=[];render(true);save();}};if(a==='saveMenu')el.onclick=showSaveMenu;if(a==='backKanban')el.onclick=backToKanban;});
  }
  function updateProgressDom(){const bar=$('#action-progress'),tm=$('#action-time'),ca=state.currentAction;if(!bar||!tm)return;if(!ca){bar.style.width='0%';return;}const dur=ca.duration||actionDuration(ca.skillId,actionById(ca.actionId)),elapsed=Math.max(0,(now()-ca.startedAt)%dur);bar.style.width=clamp(elapsed/dur*100,0,100)+'%';tm.textContent=`${(Math.max(0,dur-elapsed)/1000).toFixed(1)}s · tự lặp`;}
  function toast(title,text,type='good'){const layer=$('#toast-layer');if(!layer)return;const el=document.createElement('div');el.className=`toast ${type}`;el.innerHTML=`<b>${esc(title)}</b><span>${esc(text)}</span>`;layer.appendChild(el);setTimeout(()=>el.remove(),3400);}
  function popupFloat(text,anchor,type='resource'){const layer=$('#float-layer');if(!layer)return;const r=(anchor||$('#current-action-strip'))?.getBoundingClientRect?.()||{left:innerWidth/2,top:100,width:0,height:0};const el=document.createElement('div');el.className=`popup-float ${type}`;el.textContent=text;el.style.left=(r.left+r.width/2)+'px';el.style.top=(r.top+Math.min(r.height,55))+'px';layer.appendChild(el);setTimeout(()=>el.remove(),1500);}
  function resourceFloat(gained,actionId){const parts=Object.entries(gained||{}).filter(([,q])=>q>0).map(([id,q])=>`+${fmt(q)} ${item(id).name}`);if(!parts.length)return;const anchor=$(`[data-start="${actionId}"]`)||$('#current-action-strip');popupFloat(parts.slice(0,2).join(' · '),anchor,'resource');}
  function moneyFloat(amount){const coin=$('#coin-box');if(!coin)return;popupFloat(`${amount>0?'+':''}${fmt(amount)} xu`,coin,amount>0?'reward':'cost');}
  function modal(title,body,actions=''){ $('#modal-layer').innerHTML=`<div class="modal-wrap"><div class="modal"><div class="modal-head"><div class="modal-title">${esc(title)}</div><div class="close" data-close>×</div></div><div class="modal-body">${body}</div>${actions?`<div class="modal-actions">${actions}</div>`:''}</div></div>`;$$('[data-close]').forEach(x=>x.onclick=closeModal);}
  function closeModal(){$('#modal-layer').innerHTML='';}
  function showWelcome(){modal('Chào mừng đến Đại Lục Nghề Nghiệp',`<div class="welcome"><img src="assets/town.svg"><div><h2>Bắt đầu từ con số 0</h2><p>Hướng dẫn phía dưới sẽ dẫn từng bước. Nội dung chưa mở vẫn được nhìn thấy dưới dạng ??? để tạo mục tiêu khám phá.</p><p>Hành động đang chạy được tính tiếp khi đóng game. Hòm thư ghi lại cột mốc quan trọng và tự xóa sau 2 ngày thực tế.</p></div></div>`,`<button class="primary" data-close>Bắt đầu khám phá</button>`);}
  function showOffline(){if(!offlineReport)return;const r=offlineReport,rows=Object.entries(r.gained).map(([id,q])=>`<div class="offline-row"><span>${esc(item(id).name)}</span><b>+${fmt(q)}</b></div>`).join('');modal('Báo cáo khi quay lại',`<div class="welcome"><img src="${actionById(state.currentAction?.actionId||'')?.icon||'assets/coin.svg'}"><div><h2>${esc(r.action)}</h2><p>Vắng mặt ${durationText(r.duration)} · hoàn thành ${fmt(r.cycles)} lượt.</p></div></div><div class="offline-list">${rows}${r.coins?`<div class="offline-row"><span>Xu nhận được</span><b>+${fmt(r.coins)}</b></div>`:''}<div class="offline-row"><span>XP nghề</span><b>+${fmt(r.xp)}</b></div></div>`,`<button class="primary" data-close>Đóng báo cáo</button>`);offlineReport=null;}
  function backToKanban(){save();if(window.parent&&window.parent!==window){window.parent.postMessage({type:'dai-luc-nghe-nghiep-close'},'*');return;}location.href='../index.html';}
  function setGameSpeed(enabled){processOnline();const ca=state.currentAction,a=ca?actionById(ca.actionId):null,oldDur=ca?.duration||0,oldProgress=ca&&oldDur?clamp((now()-ca.startedAt)/oldDur,0,.999):0;speedX3=!!enabled;if(speedX3)localStorage.setItem(SPEED_KEY,'1');else localStorage.removeItem(SPEED_KEY);if(ca&&a){ca.duration=actionDuration(ca.skillId,a);ca.startedAt=now()-oldProgress*ca.duration;}render(true);save();}
  function applyGiftCode(){const input=$('#giftcode-input'),code=(input?.value||'').trim().toLowerCase();if(code==='yeubo'){setGameSpeed(true);toast('Giftcode đã bật','Tốc độ toàn bộ game ×3. Dùng mã koyeubo để tắt.','good');closeModal();return;}if(code==='koyeubo'){setGameSpeed(false);toast('Giftcode đã tắt','Tốc độ game đã trở về ×1.','good');closeModal();return;}toast('Giftcode không hợp lệ','Kiểm tra lại mã đã nhập.','warn');}
  function slotMeta(slot){try{const raw=localStorage.getItem(saveKey(slot));if(!raw)return{empty:true};const x=JSON.parse(raw),levels=Object.values(x.skills||{}).filter(v=>v?.unlocked).reduce((n,v)=>n+(v.level||1),0);return{empty:false,coins:x.coins||0,totalLevel:levels,lastSeen:x.lastSeen||x.createdAt||0};}catch{return{empty:true};}}
  function switchSlot(slot){slot=clamp(Number(slot)||1,1,3);save();localStorage.setItem(ACTIVE_SLOT_KEY,String(slot));location.reload();}
  function deleteSlot(slot){slot=clamp(Number(slot)||1,1,3);if(!confirm(`Xóa toàn bộ tiến trình ở Slot ${slot}?`))return;localStorage.removeItem(saveKey(slot));localStorage.removeItem(welcomeKey(slot));if(slot===activeSlot)location.reload();else showSaveMenu();}
  function showSaveMenu(){const slots=[1,2,3].map(slot=>{const m=slotMeta(slot),cur=slot===activeSlot;return `<div class="save-slot ${cur?'current':''}"><div><b>Slot ${slot}${cur?' · Đang chơi':''}</b><span>${m.empty?'Trống':`Tổng cấp ${fmt(m.totalLevel)} · ${fmt(m.coins)} xu${m.lastSeen?` · ${new Date(m.lastSeen).toLocaleString('vi-VN')}`:''}`}</span></div><div class="save-slot-actions">${!cur?`<button class="secondary btn-sm" data-slot-switch="${slot}">Chuyển sang</button>`:'<span class="slot-current-badge">Hiện tại</span>'}${!m.empty?`<button class="danger btn-sm" data-slot-delete="${slot}">Xóa</button>`:''}</div></div>`;}).join('');modal('Lưu và 3 Slot chơi',`<div class="section-card"><div class="section-title">3 tiến trình độc lập</div><div class="page-sub">Mỗi Slot tự lưu riêng trên trình duyệt. Có thể chuyển hoặc xóa từng Slot riêng.</div><div class="save-slots">${slots}</div></div><div class="section-card giftcode-card"><div class="section-title">Giftcode thử nghiệm</div><div class="page-sub">Trạng thái hiện tại: <b>${speedX3?'×3 đang bật':'×1 bình thường'}</b>. Mã bật/tắt được lưu trên trình duyệt và áp dụng cho cả 3 Slot.</div><div class="giftcode-row"><input id="giftcode-input" autocomplete="off" placeholder="Nhập giftcode..."><button class="gold-btn" id="giftcode-apply">Áp dụng</button></div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="secondary" id="export-save">Xuất Slot ${activeSlot}</button><label class="secondary" style="cursor:pointer">Nhập vào Slot ${activeSlot}<input id="import-save" type="file" accept="application/json" hidden></label><button class="danger" id="reset-save">Chơi lại Slot ${activeSlot}</button></div>`);$('#export-save').onclick=exportSave;$('#import-save').onchange=importSave;$('#giftcode-apply').onclick=applyGiftCode;const giftInput=$('#giftcode-input');if(giftInput)giftInput.onkeydown=e=>{if(e.key==='Enter')applyGiftCode()};$('#reset-save').onclick=()=>{if(confirm(`Xóa toàn bộ tiến trình Slot ${activeSlot} và bắt đầu lại?`)){localStorage.removeItem(saveKey());localStorage.removeItem(welcomeKey());location.reload();}};$$('[data-slot-switch]').forEach(el=>el.onclick=()=>switchSlot(el.dataset.slotSwitch));$$('[data-slot-delete]').forEach(el=>el.onclick=()=>deleteSlot(el.dataset.slotDelete));}
  function exportSave(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dai_luc_nghe_nghiep_slot_${activeSlot}.json`;a.click();URL.revokeObjectURL(a.href);}
  function importSave(e){const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const parsed=JSON.parse(rd.result);localStorage.setItem(saveKey(),JSON.stringify(parsed));location.reload();}catch{alert('File save không hợp lệ.');}};rd.readAsText(f);}
  function showMailIntro(){if(!state.flags.mailIntro){state.flags.mailIntro=true;sendMail('Hướng dẫn đã bắt đầu','Hòm thư sẽ nhắc cấp nghề, mở khóa, nhiệm vụ phụ và khu vực đủ điều kiện. Thư tự xóa sau 2 ngày thực tế.','guide');}}
  function gameLoop(){processOnline();updateProgressDom();requestAnimationFrame(gameLoop);}
  function economyLoop(){if(state.flags.marketUnlocked&&now()-(state.marketTickAt||0)>=scaledWait(30000))marketTick();ensureSideQuests();checkSideQuests();}

  if(state.currentAction){const aa=actionById(state.currentAction.actionId);if(aa)state.currentAction.duration=actionDuration(state.currentAction.skillId,aa);}simulateOffline();checkUnlockNotices();checkZoneEligibility();checkMarketUnlock();checkTutorial();ensureSideQuests();checkSideQuests();showMailIntro();render(true);save();
  if(state.createdAt&&now()-state.createdAt<5000&&!localStorage.getItem(welcomeKey())){localStorage.setItem(welcomeKey(),'1');setTimeout(showWelcome,150);}else if(offlineReport)setTimeout(showOffline,180);
  setInterval(save,4000);setInterval(economyLoop,5000);setInterval(pruneMails,60000);window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save();});requestAnimationFrame(gameLoop);
})();
