(function(root){
'use strict';
const SKILLS=root.TN_SKILLS||[];
const OPS=['add','subtract','multiply','divide'];
const META={
  add:{label:'Cộng',symbol:'+',emoji:'🍀'},subtract:{label:'Trừ',symbol:'−',emoji:'🌷'},
  multiply:{label:'Nhân',symbol:'×',emoji:'⭐'},divide:{label:'Chia',symbol:'÷',emoji:'🫧'}
};
const REVIEW_INTERVALS=[0,1,3,7,14,30,60];
const BASIC_TABLE_BY_SKILL={1:1,2:2,3:5,4:10,5:3,6:4,7:6,8:7,9:8,10:9};
const DIVISOR_BY_SKILL={1:2,2:5,3:10,4:3,5:4,6:6,7:7,8:8,9:9};
function clamp(n,min,max){return Math.min(max,Math.max(min,n));}
function rand(min,max){const lo=Math.ceil(Math.min(min,max)),hi=Math.floor(Math.max(min,max));return Math.floor(Math.random()*(hi-lo+1))+lo;}
function pick(items){return items[Math.floor(Math.random()*items.length)];}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function getSkill(id){return SKILLS.find(s=>s.id===id);}
function skillsForOperation(op){return SKILLS.filter(s=>s.operation===op).sort((a,b)=>a.order-b.order);}
function make(prompt,answer,exercise){return {prompt,answer,displayAnswer:String(answer),exercise,decimal:false};}
function add(a,b,max){if(max&&a+b>max)b=Math.max(0,max-a);return make(`${a} + ${b}`,a+b,'add');}
function sub(a,b){if(b>a)[a,b]=[b,a];return make(`${a} − ${b}`,a-b,'subtract');}
function mul(a,b){return make(`${a} × ${b}`,a*b,'multiply');}
function div(divisor,quotient){return make(`${divisor*quotient} ÷ ${divisor}`,quotient,'divide');}
function buildAdd(idx){switch(idx){
case 1:return add(rand(0,4),rand(0,4),5);case 2:return add(rand(0,9),rand(0,9),10);case 3:{const a=rand(1,9);return add(a,10-a);}case 4:{const a=rand(10,18);const maxB=Math.max(1,Math.min(9-(a%10),20-a));return add(a,rand(1,maxB));}case 5:{const a=rand(6,9);const b=rand(10-a+1,9);return add(a,b,20);}case 6:{const aT=rand(1,8),bT=rand(1,9-aT);return add(aT*10,bT*10,100);}case 7:{const a=rand(20,89);const maxB=Math.max(1,9-(a%10));return add(a,rand(1,maxB));}case 8:{const a=rand(2,8)*10+rand(2,8);const minB=10-(a%10);return add(a,rand(minB,9));}case 9:{const aT=rand(1,8),bT=rand(1,9-aT),aO=rand(0,7),bO=rand(0,9-aO);return add(aT*10+aO,bT*10+bO);}case 10:{const a=rand(21,79),minOnes=Math.max(1,10-(a%10)),bT=rand(1,Math.max(1,8-Math.floor(a/10)));return add(a,bT*10+rand(minOnes,9));}case 11:return add(pick([19,29,39,49,59,69,79,89,91,98,99]),rand(12,89));case 12:return add(rand(190,899),rand(2,9));case 13:return add(rand(120,899),rand(12,89));case 14:return add(rand(120,799),rand(110,699));case 15:return add(pick([98,99,198,199,298,398,499,898,998]),rand(23,499));case 16:{const a=rand(11,89),b=Math.max(1,100-a),c=rand(2,79);return make(`${a} + ${b} + ${c}`,a+b+c,'add');}default:return add(rand(1,9),rand(1,9));}}
function buildSubtract(idx){switch(idx){
case 1:{const a=rand(1,5);return sub(a,rand(0,a));}case 2:{const a=rand(2,10);return sub(a,rand(0,a));}case 3:{const a=rand(11,19);return sub(a,a-10);}case 4:{const a=rand(11,19);return sub(a,rand(1,Math.max(1,a%10)));}case 5:{const a=rand(11,19),minB=(a%10)+1;return sub(a,rand(minB,Math.min(9,a)));}case 6:{const aT=rand(3,10),bT=rand(1,aT-1);return sub(aT*10,bT*10);}case 7:{const a=rand(21,89);return sub(a,rand(1,Math.max(1,a%10)));}case 8:{const a=rand(2,8)*10+rand(0,7),minB=(a%10)+1;return sub(a,rand(minB,9));}case 9:{const aT=rand(2,9),bT=rand(1,aT-1),aO=rand(1,9),bO=rand(0,aO);return sub(aT*10+aO,bT*10+bO);}case 10:{const aT=rand(3,9),bT=rand(1,aT-1),aO=rand(0,7),bO=rand(aO+1,9);return sub(aT*10+aO,bT*10+bO);}case 11:{const b=pick([19,29,39,47,48,49,59,69,79,89]);return sub(rand(b+10,99),b);}case 12:{const a=rand(201,999);return sub(a,rand(2,9));}case 13:{const a=rand(150,999);return sub(a,rand(12,Math.min(89,a-1)));}case 14:{const a=rand(400,999);return sub(a,rand(120,a-100));}case 15:{const b=pick([98,99,198,199,298,299,398,399]);return sub(rand(b+30,Math.min(999,b+500)),b);}case 16:{const b=rand(120,850),gap=rand(12,149),a=b+gap;return sub(a,b);}default:return sub(rand(2,10),rand(1,5));}}
function buildMultiply(idx){if(idx>=1&&idx<=10){const table=BASIC_TABLE_BY_SKILL[idx];return mul(rand(0,10),table);}if(idx===11)return mul(rand(1,10),rand(1,10));if(idx>=12&&idx<=21){const table=idx-1;return mul(rand(1,20),table);}if(idx===22)return mul(rand(2,20),rand(11,20));if(idx===23)return mul(rand(12,89),rand(2,9));if(idx===24)return mul(pick([19,29,49,99]),rand(2,12));return mul(rand(1,10),rand(1,10));}
function buildDivide(idx){if(idx>=1&&idx<=9)return div(DIVISOR_BY_SKILL[idx],rand(1,12));if(idx===10)return div(rand(2,10),rand(1,12));if(idx===11)return div(11,rand(2,20));if(idx===12)return div(12,rand(2,20));if(idx===13)return div(rand(13,15),rand(2,20));if(idx===14)return div(rand(16,20),rand(2,20));if(idx===15)return div(rand(2,9),rand(15,79));if(idx===16)return div(pick([12,15,18,20,24,25]),rand(12,45));return div(rand(2,9),rand(1,10));}
function generateSkillQuestion(skillId){const skill=getSkill(skillId);if(!skill)throw new Error('Unknown skill '+skillId);const idx=Number(skill.id.split('-')[1]);const q=skill.operation==='add'?buildAdd(idx):skill.operation==='subtract'?buildSubtract(idx):skill.operation==='multiply'?buildMultiply(idx):buildDivide(idx);return {...q,skillId};}
function answerChoices(answer){const spread=Math.max(2,Math.min(20,Math.round(Math.abs(answer)*.12))),set=new Set([answer]);let guard=0;while(set.size<4&&guard<80){guard++;const delta=pick([-2,-1,1,2])*rand(1,spread);set.add(Math.max(0,answer+delta));}let step=1;while(set.size<4){set.add(answer+step);if(answer-step>=0)set.add(answer-step);step++;}return shuffle([...set]).slice(0,4);}
function defaultSkillState(){return {attempted:0,correct:0,averageMs:0,mastery:30,correctStreak:0,completed:false,lastPracticedAt:null,dueAt:null,intervalDays:0,reviewStep:0,memoryAttempted:0,memoryCorrect:0,memoryAverageMs:0,memoryMastery:20};}
function emptyProfile(){return {skills:{},xp:0,level:1,bosses:{},placement:null};}
function normalizeState(v){return {...defaultSkillState(),...(v||{})};}
function applyLearningResult(profile,result){const skill=getSkill(result.skillId);if(!skill)return profile;const current=normalizeState(profile.skills[result.skillId]),safeMs=clamp(result.responseMs,250,60000),now=new Date();
 if(result.mode==='memory'){const attempted=current.memoryAttempted+1,correct=current.memoryCorrect+(result.correct?1:0),averageMs=current.memoryAttempted===0?safeMs:Math.round((current.memoryAverageMs*current.memoryAttempted+safeMs)/attempted),speed=clamp(skill.targetMs/safeMs,.45,1.2),performance=result.correct?Math.min(100,82*speed+18):0,memoryMastery=Math.round(current.memoryMastery*.82+performance*.18),xp=profile.xp+(result.correct?8:2);return {...profile,xp,level:Math.floor(xp/180)+1,skills:{...profile.skills,[result.skillId]:{...current,memoryAttempted:attempted,memoryCorrect:correct,memoryAverageMs:averageMs,memoryMastery:clamp(memoryMastery,0,100),lastPracticedAt:now.toISOString()}}};}
 const attempted=current.attempted+1,correct=current.correct+(result.correct?1:0),averageMs=current.attempted===0?safeMs:Math.round((current.averageMs*current.attempted+safeMs)/attempted),speed=clamp(skill.targetMs/safeMs,.45,1.15),performance=result.correct?Math.min(100,86*speed+14):0,mastery=Math.round(current.mastery*.80+performance*.20),correctStreak=result.correct?current.correctStreak+1:0,accuracy=correct/attempted,completed=current.completed||(attempted>=8&&mastery>=76&&accuracy>=.78&&averageMs<=skill.targetMs*1.5),wasDue=Boolean(current.completed&&(!current.dueAt||new Date(current.dueAt).getTime()<=now.getTime()));let reviewStep=current.reviewStep;if(!result.correct)reviewStep=0;else if(!current.completed&&completed)reviewStep=Math.max(1,reviewStep);else if(wasDue)reviewStep=clamp(reviewStep+1,1,REVIEW_INTERVALS.length-1);const intervalDays=REVIEW_INTERVALS[reviewStep]||0,dueAt=completed?(!wasDue&&current.completed&&current.dueAt&&result.correct?current.dueAt:new Date(now.getTime()+intervalDays*86400000).toISOString()):new Date(now.getTime()+(result.correct?6:.5)*3600000).toISOString(),xpGain=result.correct?(safeMs<=skill.targetMs?8:6):2,xp=profile.xp+xpGain;
 return {...profile,xp,level:Math.floor(xp/180)+1,skills:{...profile.skills,[result.skillId]:{...current,attempted,correct,averageMs,mastery:clamp(mastery,0,100),correctStreak,completed,lastPracticedAt:now.toISOString(),dueAt,intervalDays,reviewStep}}};}
function isSkillUnlocked(profile,skillId){const skill=getSkill(skillId);if(!skill)return false;if(skill.order===0)return true;const prev=skillsForOperation(skill.operation)[skill.order-1];return Boolean(profile.skills[prev.id]?.completed);}
function dueSkills(profile,now=Date.now()){return SKILLS.filter(s=>{const st=profile.skills[s.id];return Boolean(st?.completed&&st.dueAt&&new Date(st.dueAt).getTime()<=now);}).sort((a,b)=>new Date(profile.skills[a.id].dueAt)-new Date(profile.skills[b.id].dueAt)).map(s=>s.id);}
function chooseLessonSkill(profile){const c=SKILLS.filter(s=>isSkillUnlocked(profile,s.id)&&!profile.skills[s.id]?.completed).sort((a,b)=>a.pathOrder-b.pathOrder);if(c.length)return c[0].id;const due=dueSkills(profile);if(due.length)return due[0];return [...SKILLS].sort((a,b)=>a.pathOrder-b.pathOrder)[0].id;}
function learnedSkillsThrough(profile,focusId){const focus=getSkill(focusId);if(!focus)return[];const completed=SKILLS.filter(s=>s.pathOrder<focus.pathOrder&&profile.skills[s.id]?.completed).sort((a,b)=>a.pathOrder-b.pathOrder),recent=completed.slice(-10).map(s=>s.id),overdue=dueSkills(profile).filter(id=>(getSkill(id)?.pathOrder||999)<focus.pathOrder).slice(0,4);return [...new Set([...overdue,...recent,focus.id])];}
function chooseCumulativeSkill(profile,ids,focusId){if(ids.length<=1)return ids[0];const now=Date.now(),weighted=ids.map(id=>{const st=normalizeState(profile.skills[id]),overdue=st.dueAt?Math.max(0,now-new Date(st.dueAt).getTime())/86400000:0;let w=10;if(id===focusId)w+=48;if(st.completed)w+=Math.min(24,overdue*8);if(!st.completed)w+=18+(100-st.mastery)*.25;if(st.attempted<4)w+=12;return{id,weight:Math.max(5,w)};}),total=weighted.reduce((s,x)=>s+x.weight,0);let roll=Math.random()*total;for(const item of weighted){roll-=item.weight;if(roll<=0)return item.id;}return weighted.at(-1).id;}
function branchProgress(profile,op){const branch=skillsForOperation(op),completed=branch.filter(s=>profile.skills[s.id]?.completed).length;return{completed,total:branch.length,percent:Math.round(completed/branch.length*100)};}
function isBossUnlocked(profile,op){const b=skillsForOperation(op);return b.every(s=>profile.skills[s.id]?.completed);}
function markBoss(profile,op,passed){if(!passed)return profile;return {...profile,bosses:{...profile.bosses,[op]:true},xp:profile.xp+120,level:Math.floor((profile.xp+120)/180)+1};}
function placementPassedSkills(results){const passed=new Set();for(const op of OPS){const branch=skillsForOperation(op),tested=results.filter(x=>getSkill(x.skillId)?.operation===op).sort((a,b)=>(getSkill(a.skillId)?.order||0)-(getSkill(b.skillId)?.order||0));let highest=-1;for(const r of tested){const s=getSkill(r.skillId);if(!s)continue;const ok=!r.skipped&&r.correct&&r.responseMs<=s.targetMs*1.7;if(!ok)break;highest=s.order;}branch.filter(s=>s.order<=highest).forEach(s=>passed.add(s.id));}return [...passed];}
function seedFromPlacement(profile,passedIds,placement){const skills={...profile.skills},now=new Date();for(const id of passedIds){const s=getSkill(id);if(!s)continue;skills[id]={...defaultSkillState(),attempted:8,correct:7,averageMs:Math.round(s.targetMs*.85),mastery:84,correctStreak:2,completed:true,lastPracticedAt:now.toISOString(),dueAt:new Date(now.getTime()+3*86400000).toISOString(),intervalDays:3,reviewStep:2};}const xp=Math.max(profile.xp,passedIds.length*18);return {...profile,skills,xp,level:Math.floor(xp/180)+1,placement};}
function slowestSkill(profile){let out=null;for(const s of SKILLS){const st=profile.skills[s.id];if(!st||st.attempted<3||!st.averageMs)continue;const ratio=st.averageMs/s.targetMs;if(!out||ratio>out.ratio)out={skillId:s.id,ratio};}return out;}
function weakestSkill(profile){let out=null;for(const s of SKILLS){const st=profile.skills[s.id];if(!st||st.attempted<3)continue;if(!out||st.mastery<out.mastery)out={skillId:s.id,mastery:st.mastery};}return out;}
function memorySummary(profile){const states=Object.values(profile.skills).filter(s=>s.memoryAttempted>0),attempted=states.reduce((a,s)=>a+s.memoryAttempted,0),correct=states.reduce((a,s)=>a+s.memoryCorrect,0),averageMs=attempted?Math.round(states.reduce((a,s)=>a+s.memoryAverageMs*s.memoryAttempted,0)/attempted):0,mastery=states.length?Math.round(states.reduce((a,s)=>a+s.memoryMastery,0)/states.length):20,accuracy=attempted?Math.round(correct/attempted*100):0;let level=1;if(attempted>=15&&accuracy>=75)level=2;if(attempted>=40&&accuracy>=82&&mastery>=65)level=3;if(attempted>=80&&accuracy>=88&&mastery>=78)level=4;return{attempted,correct,accuracy,averageMs,mastery,level,flashMs:[0,4500,3200,2200,1500][level]};}
function memoryCandidateSkills(profile){const c=SKILLS.filter(s=>profile.skills[s.id]?.completed).sort((a,b)=>b.pathOrder-a.pathOrder).slice(0,18).map(s=>s.id);if(c.length)return c;return ['add-01','add-02','sub-01'].filter(id=>getSkill(id));}
function accuracy(c,a){return a?Math.round(c/a*100):0;}
const api={SKILLS,OPS,META,getSkill,skillsForOperation,generateSkillQuestion,answerChoices,defaultSkillState,emptyProfile,normalizeState,applyLearningResult,isSkillUnlocked,dueSkills,chooseLessonSkill,learnedSkillsThrough,chooseCumulativeSkill,branchProgress,isBossUnlocked,markBoss,placementPassedSkills,seedFromPlacement,slowestSkill,weakestSkill,memorySummary,memoryCandidateSkills,accuracy,shuffle,rand,pick,clamp};
root.TNCore=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
