'use strict';

// StockSim VN Web 2.0 — port từ StockSim VN v1.9 Pygame sang HTML5 Canvas + JavaScript.
// Toàn bộ giá/tin trong game là mô phỏng phục vụ học tập, không phải dữ liệu thật hay khuyến nghị đầu tư.

const VERSION='2.0.0';
const SAVE_VERSION=7;
const LOT_SIZE=100;
const SESSION_MINUTES=240;
const BASE_SIM_MPS=8;
const PREGEN_DAYS=504;
const INTRADAY_HISTORY_DAYS=60;
const MAX_MINUTE_BARS=20000;
const FEE_RATE=0.0015;
const SELL_TAX_RATE=0.001;
const LEVERAGE_MIN=1;
const LEVERAGE_MAX=5;
const LEVERAGE_STEP=0.5;
const MAINTENANCE_MARGIN_RATIO=0.20;
const PRICE_SCALE_MIN=1;
const PRICE_SCALE_MAX=30;
const PRICE_SCALE_STEP=1.35;
const DB_NAME='StockSimVNWeb';
const DB_STORE='saves';
const DB_KEY='main';
const DIFFICULTIES={
  EASY:{label:'DỄ',cash:200_000_000,desc:'Vốn rộng, dễ thử nhiều mã và chiến lược.'},
  MEDIUM:{label:'TRUNG BÌNH',cash:100_000_000,desc:'Cân bằng giữa cơ hội và quản trị vốn.'},
  HARD:{label:'KHÓ',cash:50_000_000,desc:'Vốn nhỏ hơn, cần chọn lệnh và đòn bẩy cẩn thận.'}
};
const TIMEFRAME_FACTOR={'1M':1,'5M':5,'15M':15,'1H':60,'1D':SESSION_MINUTES};
const REGIMES={
  BULL_STRONG:{drift:0.000045,vol:0.85,momentum:1.25,meanrev:0.55,sentiment:0.75},
  BULL:{drift:0.000024,vol:0.75,momentum:1.10,meanrev:0.70,sentiment:0.45},
  SIDEWAY:{drift:0,vol:0.65,momentum:0.65,meanrev:1.30,sentiment:0},
  VOLATILE:{drift:0,vol:1.35,momentum:0.85,meanrev:0.95,sentiment:-0.05},
  BEAR:{drift:-0.000026,vol:1.00,momentum:1.15,meanrev:0.60,sentiment:-0.45},
  BEAR_STRONG:{drift:-0.000055,vol:1.35,momentum:1.35,meanrev:0.45,sentiment:-0.75},
  PANIC:{drift:-0.000095,vol:2.20,momentum:1.55,meanrev:0.30,sentiment:-1},
  RECOVERY:{drift:0.000060,vol:1.20,momentum:1.20,meanrev:0.75,sentiment:0.35}
};
const REGIME_TRANSITIONS={
  BULL_STRONG:['BULL','SIDEWAY','VOLATILE'], BULL:['BULL_STRONG','SIDEWAY','VOLATILE'],
  SIDEWAY:['BULL','BEAR','VOLATILE'], VOLATILE:['BULL','BEAR','PANIC','SIDEWAY'],
  BEAR:['SIDEWAY','BEAR_STRONG','VOLATILE','RECOVERY'], BEAR_STRONG:['PANIC','BEAR','RECOVERY'],
  PANIC:['BEAR_STRONG','RECOVERY'], RECOVERY:['BULL','SIDEWAY','VOLATILE']
};
const EXCHANGE_SYMBOLS={
  HOSE:['VCB','FPT','HPG','VNM','MWG','GAS','VHM','SSI','GMD','DHG'],
  HNX:['NVB','ONE','VCS','CAP','TNG','PVS','CEO','SHS','HUT','VNR'],
  UPCOM:['ABB','FOX','MSR','QNS','VGT','HND','VEF','SBS','ACV','DVN']
};
const SYMBOL_EXCHANGE=Object.fromEntries(Object.entries(EXCHANGE_SYMBOLS).flatMap(([ex,syms])=>syms.map(s=>[s,ex])));
const PRICE_LIMITS={HOSE:0.07,HNX:0.10,UPCOM:0.15};
const STOCK_CONFIGS=[
 ['VCB','BANK',91000,94000,0.85,0.020,4200000,1.00,0.00012,0.85,1.00],
 ['FPT','TECH',121000,126000,1.05,0.024,5500000,0.95,0.00018,1.20,0.75],
 ['HPG','MATERIALS',28000,29000,1.25,0.032,22000000,1.00,0.00008,1.25,0.80],
 ['VNM','CONSUMER',67000,70000,0.75,0.018,2300000,0.90,0.00010,0.75,1.15],
 ['MWG','RETAIL',62000,65000,1.15,0.030,8000000,0.95,0.00014,1.15,0.80],
 ['GAS','ENERGY',79000,82000,0.90,0.025,2800000,0.82,0.00008,0.90,1.00],
 ['VHM','REAL_ESTATE',48000,51000,1.30,0.034,9500000,0.90,0.00006,1.20,0.75],
 ['SSI','SECURITIES',34000,35000,1.45,0.038,18000000,1.00,0.00008,1.35,0.70],
 ['GMD','LOGISTICS',65000,68000,1.05,0.025,2400000,0.85,0.00010,0.95,0.90],
 ['DHG','HEALTHCARE',112000,116000,0.65,0.018,450000,0.72,0.00010,0.70,1.15],
 ['NVB','BANK',12000,12500,1.10,0.031,2000000,0.72,0.00007,1.05,0.85],
 ['ONE','TECH',9500,10000,1.05,0.036,350000,0.55,0.00010,1.10,0.85],
 ['VCS','MATERIALS',62000,66000,0.90,0.026,600000,0.70,0.00008,0.90,1.00],
 ['CAP','CONSUMER',48000,50000,0.85,0.027,450000,0.62,0.00009,0.85,1.00],
 ['TNG','RETAIL',24000,25000,1.10,0.032,2200000,0.78,0.00010,1.15,0.80],
 ['PVS','ENERGY',37000,39000,1.15,0.031,5500000,0.90,0.00008,1.15,0.82],
 ['CEO','REAL_ESTATE',18000,18500,1.45,0.046,7500000,0.87,0.00004,1.40,0.65],
 ['SHS','SECURITIES',17000,18000,1.50,0.043,12000000,0.95,0.00007,1.40,0.65],
 ['HUT','LOGISTICS',17500,18500,1.25,0.039,4500000,0.80,0.00006,1.20,0.75],
 ['VNR','HEALTHCARE',26000,27000,0.70,0.022,180000,0.55,0.00007,0.70,1.10],
 ['ABB','BANK',10500,11000,1.10,0.030,2500000,0.78,0.00008,1.00,0.90],
 ['FOX','TECH',77000,81000,0.90,0.026,550000,0.68,0.00013,1.00,0.90],
 ['MSR','MATERIALS',18000,19000,1.25,0.040,1800000,0.65,0.00007,1.25,0.72],
 ['QNS','CONSUMER',48000,51000,0.75,0.022,900000,0.72,0.00010,0.78,1.08],
 ['VGT','RETAIL',15000,15500,1.05,0.034,800000,0.62,0.00007,1.00,0.85],
 ['HND','ENERGY',14000,14800,0.78,0.024,650000,0.66,0.00007,0.80,1.05],
 ['VEF','REAL_ESTATE',190000,200000,1.20,0.036,120000,0.45,0.00005,1.10,0.78],
 ['SBS','SECURITIES',7500,8000,1.55,0.052,3500000,0.70,0.00005,1.45,0.62],
 ['ACV','LOGISTICS',115000,120000,0.90,0.025,1100000,0.78,0.00010,0.90,0.95],
 ['DVN','HEALTHCARE',26000,27500,0.72,0.026,280000,0.58,0.00009,0.75,1.08]
];
const SECTOR_SENS={BANK:1.00,TECH:0.90,MATERIALS:1.20,CONSUMER:0.78,RETAIL:1.08,ENERGY:1.18,REAL_ESTATE:1.32,SECURITIES:1.45,LOGISTICS:1.00,HEALTHCARE:0.72};
const COLORS={bg:'#11151f',panel:'#191e2b',grid:'#2b313f',border:'#353c4c',text:'#d6dbe5',muted:'#8b94a6',green:'#00c49a',red:'#f64f59',blue:'#4073ff',yellow:'#f5c242',orange:'#f1913b',purple:'#a466ff',cyan:'#2dccd3'};

const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
const fmtMoney=v=>{const s=v<0?'-':'';v=Math.abs(v);if(v>=1e9)return`${s}${(v/1e9).toFixed(2)}B`;if(v>=1e6)return`${s}${(v/1e6).toFixed(2)}M`;if(v>=1e3)return`${s}${(v/1e3).toFixed(1)}K`;return`${s}${v.toFixed(0)}`};
const fmtPrice=v=>v>=1000?Math.round(v).toLocaleString('en-US'):Number(v).toFixed(2);
const normalizeOrderPrice=v=>Math.max(10,Math.round(Number(v)/10)*10);
const pct=(v,d=2)=>`${v>=0?'+':''}${v.toFixed(d)}%`;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const dayMs=86400000;
function utcAt9(date=new Date()){return Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate(),9,0,0,0)}
function nextWeekday(ts){let d=new Date(ts+dayMs);while([0,6].includes(d.getUTCDay()))d=new Date(d.getTime()+dayMs);return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),9,0,0,0)}
function tradingDaysBefore(ts,count){let d=new Date(ts);for(let i=0;i<count;i++){d=new Date(d.getTime()-dayMs);while([0,6].includes(d.getUTCDay()))d=new Date(d.getTime()-dayMs)}return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),9,0,0,0)}
function formatDate(ts,withTime=false){const d=new Date(ts);const dd=String(d.getUTCDate()).padStart(2,'0'),mm=String(d.getUTCMonth()+1).padStart(2,'0'),yy=d.getUTCFullYear();if(!withTime)return`${dd}/${mm}/${yy}`;return`${dd}/${mm}/${yy} ${String(d.getUTCHours()).padStart(2,'0')}:${String(d.getUTCMinutes()).padStart(2,'0')}`}
function formatShortDate(ts,timeframe){const d=new Date(ts);if(timeframe==='1D')return`${String(d.getUTCMonth()+1).padStart(2,'0')}/${d.getUTCFullYear()}`;return`${String(d.getUTCDate()).padStart(2,'0')}/${String(d.getUTCMonth()+1).padStart(2,'0')} ${String(d.getUTCHours()).padStart(2,'0')}:${String(d.getUTCMinutes()).padStart(2,'0')}`}
function hashString(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function randomSeed(){const a=new Uint32Array(1);if(globalThis.crypto?.getRandomValues)globalThis.crypto.getRandomValues(a);else a[0]=Math.floor(Math.random()*0xffffffff);return (a[0]%2_000_000_000)+1}

class RNG{
  constructor(seed=1,state=null,spare=null){this.state=(state??seed)>>>0||0x6d2b79f5;this.spare=spare}
  random(){let x=this.state>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;this.state=x>>>0;return(this.state+0.5)/4294967296}
  uniform(a=0,b=1){return a+(b-a)*this.random()}
  normal(mu=0,sigma=1){if(this.spare!==null){const z=this.spare;this.spare=null;return mu+sigma*z}let u=0,v=0;while(u<=1e-12)u=this.random();v=this.random();const r=Math.sqrt(-2*Math.log(u)),theta=2*Math.PI*v;this.spare=r*Math.sin(theta);return mu+sigma*r*Math.cos(theta)}
  lognormal(mu=0,sigma=1){return Math.exp(this.normal(mu,sigma))}
  randint(a,b){return Math.floor(this.uniform(a,b+1))}
  choice(arr){return arr[Math.min(arr.length-1,Math.floor(this.random()*arr.length))]}
  shuffle(arr){for(let i=arr.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
  toJSON(){return{state:this.state,spare:this.spare}}
  static fromJSON(o){return new RNG(1,o?.state,o?.spare??null)}
}

function makeStock(cfg){const[symbol,sector,initialPrice,fairValue,beta,baseVolDaily,baseVolumeDaily,liquidity,growthRate,momentumSens,meanrevStrength]=cfg;return{symbol,sector,initialPrice,fairValue,beta,baseVolDaily,baseVolumeDaily,liquidity,growthRate,momentumSens,meanrevStrength,price:initialPrice,momentum:0,variance:(baseVolDaily/Math.sqrt(SESSION_MINUTES))**2,dayRef:initialPrice,dayOpen:initialPrice,dayVolume:0,businessCycle:0,institutionalFlow:0,swingMomentum:0,fundamentalDriftDaily:growthRate}}

class Market{
  constructor(seed=randomSeed()){
    this.seed=Number(seed)||1;this.rng=new RNG(this.seed);this.pyRng=new RNG((this.seed^0xA5A5A5)>>>0);
    this.stocks=Object.fromEntries(STOCK_CONFIGS.map(c=>{const s=makeStock(c);return[s.symbol,s]}));
    this.bars=Object.fromEntries(Object.keys(this.stocks).map(s=>[s,[]]));
    this.dailyBars=Object.fromEntries(Object.keys(this.stocks).map(s=>[s,[]]));
    this.news=[];this.activeNews=[];this.now=tradingDaysBefore(utcAt9(),PREGEN_DAYS);this.sessionMinute=0;this.tradingDayIndex=0;
    this.regime='SIDEWAY';this.regimeDaysLeft=18;this.marketSentiment=0;this.sectorState={};this.marketReturnLast=0;
    this.vnindex=1250;this.vnindexRef=this.vnindex;this.vnindexHistory=[];this.dayAccum={};this.aggCache=new Map();
    this.initSlowFactors();this.startNewDay(true);
  }
  get symbols(){return Object.keys(this.stocks)}
  initSlowFactors(){
    const sectors=[...new Set(Object.values(this.stocks).map(s=>s.sector))].sort();
    const levels=sectors.map((_,i)=>sectors.length===1?0:-0.9+i*(1.8/(sectors.length-1)));this.rng.shuffle(levels);
    sectors.forEach((sec,i)=>this.sectorState[sec]=levels[i]+this.rng.normal(0,0.10));
    const n=this.symbols.length,stockLevels=Array.from({length:n},(_,i)=>n===1?0:-1.15+i*(2.3/(n-1))),flowLevels=Array.from({length:n},(_,i)=>n===1?0:-1+i*(2/(n-1)));
    this.rng.shuffle(stockLevels);this.rng.shuffle(flowLevels);
    this.symbols.forEach((sym,i)=>{const st=this.stocks[sym];st.businessCycle=clamp(stockLevels[i]+this.rng.normal(0,0.12),-1.6,1.6);st.institutionalFlow=clamp(flowLevels[i]+this.rng.normal(0,0.12),-1.6,1.6);st.swingMomentum=0;st.fundamentalDriftDaily=st.growthRate+st.businessCycle*st.baseVolDaily*0.010})
  }
  advanceSlowFactors(){
    for(const sec of Object.keys(this.sectorState)){let shock=this.rng.normal(0,0.10);if(this.rng.random()<0.025)shock+=this.rng.normal(0,0.45);this.sectorState[sec]=clamp(0.955*this.sectorState[sec]+shock,-1.7,1.7)}
    for(const st of Object.values(this.stocks)){let b=this.rng.normal(0,0.05);if(this.rng.random()<0.018)b+=this.rng.normal(0,0.38);st.businessCycle=clamp(0.988*st.businessCycle+b,-1.8,1.8);const fairGap=Math.log(Math.max(st.fairValue,1)/Math.max(st.price,1));const target=0.42*Math.tanh(fairGap*4)+0.26*Math.tanh(st.swingMomentum*45)+0.24*Math.tanh(this.sectorState[st.sector]);let f=this.rng.normal(0,0.055);if(this.rng.random()<0.020)f+=this.rng.normal(0,0.30);st.institutionalFlow=clamp(0.965*st.institutionalFlow+0.035*target+f,-1.8,1.8);st.fundamentalDriftDaily=st.growthRate+st.businessCycle*st.baseVolDaily*0.010}
  }
  startNewDay(initial=false){
    if(!initial){this.tradingDayIndex++;this.regimeDaysLeft--;if(this.regimeDaysLeft<=0){this.regime=this.pyRng.choice(REGIME_TRANSITIONS[this.regime]);this.regimeDaysLeft=this.regime==='PANIC'?this.pyRng.randint(2,8):['BULL_STRONG','BEAR_STRONG'].includes(this.regime)?this.pyRng.randint(7,28):this.pyRng.randint(8,45)}this.advanceSlowFactors()}
    this.vnindexRef=this.vnindex;this.dayAccum={};for(const st of Object.values(this.stocks)){st.dayRef=st.price;st.dayOpen=st.price;st.dayVolume=0;this.dayAccum[st.symbol]={ts:this.now,open:st.price,high:st.price,low:st.price,close:st.price,volume:0}}
  }
  async generateHistory(days=PREGEN_DAYS,onProgress=()=>{}){
    days=Math.max(0,Math.floor(days));const dailyOnly=Math.max(0,days-INTRADAY_HISTORY_DAYS);
    for(let i=0;i<dailyOnly;i++){this.stepHistoryDay();if(i%40===0){onProgress(i/days*0.55,`Đang tạo lịch sử ngày ${i+1}/${days}…`);await sleep(0)}}
    for(let d=0;d<Math.min(days,INTRADAY_HISTORY_DAYS);d++){for(let m=0;m<SESSION_MINUTES;m++)this.stepMinute(true);onProgress(0.55+(d+1)/INTRADAY_HISTORY_DAYS*0.45,`Đang tạo dữ liệu intraday ${d+1}/${INTRADAY_HISTORY_DAYS} phiên…`);if(d%3===0)await sleep(0)}
    onProgress(1,'Hoàn tất dữ liệu 2 năm.');
  }
  stepHistoryDay(){
    const p=REGIMES[this.regime],marketRet=p.drift*30+this.rng.normal(0,0.009*p.vol),sectors=[...new Set(Object.values(this.stocks).map(s=>s.sector))],secRet={};sectors.forEach(sec=>secRet[sec]=this.rng.normal(0,0.006*p.vol*(SECTOR_SENS[sec]||1)));
    let newsScope=null,newsTarget=null,newsImpact=0;if(this.rng.random()<0.16){const rr=this.rng.random();if(rr<0.25){newsScope='MACRO';newsTarget='ALL'}else if(rr<0.60){newsScope='SECTOR';newsTarget=this.pyRng.choice(sectors)}else{newsScope='COMPANY';newsTarget=this.pyRng.choice(this.symbols)}newsImpact=this.rng.normal(0,0.008*p.vol)}
    for(const st of Object.values(this.stocks)){
      const prev=st.price;st.fairValue*=Math.exp(st.fundamentalDriftDaily);const fairGap=Math.log(Math.max(st.fairValue,1)/Math.max(prev,1)),fairPull=fairGap*0.040*st.meanrevStrength*p.meanrev;
      const sectorFlow=this.sectorState[st.sector]*0.00135*(SECTOR_SENS[st.sector]||1),instFlow=st.institutionalFlow*st.baseVolDaily*0.050,swing=st.swingMomentum*0.38*st.momentumSens*p.momentum;
      let n=0;if(newsScope==='MACRO')n=newsImpact;else if(newsScope==='SECTOR'&&newsTarget===st.sector)n=newsImpact*1.15;else if(newsScope==='COMPANY'&&newsTarget===st.symbol)n=newsImpact*1.45;
      const idio=this.rng.normal(0,st.baseVolDaily*0.66*p.vol),limit=PRICE_LIMITS[SYMBOL_EXCHANGE[st.symbol]]||0.07;let ret=marketRet*st.beta+0.50*secRet[st.sector]+sectorFlow+fairPull+instFlow+swing+n+idio;ret=clamp(ret,-limit*0.96,limit*0.96);
      const gap=this.rng.normal(0,st.baseVolDaily*0.10),o=clamp(prev*Math.exp(gap),prev*(1-limit),prev*(1+limit)),close=clamp(prev*Math.exp(ret),prev*(1-limit),prev*(1+limit)),span=Math.abs(this.rng.normal(st.baseVolDaily*0.50,st.baseVolDaily*0.22));
      const high=Math.max(o,close,Math.min(prev*(1+limit),Math.max(o,close)*(1+span))),low=Math.min(o,close,Math.max(prev*(1-limit),Math.min(o,close)*(1-span))),absRatio=Math.abs(ret)/Math.max(st.baseVolDaily,1e-6),flowActivity=1+0.30*Math.abs(st.institutionalFlow)+0.18*Math.abs(this.sectorState[st.sector]),volume=st.baseVolumeDaily*(0.68+0.58*absRatio)*flowActivity*this.rng.lognormal(0,0.25);
      st.price=close;st.momentum=0.88*st.momentum+0.12*(ret/SESSION_MINUTES);st.variance=0.94*st.variance+0.06*((ret/Math.sqrt(SESSION_MINUTES))**2);Object.assign(this.dayAccum[st.symbol],{open:o,high,low,close,volume});
    }
    this.completeDay();this.sessionMinute=0;this.now=nextWeekday(this.now);this.startNewDay(false);
  }
  newsImpactFor(st){
    if(!this.activeNews.length)return 0;let total=0;const alive=[];for(const n of this.activeNews){const age=Math.floor((this.now-n.ts)/60000);if(age<0||age>n.decayMinutes*5)continue;let relevant=n.scope==='MACRO'||(n.scope==='SECTOR'&&n.target===st.sector)||(n.scope==='COMPANY'&&n.target===st.symbol);if(relevant)total+=n.impact*Math.exp(-age/Math.max(20,n.decayMinutes));alive.push(n)}this.activeNews=alive;return total
  }
  maybeNews(){
    let base=0.00085;if(['VOLATILE','PANIC'].includes(this.regime))base*=1.8;if(this.rng.random()>base)return;const roll=this.rng.random();let scope,target,good,bad;
    if(roll<0.28){scope='MACRO';target='ALL';good=['Kỳ vọng mặt bằng lãi suất hạ nhiệt hỗ trợ tâm lý thị trường','Dòng tiền cải thiện khi thanh khoản hệ thống dồi dào','Dữ liệu tăng trưởng tốt hơn kỳ vọng của thị trường'];bad=['Áp lực tỷ giá tăng khiến nhà đầu tư thận trọng','Thanh khoản thị trường suy yếu trước thông tin vĩ mô mới','Kỳ vọng lãi suất tăng làm khẩu vị rủi ro giảm']}
    else if(roll<0.58){scope='SECTOR';target=this.pyRng.choice([...new Set(Object.values(this.stocks).map(s=>s.sector))]);good=[`Dòng tiền bắt đầu luân chuyển mạnh vào nhóm ${target}`,`Triển vọng ngành ${target} được đánh giá tích cực hơn`];bad=[`Áp lực chốt lời gia tăng ở nhóm ${target}`,`Triển vọng ngắn hạn ngành ${target} trở nên thận trọng`]}
    else{scope='COMPANY';target=this.pyRng.choice(this.symbols);good=[`${target}: kết quả kinh doanh mô phỏng vượt kỳ vọng`,`${target}: xuất hiện thông tin về hợp đồng mới tích cực`,`${target}: kỳ vọng lợi nhuận được điều chỉnh tăng`];bad=[`${target}: kết quả kinh doanh mô phỏng thấp hơn kỳ vọng`,`${target}: áp lực chi phí tăng làm biên lợi nhuận bị chú ý`,`${target}: nhà đầu tư thận trọng trước thông tin doanh nghiệp`]}
    const direction=this.rng.random()<0.5?1:-1,r=this.rng.random();let magnitude,amp,decay;if(r<0.75){magnitude='NHẸ';amp=0.00008;decay=90}else if(r<0.97){magnitude='VỪA';amp=0.00018;decay=240}else{magnitude='MẠNH';amp=0.00045;decay=600}amp*=direction*this.rng.uniform(0.7,1.3);const item={ts:this.now,title:this.pyRng.choice(direction>0?good:bad),scope,target,impact:amp,decayMinutes:decay,magnitude};this.news.unshift(item);this.news=this.news.slice(0,300);this.activeNews.push(item);this.marketSentiment=clamp(this.marketSentiment+direction*(magnitude==='NHẸ'?0.08:0.18),-1,1)
  }
  completeDay(){
    const weighted=[];for(const [sym,a] of Object.entries(this.dayAccum)){const c={ts:a.ts,open:a.open,high:a.high,low:a.low,close:a.close,volume:a.volume};this.dailyBars[sym].push(c);if(this.dailyBars[sym].length>4000)this.dailyBars[sym].shift();const st=this.stocks[sym],dr=Math.log(Math.max(c.close,1)/Math.max(c.open,1));st.swingMomentum=0.90*st.swingMomentum+0.10*dr;if(SYMBOL_EXCHANGE[sym]==='HOSE')weighted.push((c.close/Math.max(c.open,1e-9)-1)*st.liquidity)}if(weighted.length)this.vnindex*=1+weighted.reduce((a,b)=>a+b,0)/weighted.length;this.vnindexHistory.push([this.now,this.vnindex]);if(this.vnindexHistory.length>4000)this.vnindexHistory.shift();this.marketSentiment*=0.92
  }
  stepMinute(allowNews=true){
    if(allowNews)this.maybeNews();const p=REGIMES[this.regime],dailyMktVol=0.009*p.vol,minuteMktVol=dailyMktVol/Math.sqrt(SESSION_MINUTES),marketShock=this.rng.normal(0,minuteMktVol),marketDrift=p.drift+this.marketSentiment*0.000008,sectors=[...new Set(Object.values(this.stocks).map(s=>s.sector))],secShock={};sectors.forEach(sec=>secShock[sec]=this.rng.normal(0,minuteMktVol*0.55*(SECTOR_SENS[sec]||1)));const marketReturns=[];
    for(const st of Object.values(this.stocks)){
      const o=st.price,mvb=st.baseVolDaily/Math.sqrt(SESSION_MINUTES),ewma=Math.sqrt(Math.max(st.variance,1e-10));st.fairValue*=Math.exp(st.fundamentalDriftDaily/SESSION_MINUTES);const fairGap=Math.log(Math.max(st.fairValue,1)/Math.max(st.price,1)),meanrev=fairGap*0.00020*st.meanrevStrength*p.meanrev,momentumEffect=st.momentum*0.16*st.momentumSens*p.momentum,sectorFlow=this.sectorState[st.sector]*0.00135*(SECTOR_SENS[st.sector]||1)/SESSION_MINUTES,instFlow=st.institutionalFlow*st.baseVolDaily*0.050/SESSION_MINUTES,swingFlow=st.swingMomentum*0.38*st.momentumSens*p.momentum/SESSION_MINUTES,newsEffect=this.newsImpactFor(st);
      const agentPressure=0.23*Math.tanh(st.momentum*700)+0.16*Math.tanh(fairGap*3)+0.12*this.marketSentiment+0.16*Math.tanh(st.institutionalFlow)+0.10*Math.tanh(this.sectorState[st.sector])+this.rng.normal(0,0.17),orderFlow=agentPressure*mvb*0.10*st.liquidity,idioSigma=Math.max(mvb*0.55,ewma*0.70),idio=this.rng.normal(0,idioSigma*p.vol);
      let r=marketDrift+st.beta*marketShock+0.55*secShock[st.sector]+sectorFlow+instFlow+swingFlow+meanrev+momentumEffect+newsEffect+orderFlow+idio;r=clamp(r,-0.025,0.025);const raw=o*Math.exp(r),limit=PRICE_LIMITS[SYMBOL_EXCHANGE[st.symbol]]||0.07,floor=st.dayRef*(1-limit),ceil=st.dayRef*(1+limit),close=clamp(raw,floor,ceil),realized=Math.log(Math.max(close,1)/Math.max(o,1)),wiggle=Math.abs(this.rng.normal(0,Math.max(mvb,ewma)*0.45)),high=Math.max(o,close,Math.min(ceil,Math.max(o,close)*(1+wiggle))),low=Math.min(o,close,Math.max(floor,Math.min(o,close)*(1-wiggle)));
      st.variance=0.965*st.variance+0.035*realized*realized;st.momentum=0.94*st.momentum+0.06*realized;st.price=close;const absRatio=Math.abs(realized)/Math.max(mvb,1e-6),curve=0.75+0.65*Math.abs((this.sessionMinute/SESSION_MINUTES)-0.5)*2,activity=1+0.28*Math.abs(st.institutionalFlow)+0.15*Math.abs(this.sectorState[st.sector]);let volume=(st.baseVolumeDaily/SESSION_MINUTES)*curve*(1+0.65*absRatio)*activity*this.rng.lognormal(0,0.22);st.dayVolume+=volume;const candle={ts:this.now,open:o,high,low,close,volume};this.bars[st.symbol].push(candle);if(this.bars[st.symbol].length>MAX_MINUTE_BARS)this.bars[st.symbol].shift();const a=this.dayAccum[st.symbol];a.high=Math.max(a.high,high);a.low=Math.min(a.low,low);a.close=close;a.volume+=volume;marketReturns.push(realized*st.beta)
    }
    this.marketReturnLast=marketReturns.reduce((a,b)=>a+b,0)/marketReturns.length;this.sessionMinute++;this.now+=60000;this.aggCache.clear();if(this.sessionMinute>=SESSION_MINUTES){this.completeDay();this.sessionMinute=0;this.now=nextWeekday(this.now);this.startNewDay(false)}
  }
  static aggregate(bucket){return{ts:bucket[0].ts,open:bucket[0].open,high:Math.max(...bucket.map(x=>x.high)),low:Math.min(...bucket.map(x=>x.low)),close:bucket.at(-1).close,volume:bucket.reduce((s,x)=>s+x.volume,0)}}
  getBars(symbol,timeframe,maxBars=1800){
    const raw=this.bars[symbol]||[],factor=TIMEFRAME_FACTOR[timeframe];if(factor===1)return raw.slice(-maxBars);if(timeframe==='1D'){const out=[...(this.dailyBars[symbol]||[])],a=this.dayAccum[symbol];if(a?.volume>0)out.push({...a});return out.slice(-maxBars)}const key=`${symbol}|${timeframe}|${raw.length}`;if(this.aggCache.has(key))return this.aggCache.get(key).slice(-maxBars);const groups=[];let bucket=[],lastDate='';for(const c of raw){const d=new Date(c.ts).toISOString().slice(0,10);if(lastDate&&d!==lastDate){if(bucket.length)groups.push(Market.aggregate(bucket));bucket=[]}bucket.push(c);lastDate=d;if(bucket.length===factor){groups.push(Market.aggregate(bucket));bucket=[]}}if(bucket.length)groups.push(Market.aggregate(bucket));this.aggCache.set(key,groups);return groups.slice(-maxBars)
  }
  dayChangePct(symbol){const st=this.stocks[symbol];return(st.price/Math.max(st.dayRef,1e-9)-1)*100}
  orderBook(symbol,levels=5){
    const st=this.stocks[symbol],vol=Math.sqrt(Math.max(st.variance,1e-10)),spread=clamp(0.0007+vol*0.6/Math.max(st.liquidity,0.5),0.0005,0.006),mid=st.price,tick=Math.max(10,Math.round(mid*0.0005/10)*10),bid0=mid*(1-spread/2),ask0=mid*(1+spread/2),seed=hashString(`${symbol}:${this.tradingDayIndex}:${this.sessionMinute}`),r=new RNG(seed),bids=[],asks=[];for(let i=0;i<levels;i++){const bid=Math.round((bid0-i*tick)/10)*10,ask=Math.round((ask0+i*tick)/10)*10,base=st.baseVolumeDaily/SESSION_MINUTES*st.liquidity,bv=Math.max(100,Math.floor(base*r.uniform(0.5,1.8)/100)*100),av=Math.max(100,Math.floor(base*r.uniform(0.5,1.8)/100)*100);bids.push([bid,bv]);asks.push([ask,av])}return{bids,asks}
  }
  toJSON(){const packBars=o=>Object.fromEntries(Object.entries(o).map(([s,a])=>[s,a.map(c=>[c.ts,c.open,c.high,c.low,c.close,c.volume])]));return{seed:this.seed,rng:this.rng.toJSON(),pyRng:this.pyRng.toJSON(),stocks:this.stocks,bars:packBars(this.bars),dailyBars:packBars(this.dailyBars),news:this.news,activeNews:this.activeNews,now:this.now,sessionMinute:this.sessionMinute,tradingDayIndex:this.tradingDayIndex,regime:this.regime,regimeDaysLeft:this.regimeDaysLeft,marketSentiment:this.marketSentiment,sectorState:this.sectorState,marketReturnLast:this.marketReturnLast,vnindex:this.vnindex,vnindexRef:this.vnindexRef,vnindexHistory:this.vnindexHistory,dayAccum:this.dayAccum}}
  static fromJSON(o){const m=Object.create(Market.prototype),unpack=o=>Object.fromEntries(Object.entries(o||{}).map(([s,a])=>[s,a.map(x=>({ts:x[0],open:x[1],high:x[2],low:x[3],close:x[4],volume:x[5]}))]));Object.assign(m,{seed:o.seed,rng:RNG.fromJSON(o.rng),pyRng:RNG.fromJSON(o.pyRng),stocks:o.stocks,bars:unpack(o.bars),dailyBars:unpack(o.dailyBars),news:o.news||[],activeNews:o.activeNews||[],now:o.now,sessionMinute:o.sessionMinute,tradingDayIndex:o.tradingDayIndex,regime:o.regime,regimeDaysLeft:o.regimeDaysLeft,marketSentiment:o.marketSentiment,sectorState:o.sectorState||{},marketReturnLast:o.marketReturnLast||0,vnindex:o.vnindex||1250,vnindexRef:o.vnindexRef||1250,vnindexHistory:o.vnindexHistory||[],dayAccum:o.dayAccum||{},aggCache:new Map()});return m}
}

class Player{
  constructor(cash=100_000_000){
    this.cash=cash;this.startCash=cash;this.positions={};this.orders=[];this.trades=[];this.realizedPnl=0;this.totalFees=0;this.nextOid=1;this.maxEquity=cash;this.maxDrawdown=0;
    this.firstTradeDone=false;this.closeDone=false;this.limitOrderDone=false;this.stopOrderDone=false;
  }
  positionValue(market,symbol,p){const px=market.stocks[symbol].price;const pnl=p.side==='LONG'?(px-p.avgCost)*p.qty:(p.avgCost-px)*p.qty;return p.marginLocked+pnl}
  equity(market){let eq=this.cash;for(const [s,p] of Object.entries(this.positions))eq+=this.positionValue(market,s,p);this.maxEquity=Math.max(this.maxEquity,eq);if(this.maxEquity>0)this.maxDrawdown=Math.max(this.maxDrawdown,(this.maxEquity-eq)/this.maxEquity);return eq}
  unrealizedPnl(market,net=false){let total=0;for(const [s,p] of Object.entries(this.positions)){const px=market.stocks[s].price,gross=p.side==='LONG'?(px-p.avgCost)*p.qty:(p.avgCost-px)*p.qty;let costs=p.openFees;if(net){costs+=px*p.qty*FEE_RATE;if(p.side==='LONG')costs+=px*p.qty*SELL_TAX_RATE}total+=gross-costs}return total}
  netPnl(market){return this.realizedPnl+this.unrealizedPnl(market,true)}
  effectiveLeverage(p){return p.marginLocked>0?(p.avgCost*p.qty)/p.marginLocked:1}
  orderById(oid){return this.orders.find(o=>o.oid===Number(oid))||null}
  placeOrder(market,symbol,side,orderType,qty,limitPrice=0,leverageX=1){
    side=String(side).toUpperCase();orderType=String(orderType).toUpperCase();qty=Math.floor(Number(qty)/LOT_SIZE)*LOT_SIZE;leverageX=clamp(Number(leverageX)||1,LEVERAGE_MIN,LEVERAGE_MAX);
    if(!['BUY','SELL'].includes(side))return[false,'Loại lệnh BUY/SELL không hợp lệ.'];if(!['MARKET','LIMIT','STOP'].includes(orderType))return[false,'Chỉ hỗ trợ MARKET / LIMIT / STOP.'];if(qty<=0)return[false,`Khối lượng tối thiểu ${LOT_SIZE} và theo lô ${LOT_SIZE}.`];
    const posSide=side==='BUY'?'LONG':'SHORT',existing=this.positions[symbol];if(existing&&existing.qty>0&&existing.side!==posSide)return[false,`${symbol} đang có ${existing.side}. Hãy đóng vị thế trước khi mở ${posSide}.`];
    const current=market.stocks[symbol].price;if(orderType!=='MARKET'){limitPrice=normalizeOrderPrice(limitPrice);if(limitPrice<=0)return[false,'Giá lệnh không hợp lệ.'];const valid=orderType==='LIMIT'?(side==='BUY'?limitPrice<current:limitPrice>current):(side==='BUY'?limitPrice>current:limitPrice<current);if(!valid)return[false,`${side} ${orderType} đang đặt sai phía so với giá thị trường.`]}
    const o={oid:this.nextOid++,ts:market.now,symbol,side,orderType,qty,limitPrice,filledQty:0,avgFill:0,status:'OPEN',intent:'OPEN',positionSide:posSide,leverageX,closedQty:0,realizedPnl:0,lastClosePrice:0,lastCloseTs:0};this.orders.push(o);
    if(orderType==='MARKET')this.executeMarket(market,o);else{if(orderType==='LIMIT')this.limitOrderDone=true;if(orderType==='STOP')this.stopOrderDone=true}
    return[true,orderType==='MARKET'?`Đã gửi ${side} ${symbol}.`:`Đã đặt ${side} ${orderType} ${symbol} @ ${fmtPrice(limitPrice)}.`]
  }
  editOrderPrice(market,oid,newPrice){const o=this.orderById(oid);if(!o||o.intent!=='OPEN'||!['LIMIT','STOP'].includes(o.orderType)||!['OPEN','PARTIAL'].includes(o.status)||o.qty-o.filledQty<=0)return[false,'Chỉ lệnh LIMIT/STOP còn chờ mới sửa được.'];newPrice=normalizeOrderPrice(newPrice);const current=market.stocks[o.symbol].price;const valid=o.orderType==='LIMIT'?(o.side==='BUY'?newPrice<current:newPrice>current):(o.side==='BUY'?newPrice>current:newPrice<current);if(!valid)return[false,`${o.side} ${o.orderType} đang đặt sai phía so với giá thị trường.`];const old=o.limitPrice;o.limitPrice=newPrice;o.modifiedTs=market.now;return[true,`Đã dời #${o.oid}: ${fmtPrice(old)} → ${fmtPrice(newPrice)}.`]}
  slippagePrice(market,symbol,qty,buyLeg){const st=market.stocks[symbol],typical=Math.max(st.baseVolumeDaily/SESSION_MINUTES,LOT_SIZE),participation=qty/typical,slip=clamp(0.0004+0.0018*Math.sqrt(Math.max(0,participation)),0.0004,0.012);return st.price*(buyLeg?1+slip:1-slip)}
  executeMarket(market,o){const remain=o.qty-o.filledQty;if(remain<=0)return;const buyLeg=o.intent==='CLOSE'?o.positionSide==='SHORT':o.side==='BUY',px=this.slippagePrice(market,o.symbol,remain,buyLeg);o.intent==='CLOSE'?this.fillClose(o,remain,px,market):this.fillEntry(o,remain,px,market)}
  fillEntry(o,qty,px,market){
    if(qty<=0)return;const posSide=o.positionSide|| (o.side==='BUY'?'LONG':'SHORT'),existing=this.positions[o.symbol];if(existing&&existing.side!==posSide){o.status='CANCELLED';return}
    const lev=clamp(Number(o.leverageX)||1,LEVERAGE_MIN,LEVERAGE_MAX),cashNeedPerShare=px/lev+px*(FEE_RATE+(posSide==='SHORT'?SELL_TAX_RATE:0)),maxAfford=Math.floor(this.cash/Math.max(cashNeedPerShare,1)/LOT_SIZE)*LOT_SIZE;qty=Math.min(qty,maxAfford);if(qty<=0){o.status='CANCELLED';return}
    const gross=qty*px,fee=gross*FEE_RATE,openTax=posSide==='SHORT'?gross*SELL_TAX_RATE:0,margin=gross/lev;this.cash-=margin+fee+openTax;let p=this.positions[o.symbol];if(!p)p=this.positions[o.symbol]={side:posSide,qty:0,avgCost:0,marginLocked:0,openFees:0,stopLoss:0,takeProfit:0};const newQty=p.qty+qty;p.avgCost=(p.avgCost*p.qty+px*qty)/Math.max(newQty,1);p.qty=newQty;p.marginLocked+=margin;p.openFees+=fee+openTax;this.totalFees+=fee+openTax;const prev=o.filledQty;o.filledQty+=qty;o.avgFill=(o.avgFill*prev+px*qty)/Math.max(o.filledQty,1);o.status=o.filledQty>=o.qty?'FILLED':'PARTIAL';this.trades.unshift({ts:market.now,symbol:o.symbol,side:o.side,positionSide:posSide,action:posSide==='LONG'?'OPEN_LONG':'OPEN_SHORT',qty,price:px,fee:fee+openTax,oid:o.oid});this.trades=this.trades.slice(0,1200);this.firstTradeDone=true
  }
  processPending(market){for(const o of this.orders){if(o.intent!=='OPEN'||!['OPEN','PARTIAL'].includes(o.status)||!['LIMIT','STOP'].includes(o.orderType))continue;const c=market.bars[o.symbol]?.at(-1);if(!c||c.ts<o.ts)continue;const touched=o.orderType==='LIMIT'?(o.side==='BUY'?c.low<=o.limitPrice:c.high>=o.limitPrice):(o.side==='BUY'?c.high>=o.limitPrice:c.low<=o.limitPrice);if(!touched)continue;if(o.orderType==='STOP'){this.executeMarket(market,o);continue}const remain=o.qty-o.filledQty,available=Math.max(LOT_SIZE,Math.floor(c.volume*market.rng.uniform(0.05,0.35)/LOT_SIZE)*LOT_SIZE);this.fillEntry(o,Math.min(remain,available),o.limitPrice,market)}}
  setExitTrigger(market,symbol,kind,price){const p=this.positions[symbol];if(!p||p.qty<=0)return[false,`${symbol} chưa có vị thế.`];price=normalizeOrderPrice(price);const cur=market.stocks[symbol].price;kind=String(kind).toUpperCase();if(kind==='STOP_LOSS'){if(p.side==='LONG'&&price>=cur)return[false,'Stop Loss LONG phải dưới giá hiện tại.'];if(p.side==='SHORT'&&price<=cur)return[false,'Stop Loss SHORT phải trên giá hiện tại.'];p.stopLoss=price;return[true,`Đã đặt Stop Loss ${symbol} @ ${fmtPrice(price)}.`]}if(kind==='TAKE_PROFIT'){if(p.side==='LONG'&&price<=cur)return[false,'Take Profit LONG phải trên giá hiện tại.'];if(p.side==='SHORT'&&price>=cur)return[false,'Take Profit SHORT phải dưới giá hiện tại.'];p.takeProfit=price;return[true,`Đã đặt Take Profit ${symbol} @ ${fmtPrice(price)}.`]}return[false,'Loại trigger không hợp lệ.']}
  clearExitTrigger(symbol,kind){const p=this.positions[symbol];if(!p)return[false,'Không có vị thế.'];if(kind==='STOP_LOSS'){p.stopLoss=0;return[true,'Đã xóa Stop Loss.']}if(kind==='TAKE_PROFIT'){p.takeProfit=0;return[true,'Đã xóa Take Profit.']}return[false,'Không hợp lệ.']}
  processExitTriggers(market){for(const [symbol,p] of Object.entries({...this.positions})){const c=market.bars[symbol]?.at(-1);if(!c)continue;const sl=p.stopLoss>0&&(p.side==='LONG'?c.low<=p.stopLoss:c.high>=p.stopLoss),tp=p.takeProfit>0&&(p.side==='LONG'?c.high>=p.takeProfit:c.low<=p.takeProfit);if(!sl&&!tp)continue;const kind=sl?'STOP_LOSS':'TAKE_PROFIT',trigger=sl?p.stopLoss:p.takeProfit,o={oid:this.nextOid++,ts:market.now,symbol,side:'CLOSE',orderType:kind,qty:p.qty,limitPrice:trigger,filledQty:0,avgFill:0,status:'OPEN',intent:'CLOSE',positionSide:p.side,leverageX:1};this.orders.push(o);let px=trigger;if(sl){const typical=Math.max(market.stocks[symbol].baseVolumeDaily/SESSION_MINUTES,LOT_SIZE),part=p.qty/typical,slip=clamp(0.0004+0.0018*Math.sqrt(Math.max(0,part)),0.0004,0.012);px=trigger*(p.side==='LONG'?1-slip:1+slip)}this.fillClose(o,p.qty,px,market)}}
  allocateClose(symbol,side,qty,closePx,market){let remain=qty;for(const o of this.orders){if(remain<=0)break;if(o.intent!=='OPEN'||o.symbol!==symbol||o.positionSide!==side||o.filledQty<=0)continue;const already=o.closedQty||0,open=Math.max(0,o.filledQty-already);if(open<=0)continue;const take=Math.min(open,remain),gross=side==='LONG'?(closePx-o.avgFill)*take:(o.avgFill-closePx)*take,entry=o.avgFill*take*(FEE_RATE+(side==='SHORT'?SELL_TAX_RATE:0)),exit=closePx*take*(FEE_RATE+(side==='LONG'?SELL_TAX_RATE:0));o.closedQty=already+take;o.realizedPnl=(o.realizedPnl||0)+gross-entry-exit;o.lastClosePrice=closePx;o.lastCloseTs=market.now;remain-=take}}
  fillClose(o,qty,px,market){const p=this.positions[o.symbol];if(!p||p.qty<=0||p.side!==o.positionSide){o.status='CANCELLED';return}qty=Math.min(qty,p.qty);const gross=qty*px,closeFee=gross*FEE_RATE,closeTax=p.side==='LONG'?gross*SELL_TAX_RATE:0,openAlloc=p.openFees*(qty/p.qty),pnlBefore=p.side==='LONG'?(px-p.avgCost)*qty:(p.avgCost-px)*qty,marginRelease=p.marginLocked*(qty/p.qty);this.cash+=marginRelease+pnlBefore-closeFee-closeTax;p.marginLocked=Math.max(0,p.marginLocked-marginRelease);const realized=pnlBefore-openAlloc-closeFee-closeTax;this.allocateClose(o.symbol,p.side,qty,px,market);this.realizedPnl+=realized;this.totalFees+=closeFee+closeTax;p.openFees=Math.max(0,p.openFees-openAlloc);p.qty-=qty;if(p.qty<=0)delete this.positions[o.symbol];o.filledQty+=qty;o.avgFill=px;o.status=o.filledQty>=o.qty?'FILLED':'PARTIAL';let action=`CLOSE_${o.positionSide}`;if(o.orderType==='STOP_LOSS')action=`SL_${o.positionSide}`;else if(o.orderType==='TAKE_PROFIT')action=`TP_${o.positionSide}`;else if(o.orderType==='LIQUIDATION')action=`LIQ_${o.positionSide}`;this.trades.unshift({ts:market.now,symbol:o.symbol,side:'CLOSE',positionSide:o.positionSide,action,qty,price:px,fee:closeFee+closeTax,pnl:realized,oid:o.oid});this.trades=this.trades.slice(0,1200);this.closeDone=true}
  closePosition(market,symbol){const p=this.positions[symbol];if(!p||p.qty<=0)return[false,`${symbol} không có vị thế.`];const side=p.side,o={oid:this.nextOid++,ts:market.now,symbol,side:'CLOSE',orderType:'MARKET',qty:p.qty,limitPrice:0,filledQty:0,avgFill:0,status:'OPEN',intent:'CLOSE',positionSide:side,leverageX:1};this.orders.push(o);this.executeMarket(market,o);return[o.status==='FILLED',o.status==='FILLED'?`Đã đóng ${side} ${symbol} @ ${fmtPrice(o.avgFill)}.`:`Không thể đóng ${symbol}.`]}
  processMarginCalls(market){const msgs=[];for(const [symbol,p] of Object.entries({...this.positions})){const px=market.stocks[symbol].price,pnl=p.side==='LONG'?(px-p.avgCost)*p.qty:(p.avgCost-px)*p.qty;if(p.marginLocked+pnl>p.marginLocked*MAINTENANCE_MARGIN_RATIO)continue;const o={oid:this.nextOid++,ts:market.now,symbol,side:'CLOSE',orderType:'LIQUIDATION',qty:p.qty,limitPrice:0,filledQty:0,avgFill:0,status:'OPEN',intent:'CLOSE',positionSide:p.side,leverageX:1};this.orders.push(o);this.executeMarket(market,o);if(o.status==='FILLED')msgs.push(`MARGIN CALL: đã thanh lý ${p.side} ${symbol}.`)}return msgs}
  cancelOrder(oid){const o=this.orderById(oid);if(o&&['OPEN','PARTIAL'].includes(o.status)){o.status='CANCELLED';return true}return false}
  orderPnlSnapshot(market,o){if(o.intent==='CLOSE'){const t=this.trades.find(t=>t.oid===o.oid&&t.pnl!=null);return t?[t.pnl,null,'REALIZED']:[null,null,'-']}if(o.filledQty<=0||o.avgFill<=0)return[null,null,'WAITING'];const closed=Math.min(o.filledQty,o.closedQty||0),remain=Math.max(0,o.filledQty-closed);let pnl=o.realizedPnl||0;if(remain>0){const cur=market.stocks[o.symbol].price,gross=o.positionSide==='LONG'?(cur-o.avgFill)*remain:(o.avgFill-cur)*remain,entry=o.avgFill*remain*(FEE_RATE+(o.positionSide==='SHORT'?SELL_TAX_RATE:0)),exit=cur*remain*(FEE_RATE+(o.positionSide==='LONG'?SELL_TAX_RATE:0));pnl+=gross-entry-exit}const base=o.avgFill*Math.max(o.filledQty,1)/Math.max(1,o.leverageX||1),pr=base>0?pnl/base*100:null;return[pnl,pr,remain>0?'LIVE':'REALIZED']}
  toJSON(){return{cash:this.cash,startCash:this.startCash,positions:this.positions,orders:this.orders,trades:this.trades,realizedPnl:this.realizedPnl,totalFees:this.totalFees,nextOid:this.nextOid,maxEquity:this.maxEquity,maxDrawdown:this.maxDrawdown,firstTradeDone:this.firstTradeDone,closeDone:this.closeDone,limitOrderDone:this.limitOrderDone,stopOrderDone:this.stopOrderDone}}
  static fromJSON(o){const p=Object.create(Player.prototype);Object.assign(p,{cash:o.cash,startCash:o.startCash,positions:o.positions||{},orders:o.orders||[],trades:o.trades||[],realizedPnl:o.realizedPnl||0,totalFees:o.totalFees||0,nextOid:o.nextOid||1,maxEquity:o.maxEquity||o.startCash,maxDrawdown:o.maxDrawdown||0,firstTradeDone:!!o.firstTradeDone,closeDone:!!o.closeDone,limitOrderDone:!!o.limitOrderDone,stopOrderDone:!!o.stopOrderDone});return p}
}

class MissionManager{
  constructor(startCash){this.startCash=startCash;this.index=0;this.viewed=[];this.drawn=[];this.missions=[
    ['Làm quen Watchlist','Xem ít nhất 3 mã khác nhau.','symbols',3],['Giao dịch đầu tiên','Mở một vị thế LONG hoặc SHORT.','trade',1],['Đổi khung thời gian','Thử một timeframe khác 1D.','timeframe',1],['Vẽ vùng giá','Dùng Rectangle đánh dấu một vùng.','rect',1],['Dùng Fibonacci','Vẽ Fibonacci thoái lui.','fib',1],['Lệnh chờ','Đặt một lệnh LIMIT.','limit',1],['Lệnh phá vỡ','Đặt một lệnh STOP.','stop',1],['Quản trị vị thế','Đặt Stop Loss hoặc Take Profit.','risk',1],['Chốt giao dịch','Đóng ít nhất một vị thế.','close',1],['Mục tiêu lợi nhuận','Đạt Net P/L +1.000.000đ.','pnl',1_000_000],['Đa dạng hóa','Nắm ít nhất 3 mã cùng lúc.','positions',3],['Tăng tài khoản','Đưa Equity lên +5% vốn đầu.','equity',startCash*1.05]
  ].map(([title,desc,kind,target])=>({title,desc,kind,target,done:false}))}
  markView(s){if(!this.viewed.includes(s))this.viewed.push(s)}markDraw(k){if(!this.drawn.includes(k))this.drawn.push(k)}
  value(market,player,ui,m){switch(m.kind){case'symbols':return this.viewed.length;case'trade':return player.firstTradeDone?1:0;case'timeframe':return ui.timeframe!=='1D'?1:0;case'rect':return this.drawn.includes('RECT')?1:0;case'fib':return this.drawn.includes('FIB')?1:0;case'limit':return player.limitOrderDone?1:0;case'stop':return player.stopOrderDone?1:0;case'risk':return Object.values(player.positions).some(p=>p.stopLoss>0||p.takeProfit>0)?1:0;case'close':return player.closeDone?1:0;case'pnl':return player.netPnl(market);case'positions':return Object.keys(player.positions).length;case'equity':return player.equity(market);default:return 0}}
  update(market,player,ui){while(this.index<this.missions.length){const m=this.missions[this.index],v=this.value(market,player,ui,m);if(v<m.target)break;m.done=true;this.index++}}
  current(){return this.missions[this.index]||null}
  toJSON(){return{startCash:this.startCash,index:this.index,viewed:this.viewed,drawn:this.drawn,missions:this.missions}}
  static fromJSON(o){const m=Object.create(MissionManager.prototype);Object.assign(m,{startCash:o.startCash,index:o.index||0,viewed:o.viewed||[],drawn:o.drawn||[],missions:o.missions||[]});return m}
}

class SaveDB{
  constructor(){this.db=null}
  async open(){if(!('indexedDB'in window))return null;this.db=await new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(DB_STORE))db.createObjectStore(DB_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return this.db}
  async get(){if(!this.db)return null;return await new Promise((resolve,reject)=>{const tx=this.db.transaction(DB_STORE,'readonly'),r=tx.objectStore(DB_STORE).get(DB_KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
  async put(data){if(!this.db)return false;await new Promise((resolve,reject)=>{const tx=this.db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(data,DB_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});return true}
  async clear(){if(!this.db)return;await new Promise((resolve,reject)=>{const tx=this.db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).delete(DB_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
}

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const dom={app:$('#app'),canvas:$('#chartCanvas'),chartShell:$('#chartShell'),tooltip:$('#ohlcTooltip'),context:$('#contextMenu'),hint:$('#chartHint'),watchlist:$('#watchlist'),symbolTitle:$('#symbolTitle'),quoteTop:$('#quoteTop'),gameClock:$('#gameClock'),pauseBtn:$('#pauseBtn'),saveBtn:$('#saveBtn'),backBtn:$('#backKanbanBtn'),qty:$('#qtyInput'),price:$('#priceInput'),buy:$('#buySideBtn'),sell:$('#sellSideBtn'),levOut:$('#levOutput'),levDown:$('#levDown'),levUp:$('#levUp'),estimate:$('#orderEstimate'),submit:$('#submitOrderBtn'),orderSymbol:$('#orderSymbol'),tradeTab:$('#tradeTab'),portfolioTab:$('#portfolioTab'),missionTab:$('#missionTab'),account:$('#accountStats'),book:$('#orderBook'),bottom:$('#bottomContent'),bottomSummary:$('#bottomSummary'),toast:$('#toastHost'),loading:$('#loadingOverlay'),loadingTitle:$('#loadingTitle'),loadingText:$('#loadingText'),loadingProgress:$('#loadingProgress'),newGame:$('#newGameModal'),seed:$('#seedInput'),startNewGame:$('#startNewGameBtn'),cancelNewGame:$('#cancelNewGameBtn'),restart:$('#restartBtn')};

const appState={market:null,player:null,missions:null,db:new SaveDB(),selected:'FPT',exchange:'HOSE',timeframe:'1D',chartMode:'CANDLE',speed:1,paused:false,side:'BUY',orderType:'MARKET',leverage:1,bottomTab:'NEWS',sideTab:'TRADE',tool:'CURSOR',visibleCount:120,scrollOffset:0,priceScale:1,drawings:[],redo:[],draft:null,mouse:null,pan:null,axisDrag:null,lineDrag:null,lastRender:0,lastUi:0,simCarry:0,lastSave:0,difficulty:'MEDIUM',seed:1};

function toast(msg,type='info'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;dom.toast.appendChild(el);setTimeout(()=>{el.style.opacity='0';el.style.transform='translateY(-4px)'},3000);setTimeout(()=>el.remove(),3400)}
function showLoading(show,title='',text='',progress=null){dom.loading.hidden=!show;if(title)dom.loadingTitle.textContent=title;if(text)dom.loadingText.textContent=text;if(progress!=null)dom.loadingProgress.style.width=`${clamp(progress,0,1)*100}%`}
function snapshot(){return{saveVersion:SAVE_VERSION,version:VERSION,savedAt:Date.now(),difficulty:appState.difficulty,seed:appState.seed,market:appState.market.toJSON(),player:appState.player.toJSON(),missions:appState.missions.toJSON(),ui:{selected:appState.selected,exchange:appState.exchange,timeframe:appState.timeframe,chartMode:appState.chartMode,speed:appState.speed,paused:appState.paused,leverage:appState.leverage,visibleCount:appState.visibleCount,scrollOffset:appState.scrollOffset,priceScale:appState.priceScale,drawings:appState.drawings}}}
async function saveGame(silent=false){if(!appState.market)return;try{await appState.db.put(snapshot());appState.lastSave=performance.now();if(!silent)toast('Đã lưu game.','success')}catch(e){console.error(e);if(!silent)toast('Không thể lưu game vào trình duyệt.','error')}}
function restore(data){if(!data||data.saveVersion!==SAVE_VERSION)return false;appState.difficulty=data.difficulty||'MEDIUM';appState.seed=data.seed||1;appState.market=Market.fromJSON(data.market);appState.player=Player.fromJSON(data.player);appState.missions=MissionManager.fromJSON(data.missions);Object.assign(appState,{selected:data.ui?.selected||'FPT',exchange:data.ui?.exchange||SYMBOL_EXCHANGE[data.ui?.selected]||'HOSE',timeframe:data.ui?.timeframe||'1D',chartMode:data.ui?.chartMode||'CANDLE',speed:data.ui?.speed||1,paused:!!data.ui?.paused,leverage:data.ui?.leverage||1,visibleCount:data.ui?.visibleCount||120,scrollOffset:data.ui?.scrollOffset||0,priceScale:data.ui?.priceScale||1,drawings:data.ui?.drawings||[],redo:[]});return true}

async function startNewGame(difficulty='MEDIUM',seed=randomSeed()){
  showLoading(true,'Đang tạo thị trường mới','Đang tạo lịch sử 2 năm…',0);appState.difficulty=difficulty;appState.seed=Number(seed)||randomSeed();appState.market=new Market(appState.seed);appState.player=new Player(DIFFICULTIES[difficulty].cash);appState.missions=new MissionManager(appState.player.startCash);Object.assign(appState,{selected:'FPT',exchange:'HOSE',timeframe:'1D',chartMode:'CANDLE',speed:1,paused:false,side:'BUY',orderType:'MARKET',leverage:1,bottomTab:'NEWS',sideTab:'TRADE',tool:'CURSOR',visibleCount:120,scrollOffset:0,priceScale:1,drawings:[],redo:[],draft:null,lineDrag:null});
  await appState.market.generateHistory(PREGEN_DAYS,(p,t)=>showLoading(true,'Đang tạo thị trường mới',t,p));appState.missions.markView('FPT');await saveGame(true);showLoading(false);dom.newGame.hidden=true;syncControls();renderAll(true);toast(`Thị trường mới · Seed ${appState.seed}`,'success')
}

function sma(arr,n,i){if(i<n-1)return null;let s=0;for(let k=i-n+1;k<=i;k++)s+=arr[k].close;return s/n}
function chartData(){const all=appState.market.getBars(appState.selected,appState.timeframe,1800),n=clamp(Math.floor(appState.visibleCount),20,Math.max(20,all.length||20)),off=clamp(Math.floor(appState.scrollOffset),0,Math.max(0,all.length-n)),end=all.length-off,start=Math.max(0,end-n);return{all,bars:all.slice(start,end),start,end,off}}
function chartMetrics(){const c=dom.canvas,rect=c.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1);if(c.width!==Math.round(rect.width*dpr)||c.height!==Math.round(rect.height*dpr)){c.width=Math.round(rect.width*dpr);c.height=Math.round(rect.height*dpr)}const w=rect.width,h=rect.height,left=8,right=72,top=10,bottom=27,volumeH=Math.max(48,h*0.18),plot={x:left,y:top,w:Math.max(10,w-left-right),h:Math.max(50,h-top-bottom-volumeH-5)},vol={x:left,y:top+plot.h+5,w:Math.max(10,w-left-right),h:volumeH},yAxis={x:w-right,y:top,w:right,h:h-top-bottom},xAxis={x:left,y:h-bottom,w:w-left-right,h:bottom};return{c,ctx:c.getContext('2d'),rect,dpr,w,h,plot,vol,yAxis,xAxis}}
function priceRange(bars){if(!bars.length)return{lo:0,hi:1};let lo=Math.min(...bars.map(b=>b.low)),hi=Math.max(...bars.map(b=>b.high));for(const o of appState.player.orders){if(o.symbol===appState.selected&&o.intent==='OPEN'&&['OPEN','PARTIAL'].includes(o.status)&&o.limitPrice>0){lo=Math.min(lo,o.limitPrice);hi=Math.max(hi,o.limitPrice)}}const p=appState.player.positions[appState.selected];if(p){if(p.stopLoss)lo=Math.min(lo,p.stopLoss);if(p.takeProfit)hi=Math.max(hi,p.takeProfit);lo=Math.min(lo,p.avgCost);hi=Math.max(hi,p.avgCost)}const span=Math.max(hi-lo,Math.max(hi,1)*0.01),center=(hi+lo)/2,expanded=span*1.18*appState.priceScale;return{lo:Math.max(0,center-expanded/2),hi:center+expanded/2}}
function xyConverters(bars,m){const range=priceRange(bars),step=m.plot.w/Math.max(1,bars.length),x=i=>m.plot.x+(i+0.5)*step,y=p=>m.plot.y+(range.hi-p)/(range.hi-range.lo)*m.plot.h,priceFromY=yy=>range.hi-(yy-m.plot.y)/m.plot.h*(range.hi-range.lo),idxFromX=xx=>clamp(Math.floor((xx-m.plot.x)/step),0,Math.max(0,bars.length-1));return{range,step,x,y,priceFromY,idxFromX}}
function dashed(ctx,x1,y1,x2,y2,color,width=1,dash=[7,5]){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.restore()}
function lineColor(o){if(o.orderType==='STOP')return o.side==='BUY'?COLORS.cyan:COLORS.orange;return o.side==='BUY'?COLORS.green:COLORS.red}
function liveLines(){const out=[];for(const o of appState.player.orders){if(o.symbol!==appState.selected)continue;if(o.intent==='OPEN'&&['OPEN','PARTIAL'].includes(o.status)&&['LIMIT','STOP'].includes(o.orderType)&&o.limitPrice>0)out.push({kind:'ORDER',id:o.oid,price:o.limitPrice,color:lineColor(o),label:`#${o.oid} ${o.side} ${o.orderType}`,draggable:true});if(o.intent==='OPEN'&&o.filledQty>0&&o.avgFill>0)out.push({kind:'ENTRY',id:o.oid,price:o.avgFill,color:o.positionSide==='LONG'?COLORS.green:COLORS.red,label:`${o.positionSide==='LONG'?'BUY':'SHORT'} #${o.oid}`,draggable:false})}const p=appState.player.positions[appState.selected];if(p){out.push({kind:'AVG',id:0,price:p.avgCost,color:p.side==='LONG'?COLORS.green:COLORS.red,label:`GIÁ VỐN ${p.side}`,draggable:false});if(p.stopLoss>0)out.push({kind:'STOP_LOSS',id:0,price:p.stopLoss,color:COLORS.red,label:'STOP LOSS',draggable:true});if(p.takeProfit>0)out.push({kind:'TAKE_PROFIT',id:0,price:p.takeProfit,color:COLORS.green,label:'TAKE PROFIT',draggable:true})}return out}
function nearestLine(mouseY,bars,m,conv,maxPx=7){let best=null;for(const l of liveLines()){if(!l.draggable)continue;const yy=conv.y(l.price),dist=Math.abs(mouseY-yy);if(dist<=maxPx&&(!best||dist<best.dist))best={...l,y:yy,dist}}return best}
function drawChart(){
  if(!appState.market)return;const m=chartMetrics(),ctx=m.ctx;ctx.setTransform(m.dpr,0,0,m.dpr,0,0);ctx.clearRect(0,0,m.w,m.h);ctx.fillStyle=COLORS.bg;ctx.fillRect(0,0,m.w,m.h);const {bars}=chartData();if(!bars.length)return;const conv=xyConverters(bars,m),{x,y,step,range}=conv;
  ctx.strokeStyle=COLORS.grid;ctx.lineWidth=1;ctx.font='10px system-ui';ctx.fillStyle='#778194';ctx.textAlign='left';for(let i=0;i<=6;i++){const yy=m.plot.y+i*m.plot.h/6,price=range.hi-i*(range.hi-range.lo)/6;ctx.beginPath();ctx.moveTo(m.plot.x,yy);ctx.lineTo(m.plot.x+m.plot.w,yy);ctx.stroke();ctx.fillText(fmtPrice(price),m.yAxis.x+6,yy+3)}for(let i=0;i<=6;i++){const xx=m.plot.x+i*m.plot.w/6;ctx.beginPath();ctx.moveTo(xx,m.plot.y);ctx.lineTo(xx,m.vol.y+m.vol.h);ctx.stroke()}
  const maxVol=Math.max(...bars.map(b=>b.volume),1),bodyW=Math.max(1,Math.min(12,step*0.62));for(let i=0;i<bars.length;i++){const b=bars[i],xx=x(i),up=b.close>=b.open,col=up?COLORS.green:COLORS.red;ctx.globalAlpha=.55;ctx.fillStyle=col;ctx.fillRect(xx-bodyW/2,m.vol.y+m.vol.h-(b.volume/maxVol)*m.vol.h,bodyW,(b.volume/maxVol)*m.vol.h);ctx.globalAlpha=1;if(appState.chartMode==='LINE')continue;ctx.strokeStyle=col;ctx.beginPath();ctx.moveTo(xx,y(b.high));ctx.lineTo(xx,y(b.low));ctx.stroke();const yo=y(b.open),yc=y(b.close),top=Math.min(yo,yc),hh=Math.max(1,Math.abs(yc-yo));ctx.fillStyle=col;ctx.fillRect(xx-bodyW/2,top,bodyW,hh)}if(appState.chartMode==='LINE'){ctx.strokeStyle='#5c8dff';ctx.lineWidth=1.6;ctx.beginPath();bars.forEach((b,i)=>{const xx=x(i),yy=y(b.close);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke()}
  for(const [n,col] of [[20,'#d49b45'],[50,'#7d74d8']]){ctx.strokeStyle=col;ctx.lineWidth=1;ctx.beginPath();let started=false;for(let i=0;i<bars.length;i++){const v=sma(bars,n,i);if(v==null)continue;const xx=x(i),yy=y(v);if(!started){ctx.moveTo(xx,yy);started=true}else ctx.lineTo(xx,yy)}ctx.stroke()}
  const cur=appState.market.stocks[appState.selected].price,cy=y(cur);dashed(ctx,m.plot.x,cy,m.plot.x+m.plot.w,cy,'#8e98aa',1,[3,4]);ctx.fillStyle='#4d7cff';ctx.fillRect(m.yAxis.x+2,cy-9,m.yAxis.w-4,18);ctx.fillStyle='white';ctx.fillText(fmtPrice(cur),m.yAxis.x+6,cy+3);
  drawDrawings(ctx,bars,m,conv);const hover=appState.mouse?nearestLine(appState.mouse.y,bars,m,conv):null;for(const l of liveLines()){const yy=y(appState.lineDrag&&appState.lineDrag.kind===l.kind&&appState.lineDrag.id===l.id?appState.lineDrag.preview:l.price),hl=hover&&hover.kind===l.kind&&hover.id===l.id;dashed(ctx,m.plot.x,yy,m.plot.x+m.plot.w,yy,l.color,hl?2:1.2,l.kind==='AVG'?[10,5]:[6,4]);ctx.font='10px system-ui';ctx.fillStyle=l.color;const label=`${l.label} ${fmtPrice(appState.lineDrag&&appState.lineDrag.kind===l.kind&&appState.lineDrag.id===l.id?appState.lineDrag.preview:l.price)}`;const tw=ctx.measureText(label).width+10;ctx.fillStyle='#161c28';ctx.fillRect(m.plot.x+4,yy-10,tw,19);ctx.strokeStyle=l.color;ctx.strokeRect(m.plot.x+4,yy-10,tw,19);ctx.fillStyle=l.color;ctx.fillText(label,m.plot.x+9,yy+3)}
  if(appState.mouse&&appState.mouse.inside){const mx=appState.mouse.x,my=appState.mouse.y;if(mx>=m.plot.x&&mx<=m.plot.x+m.plot.w&&my>=m.plot.y&&my<=m.vol.y+m.vol.h){dashed(ctx,m.plot.x,my,m.plot.x+m.plot.w,my,'#536078',1,[2,4]);dashed(ctx,mx,m.plot.y,mx,m.vol.y+m.vol.h,'#536078',1,[2,4])}}
  ctx.fillStyle='#6f798d';ctx.font='10px system-ui';ctx.textAlign='center';for(let i=0;i<5;i++){const idx=Math.min(bars.length-1,Math.floor(i*(bars.length-1)/4));if(idx>=0)ctx.fillText(formatShortDate(bars[idx].ts,appState.timeframe),x(idx),m.h-7)}ctx.textAlign='left';ctx.fillStyle='#687386';ctx.fillText(`Y x${appState.priceScale.toFixed(2)} · ${bars.length} nến`,m.plot.x+8,m.plot.y+14);
}
function drawingIndexForTs(bars,ts){let best=0,dist=Infinity;for(let i=0;i<bars.length;i++){const d=Math.abs(bars[i].ts-ts);if(d<dist){dist=d;best=i}}return best}
function drawDrawings(ctx,bars,m,conv){const arr=appState.drawings.filter(d=>d.symbol===appState.selected&&d.timeframe===appState.timeframe);if(appState.draft)arr.push(appState.draft);for(const d of arr){const i1=drawingIndexForTs(bars,d.t1),x1=conv.x(i1),y1=conv.y(d.p1),i2=d.t2?drawingIndexForTs(bars,d.t2):i1,x2=conv.x(i2),y2=conv.y(d.p2??d.p1);ctx.save();ctx.lineWidth=1.2;if(d.kind==='HLINE'){dashed(ctx,m.plot.x,y1,m.plot.x+m.plot.w,y1,'#e8b84d',1,[8,5])}else if(d.kind==='TREND'){ctx.strokeStyle='#67a0ff';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}else if(d.kind==='RECT'){ctx.fillStyle='rgba(78,123,255,.08)';ctx.strokeStyle='#6f96ff';ctx.fillRect(Math.min(x1,x2),Math.min(y1,y2),Math.abs(x2-x1),Math.abs(y2-y1));ctx.strokeRect(Math.min(x1,x2),Math.min(y1,y2),Math.abs(x2-x1),Math.abs(y2-y1))}else if(d.kind==='FIB'){const hi=d.p1,lo=d.p2??d.p1,levels=[0,.382,.5,.618,1];for(const lv of levels){const pp=hi+(lo-hi)*lv,yy=conv.y(pp);dashed(ctx,Math.min(x1,x2),yy,Math.max(x1,x2),yy,'#a977dc',1,[5,4]);ctx.fillStyle='#c79af0';ctx.font='9px system-ui';ctx.fillText(`${(lv*100).toFixed(lv===0||lv===1?0:1)}% ${fmtPrice(pp)}`,Math.min(x1,x2)+3,yy-3)}}ctx.restore()}}

function pointFromEvent(e){const r=dom.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function candlePointAt(pos){const m=chartMetrics(),{bars}=chartData(),conv=xyConverters(bars,m),i=conv.idxFromX(pos.x),b=bars[i];return{m,bars,conv,i,ts:b?.ts??appState.market.now,price:normalizeOrderPrice(conv.priceFromY(pos.y))}}
function updateTooltip(pos){const {m,bars,conv,i}=candlePointAt(pos);if(!bars.length||pos.x<m.plot.x||pos.x>m.plot.x+m.plot.w||pos.y<m.plot.y||pos.y>m.vol.y+m.vol.h){dom.tooltip.hidden=true;return}const b=bars[i],ch=(b.close/b.open-1)*100;dom.tooltip.innerHTML=`<b>${appState.selected} · ${formatDate(b.ts,true)}</b><br>O ${fmtPrice(b.open)} · H ${fmtPrice(b.high)}<br>L ${fmtPrice(b.low)} · C <span class="${ch>=0?'pos':'neg'}">${fmtPrice(b.close)} (${pct(ch)})</span><br>Vol ${fmtMoney(b.volume)}`;dom.tooltip.hidden=false;dom.tooltip.style.left=`${Math.min(pos.x+14,m.w-205)}px`;dom.tooltip.style.top=`${Math.min(pos.y+14,m.h-100)}px`}
function openContext(pos){const cp=candlePointAt(pos),price=cp.price,cur=appState.market.stocks[appState.selected].price,p=appState.player.positions[appState.selected],items=[];const add=(label,fn,enabled=true)=>items.push({label,fn,enabled});add(`BUY LIMIT @ ${fmtPrice(price)}`,()=>quickOrder('BUY','LIMIT',price),price<cur);add(`SELL LIMIT @ ${fmtPrice(price)}`,()=>quickOrder('SELL','LIMIT',price),price>cur);add(`BUY STOP @ ${fmtPrice(price)}`,()=>quickOrder('BUY','STOP',price),price>cur);add(`SELL STOP @ ${fmtPrice(price)}`,()=>quickOrder('SELL','STOP',price),price<cur);items.push({sep:true});add(`STOP LOSS @ ${fmtPrice(price)}`,()=>setTrigger('STOP_LOSS',price),!!p&&((p.side==='LONG'&&price<cur)||(p.side==='SHORT'&&price>cur)));add(`TAKE PROFIT @ ${fmtPrice(price)}`,()=>setTrigger('TAKE_PROFIT',price),!!p&&((p.side==='LONG'&&price>cur)||(p.side==='SHORT'&&price<cur)));if(p?.stopLoss)add('Xóa Stop Loss',()=>clearTrigger('STOP_LOSS'));if(p?.takeProfit)add('Xóa Take Profit',()=>clearTrigger('TAKE_PROFIT'));if(p){items.push({sep:true});add(`ĐÓNG ${p.side} NGAY`,()=>closePosition(appState.selected),true)}dom.context.innerHTML=items.map((it,i)=>it.sep?'<div class="menu-sep"></div>':`<button data-menu-index="${i}" ${it.enabled?'':'disabled'}><span>${it.label}</span></button>`).join('');dom.context._items=items;dom.context.hidden=false;dom.context.style.left=`${Math.min(pos.x,dom.chartShell.clientWidth-235)}px`;dom.context.style.top=`${Math.min(pos.y,dom.chartShell.clientHeight-260)}px`}
function quickOrder(side,type,price){const qty=parseInt(dom.qty.value,10)||LOT_SIZE,[ok,msg]=appState.player.placeOrder(appState.market,appState.selected,side,type,qty,price,appState.leverage);toast(msg,ok?'success':'error');dom.context.hidden=true;renderAll(true);if(ok)saveGame(true)}
function setTrigger(kind,price){const[ok,msg]=appState.player.setExitTrigger(appState.market,appState.selected,kind,price);toast(msg,ok?'success':'error');dom.context.hidden=true;renderAll(true);if(ok)saveGame(true)}
function clearTrigger(kind){const[ok,msg]=appState.player.clearExitTrigger(appState.selected,kind);toast(msg,ok?'success':'error');dom.context.hidden=true;renderAll(true);if(ok)saveGame(true)}
function closePosition(symbol){const[ok,msg]=appState.player.closePosition(appState.market,symbol);toast(msg,ok?'success':'error');renderAll(true);if(ok)saveGame(true)}

function startDrawing(pos){const cp=candlePointAt(pos);if(!cp.bars.length)return;if(appState.tool==='HLINE'){appState.drawings.push({kind:'HLINE',symbol:appState.selected,timeframe:appState.timeframe,t1:cp.ts,p1:cp.price});appState.redo=[];appState.missions.markDraw('HLINE');saveGame(true);return}appState.draft={kind:appState.tool,symbol:appState.selected,timeframe:appState.timeframe,t1:cp.ts,p1:cp.price,t2:cp.ts,p2:cp.price}}
function updateDrawing(pos){if(!appState.draft)return;const cp=candlePointAt(pos);appState.draft.t2=cp.ts;appState.draft.p2=cp.price}
function finishDrawing(){if(!appState.draft)return;appState.drawings.push(appState.draft);appState.missions.markDraw(appState.draft.kind);appState.draft=null;appState.redo=[];saveGame(true)}
function undoDrawing(){if(appState.draft){appState.draft=null;return}const d=appState.drawings.pop();if(d){appState.redo.push(d);toast('Undo hình vẽ.')}}function redoDrawing(){const d=appState.redo.pop();if(d){appState.drawings.push(d);toast('Redo hình vẽ.')}}

function onPointerDown(e){if(e.button!==0)return;dom.context.hidden=true;const pos=pointFromEvent(e),cp=candlePointAt(pos),m=cp.m;appState.mouse={...pos,inside:true};if(pos.x>=m.yAxis.x){appState.axisDrag={axis:'Y',start:pos.y,scale:appState.priceScale};dom.chartShell.classList.add('dragging-y');dom.canvas.setPointerCapture(e.pointerId);return}if(pos.y>=m.xAxis.y){appState.axisDrag={axis:'X',start:pos.x,count:appState.visibleCount};dom.chartShell.classList.add('dragging-x');dom.canvas.setPointerCapture(e.pointerId);return}const near=nearestLine(pos.y,cp.bars,m,cp.conv,8);if(near){appState.lineDrag={...near,old:near.price,preview:near.price,wasPaused:appState.paused};appState.paused=true;dom.chartShell.classList.add('dragging-line');dom.canvas.setPointerCapture(e.pointerId);return}if(appState.tool!=='CURSOR'){startDrawing(pos);dom.canvas.setPointerCapture(e.pointerId);return}appState.pan={x:pos.x,offset:appState.scrollOffset};dom.chartShell.classList.add('panning');dom.canvas.setPointerCapture(e.pointerId)}
function onPointerMove(e){const pos=pointFromEvent(e);appState.mouse={...pos,inside:true};if(appState.axisDrag){const d=appState.axisDrag;if(d.axis==='Y'){const dy=pos.y-d.start;appState.priceScale=clamp(d.scale*Math.exp(dy/130),PRICE_SCALE_MIN,PRICE_SCALE_MAX)}else{const dx=pos.x-d.start;appState.visibleCount=clamp(Math.round(d.count*Math.exp(-dx/220)),20,650);appState.scrollOffset=clamp(appState.scrollOffset,0,1700)}drawChart();return}if(appState.lineDrag){const cp=candlePointAt(pos);appState.lineDrag.preview=cp.price;drawChart();return}if(appState.draft){updateDrawing(pos);drawChart();return}if(appState.pan){const m=chartMetrics(),{bars}=chartData(),step=m.plot.w/Math.max(1,bars.length),delta=Math.round((pos.x-appState.pan.x)/Math.max(1,step));appState.scrollOffset=clamp(appState.pan.offset+delta,0,1700);drawChart();return}updateTooltip(pos);drawChart()}
function onPointerUp(e){if(appState.axisDrag){appState.axisDrag=null;dom.chartShell.classList.remove('dragging-x','dragging-y');saveGame(true);return}if(appState.lineDrag){const d=appState.lineDrag;let result=[false,'Không thể sửa đường.'];if(d.kind==='ORDER')result=appState.player.editOrderPrice(appState.market,d.id,d.preview);else if(d.kind==='STOP_LOSS'||d.kind==='TAKE_PROFIT')result=appState.player.setExitTrigger(appState.market,appState.selected,d.kind,d.preview);toast(result[1],result[0]?'success':'error');appState.paused=d.wasPaused;appState.lineDrag=null;dom.chartShell.classList.remove('dragging-line');renderAll(true);if(result[0])saveGame(true);return}if(appState.draft){finishDrawing();drawChart();return}if(appState.pan){appState.pan=null;dom.chartShell.classList.remove('panning');saveGame(true)}}
function onWheel(e){e.preventDefault();if(e.shiftKey){appState.priceScale=clamp(appState.priceScale*(e.deltaY>0?PRICE_SCALE_STEP:1/PRICE_SCALE_STEP),PRICE_SCALE_MIN,PRICE_SCALE_MAX)}else{appState.visibleCount=clamp(Math.round(appState.visibleCount*(e.deltaY>0?1.18:0.84)),20,650)}drawChart()}
function onDoubleClick(e){const pos=pointFromEvent(e),m=chartMetrics();if(pos.x>=m.yAxis.x){appState.priceScale=1;toast('Trục Y: Auto-fit.')}else if(pos.y>=m.xAxis.y){appState.visibleCount=120;appState.scrollOffset=0;toast('Trục X: mặc định.')}drawChart()}

function renderWatchlist(){const syms=EXCHANGE_SYMBOLS[appState.exchange]||[];dom.watchlist.innerHTML=syms.map(s=>{const st=appState.market.stocks[s],ch=appState.market.dayChangePct(s);return`<div class="watch-row ${s===appState.selected?'active':''}" data-symbol="${s}"><b>${s}</b><span class="sector">${st.sector}</span><span>${fmtPrice(st.price)}</span><span class="${ch>=0?'pos':'neg'}">${pct(ch)}</span></div>`}).join('')}
function renderHeader(){const st=appState.market.stocks[appState.selected],ch=appState.market.dayChangePct(appState.selected);dom.symbolTitle.textContent=`${appState.selected} ${SYMBOL_EXCHANGE[appState.selected]} ${appState.timeframe}`;dom.quoteTop.innerHTML=`<b>${fmtPrice(st.price)}</b> <span class="${ch>=0?'pos':'neg'}">${pct(ch)}</span>`;dom.gameClock.textContent=`${formatDate(appState.market.now,true)} · ${appState.paused?'DỪNG':`x${appState.speed}`}`;dom.pauseBtn.textContent=appState.paused?'▶ Chạy':'⏸ Dừng';dom.orderSymbol.textContent=appState.selected}
function renderTradePanel(){dom.price.disabled=appState.orderType==='MARKET';dom.price.placeholder=appState.orderType==='MARKET'?'Theo TT':'Nhập giá';dom.levOut.textContent=`${Math.round(appState.leverage*100)}% x${appState.leverage.toFixed(1)}`;const qty=Math.floor((Number(dom.qty.value)||0)/LOT_SIZE)*LOT_SIZE,cur=appState.market.stocks[appState.selected].price,px=appState.orderType==='MARKET'?cur:(Number(dom.price.value)||cur),value=qty*px,margin=value/appState.leverage,fee=value*(FEE_RATE+(appState.side==='SELL'?SELL_TAX_RATE:0));dom.estimate.innerHTML=`Giá trị vị thế: <b>${fmtMoney(value)}</b><br>Ký quỹ cần ~ <b>${fmtMoney(margin)}</b> · Phí mở ~ ${fmtMoney(fee)}`;dom.submit.textContent=`MỞ ${appState.side==='BUY'?'LONG':'SHORT'} - ${appState.orderType}`;dom.submit.style.borderColor=appState.side==='BUY'?COLORS.green:COLORS.red}
function renderPortfolio(){const entries=Object.entries(appState.player.positions);dom.portfolioTab.innerHTML=entries.length?`<div class="portfolio-list">${entries.map(([s,p])=>{const px=appState.market.stocks[s].price,gross=p.side==='LONG'?(px-p.avgCost)*p.qty:(p.avgCost-px)*p.qty,lev=appState.player.effectiveLeverage(p);return`<div class="portfolio-item" data-symbol="${s}"><div class="row"><b>${s} · ${p.side}</b><span class="${gross>=0?'pos':'neg'}">${fmtMoney(gross)}</span></div><div class="row"><span>${p.qty} cp · vốn ${fmtPrice(p.avgCost)}</span><span>x${lev.toFixed(1)}</span></div><div class="row"><span>SL ${p.stopLoss?fmtPrice(p.stopLoss):'-'}</span><span>TP ${p.takeProfit?fmtPrice(p.takeProfit):'-'}</span></div></div>`}).join('')}</div>`:'<div class="muted-copy">Chưa có vị thế.</div>'}
function renderMissionSide(){const m=appState.missions.current();if(!m){dom.missionTab.innerHTML='<div class="mission-side"><h3>Đã hoàn tất hướng dẫn</h3><p>Từ đây anh tự do thử chiến lược, quản trị vốn và đọc thị trường.</p></div>';return}const v=appState.missions.value(appState.market,appState.player,appState,m),ratio=clamp(v/m.target,0,1);dom.missionTab.innerHTML=`<div class="mission-side"><p>Nhiệm vụ ${appState.missions.index+1}/${appState.missions.missions.length}</p><h3>${m.title}</h3><p>${m.desc}</p><div class="progress-track"><div class="progress-bar" style="width:${ratio*100}%"></div></div><p>${m.kind==='pnl'||m.kind==='equity'?fmtMoney(v):Math.floor(v)} / ${m.kind==='pnl'||m.kind==='equity'?fmtMoney(m.target):m.target}</p></div>`}
function renderAccount(){const eq=appState.player.equity(appState.market),net=appState.player.netPnl(appState.market),unr=appState.player.unrealizedPnl(appState.market,true);dom.account.innerHTML=`<span>Tiền mặt</span><strong>${fmtMoney(appState.player.cash)}</strong><span>Equity</span><strong>${fmtMoney(eq)}</strong><span>NET P/L</span><strong class="${net>=0?'pos':'neg'}">${fmtMoney(net)}</strong><span>Đã chốt</span><strong class="${appState.player.realizedPnl>=0?'pos':'neg'}">${fmtMoney(appState.player.realizedPnl)}</strong><span>Đang mở</span><strong class="${unr>=0?'pos':'neg'}">${fmtMoney(unr)}</strong><span>Max DD</span><strong>${(appState.player.maxDrawdown*100).toFixed(1)}%</strong>`;const book=appState.market.orderBook(appState.selected,5);dom.book.innerHTML=[...book.asks].reverse().map((x,i)=>`<div class="book-row ask"><span>A${5-i}</span><span>${fmtPrice(x[0])}</span><span>${fmtMoney(x[1])}</span></div>`).join('')+`<div class="book-row"><b>LAST</b><b>${fmtPrice(appState.market.stocks[appState.selected].price)}</b><span></span></div>`+book.bids.map((x,i)=>`<div class="book-row bid"><span>B${i+1}</span><span>${fmtPrice(x[0])}</span><span>${fmtMoney(x[1])}</span></div>`).join('')}
function renderBottom(){const net=appState.player.netPnl(appState.market),unr=appState.player.unrealizedPnl(appState.market,true);dom.bottomSummary.innerHTML=`NET <span class="${net>=0?'pos':'neg'}">${fmtMoney(net)}</span> · Đã chốt ${fmtMoney(appState.player.realizedPnl)} · Đang mở ${fmtMoney(unr)}`;if(appState.bottomTab==='NEWS'){dom.bottom.innerHTML=appState.market.news.length?appState.market.news.slice(0,80).map(n=>`<div class="news-row"><span>${formatDate(n.ts,true)}</span><span class="scope">${n.scope}</span><span>${n.title}</span><span class="mag">${n.magnitude}</span></div>`).join(''):'<div class="muted-copy">Chưa có tin mới.</div>';return}if(appState.bottomTab==='ORDERS'){const rows=[...appState.player.orders].reverse().slice(0,160);dom.bottom.innerHTML=`<table class="data-table"><thead><tr><th>ID</th><th>Thời gian</th><th>Mã</th><th>Lệnh</th><th>KL</th><th>Giá</th><th>NET P/L</th><th>% KQ</th><th>Trạng thái</th><th class="action-cell">X</th></tr></thead><tbody>${rows.map(o=>{const[p,pr,state]=appState.player.orderPnlSnapshot(appState.market,o),action=o.status==='OPEN'||o.status==='PARTIAL'?`<button class="x-action" data-cancel="${o.oid}">×</button>`:(o.intent==='OPEN'&&state==='LIVE'?`<button class="x-action" data-close-symbol="${o.symbol}">×</button>`:'');return`<tr><td>#${o.oid}</td><td>${formatDate(o.ts,true)}</td><td>${o.symbol}</td><td>${o.intent==='CLOSE'?o.orderType:`${o.side}/${o.orderType} ${o.positionSide}`}</td><td>${o.filledQty}/${o.qty}</td><td>${o.avgFill?fmtPrice(o.avgFill):(o.limitPrice?fmtPrice(o.limitPrice):'-')}</td><td class="${p!=null?(p>=0?'pos':'neg'):''}">${p==null?'-':fmtMoney(p)}</td><td class="${pr!=null?(pr>=0?'pos':'neg'):''}">${pr==null?'-':pct(pr)}</td><td>${o.status}</td><td>${action}</td></tr>`}).join('')}</tbody></table>`;return}if(appState.bottomTab==='TRADES'){dom.bottom.innerHTML=`<table class="data-table"><thead><tr><th>Thời gian</th><th>Mã</th><th>Hành động</th><th>KL</th><th>Giá</th><th>Phí</th><th>P/L</th></tr></thead><tbody>${appState.player.trades.slice(0,180).map(t=>`<tr><td>${formatDate(t.ts,true)}</td><td>${t.symbol}</td><td>${t.action}</td><td>${t.qty}</td><td>${fmtPrice(t.price)}</td><td>${fmtMoney(t.fee||0)}</td><td class="${t.pnl!=null?(t.pnl>=0?'pos':'neg'):''}">${t.pnl==null?'-':fmtMoney(t.pnl)}</td></tr>`).join('')}</tbody></table>`;return}const cur=appState.missions.current();dom.bottom.innerHTML=`<div class="mission-side"><h3>${cur?cur.title:'Đã hoàn tất hướng dẫn'}</h3><p>${cur?cur.desc:'Tiếp tục khám phá thị trường, chart và quản trị vốn.'}</p><p>Hoàn thành ${appState.missions.index}/${appState.missions.missions.length} nhiệm vụ.</p></div>`}
function renderAll(force=false){if(!appState.market)return;appState.missions.update(appState.market,appState.player,appState);renderHeader();renderWatchlist();renderTradePanel();renderPortfolio();renderMissionSide();renderAccount();renderBottom();drawChart()}

function selectSymbol(s){if(!appState.market.stocks[s])return;appState.selected=s;appState.exchange=SYMBOL_EXCHANGE[s]||appState.exchange;appState.scrollOffset=0;appState.missions.markView(s);renderAll(true)}
function syncControls(){$$('[data-timeframe]').forEach(b=>b.classList.toggle('active',b.dataset.timeframe===appState.timeframe));$$('[data-chart-mode]').forEach(b=>b.classList.toggle('active',b.dataset.chartMode===appState.chartMode));$$('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===appState.speed));$$('[data-exchange]').forEach(b=>b.classList.toggle('active',b.dataset.exchange===appState.exchange));$$('[data-order-type]').forEach(b=>b.classList.toggle('active',b.dataset.orderType===appState.orderType));$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===appState.tool));dom.buy.classList.toggle('active',appState.side==='BUY');dom.sell.classList.toggle('active',appState.side==='SELL');$$('[data-side-tab]').forEach(b=>b.classList.toggle('active',b.dataset.sideTab===appState.sideTab));dom.tradeTab.hidden=appState.sideTab!=='TRADE';dom.portfolioTab.hidden=appState.sideTab!=='PORTFOLIO';dom.missionTab.hidden=appState.sideTab!=='MISSION';$$('[data-bottom-tab]').forEach(b=>b.classList.toggle('active',b.dataset.bottomTab===appState.bottomTab));renderTradePanel()}

function bindUI(){
  dom.canvas.addEventListener('pointerdown',onPointerDown);dom.canvas.addEventListener('pointermove',onPointerMove);dom.canvas.addEventListener('pointerup',onPointerUp);dom.canvas.addEventListener('pointercancel',onPointerUp);dom.canvas.addEventListener('pointerleave',()=>{appState.mouse=null;if(!appState.pan&&!appState.axisDrag&&!appState.lineDrag){dom.tooltip.hidden=true;drawChart()}});dom.canvas.addEventListener('wheel',onWheel,{passive:false});dom.canvas.addEventListener('dblclick',onDoubleClick);dom.canvas.addEventListener('contextmenu',e=>{e.preventDefault();openContext(pointFromEvent(e))});
  dom.context.addEventListener('click',e=>{const b=e.target.closest('[data-menu-index]');if(!b||b.disabled)return;const it=dom.context._items?.[Number(b.dataset.menuIndex)];it?.fn?.()});document.addEventListener('pointerdown',e=>{if(!dom.context.hidden&&!dom.context.contains(e.target)&&e.target!==dom.canvas)dom.context.hidden=true});
  dom.watchlist.addEventListener('click',e=>{const r=e.target.closest('[data-symbol]');if(r)selectSymbol(r.dataset.symbol)});dom.portfolioTab.addEventListener('click',e=>{const r=e.target.closest('[data-symbol]');if(r)selectSymbol(r.dataset.symbol)});
  $$('[data-exchange]').forEach(b=>b.onclick=()=>{appState.exchange=b.dataset.exchange;syncControls();renderWatchlist()});$$('[data-timeframe]').forEach(b=>b.onclick=()=>{appState.timeframe=b.dataset.timeframe;appState.scrollOffset=0;syncControls();renderAll(true)});$$('[data-chart-mode]').forEach(b=>b.onclick=()=>{appState.chartMode=b.dataset.chartMode;syncControls();drawChart()});$$('[data-speed]').forEach(b=>b.onclick=()=>{appState.speed=Number(b.dataset.speed);appState.paused=false;syncControls();renderHeader()});
  dom.pauseBtn.onclick=()=>{appState.paused=!appState.paused;renderHeader()};dom.saveBtn.onclick=()=>saveGame(false);dom.backBtn.onclick=()=>{saveGame(true);if(window.parent!==window)window.parent.postMessage({type:'stocksim-close'},'*');else location.href='../index.html'};
  dom.buy.onclick=()=>{appState.side='BUY';syncControls()};dom.sell.onclick=()=>{appState.side='SELL';syncControls()};$$('[data-order-type]').forEach(b=>b.onclick=()=>{appState.orderType=b.dataset.orderType;syncControls()});dom.qty.oninput=renderTradePanel;dom.price.oninput=renderTradePanel;dom.levDown.onclick=()=>{appState.leverage=clamp(appState.leverage-LEVERAGE_STEP,LEVERAGE_MIN,LEVERAGE_MAX);renderTradePanel()};dom.levUp.onclick=()=>{appState.leverage=clamp(appState.leverage+LEVERAGE_STEP,LEVERAGE_MIN,LEVERAGE_MAX);renderTradePanel()};dom.submit.onclick=()=>{const qty=Number(dom.qty.value),price=appState.orderType==='MARKET'?0:Number(dom.price.value),[ok,msg]=appState.player.placeOrder(appState.market,appState.selected,appState.side,appState.orderType,qty,price,appState.leverage);toast(msg,ok?'success':'error');renderAll(true);if(ok)saveGame(true)};
  $$('[data-side-tab]').forEach(b=>b.onclick=()=>{appState.sideTab=b.dataset.sideTab;syncControls();renderAll(true)});$$('[data-bottom-tab]').forEach(b=>b.onclick=()=>{appState.bottomTab=b.dataset.bottomTab;syncControls();renderBottom()});dom.bottom.addEventListener('click',e=>{const c=e.target.closest('[data-cancel]');if(c){if(appState.player.cancelOrder(Number(c.dataset.cancel)))toast('Đã hủy phần lệnh đang chờ.','success');renderAll(true);saveGame(true);return}const x=e.target.closest('[data-close-symbol]');if(x)closePosition(x.dataset.closeSymbol)});
  $$('[data-tool]').forEach(b=>b.onclick=()=>{appState.tool=b.dataset.tool;syncControls()});$('#zoomXInBtn').onclick=()=>{appState.visibleCount=clamp(Math.round(appState.visibleCount*.8),20,650);drawChart()};$('#zoomXOutBtn').onclick=()=>{appState.visibleCount=clamp(Math.round(appState.visibleCount*1.25),20,650);drawChart()};$('#zoomYInBtn').onclick=()=>{appState.priceScale=clamp(appState.priceScale/PRICE_SCALE_STEP,1,30);drawChart()};$('#zoomYOutBtn').onclick=()=>{appState.priceScale=clamp(appState.priceScale*PRICE_SCALE_STEP,1,30);drawChart()};$('#resetViewBtn').onclick=()=>{appState.visibleCount=120;appState.scrollOffset=0;appState.priceScale=1;drawChart()};$('#undoBtn').onclick=()=>{undoDrawing();drawChart()};$('#redoBtn').onclick=()=>{redoDrawing();drawChart()};$('#deleteDrawingBtn').onclick=()=>{const d=appState.drawings.pop();if(d){appState.redo.push(d);toast('Đã xóa hình vẽ cuối.');drawChart()}};
  dom.restart.onclick=()=>openNewGame(true);$('#randomSeedBtn').onclick=()=>dom.seed.value=randomSeed();$$('[data-difficulty]').forEach(b=>b.onclick=()=>{$$('[data-difficulty]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});dom.startNewGame.onclick=async()=>{const diff=$('[data-difficulty].active')?.dataset.difficulty||'MEDIUM',seed=Number(dom.seed.value)||randomSeed();await appState.db.clear();await startNewGame(diff,seed)};dom.cancelNewGame.onclick=()=>{if(appState.market)dom.newGame.hidden=true};
  window.addEventListener('resize',()=>drawChart());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveGame(true)});window.addEventListener('beforeunload',()=>saveGame(true));document.addEventListener('keydown',e=>{const edit=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(edit)return;if(e.key==='Escape'){if(appState.lineDrag){appState.paused=appState.lineDrag.wasPaused;appState.lineDrag=null;dom.chartShell.classList.remove('dragging-line');drawChart();return}dom.context.hidden=true;appState.draft=null;drawChart();return}if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redoDrawing():undoDrawing();drawChart();return}if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redoDrawing();drawChart();return}if(e.code==='Space'){e.preventDefault();appState.paused=!appState.paused;renderHeader();return}if(e.key==='+'||e.key==='='){if(e.ctrlKey)appState.priceScale=clamp(appState.priceScale/PRICE_SCALE_STEP,1,30);else appState.visibleCount=clamp(Math.round(appState.visibleCount*.8),20,650);drawChart()}if(e.key==='-'){if(e.ctrlKey)appState.priceScale=clamp(appState.priceScale*PRICE_SCALE_STEP,1,30);else appState.visibleCount=clamp(Math.round(appState.visibleCount*1.25),20,650);drawChart()}if(e.key==='Home'){appState.visibleCount=120;appState.scrollOffset=0;appState.priceScale=1;drawChart()}const km={v:'CURSOR',t:'TREND',h:'HLINE',r:'RECT',f:'FIB'};if(km[e.key.toLowerCase()]){appState.tool=km[e.key.toLowerCase()];syncControls()}})
}
function openNewGame(restart=false){dom.newGame.hidden=false;dom.cancelNewGame.hidden=!appState.market;dom.seed.value='';if(restart)toast('Chọn mức vốn và seed để tạo thị trường mới.','info')}

async function boot(){
  bindUI();try{await appState.db.open()}catch(e){console.warn('IndexedDB unavailable',e)}showLoading(true,'Đang khởi động StockSim VN Web','Đang đọc save trên máy này…',.08);let data=null;try{data=await appState.db.get()}catch(e){console.warn(e)}if(data&&restore(data)){showLoading(false);appState.missions.markView(appState.selected);syncControls();renderAll(true);toast(`Đã tải save · Seed ${appState.seed}`,'success')}else{showLoading(false);openNewGame(false)}dom.app.setAttribute('aria-busy','false');requestAnimationFrame(loop)
}
function loop(t){if(appState.market){let dt=Math.min(.12,(t-(appState.lastRender||t))/1000);appState.lastRender=t;if(!appState.paused&&!appState.lineDrag){appState.simCarry+=dt*BASE_SIM_MPS*appState.speed;let steps=Math.min(120,Math.floor(appState.simCarry));if(steps>0)appState.simCarry-=steps;for(let i=0;i<steps;i++){appState.market.stepMinute(true);appState.player.processPending(appState.market);appState.player.processExitTriggers(appState.market);for(const msg of appState.player.processMarginCalls(appState.market))toast(msg,'error')}}if(t-appState.lastUi>180){appState.lastUi=t;renderAll()}if(t-appState.lastSave>60_000)saveGame(true)}requestAnimationFrame(loop)}

boot().catch(err=>{console.error(err);showLoading(true,'StockSim VN gặp lỗi',String(err?.stack||err),1)});
