import {TAROT_CARDS,SPREADS,TOPICS} from './tarot-data.js';
const $=s=>document.querySelector(s);
const refs={topic:$('#topicSelect'),question:$('#questionInput'),count:$('#cardCountSelect'),start:$('#startBtn'),reset:$('#resetBtn'),intro:$('#introView'),deck:$('#deckView'),result:$('#resultView'),deckGrid:$('#deckGrid'),pickTitle:$('#pickTitle'),pickCounter:$('#pickCounter'),reveal:$('#revealBtn'),title:$('#readingTitle'),summary:$('#summaryText'),action:$('#actionText'),cards:$('#cardsResult'),copy:$('#copyBtn'),download:$('#downloadBtn'),history:$('#historyList'),clearHistory:$('#clearHistoryBtn'),fullscreen:$('#fullscreenBtn'),close:$('#closeBtn'),toast:$('#toast')};
const HISTORY_KEY='linh_tarot_history_v1';
let deck=[],selected=[],currentReading=null,history=load(HISTORY_KEY,[]),toastTimer=null;
init();
function init(){bind();renderHistory()}
function bind(){refs.start.onclick=startReading;refs.reset.onclick=resetReading;refs.reveal.onclick=revealSelected;refs.copy.onclick=copyReading;refs.download.onclick=downloadReading;refs.clearHistory.onclick=()=>{history=[];save(HISTORY_KEY,history);renderHistory();showToast('Đã xóa lịch sử.')};refs.fullscreen.onclick=toggleFullscreen;refs.close.onclick=closeTarot}
function startReading(){const count=+refs.count.value;deck=shuffle(TAROT_CARDS.map(card=>({...card,reversed:randomInt(0,99)<32})));selected=[];const method=document.querySelector('input[name="method"]:checked')?.value||'manual';if(method==='auto'){selected=deck.slice(0,count);createReading(selected);return}show(refs.deck);refs.pickTitle.textContent=`Chọn ${count} lá theo cảm nhận`;refs.pickCounter.textContent=`0/${count}`;refs.reveal.disabled=true;refs.deckGrid.innerHTML=deck.map((card,index)=>`<button class="card-back" type="button" data-index="${index}" aria-label="Lá bài úp số ${index+1}"></button>`).join('');refs.deckGrid.querySelectorAll('.card-back').forEach(btn=>btn.onclick=()=>toggleCard(btn,count))}
function toggleCard(btn,count){const index=+btn.dataset.index;const found=selected.findIndex(x=>x._deckIndex===index);if(found>=0){selected.splice(found,1);btn.classList.remove('selected')}else{if(selected.length>=count){showToast(`Chỉ chọn ${count} lá.`);return}selected.push({...deck[index],_deckIndex:index});btn.classList.add('selected')}refs.pickCounter.textContent=`${selected.length}/${count}`;refs.reveal.disabled=selected.length!==count}
function revealSelected(){if(selected.length!==+refs.count.value)return;createReading(selected)}
function createReading(cards){const count=cards.length,positions=SPREADS[count]||Array.from({length:count},(_,i)=>`Lá ${i+1}`),topic=refs.topic.value,question=refs.question.value.trim();const placed=cards.map((c,i)=>({...c,position:positions[i]}));const reading=interpret(placed,topic,question);currentReading={id:Date.now(),createdAt:new Date().toISOString(),topic,question,count,cards:placed.map(c=>({id:c.id,reversed:c.reversed,position:c.position})),summary:reading.summary,action:reading.action};renderReading(currentReading);history.unshift(currentReading);history=history.slice(0,30);save(HISTORY_KEY,history);renderHistory()}
function interpret(cards,topic,question){const majors=cards.filter(c=>c.arcana==='major').length,upright=cards.filter(c=>!c.reversed).length,first=cards[0],last=cards[cards.length-1];const tone=upright>=Math.ceil(cards.length/2)?'Trải bài nghiêng về khả năng chủ động và mở ra hướng xử lý.':'Trải bài nhấn mạnh việc chậm lại, kiểm tra điểm mù và điều chỉnh trước khi tiến tiếp.';const majorText=majors?`${majors} lá Ẩn Chính cho thấy vấn đề này có ý nghĩa lớn hơn một tình huống nhất thời.`:'Các lá Ẩn Phụ cho thấy trọng tâm nằm ở lựa chọn và hành động thực tế hằng ngày.';const q=question?`Với câu hỏi “${question}”, `:'';const summary=`${q}${first.nameVi} mở ra chủ đề về ${first.keywords.slice(0,2).join(' và ')}. ${majorText} ${tone} Lá cuối ${last.nameVi} gợi ý hướng kết lại bằng việc ${lowerFirst(last.advice)}`;const actionItems=cards.slice(-Math.min(3,cards.length)).map(c=>c.advice.replace(/[.]$/,'')).filter((x,i,a)=>a.indexOf(x)===i);return{summary,action:`Gợi ý thực tế: ${actionItems.join(' • ')}.`}}
function renderReading(reading){show(refs.result);const cards=reading.cards.map(saved=>{const base=TAROT_CARDS.find(c=>c.id===saved.id);return {...base,reversed:saved.reversed,position:saved.position}});refs.title.textContent=reading.question?`Chủ đề: ${TOPICS[reading.topic]}`:`Thông điệp ${TOPICS[reading.topic].toLowerCase()}`;refs.summary.textContent=reading.summary;refs.action.textContent=reading.action;refs.cards.innerHTML=cards.map((card,index)=>`<article class="reading-card"><div class="card-image-wrap"><img class="card-image ${card.reversed?'reversed':''}" src="assets/cards/${card.img}" alt="${escAttr(card.nameVi)}" loading="lazy"></div><div class="card-copy"><span class="position">${esc(card.position)}</span><h3>${esc(card.nameVi)}</h3><div class="orientation">${card.reversed?'Lá ngược':'Lá xuôi'}</div><div class="keywords">${card.keywords.map(k=>`<span>${esc(k)}</span>`).join('')}</div><p>${esc(card.reversed?card.reversed:card.upright)}</p><p>${esc(topicInsight(card,reading.topic,index,cards.length))}</p><div class="advice"><strong>Lời gợi ý:</strong> ${esc(card.advice)}</div></div></article>`).join('')}
function topicInsight(card,topic,index,total){const pos=card.position.toLowerCase();const suitText={major:'Đây là một thông điệp có tính định hướng và nên được nhìn trong bức tranh lớn.',c:'Trong chủ đề này, cảm xúc và chất lượng kết nối là biến số quan trọng.',p:'Hãy nhìn vào nguồn lực, thời gian, tiền bạc và khả năng thực hiện.',s:'Giao tiếp rõ và kiểm tra giả định sẽ giúp giảm sai lệch.',w:'Động lực cần được chuyển thành hành động cụ thể thay vì chỉ là ý định.'}[card.suit]||'';const topicText={general:'Hãy xem lá này như một góc nhìn bổ sung cho tình hình hiện tại.',love:'Trong tình cảm, sự chân thành cần đi cùng ranh giới và khả năng lắng nghe.',work:'Trong công việc, nên làm rõ mục tiêu, vai trò và tiêu chuẩn kết quả.',finance:'Với tài chính, ưu tiên an toàn, số liệu và khả năng chịu rủi ro.',family:'Trong gia đình, cách giao tiếp và sự công bằng giữa các bên rất quan trọng.',mind:'Về tinh thần, nên phân biệt cảm xúc tức thời với nhu cầu sâu hơn.',decision:'Với quyết định này, hãy so sánh hệ quả ngắn hạn và dài hạn.'}[topic];return `${topicText} ${suitText}`}
function resetReading(){selected=[];deck=[];currentReading=null;refs.question.value='';show(refs.intro)}
function show(target){[refs.intro,refs.deck,refs.result].forEach(el=>el.hidden=el!==target);target.scrollIntoView({behavior:'smooth',block:'start'})}
function renderHistory(){if(!history.length){refs.history.innerHTML='<span>Chưa có trải bài.</span>';return}refs.history.innerHTML=history.slice(0,12).map((item,index)=>`<button class="history-item" type="button" data-index="${index}"><span>${formatDate(item.createdAt)} · ${item.count} lá</span><strong>${esc(TOPICS[item.topic]||'Tổng quan')}</strong><small>${esc(item.question||item.summary.slice(0,65)+'…')}</small></button>`).join('');refs.history.querySelectorAll('.history-item').forEach(btn=>btn.onclick=()=>{currentReading=history[+btn.dataset.index];refs.topic.value=currentReading.topic;refs.question.value=currentReading.question||'';refs.count.value=String(currentReading.count);renderReading(currentReading)})}
async function copyReading(){if(!currentReading)return;await navigator.clipboard.writeText(readingText(currentReading));showToast('Đã sao chép nội dung.')}
function downloadReading(){if(!currentReading)return;const blob=new Blob([readingText(currentReading)],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Tarot_${new Date(currentReading.createdAt).toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function readingText(r){const lines=[`TAROT VIỆT – ${TOPICS[r.topic]}`,r.question?`Câu hỏi: ${r.question}`:'',`Thời gian: ${formatDate(r.createdAt)}`,'',r.summary,'',r.action,''];r.cards.forEach((saved,i)=>{const c=TAROT_CARDS.find(x=>x.id===saved.id);lines.push(`${i+1}. ${saved.position}: ${c.nameVi} – ${saved.reversed?'Lá ngược':'Lá xuôi'}`,saved.reversed?c.reversed:c.upright,`Gợi ý: ${c.advice}`,'')});lines.push('Kết quả mang tính gợi mở và giải trí.');return lines.filter((x,i)=>x!==''||lines[i-1]!=='').join('\n')}
function shuffle(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=randomInt(0,i);[out[i],out[j]]=[out[j],out[i]]}return out}
function randomInt(min,max){const a=new Uint32Array(1);crypto.getRandomValues(a);return min+(a[0]%(max-min+1))}
function formatDate(v){return new Date(v).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function lowerFirst(s){return s?s.charAt(0).toLowerCase()+s.slice(1):''}
async function toggleFullscreen(){if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.()}
function closeTarot(){if(parent!==window)parent.postMessage({type:'tarot-game-close'},'*');else location.href='../index.html'}
function load(k,f){try{const v=JSON.parse(localStorage.getItem(k));return Array.isArray(v)?v:f}catch{return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function showToast(s){clearTimeout(toastTimer);refs.toast.textContent=s;refs.toast.classList.add('show');toastTimer=setTimeout(()=>refs.toast.classList.remove('show'),2300)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c])}
function escAttr(v){return esc(v).replace(/`/g,'&#96;')}
