const majors=[
['m00.jpg','The Fool','Kẻ Khờ',['khởi đầu','tự do','niềm tin'],'Một hành trình mới đang mở ra. Hãy cho mình quyền thử nghiệm, nhưng vẫn giữ một điểm tựa thực tế.','Sự vội vàng hoặc ngây thơ có thể khiến bạn bỏ qua tín hiệu cảnh báo.','Bước nhỏ trước, kiểm chứng sau, rồi mới cam kết lớn.'],
['m01.jpg','The Magician','Nhà Ảo Thuật',['năng lực','chủ động','tập trung'],'Bạn đang có đủ công cụ để biến ý tưởng thành hành động. Điều quan trọng là tập trung và dùng đúng thế mạnh.','Năng lực đang bị phân tán, hoặc có nguy cơ dùng sự khéo léo để né tránh vấn đề cốt lõi.','Chọn một mục tiêu rõ và bắt đầu bằng nguồn lực đang có.'],
['m02.jpg','The High Priestess','Nữ Tư Tế',['trực giác','quan sát','bí mật'],'Có những điều chưa cần hành động ngay. Quan sát kỹ và tin vào cảm nhận đã được kiểm chứng.','Bạn có thể đang bỏ qua trực giác hoặc bị cuốn vào suy đoán thiếu căn cứ.','Tạm lùi một bước, thu thập thêm dữ kiện rồi quyết định.'],
['m03.jpg','The Empress','Hoàng Hậu',['nuôi dưỡng','sáng tạo','sung túc'],'Năng lượng phát triển và chăm sóc đang mạnh. Điều bạn vun bồi đúng cách có khả năng sinh kết quả tốt.','Sự nuông chiều, phụ thuộc hoặc chăm sóc quá mức có thể làm giảm tính chủ động.','Nuôi dưỡng điều quan trọng nhưng vẫn giữ ranh giới.'],
['m04.jpg','The Emperor','Hoàng Đế',['kỷ luật','cấu trúc','quyền hạn'],'Cần một cấu trúc rõ ràng, nguyên tắc nhất quán và trách nhiệm cụ thể.','Sự cứng nhắc hoặc kiểm soát quá mức đang tạo áp lực không cần thiết.','Đặt luật chơi đơn giản, công khai và có thể thực hiện.'],
['m05.jpg','The Hierophant','Giáo Hoàng',['truyền thống','học hỏi','chuẩn mực'],'Kinh nghiệm, quy trình hoặc lời khuyên từ người đáng tin có thể giúp bạn tránh sai lầm.','Một khuôn mẫu cũ có thể không còn phù hợp; đừng tuân theo chỉ vì thói quen.','Hiểu nguyên tắc trước khi quyết định giữ hay đổi cách làm.'],
['m06.jpg','The Lovers','Những Người Yêu',['lựa chọn','kết nối','giá trị'],'Một lựa chọn quan trọng cần phù hợp với giá trị cốt lõi và sự đồng thuận thật sự.','Sự lệch giá trị, thiếu cam kết hoặc né tránh lựa chọn đang làm tình hình kéo dài.','Nói rõ điều bạn thực sự coi trọng.'],
['m07.jpg','The Chariot','Cỗ Xe',['ý chí','tiến lên','kiểm soát'],'Động lực đang mạnh; khi mục tiêu và kỷ luật cùng hướng, bạn có thể tiến rất nhanh.','Hấp tấp, tranh quyền hoặc thiếu định hướng có thể khiến năng lượng bị lãng phí.','Chọn hướng đi, đặt giới hạn và giữ nhịp ổn định.'],
['m08.jpg','Strength','Sức Mạnh',['kiên nhẫn','can đảm','tự chủ'],'Sức mạnh phù hợp lúc này là sự bình tĩnh, kiên trì và khả năng điều hòa cảm xúc.','Bạn có thể đang nghi ngờ bản thân hoặc cố dùng sức ép để xử lý điều cần sự mềm dẻo.','Kiên định nhưng không đối đầu vô ích.'],
['m09.jpg','The Hermit','Ẩn Sĩ',['chiêm nghiệm','tìm hiểu','độc lập'],'Khoảng lặng sẽ giúp bạn nhìn thấy điều tiếng ồn bên ngoài đang che khuất.','Cô lập quá lâu hoặc phân tích quá mức có thể làm bạn mất kết nối với thực tế.','Dành thời gian suy nghĩ, sau đó quay lại kiểm chứng với đời sống thật.'],
['m10.jpg','Wheel of Fortune','Bánh Xe Số Phận',['chu kỳ','thay đổi','cơ hội'],'Một chu kỳ đang chuyển. Sự linh hoạt giúp bạn tận dụng thời điểm tốt hơn.','Bạn có thể đang chống lại thay đổi hoặc lặp lại một mô thức chưa được nhận diện.','Xem điều gì đang đổi và điều gì vẫn nằm trong quyền kiểm soát.'],
['m11.jpg','Justice','Công Lý',['cân bằng','sự thật','trách nhiệm'],'Quyết định tốt cần dựa trên dữ kiện, sự công bằng và trách nhiệm với hậu quả.','Thiên kiến, thiếu thông tin hoặc né trách nhiệm có thể làm kết luận sai lệch.','Kiểm tra bằng chứng và áp cùng một tiêu chuẩn cho mọi bên.'],
['m12.jpg','The Hanged Man','Người Treo Ngược',['tạm dừng','góc nhìn mới','buông bỏ'],'Tạm dừng không phải thất bại. Một góc nhìn khác có thể mở ra lời giải đơn giản hơn.','Sự trì hoãn hoặc hy sinh vô ích đang tiêu hao năng lượng.','Đổi góc nhìn, nhưng đặt thời hạn cho việc chờ đợi.'],
['m13.jpg','Death','Cái Chết',['kết thúc','chuyển hóa','tái sinh'],'Một giai đoạn cần kết thúc để tạo không gian cho điều phù hợp hơn.','Bám giữ điều đã hết vai trò khiến quá trình chuyển đổi khó khăn hơn.','Chủ động khép lại phần đã hoàn thành.'],
['m14.jpg','Temperance','Tiết Chế',['điều độ','hòa hợp','chữa lành'],'Sự kết hợp vừa đủ, nhịp độ bền vững và khả năng điều chỉnh sẽ đem lại kết quả tốt.','Mất cân bằng hoặc cực đoan đang khiến hệ thống khó vận hành.','Giảm cường độ và tìm tỷ lệ hợp lý.'],
['m15.jpg','The Devil','Ác Quỷ',['ràng buộc','ham muốn','ảo tưởng'],'Một ràng buộc, thói quen hoặc lợi ích ngắn hạn đang có sức ảnh hưởng lớn hơn bạn nghĩ.','Bạn bắt đầu nhận ra xiềng xích và có khả năng thoát khỏi nó.','Gọi đúng tên điều đang kiểm soát bạn và cắt một mắt xích nhỏ trước.'],
['m16.jpg','The Tower','Tòa Tháp',['đột biến','sự thật','phá vỡ'],'Một cấu trúc thiếu vững chắc có thể bị buộc phải thay đổi. Sự thật dù khó chịu vẫn giúp tái thiết đúng hơn.','Bạn đang trì hoãn thay đổi cần thiết hoặc sợ mất kiểm soát.','Bảo vệ phần cốt lõi, chấp nhận bỏ phần không còn bền.'],
['m17.jpg','The Star','Ngôi Sao',['hy vọng','hồi phục','định hướng'],'Có tín hiệu tích cực cho sự hồi phục và định hướng dài hạn, đặc biệt khi bạn giữ sự chân thành.','Mất niềm tin hoặc kỳ vọng thiếu thực tế có thể làm bạn hụt năng lượng.','Chọn một hy vọng có thể chuyển thành hành động nhỏ.'],
['m18.jpg','The Moon','Mặt Trăng',['mơ hồ','cảm xúc','tiềm thức'],'Không phải mọi thứ đều rõ. Cảm xúc và nỗi sợ có thể đang nhuộm màu cách bạn nhìn vấn đề.','Sự mơ hồ bắt đầu tan, nhưng vẫn cần kiểm tra thông tin trước khi tin chắc.','Phân biệt cảm giác, giả định và dữ kiện.'],
['m19.jpg','The Sun','Mặt Trời',['rõ ràng','thành công','sinh lực'],'Sự rõ ràng, tinh thần cởi mở và năng lượng tích cực đang hỗ trợ kết quả tốt.','Niềm vui bị che bởi kỳ vọng quá cao hoặc nhu cầu được công nhận.','Đơn giản hóa và tập trung vào điều đang thực sự tiến triển.'],
['m20.jpg','Judgement','Phán Xét',['thức tỉnh','đánh giá','quyết định'],'Đã đến lúc nhìn lại toàn bộ quá trình và đưa ra quyết định dựa trên bài học đã có.','Tự phán xét quá nặng hoặc né việc tổng kết khiến bạn khó bước sang giai đoạn mới.','Đánh giá hành động, không kết tội bản thân.'],
['m21.jpg','The World','Thế Giới',['hoàn tất','tích hợp','thành tựu'],'Một chu kỳ có khả năng hoàn thành trọn vẹn; kết quả đến từ việc kết nối các phần thành một hệ thống.','Còn một mắt xích chưa hoàn thiện hoặc bạn chưa công nhận thành quả đã đạt.','Hoàn tất phần cuối và ghi nhận tiến bộ.']
];
const suits={
 c:{en:'Cups',vi:'Cốc',domain:'cảm xúc, tình cảm và sự kết nối',keywords:['cảm xúc','tình cảm','trực giác'],tone:'Hãy lắng nghe cảm xúc nhưng không để cảm xúc thay thế toàn bộ dữ kiện.'},
 p:{en:'Pentacles',vi:'Tiền',domain:'công việc, tài chính và nền tảng thực tế',keywords:['tài chính','công việc','ổn định'],tone:'Ưu tiên tính khả thi, nguồn lực và kết quả bền vững.'},
 s:{en:'Swords',vi:'Kiếm',domain:'suy nghĩ, giao tiếp và quyết định',keywords:['tư duy','sự thật','quyết định'],tone:'Làm rõ thông tin và tránh phản ứng chỉ dựa trên lo lắng.'},
 w:{en:'Wands',vi:'Gậy',domain:'hành động, sáng tạo và tham vọng',keywords:['hành động','động lực','sáng tạo'],tone:'Chuyển năng lượng thành một bước đi cụ thể, có giới hạn.'}
};
const ranks=[
 {n:1,en:'Ace',vi:'Át',up:'Một cơ hội hoặc khởi đầu mới xuất hiện trong {d}.',rev:'Khởi đầu này có thể bị trì hoãn, thiếu chuẩn bị hoặc chưa đủ rõ trong {d}.',adv:'Xác định bước đầu tiên nhỏ nhất có thể làm ngay.'},
 {n:2,en:'Two',vi:'Hai',up:'Cần cân bằng, lựa chọn hoặc hợp tác trong {d}.',rev:'Sự do dự hoặc mất cân bằng đang làm {d} khó tiến triển.',adv:'Chọn tiêu chí ưu tiên trước khi chọn phương án.'},
 {n:3,en:'Three',vi:'Ba',up:'Sự phối hợp và phát triển đang hình thành trong {d}.',rev:'Năng lượng phân tán hoặc phối hợp chưa tốt đang ảnh hưởng {d}.',adv:'Làm rõ vai trò và kỳ vọng của từng bên.'},
 {n:4,en:'Four',vi:'Bốn',up:'Một nền tảng ổn định đang được củng cố trong {d}.',rev:'Sự trì trệ, giữ chặt hoặc khép kín có thể cản trở {d}.',adv:'Giữ điều cần thiết và nới lỏng phần quá cứng.'},
 {n:5,en:'Five',vi:'Năm',up:'Một thử thách, xung đột hoặc mất mát cần được xử lý trong {d}.',rev:'Giai đoạn khó đang có dấu hiệu hồi phục, nhưng bài học vẫn cần được nhìn nhận.',adv:'Tập trung vào phần còn có thể cứu vãn và điều chỉnh.'},
 {n:6,en:'Six',vi:'Sáu',up:'Sự hỗ trợ, chuyển tiếp hoặc hài hòa đang xuất hiện trong {d}.',rev:'Quá khứ, sự lệ thuộc hoặc trao đổi không cân bằng đang ảnh hưởng {d}.',adv:'Kiểm tra sự cho và nhận có thực sự công bằng không.'},
 {n:7,en:'Seven',vi:'Bảy',up:'Bạn đang ở giai đoạn đánh giá, thử thách hoặc cần chiến lược trong {d}.',rev:'Sự né tránh, bối rối hoặc thiếu kiên nhẫn đang làm giảm hiệu quả.',adv:'Dừng lại để chọn chiến lược thay vì phản ứng theo thói quen.'},
 {n:8,en:'Eight',vi:'Tám',up:'Kỷ luật và chuyển động đều đặn có thể tạo tiến bộ rõ trong {d}.',rev:'Cảm giác bị kẹt hoặc tiến độ chậm cho thấy cách làm cần thay đổi.',adv:'Tách trở ngại thành phần có thể kiểm soát.'},
 {n:9,en:'Nine',vi:'Chín',up:'Bạn đang gần điểm hoàn thiện, cần giữ vững sự độc lập và bền bỉ trong {d}.',rev:'Kiệt sức, lo lắng hoặc quá tải có thể làm bạn đánh giá sai tình hình.',adv:'Bảo vệ năng lượng và bỏ bớt việc không thiết yếu.'},
 {n:10,en:'Ten',vi:'Mười',up:'Một chu kỳ đang đạt mức hoàn tất hoặc tích lũy lớn trong {d}.',rev:'Gánh nặng hoặc một chu kỳ chưa khép lại đang kéo dài.',adv:'Hoàn tất, bàn giao hoặc đóng lại điều đã đủ.'},
 {n:11,en:'Page',vi:'Tiểu Đồng',up:'Một thông tin mới, bài học hoặc sự tò mò đang mở đường trong {d}.',rev:'Sự non nớt hoặc thông tin chưa kiểm chứng có thể gây nhiễu.',adv:'Học và kiểm tra trước khi khẳng định.'},
 {n:12,en:'Knight',vi:'Hiệp Sĩ',up:'Động lực đang thúc đẩy bạn tiến nhanh trong {d}.',rev:'Hấp tấp, thiếu nhất quán hoặc theo đuổi quá mức có thể gây phản tác dụng.',adv:'Giữ tốc độ nhưng đặt điểm kiểm tra giữa đường.'},
 {n:13,en:'Queen',vi:'Nữ Hoàng',up:'Sự trưởng thành, thấu hiểu và khả năng nuôi dưỡng {d} đang là lợi thế.',rev:'Sự nhạy cảm quá mức, kiểm soát hoặc thiếu tự tin đang làm lệch cân bằng.',adv:'Tin vào kinh nghiệm nhưng vẫn lắng nghe phản hồi.'},
 {n:14,en:'King',vi:'Vua',up:'Khả năng lãnh đạo và làm chủ {d} đang được yêu cầu.',rev:'Sự cứng nhắc, lạm quyền hoặc quá tự tin có thể gây hậu quả.',adv:'Dùng quyền quyết định đi cùng trách nhiệm.'}
];
export const TAROT_CARDS=[...majors.map((m,i)=>({id:`M${i}`,img:m[0],nameEn:m[1],nameVi:m[2],arcana:'major',suit:'major',keywords:m[3],upright:m[4],reversed:m[5],advice:m[6]})),...Object.entries(suits).flatMap(([key,s])=>ranks.map(r=>({id:`${key.toUpperCase()}${r.n}`,img:`${key}${String(r.n).padStart(2,'0')}.jpg`,nameEn:`${r.en} of ${s.en}`,nameVi:`${r.vi} ${s.vi}`,arcana:'minor',suit:key,keywords:[...s.keywords,r.vi.toLowerCase()],upright:r.up.replace('{d}',s.domain),reversed:r.rev.replace('{d}',s.domain),advice:`${r.adv} ${s.tone}`})))];
export const SPREADS={1:['Thông điệp chính'],3:['Nền tảng','Hiện tại','Hướng phát triển'],5:['Cốt lõi','Ảnh hưởng thuận','Trở ngại','Điểm mù','Lời khuyên'],7:['Bối cảnh','Điều đang diễn ra','Nguồn lực','Thử thách','Điều cần buông','Hành động nên làm','Xu hướng tiếp theo']};
export const TOPICS={general:'Tổng quan',love:'Tình cảm',work:'Công việc',finance:'Tài chính',family:'Gia đình',mind:'Tinh thần',decision:'Quyết định'};
