(()=>{
'use strict';
const app=document.querySelector('#app');
const META_KEY='dln_meta_v1';
const SLOT_KEY=i=>`dln_slot_${i}_v1`;
const DAYS_PER_YEAR=120;
const MONTH_DAYS=30;
const TRAITS=[
{id:'benbi',name:'Bền bỉ',unlock:0,desc:'Ít mất sức khi làm việc, hợp người thích tự thân đi lên.',perk:'Năng lượng tiêu hao khi làm việc -12%.',mods:{energy:.88}},
{id:'tietkiem',name:'Biết vun vén',unlock:0,desc:'Không giàu nhanh nhưng giữ tiền rất tốt.',perk:'Chi phí ăn ở và sinh hoạt -10%.',mods:{living:.90}},
{id:'kheomieng',name:'Khéo giao tiếp',unlock:0,desc:'Dễ được giới thiệu việc, làm quen và tạo uy tín.',perk:'Uy tín nhận được +50%, hẹn hò hiệu quả hơn.',mods:{rep:1.5,love:1.15}},
{id:'kyLuat',name:'Kỷ luật',unlock:2,desc:'Ăn ngủ, tập luyện đều đặn giúp đường dài bền hơn.',perk:'Tập luyện tăng sức khỏe nhiều hơn 40%.',mods:{workout:1.4}},
{id:'thoNghe',name:'Có nghề trong tay',unlock:4,desc:'Giỏi các việc kỹ thuật và dịch vụ có tay nghề.',perk:'Thu nhập việc kỹ thuật +18%.',mods:{skilled:1.18}},
{id:'damLam',name:'Dám làm',unlock:6,desc:'Chấp nhận cơ hội khó để đổi lấy tốc độ tăng trưởng.',perk:'Việc rủi ro trả thêm 18%, biến cố xấu nặng hơn nhẹ.',mods:{risky:1.18}},
{id:'danBuon',name:'Máu kinh doanh',unlock:8,desc:'Nhìn thấy biên lợi nhuận và mở cơ sở nhanh hơn.',perk:'Chi phí mở kinh doanh -7%, lợi nhuận cơ sở +5%.',mods:{setup:.93,biz:1.05}},
{id:'quanHe',name:'Quan hệ rộng',unlock:11,desc:'Người quen thường mang đến việc và hợp đồng tốt.',perk:'Mỗi ngày dễ xuất hiện việc tốt hơn; mở hẹn hò sớm hơn.',mods:{offers:1,love:1.08}},
{id:'laoDong',name:'Con nhà lao động',unlock:14,desc:'Không có vốn lớn nhưng được dạy cách sống chắc chắn.',perk:'Sức khỏe khởi đầu +10, tiền khởi đầu +200.000đ.',mods:{health:10,startCash:200000}},
{id:'tayTrang',name:'Tay trắng lì đòn',unlock:18,desc:'Khởi đầu khó nhất, dành cho hành trình thử thách.',perk:'Chỉ có 150.000đ nhưng Điểm sự nghiệp cuối hành trình +50%.',mods:{startCash:-350000,career:1.5}}
];
const FOODS=[
{id:'mi',name:'Mì + trứng ở phòng trọ',cost:18000,health:0,mood:-1,energy:12,desc:'Rẻ, đủ cầm cự nhưng không thể sống kiểu này mãi.'},
{id:'com',name:'Cơm bình dân',cost:42000,health:3,mood:1,energy:22,desc:'Lựa chọn cân bằng cho giai đoạn mưu sinh.'},
{id:'pho',name:'Phở / bún / cơm ngon',cost:75000,health:5,mood:3,energy:26,desc:'Ăn đàng hoàng, tinh thần cũng dễ chịu hơn.'},
{id:'ngon',name:'Một bữa tử tế',cost:180000,health:6,mood:8,energy:28,desc:'Không chỉ no mà còn là cảm giác cuộc sống đang khá lên.'}
];
const WORKOUTS=[
{id:'walk',name:'Đi bộ / chạy nhẹ',cost:0,health:4,mood:3,energy:12,desc:'Không tốn tiền, cần chút thời gian và kỷ luật.'},
{id:'park',name:'Tập công viên',cost:15000,health:6,mood:4,energy:16,desc:'Xà đơn, chạy bộ, vài bài thể lực cơ bản.'},
{id:'martial',name:'Đi học võ',cost:80000,health:9,mood:7,energy:22,desc:'Tốn hơn nhưng vừa khỏe vừa giải tỏa đầu óc.'},
{id:'gym',name:'Tập gym',cost:120000,health:8,mood:6,energy:20,desc:'Ổn định thể lực khi công việc bắt đầu bận.'}
];
const HOUSING=[
{id:'tro',name:'Phòng trọ 12m²',kind:'rent',price:0,monthly:900000,quality:0,mood:0,energy:0,minNet:0,desc:'Nhỏ, nóng, nhưng là chỗ để bắt đầu.'},
{id:'troTot',name:'Phòng trọ sạch sẽ',kind:'rent',price:0,monthly:2200000,quality:1,mood:2,energy:4,minNet:8000000,desc:'Có máy lạnh, bếp nhỏ, ngủ ngon hơn.'},
{id:'chungCuThue',name:'Căn hộ thuê',kind:'rent',price:0,monthly:7500000,quality:2,mood:5,energy:7,minNet:50000000,desc:'Một bước chuyển rõ rệt về chất lượng sống.'},
{id:'chungCuMua',name:'Căn hộ sở hữu',kind:'buy',price:1800000000,monthly:2500000,quality:3,mood:7,energy:8,minNet:800000000,desc:'Có chỗ ở của mình; vẫn có phí quản lý và bảo trì.'},
{id:'nhaPho',name:'Nhà phố',kind:'buy',price:5500000000,monthly:4500000,quality:4,mood:10,energy:9,minNet:2500000000,desc:'Ổn định cho gia đình và mở nhiều lựa chọn xã hội.'},
{id:'bietThu',name:'Biệt thự',kind:'buy',price:18000000000,monthly:12000000,quality:5,mood:14,energy:10,minNet:9000000000,desc:'Không làm bạn thắng game, nhưng cho thấy bạn đã bước sang một tầng đời khác.'}
];
const VEHICLES=[
{id:'none',name:'Đi bộ / xe buýt',price:0,monthly:120000,resale:.0,tier:0,desc:'Chậm nhưng chưa tạo gánh nặng.'},
{id:'bike',name:'Xe đạp cũ',price:900000,monthly:50000,resale:.35,tier:1,desc:'Mở thêm vài việc giao hàng gần.'},
{id:'motorOld',name:'Xe máy cũ',price:5500000,monthly:450000,resale:.55,tier:2,desc:'Mốc đời quan trọng: bắt đầu chạy dịch vụ nghiêm túc.'},
{id:'motor',name:'Xe máy tốt',price:28000000,monthly:850000,resale:.62,tier:3,desc:'Ít hư, uy tín dịch vụ tốt hơn.'},
{id:'carOld',name:'Ô tô cũ',price:320000000,monthly:5500000,resale:.58,tier:4,desc:'Mở một số cơ hội khách hàng và đời sống mới.'},
{id:'car',name:'Ô tô gia đình',price:850000000,monthly:9000000,resale:.62,tier:5,desc:'Tốt cho gia đình, gặp khách và vị thế xã hội.'},
{id:'van',name:'Xe tải van',price:520000000,monthly:11000000,resale:.60,tier:5,desc:'Tài sản làm ăn, mở việc vận chuyển hàng nhỏ.'}
];
const JOBS=[
{id:'vechai',name:'Nhặt ve chai cuối buổi chợ',pay:[90000,170000],energy:24,health:2,rep:0,tier:0,vehicle:0,kind:'basic',desc:'Giấy carton, lon, nhựa. Ít vốn, đổi sức lấy tiền.'},
{id:'bocHang',name:'Bốc hàng chợ đầu mối',pay:[170000,300000],energy:34,health:4,rep:1,tier:0,vehicle:0,kind:'risky',desc:'Nặng nhưng trả ngay trong ngày.'},
{id:'ruaXe',name:'Phụ rửa xe',pay:[140000,250000],energy:26,health:2,rep:1,tier:0,vehicle:0,kind:'basic',desc:'Chủ tiệm đang thiếu người một ca.'},
{id:'chayBan',name:'Chạy bàn tiệc cưới',pay:[180000,320000],energy:30,health:2,rep:1,tier:0,vehicle:0,kind:'basic',desc:'Ca tối, đông nhưng thường có thêm tiền bo.'},
{id:'giaoPho',name:'Giao phở buổi sáng',pay:[180000,330000],energy:25,health:1,rep:1,tier:1,vehicle:1,kind:'basic',desc:'Quán cô Năm cần giao vài chục tô quanh khu.'},
{id:'shipShop',name:'Ship đơn shop quần áo',pay:[260000,480000],energy:29,health:2,rep:2,tier:1,vehicle:2,kind:'basic',desc:'Đi nhiều điểm, tiền khá hơn nếu chạy gọn.'},
{id:'giaoCom',name:'Giao cơm văn phòng',pay:[280000,520000],energy:30,health:2,rep:2,tier:1,vehicle:2,kind:'basic',desc:'Khung giờ gắt nhưng đơn đều.'},
{id:'gaRan',name:'Giao gà rán & đồ ăn tối',pay:[300000,560000],energy:31,health:2,rep:2,tier:1,vehicle:2,kind:'basic',desc:'Đông nhất khi trời mưa hoặc cuối tuần.'},
{id:'xeOm',name:'Chạy xe ôm ứng dụng',pay:[320000,620000],energy:35,health:3,rep:2,tier:1,vehicle:2,kind:'risky',desc:'Thu nhập tốt hơn, đổi lại chạy đường nhiều.'},
{id:'binhNuoc',name:'Chở bình nước cho đại lý',pay:[360000,680000],energy:35,health:4,rep:2,tier:2,vehicle:2,kind:'risky',desc:'Nặng, đều tiền, quen được nhiều chủ cửa hàng.'},
{id:'dienMay',name:'Phụ lắp điện máy',pay:[420000,760000],energy:30,health:2,rep:3,tier:2,vehicle:2,kind:'skilled',minRep:8,desc:'Cần biết việc và giữ lời hẹn với khách.'},
{id:'chuyenNha',name:'Phụ chuyển nhà',pay:[500000,900000],energy:40,health:5,rep:3,tier:2,vehicle:2,kind:'risky',minRep:10,desc:'Một ngày mệt nhưng thu nhập đã khác trước.'},
{id:'giaoHangVan',name:'Nhận tuyến giao hàng bằng van',pay:[750000,1350000],energy:34,health:2,rep:4,tier:3,vehicle:5,kind:'skilled',minRep:22,needVan:true,desc:'Khách doanh nghiệp nhỏ trả theo tuyến.'}
];
const BUSINESSES=[
{id:'toThuGom',name:'Tổ thu gom ve chai',cost:4500000,rep:3,level:1,gross:[450000,750000],op:.36,staff:1,salary:5500000,max:3,desc:'Thuê 1 người đi gom, bạn lo đầu mối và bán lại.'},
{id:'banhMi',name:'Xe bánh mì',cost:14000000,rep:6,level:1,gross:[700000,1250000],op:.55,staff:1,salary:6500000,max:4,desc:'Đồ ăn sáng rất đời; lời vừa phải và sớm bão hòa.'},
{id:'caPhe',name:'Xe cà phê mang đi',cost:19000000,rep:7,level:1,gross:[850000,1450000],op:.57,staff:1,salary:6500000,max:4,desc:'Đẹp vị trí thì bán tốt, nhưng cạnh tranh dày.'},
{id:'daiLyNuoc',name:'Đại lý nước uống nhỏ',cost:38000000,rep:10,level:2,gross:[1400000,2400000],op:.60,staff:2,salary:7000000,max:3,desc:'Có khách lẻ và khách văn phòng; xe máy tốt giúp vận hành.'},
{id:'doiGiaoHang',name:'Đội giao hàng nội quận',cost:52000000,rep:12,level:2,gross:[1900000,3300000],op:.54,staff:4,salary:7200000,max:3,desc:'Bạn bắt đầu kiếm tiền bằng tổ chức người khác chạy.'},
{id:'ruaXeBiz',name:'Tiệm rửa xe',cost:70000000,rep:14,level:2,gross:[2100000,3600000],op:.50,staff:3,salary:7500000,max:2,desc:'Dòng tiền khá đều, khó tăng quá lớn nếu chỉ một điểm.'},
{id:'bepCom',name:'Bếp cơm văn phòng',cost:145000000,rep:18,level:3,gross:[5200000,8200000],op:.66,staff:6,salary:7800000,max:2,desc:'Hợp đồng suất ăn đưa bạn sang kinh doanh có hệ thống.'},
{id:'gara',name:'Gara xe máy',cost:210000000,rep:22,level:3,gross:[6500000,10500000],op:.60,staff:7,salary:8500000,max:2,desc:'Tay nghề, phụ tùng và uy tín quyết định khách quay lại.'},
{id:'khoThucPham',name:'Kho thực phẩm & phân phối',cost:360000000,rep:28,level:4,gross:[10000000,17000000],op:.70,staff:9,salary:9000000,max:2,desc:'Biên không quá dày nhưng doanh thu lớn hơn rõ rệt.'},
{id:'logistics',name:'Công ty giao nhận nội thành',cost:720000000,rep:35,level:4,gross:[21000000,36000000],op:.73,staff:18,salary:10500000,max:2,desc:'Không còn chạy từng đơn; bạn quản đội xe, khách và dòng tiền.'},
{id:'chuoiDoAn',name:'Chuỗi đồ ăn nhanh Việt',cost:1800000000,rep:48,level:5,gross:[55000000,90000000],op:.77,staff:42,salary:11000000,max:2,desc:'Bánh mì, cơm, bún, đồ uống thành một chuỗi vận hành thật.'},
{id:'phanPhoi',name:'Công ty phân phối hàng tiêu dùng',cost:4200000000,rep:62,level:6,gross:[130000000,210000000],op:.81,staff:85,salary:12500000,max:2,desc:'Doanh thu rất lớn nhưng lợi nhuận biên vẫn không vô hạn.'},
{id:'tapDoan',name:'Hệ sinh thái logistics & bán lẻ',cost:12000000000,rep:78,level:7,gross:[380000000,620000000],op:.85,staff:220,salary:14500000,max:1,desc:'Late game: nhiều tiền hơn nhưng trách nhiệm và chi phí cũng ở quy mô khác.'}
];
const PARTNERS=[
{id:'mai',gender:'female',name:'Mai',trait:'Thực tế',monthly:3500000,desc:'Không đòi hỏi hào nhoáng, nhưng rất coi trọng sự ổn định và kế hoạch tương lai.'},
{id:'lan',gender:'female',name:'Lan',trait:'Tham vọng',monthly:5200000,desc:'Thích người có chí làm ăn; đôi khi mở ra cơ hội kinh doanh mới.'},
{id:'vy',gender:'female',name:'Vy',trait:'Tình cảm',monthly:3000000,desc:'Cần thời gian bên nhau hơn là quà đắt tiền.'},
{id:'minh',gender:'male',name:'Minh',trait:'Điềm đạm',monthly:3600000,desc:'Sống có kế hoạch, coi trọng sức khỏe và gia đình.'},
{id:'khoa',gender:'male',name:'Khoa',trait:'Năng động',monthly:4800000,desc:'Thích trải nghiệm, du lịch và những quyết định táo bạo.'},
{id:'nam',gender:'male',name:'Nam',trait:'Thực tế',monthly:3200000,desc:'Ưu tiên nền tảng tài chính chắc và cuộc sống gọn gàng.'}
];
const RANDOM_NAMES=['An','Bình','Chi','Duy','Hân','Hải','Khang','Linh','Minh','My','Nam','Ngân','Phúc','Quân','Thảo','Vy'];
const TABS=[['tongquan','Tổng quan'],['vieclam','Việc làm'],['doisong','Đời sống'],['sunghiep','Sự nghiệp'],['tinhcam','Tình cảm'],['taisan','Tài sản'],['nhatky','Nhật ký']];
let state=null,meta=loadMeta(),slot=1,tab='tongquan',modal=null,cashFxQueue=[];

function defaultMeta(){return{version:1,runs:0,totalDays:0,careerPoints:0,bestNetWorth:0,milestones:[],history:[],unlockedTraits:['benbi','tietkiem','kheomieng']};}
function loadMeta(){try{const d=defaultMeta(),x=Object.assign(d,JSON.parse(localStorage.getItem(META_KEY)||'{}'));x.unlockedTraits=x.unlockedTraits||d.unlockedTraits;x.milestones=x.milestones||[];syncTraitUnlocks(x);return x;}catch{return defaultMeta();}}
function saveMeta(){localStorage.setItem(META_KEY,JSON.stringify(meta));}
function loadSlot(i){try{return JSON.parse(localStorage.getItem(SLOT_KEY(i)));}catch{return null;}}
function save(){if(!state)return;state.updatedAt=Date.now();localStorage.setItem(SLOT_KEY(slot),JSON.stringify(state));}
function eraseSlot(i){localStorage.removeItem(SLOT_KEY(i));}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a;}
function pick(a){return a[Math.floor(Math.random()*a.length)];}
function fmt(v){const n=Math.abs(Math.round(v)),sign=v<0?'-':'';if(n>=1000000000)return sign+(n/1000000000).toLocaleString('vi-VN',{maximumFractionDigits:2})+' tỷ';if(n>=1000000)return sign+(n/1000000).toLocaleString('vi-VN',{maximumFractionDigits:1})+' tr';if(n>=1000)return sign+Math.round(n/1000).toLocaleString('vi-VN')+'k';return sign+n.toLocaleString('vi-VN')+'đ';}
function trait(){return TRAITS.find(x=>x.id===state?.trait)||TRAITS[0];}
function vehicle(){return VEHICLES.find(x=>x.id===state?.vehicle)||VEHICLES[0];}
function home(){return HOUSING.find(x=>x.id===state?.housing)||HOUSING[0];}
function partner(){return PARTNERS.find(x=>x.id===state?.relationship?.partnerId)||null;}
function playerAge(s=state){return 20+Math.floor(((s?.day||1)-1)/DAYS_PER_YEAR);}
function childAge(c){return Math.max(0,Math.floor((state.day-c.birthDay)/DAYS_PER_YEAR));}
function businessCount(){return Object.values(state?.businesses||{}).reduce((a,b)=>a+b,0);}
function totalStaff(){let n=0;for(const b of BUSINESSES)n+=(state?.businesses?.[b.id]||0)*b.staff;return n;}
function netWorth(s=state){if(!s)return 0;let n=s.cash-(s.debt||0);const v=VEHICLES.find(x=>x.id===s.vehicle);if(v)n+=v.price*v.resale;const h=HOUSING.find(x=>x.id===s.housing);if(h?.kind==='buy')n+=h.price*.82;for(const b of BUSINESSES)n+=(s.businesses?.[b.id]||0)*b.cost*.60;return Math.round(n);}
function livingMultiplier(){return trait().mods.living||1;}
function incomeMultiplier(job){let m=1;if(job.kind==='skilled')m*=trait().mods.skilled||1;if(job.kind==='risky')m*=trait().mods.risky||1;return m;}
function changeCash(delta,label='Giao dịch',animate=true){if(!state||!Number.isFinite(delta)||!delta)return;state.cash+=Math.round(delta);if(animate)cashFxQueue.push({delta:Math.round(delta),label});}
function flushCashFx(){if(!cashFxQueue.length)return;const anchor=document.querySelector('[data-cash-anchor]');if(!anchor){cashFxQueue=[];return;}const r=anchor.getBoundingClientRect();cashFxQueue.splice(0,7).forEach((fx,i)=>setTimeout(()=>{const el=document.createElement('div');el.className=`money-fx ${fx.delta>0?'gain':'loss'}`;el.innerHTML=`${fx.delta>0?'+':'−'}${fmt(Math.abs(fx.delta))}<small>${esc(fx.label)}</small>`;el.style.left=`${Math.max(8,Math.min(window.innerWidth-178,r.left+r.width/2-58+(i%3-1)*20))}px`;el.style.top=`${Math.max(70,r.bottom+2)}px`;document.body.appendChild(el);setTimeout(()=>el.remove(),2350);},i*140));}
function log(text,type='normal'){state.journal.unshift({day:state.day,text,type});state.journal=state.journal.slice(0,180);}
function news(title,text,type='Đời sống'){state.news.unshift({day:state.day,title,text,type});state.news=state.news.slice(0,30);}
function syncTraitUnlocks(m=meta){for(const t of TRAITS)if((m.careerPoints||0)>=t.unlock&&!m.unlockedTraits.includes(t.id))m.unlockedTraits.push(t.id);}
function careerPoint(key,label){if(meta.milestones.includes(key))return;meta.milestones.push(key);meta.careerPoints++;syncTraitUnlocks(meta);saveMeta();news('Điểm sự nghiệp',`${label}. Bạn nhận +1 Điểm sự nghiệp dùng để mở lối sống cho những hành trình sau.`,'Roguelite');}
function milestone(key,title,text){if(state.milestones.includes(key))return false;state.milestones.push(key);state.storyFlags[key]=true;news(title,text,'Cột mốc');log(`${title}: ${text}`,'good');careerPoint(key,title);return true;}
function createState(name,gender,pref,traitId){const t=TRAITS.find(x=>x.id===traitId)||TRAITS[0],start=500000+(t.mods.startCash||0);const s={version:1,status:'playing',name:name||'Linh',gender,pref,trait:t.id,day:1,cash:Math.max(150000,start),debt:0,health:clamp(86+(t.mods.health||0),1,100),mood:72,energy:100,reputation:0,vehicle:'none',housing:'tro',housingOwned:false,nextHousingDue:15,ateToday:false,workoutToday:false,workCountToday:0,dateToday:false,businesses:{},jobOffers:[],relationship:{status:'single',partnerId:null,love:0,metDay:null,lastDateDay:-99},children:[],events:[],news:[],journal:[],milestones:[],storyFlags:{},stats:{earned:0,spent:0,jobsDone:0,businessRevenue:0,bestCash:start,maxNet:0,daysWorked:0},createdAt:Date.now(),updatedAt:Date.now(),monthlyReport:null,consecutiveNoFood:0,hospitalVisits:0,fastForwardUnlocked:false};
 state=s;refreshJobs(true);s.events.push({title:'Ngày đầu ở thành phố',text:`Bạn kéo chiếc ba lô vào phòng trọ 12m². Trong túi có ${fmt(s.cash)}. Chủ trọ cô Út cho bạn khất tiền phòng tới Ngày 15. Không ai đưa sẵn sự nghiệp cho bạn: ngày mai có ăn gì, ở đâu và sống ra sao phụ thuộc vào việc bạn chịu đi làm hôm nay.`,type:'Mở đầu',choices:[{label:'Ra ngoài kiếm việc',effect:{mood:2}},{label:'Sắp xếp phòng rồi bắt đầu',effect:{health:1}}]});
 return s;}
function migrateState(s){if(!s)return null;s.version=1;s.debt=s.debt||0;s.businesses=s.businesses||{};s.children=s.children||[];s.news=s.news||[];s.journal=s.journal||[];s.events=s.events||[];s.milestones=s.milestones||[];s.storyFlags=s.storyFlags||{};s.relationship=s.relationship||{status:'single',partnerId:null,love:0,metDay:null,lastDateDay:-99};s.stats=Object.assign({earned:0,spent:0,jobsDone:0,businessRevenue:0,bestCash:s.cash||0,maxNet:0,daysWorked:0},s.stats||{});s.jobOffers=s.jobOffers||[];s.nextHousingDue=s.nextHousingDue||s.day+15;return s;}

function startScreen(){state=null;const slots=[1,2,3].map(i=>({i,s:migrateState(loadSlot(i))}));app.innerHTML=`<div class="shell"><div class="slot-wrap"><div class="row" style="justify-content:flex-end"><button class="btn" id="exitGameBtn">Đóng game</button></div><div class="hero"><div class="brand-mark" style="margin:auto">ĐỜI</div><h1>Đời Lập Nghiệp</h1><p>Game số liệu về một cuộc đời: từ phòng trọ, việc lặt vặt và chiếc xe cũ đến tình yêu, gia đình, doanh nghiệp và tài sản.</p></div><div class="grid"><div class="card"><h2>Nhịp game</h2><div class="brief"><div class="brief-item"><strong>1. Phải làm mới có tiền</strong><span class="muted mini">Đầu game gần như không có thu nhập thụ động. Việc xuất hiện theo từng ngày và hoàn cảnh.</span></div><div class="brief-item"><strong>2. Tiền mở cuộc sống</strong><span class="muted mini">Ăn uống, tập luyện, xe, nhà ở, người yêu, kết hôn, con cái chỉ mở dần khi đủ khả năng.</span></div><div class="brief-item"><strong>3. Giàu hơn không có nghĩa nhẹ hơn</strong><span class="muted mini">Khi có doanh nghiệp và gia đình, dòng tiền lớn hơn nhưng trách nhiệm cũng lớn hơn.</span></div></div></div><div class="card"><h2>Roguelite nhẹ</h2><p class="mini muted">Mỗi hành trình chọn 1 trong 10 “lối sống”. Thành tích trong các hành trình tạo Điểm sự nghiệp để mở thêm cách khởi đầu, nhưng không cộng tiền miễn phí vào ván sau.</p><div class="row"><span class="tag">${meta.unlockedTraits.length}/10 đã mở</span><span class="tag">${meta.careerPoints} Điểm sự nghiệp</span></div></div></div><div class="career"><div class="card"><span class="mini muted">Hành trình</span><div class="kpi">${meta.runs}</div></div><div class="card"><span class="mini muted">Ngày đã sống</span><div class="kpi">${meta.totalDays}</div></div><div class="card"><span class="mini muted">Điểm sự nghiệp</span><div class="kpi">${meta.careerPoints}</div></div><div class="card"><span class="mini muted">Tài sản kỷ lục</span><div class="kpi">${fmt(meta.bestNetWorth)}</div></div></div><h2>3 ô lưu</h2><div class="grid3">${slots.map(x=>slotCard(x.i,x.s)).join('')}</div><div class="card" style="margin-top:10px"><h2>10 lối sống</h2><div class="row">${TRAITS.map(t=>`<span class="tag ${meta.unlockedTraits.includes(t.id)?'good':'warn'}" title="${esc(t.perk)}">${meta.unlockedTraits.includes(t.id)?'✓':'🔒'} ${t.name}</span>`).join('')}</div></div><div class="footer-note">Dữ liệu game lưu riêng trong trình duyệt, không ảnh hưởng dữ liệu KanBan hoặc Thương Lộ Việt.</div></div></div>`;bindStart();}
function slotCard(i,s){if(!s)return `<div class="card slot empty"><div><span class="tag">Ô ${i}</span><h3>Chưa có cuộc đời</h3><p class="muted mini">Tạo nhân vật mới và bắt đầu từ Ngày 1.</p></div><button class="btn primary" data-new="${i}">Bắt đầu</button></div>`;return `<div class="card slot"><div><span class="tag">Ô ${i}</span><h3>${esc(s.name)}</h3><div class="big">${fmt(netWorth(s))}</div><div class="mini muted">Ngày ${s.day} · ${playerAge(s)} tuổi · ${TRAITS.find(t=>t.id===s.trait)?.name||''}</div><div class="mini muted">${s.status==='playing'?'Đang sống hành trình':'Đã kết thúc'}</div></div><div class="slot-actions"><button class="btn primary" data-load="${i}">Tiếp tục</button><button class="btn danger" data-delete="${i}">Xóa</button></div></div>`;}
function bindStart(){const ex=document.querySelector('#exitGameBtn');if(ex)ex.onclick=closeGame;document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>openNew(Number(b.dataset.new)));document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>openSlot(Number(b.dataset.load)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Xóa hẳn ô lưu này?')){eraseSlot(Number(b.dataset.delete));startScreen();}});}
function openNew(i){slot=i;const traitCards=TRAITS.map(t=>`<button type="button" class="trait ${meta.unlockedTraits.includes(t.id)?'':'locked'}" data-trait="${t.id}" ${meta.unlockedTraits.includes(t.id)?'':`title="Cần ${t.unlock} Điểm sự nghiệp"`}><b>${meta.unlockedTraits.includes(t.id)?'':'🔒 '}${t.name}</b><span class="mini muted">${t.desc}</span><span class="mini"><b>Lợi thế:</b> ${t.perk}</span>${meta.unlockedTraits.includes(t.id)?'':`<span class="mini muted">Mở ở ${t.unlock} điểm · hiện có ${meta.careerPoints}</span>`}</button>`).join('');openModal(`<div class="modal-card"><h2>Tạo cuộc đời mới · Ô ${i}</h2><div class="form-grid"><label>Tên nhân vật<input id="playerName" value="Linh" maxlength="24"></label><label>Giới tính<select id="playerGender"><option value="male">Nam</option><option value="female">Nữ</option><option value="other">Khác / không đặt nặng</option></select></label><label>Muốn hẹn hò với<select id="pref"><option value="female">Nữ</option><option value="male">Nam</option><option value="any">Bất kỳ</option></select></label><label>Thời gian đời<div class="brief-item" style="margin-top:4px">120 ngày game ≈ 1 tuổi</div></label></div><h3 style="margin-top:14px">Chọn 1 lối sống cho hành trình này</h3><div class="trait-grid">${traitCards}</div><div class="row" style="margin-top:12px"><button class="btn" id="cancelNew">Hủy</button><button class="btn primary" id="createNew">Bắt đầu từ phòng trọ</button></div></div>`);let chosen=meta.unlockedTraits[0]||'benbi';const setChoice=id=>{chosen=id;document.querySelectorAll('.trait').forEach(x=>x.classList.toggle('selected',x.dataset.trait===id));};setChoice(chosen);document.querySelectorAll('.trait:not(.locked)').forEach(b=>b.onclick=()=>setChoice(b.dataset.trait));document.querySelector('#cancelNew').onclick=closeModal;document.querySelector('#createNew').onclick=()=>{state=createState(document.querySelector('#playerName').value.trim()||'Linh',document.querySelector('#playerGender').value,document.querySelector('#pref').value,chosen);tab='tongquan';save();closeModal();renderGame();showPendingEvent();};}
function openSlot(i){const s=migrateState(loadSlot(i));if(!s)return;slot=i;state=s;tab='tongquan';if(!state.jobOffers.length)refreshJobs(true);renderGame();if(state.events.length)showPendingEvent();}

function renderGame(){if(!state)return startScreen();const p=partner(),rel=state.relationship.status==='single'?'Độc thân':state.relationship.status==='dating'?`Đang yêu ${p?.name||''}`:state.relationship.status==='married'?`Đã kết hôn · ${p?.name||''}`:'Đang tìm hiểu';const n=netWorth();state.stats.maxNet=Math.max(state.stats.maxNet||0,n);meta.bestNetWorth=Math.max(meta.bestNetWorth||0,n);saveMeta();app.innerHTML=`<div class="shell"><div class="top"><div class="content"><div class="top-row"><div class="brand"><div class="brand-mark">ĐỜI</div><div><h1>${esc(state.name)}</h1><small>${trait().name} · ${rel}</small></div></div><div class="top-actions"><span class="day-pill">Ngày ${state.day} · ${playerAge()} tuổi</span><button class="btn ghost" id="homeBtn">Ô lưu</button><button class="btn ghost" id="exitGameBtn">Đóng</button><button class="btn primary next-btn" id="nextDayBtn">Qua ngày →</button></div></div><div class="stats"><div class="stat" data-cash-anchor><span>Tiền mặt</span><b>${fmt(state.cash)}</b></div><div class="stat"><span>Tài sản ròng</span><b>${fmt(n)}</b></div><div class="stat"><span>Sức khỏe</span><b>${Math.round(state.health)}/100</b><div class="progress ${state.health<35?'bad':''}"><i style="width:${clamp(state.health,0,100)}%"></i></div></div><div class="stat"><span>Tinh thần</span><b>${Math.round(state.mood)}/100</b><div class="progress"><i style="width:${clamp(state.mood,0,100)}%"></i></div></div><div class="stat"><span>Năng lượng hôm nay</span><b>${Math.round(state.energy)}/100</b><div class="progress"><i style="width:${clamp(state.energy,0,100)}%"></i></div></div><div class="stat"><span>Uy tín</span><b>${Math.round(state.reputation)}</b></div></div><div class="nav">${TABS.map(([id,label])=>`<button data-tab="${id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</div></div></div><div class="content">${viewForTab()}<div class="footer-note">Thời gian được nén để chơi được một đời: 120 ngày game ≈ 1 tuổi. Mỗi ngày chỉ chạy tiếp khi bạn bấm Qua ngày.</div></div></div>`;bindGame();setTimeout(flushCashFx,80);}
function viewForTab(){return tab==='vieclam'?jobsView():tab==='doisong'?lifeView():tab==='sunghiep'?careerView():tab==='tinhcam'?relationshipView():tab==='taisan'?assetsView():tab==='nhatky'?journalView():overviewView();}
function overviewView(){const p=partner(),monthly=monthlyExpenseEstimate(),nextGoal=nextProgressGoal();return `<div class="grid"><div><div class="card"><div class="screen-title"><div><h2>Hôm nay</h2><div class="mini muted">Muốn có tiền đầu game, bạn phải tự đi làm. Khi có cơ sở, tiền mới bắt đầu tự chạy một phần.</div></div><span class="tag">${state.ateToday?'Đã ăn':'Chưa ăn'} · ${state.workoutToday?'Đã tập':'Chưa tập'}</span></div><div class="grid3">${state.jobOffers.slice(0,3).map(jobCard).join('')}</div>${!state.jobOffers.length?'<div class="empty-state">Hôm nay chưa còn việc phù hợp. Qua ngày để tìm việc mới.</div>':''}</div><div class="card" style="margin-top:10px"><h2>Chặng đời tiếp theo</h2><div class="story hot"><div class="story-title">${esc(nextGoal.title)}</div><div class="mini muted">${esc(nextGoal.text)}</div></div></div></div><div><div class="card"><h2>Cuộc sống hiện tại</h2><div class="brief"><div class="brief-item"><strong>Nhà ở</strong><span class="muted mini">${home().name} · chi khoảng ${fmt(home().monthly*livingMultiplier())}/30 ngày</span></div><div class="brief-item"><strong>Đi lại</strong><span class="muted mini">${vehicle().name}</span></div><div class="brief-item"><strong>Gia đình</strong><span class="muted mini">${state.relationship.status==='single'?'Chưa có người yêu':`${p?.name||'Người yêu'} · tình cảm ${Math.round(state.relationship.love)}/100`}${state.children.length?` · ${state.children.length} con`:''}</span></div><div class="brief-item"><strong>Chi phí cố định ước tính</strong><span class="muted mini">${fmt(monthly)}/30 ngày, chưa gồm ăn uống tự chọn</span></div><div class="brief-item"><strong>Kinh doanh</strong><span class="muted mini">${businessCount()} cơ sở · ${totalStaff()} nhân sự</span></div></div></div><div class="card" style="margin-top:10px"><h2>Tin gần đây</h2><div class="log">${state.news.slice(0,5).map(n=>`<div class="log-item"><span class="tag">${esc(n.type)}</span> <b>${esc(n.title)}</b><div class="mini muted">Ngày ${n.day}: ${esc(n.text)}</div></div>`).join('')||'<div class="mini muted">Mọi thứ còn rất mới.</div>'}</div></div>${canFastForward()?`<div class="card" style="margin-top:10px"><h3>Đã có hệ thống tự chạy</h3><div class="mini muted">Khi có nhiều cơ sở, bạn có thể cho đời chạy nhanh 7 ngày. Game sẽ dừng nếu xuất hiện sự kiện cần quyết định.</div><button class="btn" id="weekBtn" style="margin-top:8px">Qua tối đa 7 ngày</button></div>`:''}</div></div>`;}
function jobCard(jid){const j=JOBS.find(x=>x.id===jid);if(!j)return'';const energy=Math.ceil(j.energy*(trait().mods.energy||1)),done=state.energy<energy;return `<div class="job ${done?'locked':''}"><div class="job-top"><div><b>${j.name}</b><span class="mini muted">${j.desc}</span></div><span class="tag good">${fmt(j.pay[0])}–${fmt(j.pay[1])}</span></div><div class="mini muted" style="margin-top:5px">Tốn khoảng ${energy} năng lượng · +${Math.round(j.rep*(trait().mods.rep||1))} uy tín</div><button class="btn primary" data-job="${j.id}" ${done?'disabled':''}>Đi làm</button></div>`;}
function jobsView(){const eligible=eligibleJobs();return `<div class="card"><div class="screen-title"><div><h2>Việc xuất hiện hôm nay</h2><div class="mini muted">Không có nút “nhận lương”. Muốn có tiền, bạn phải chọn việc và trả bằng thời gian/năng lượng.</div></div><span class="tag">Đã làm ${state.workCountToday} việc hôm nay</span></div><div class="grid3">${state.jobOffers.map(jobCard).join('')||'<div class="empty-state">Hết việc hôm nay.</div>'}</div><h3 style="margin-top:14px">Những nghề bạn đang đủ điều kiện thấy</h3><div class="row">${eligible.map(j=>`<span class="tag">${j.name}</span>`).join('')}</div></div>`;}
function lifeView(){return `<div class="grid"><div class="card"><h2>Ăn uống</h2><div class="mini muted">Không có thanh đói riêng. Nếu qua ngày mà chưa ăn, sức khỏe và tinh thần sẽ tụt rõ rệt.</div><div class="grid3" style="margin-top:9px">${FOODS.map(f=>`<div class="life-action ${state.ateToday?'locked':''}"><b>${f.name}</b><div class="mini muted">${f.desc}</div><div class="mini">${fmt(Math.round(f.cost*livingMultiplier()))} · sức khỏe +${f.health} · tinh thần ${f.mood>=0?'+':''}${f.mood}</div><button class="btn" data-food="${f.id}" ${state.ateToday?'disabled':''}>${state.ateToday?'Hôm nay đã ăn':'Ăn'}</button></div>`).join('')}</div></div><div class="card"><h2>Giữ sức khỏe</h2><div class="mini muted">Làm việc nặng liên tục mà không tập hay nghỉ tốt sẽ khiến thanh sức khỏe tụt dần.</div><div class="brief" style="margin-top:9px">${WORKOUTS.map(w=>`<div class="life-action ${state.workoutToday?'locked':''}"><b>${w.name}</b><div class="mini muted">${w.desc}</div><div class="mini">${fmt(Math.round(w.cost*livingMultiplier()))} · sức khỏe +${Math.round(w.health*(trait().mods.workout||1))} · tinh thần +${w.mood}</div><button class="btn" data-workout="${w.id}" ${state.workoutToday||state.energy<w.energy?'disabled':''}>Tập</button></div>`).join('')}</div></div></div>`;}
function careerView(){return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>Mở cơ sở kinh doanh</h2><div class="mini muted">Mỗi ngành có trần và bão hòa. Mở quá nhiều cùng một loại sẽ giảm hiệu quả, buộc bạn chuyển dần sang ngành cao hơn.</div></div><span class="tag">${totalStaff()} nhân sự</span></div><div class="grid3">${BUSINESSES.map(businessCard).join('')}</div></div><div><div class="card"><h2>Dòng tiền hệ thống</h2>${businessSummary()}</div><div class="card" style="margin-top:10px"><h2>Vốn vay</h2><div class="mini muted">Chỉ mở khi đã có uy tín. Vay giúp vượt ngưỡng vốn nhưng có lãi 1,3% mỗi 30 ngày.</div><div class="brief" style="margin-top:8px"><div class="brief-item"><strong>Nợ hiện tại</strong><span>${fmt(state.debt)}</span></div><div class="brief-item"><strong>Hạn mức</strong><span>${fmt(loanLimit())}</span></div></div><div class="row" style="margin-top:8px"><button class="btn" id="borrowBtn" ${state.reputation<15?'disabled':''}>Vay 20 triệu</button><button class="btn" id="repayBtn" ${state.debt<=0||state.cash<5000000?'disabled':''}>Trả 10 triệu</button></div></div></div></div>`;}
function businessCard(b){const count=state.businesses[b.id]||0,setup=Math.round(b.cost*(trait().mods.setup||1)),locked=state.reputation<b.rep||state.cash<setup||count>=b.max;const reason=count>=b.max?'Đã chạm trần ngành':state.reputation<b.rep?`Cần uy tín ${b.rep}`:state.cash<setup?'Chưa đủ vốn':'';return `<div class="business ${locked?'locked':''}"><div class="business-top"><div><b>${b.name}</b><span class="mini muted">${b.desc}</span></div><span class="tag">Lv ${b.level}</span></div><div class="mini" style="margin-top:6px">Mở: ${fmt(setup)} · cần ${b.staff} người · lương ${fmt(b.salary)}/người/30 ngày</div><div class="mini muted">Đang có ${count}/${b.max} · doanh thu/ngày khoảng ${fmt(b.gross[0])}–${fmt(b.gross[1])}</div><button class="btn primary" data-business="${b.id}" ${locked?'disabled':''}>${reason||'Mở cơ sở'}</button></div>`;}
function businessSummary(){if(!businessCount())return '<div class="empty-state">Bạn vẫn đang tự bán sức lao động. Cơ sở đầu tiên sẽ là lúc tiền bắt đầu làm việc thay bạn.</div>';let monthlySalary=0;const lines=[];for(const b of BUSINESSES){const c=state.businesses[b.id]||0;if(!c)continue;monthlySalary+=c*b.staff*b.salary;lines.push(`<div class="brief-item"><strong>${b.name} ×${c}</strong><span class="mini muted">${c*b.staff} người · bão hòa ${Math.round(saturation(b.id)*100)}%</span></div>`);}return `<div class="brief">${lines.join('')}<div class="brief-item"><strong>Lương nhân sự 30 ngày</strong><span>${fmt(monthlySalary)}</span></div></div>`;}
function relationshipView(){const p=partner();if(state.relationship.status==='single')return `<div class="card"><h2>Tình cảm chưa mở</h2><p class="muted">Game không đẩy người yêu vào ngay khi bạn còn đang lo bữa ăn. Khi cuộc sống có chút nền tảng, một cuộc gặp sẽ xuất hiện tự nhiên qua sự kiện.</p><div class="notice"><b>Điều kiện mềm:</b> đã sống ít nhất 18 ngày, uy tín khoảng 6–8+, sức khỏe trên 50 và tài sản ròng đủ để không còn ở trạng thái sống từng bữa.</div></div>`;const status=state.relationship.status==='married'?'Vợ/chồng':'Người yêu';return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>${status}: ${p?.name||''}</h2><div class="mini muted">${p?.trait||''} · ${p?.desc||''}</div></div><span class="tag good">Tình cảm ${Math.round(state.relationship.love)}/100</span></div><div class="progress"><i style="width:${clamp(state.relationship.love,0,100)}%"></i></div><h3 style="margin-top:14px">Dành thời gian cho nhau</h3><div class="grid3">${dateActions().map(a=>`<div class="life-action"><b>${a.name}</b><div class="mini muted">${a.desc}</div><div class="mini">${fmt(a.cost)} · tình cảm +${a.love}</div><button class="btn" data-date="${a.id}" ${state.dateToday||state.cash<a.cost?'disabled':''}>Đi cùng nhau</button></div>`).join('')}</div>${state.relationship.status==='dating'?marriageBox():childBox()}</div><div class="card"><h2>Gia đình</h2>${familyView()}</div></div>`;}
function dateActions(){return[{id:'coffee',name:'Cà phê & đi dạo',cost:180000,love:5,desc:'Rẻ nhưng có thời gian nói chuyện.'},{id:'food',name:'Ăn một bữa ngon',cost:650000,love:8,desc:'Dễ chịu sau tuần làm việc mệt.'},{id:'movie',name:'Xem phim + ăn tối',cost:1100000,love:10,desc:'Một buổi hẹn đúng nghĩa.'},{id:'trip',name:'Đi chơi cuối tuần',cost:4200000,love:15,desc:'Tốn tiền nhưng tạo kỷ niệm lớn.'}];}
function marriageBox(){const h=home(),eligible=state.relationship.love>=80&&state.day-state.relationship.metDay>=30&&netWorth()>=180000000&&(h.quality>=2||vehicle().tier>=4);return `<div class="card" style="margin-top:12px;background:var(--panel2)"><h3>Chuyện lâu dài</h3><div class="mini muted">Kết hôn không bắt buộc phải có nhà. Nhưng hai người cần đủ gắn bó, có nền tài chính và ít nhất một dấu hiệu ổn định: chỗ ở tử tế hoặc ô tô.</div><button class="btn primary" id="marryBtn" style="margin-top:8px" ${eligible?'':'disabled'}>${eligible?'Bàn chuyện kết hôn':'Chưa đủ điều kiện kết hôn'}</button></div>`;}
function childBox(){const can=state.relationship.status==='married'&&state.relationship.love>=72&&home().quality>=2&&state.cash>=30000000&&state.children.length<3;return `<div class="card" style="margin-top:12px;background:var(--panel2)"><h3>Có con</h3><div class="mini muted">Không tự động. Chính bạn quyết định có thêm thành viên và chấp nhận viện phí, chi phí nuôi dưỡng, học hành sau này.</div><button class="btn primary" id="childBtn" style="margin-top:8px" ${can?'':'disabled'}>${can?'Bàn chuyện có con':state.children.length>=3?'Gia đình đã khá đông':'Chưa đủ điều kiện'}</button></div>`;}
function familyView(){if(state.relationship.status!=='married')return '<div class="mini muted">Hai người chưa kết hôn. Hiện chỉ có chi tiêu hẹn hò tự chọn.</div>';const p=partner();return `<div class="brief"><div class="brief-item"><strong>Chi tiêu chung vợ/chồng</strong><span class="mini muted">Khoảng ${fmt((p?.monthly||0)*livingMultiplier())}/30 ngày. Đây là sinh hoạt chung, không phải “phí người yêu”.</span></div>${state.children.map(c=>`<div class="brief-item"><strong>${esc(c.name)} · ${childAge(c)} tuổi</strong><span class="mini muted">${childStage(c).label} · khoảng ${fmt(childStage(c).monthly*livingMultiplier())}/30 ngày</span></div>`).join('')||'<div class="brief-item"><strong>Chưa có con</strong><span class="mini muted">Hai người có thể chọn sống như vậy lâu dài.</span></div>'}</div>`;}
function assetsView(){return `<div class="grid"><div class="card"><h2>Nhà ở</h2><div class="mini muted">Nhà tốt hơn giúp ngủ hồi sức tốt, mở tình cảm/gia đình và thể hiện vị thế. Chỉ nâng khi bạn muốn.</div><div class="brief" style="margin-top:9px">${HOUSING.map(h=>assetHousing(h)).join('')}</div></div><div class="card"><h2>Phương tiện</h2><div class="mini muted">Xe vừa là chất lượng sống vừa mở nghề. Chi phí vận hành được gom theo tháng.</div><div class="brief" style="margin-top:9px">${VEHICLES.map(v=>assetVehicle(v)).join('')}</div></div></div>`;}
function assetHousing(h){const current=state.housing===h.id,canNet=netWorth()>=h.minNet,cost=h.kind==='buy'?h.price:Math.round(h.monthly*1.5),can=!current&&canNet&&state.cash>=cost;return `<div class="asset ${!can&&!current?'locked':''}"><div class="asset-top"><div><b>${h.name}</b><span class="mini muted">${h.desc}</span></div>${current?'<span class="tag good">Đang ở</span>':`<span class="tag">${h.kind==='buy'?fmt(h.price):fmt(h.monthly)+'/30 ngày'}</span>`}</div>${!current?`<button class="btn" data-home="${h.id}" ${can?'':'disabled'}>${h.kind==='buy'?'Mua nhà':'Chuyển tới thuê'}${!canNet?' · tài sản chưa phù hợp':''}</button>`:''}</div>`;}
function assetVehicle(v){const current=state.vehicle===v.id,resale=Math.round(vehicle().price*vehicle().resale),can=!current&&v.tier>=vehicle().tier&&state.cash+resale>=v.price;return `<div class="asset ${!can&&!current?'locked':''}"><div class="asset-top"><div><b>${v.name}</b><span class="mini muted">${v.desc}</span></div>${current?'<span class="tag good">Đang dùng</span>':`<span class="tag">${fmt(v.price)}</span>`}</div>${!current&&v.id!=='none'?`<button class="btn" data-vehicle="${v.id}" ${can?'':'disabled'}>Mua</button>`:''}</div>`;}
function journalView(){return `<div class="grid"><div class="card"><h2>Nhật ký cuộc đời</h2><div class="log">${state.journal.map(j=>`<div class="log-item"><span class="mini muted">Ngày ${j.day}</span><div>${esc(j.text)}</div></div>`).join('')||'<div class="mini muted">Chưa có gì để ghi.</div>'}</div></div><div><div class="card"><h2>Thành tựu hành trình</h2><div class="row">${state.milestones.map(x=>`<span class="tag good">✓ ${esc(milestoneLabel(x))}</span>`).join('')||'<span class="mini muted">Cột mốc đầu tiên thường là kiếm đủ 1 triệu hoặc mua chiếc xe đầu tiên.</span>'}</div></div><div class="card" style="margin-top:10px"><h2>Thống kê</h2><div class="brief"><div class="brief-item"><strong>Tổng tiền từng kiếm</strong><span>${fmt(state.stats.earned)}</span></div><div class="brief-item"><strong>Việc đã làm</strong><span>${state.stats.jobsDone}</span></div><div class="brief-item"><strong>Doanh thu kinh doanh</strong><span>${fmt(state.stats.businessRevenue)}</span></div><div class="brief-item"><strong>Tài sản cao nhất</strong><span>${fmt(state.stats.maxNet)}</span></div></div></div><button class="btn danger" id="retireBtn" style="margin-top:10px">Kết thúc hành trình & ghi điểm</button></div></div>`;}
function milestoneLabel(k){const map={million:'Có 1 triệu đầu tiên',motorbike:'Mua xe máy',firstBiz:'Thuê người & mở cơ sở',dating:'Có người yêu',marriage:'Kết hôn',child:'Có con',home:'Mua nhà',hundred:'Tài sản 100 triệu',billion:'Tài sản 1 tỷ',company:'Lên doanh nghiệp lớn'};return map[k]||k;}

function bindGame(){document.querySelector('#homeBtn').onclick=()=>{save();startScreen();};const ex=document.querySelector('#exitGameBtn');if(ex)ex.onclick=closeGame;document.querySelector('#nextDayBtn').onclick=()=>advanceDay();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderGame();});document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>doJob(b.dataset.job));document.querySelectorAll('[data-food]').forEach(b=>b.onclick=()=>eat(b.dataset.food));document.querySelectorAll('[data-workout]').forEach(b=>b.onclick=()=>workout(b.dataset.workout));document.querySelectorAll('[data-business]').forEach(b=>b.onclick=()=>buyBusiness(b.dataset.business));document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>datePartner(b.dataset.date));document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>changeHome(b.dataset.home));document.querySelectorAll('[data-vehicle]').forEach(b=>b.onclick=()=>buyVehicle(b.dataset.vehicle));const w=document.querySelector('#weekBtn');if(w)w.onclick=()=>advanceDays(7);const br=document.querySelector('#borrowBtn');if(br)br.onclick=borrow;const rp=document.querySelector('#repayBtn');if(rp)rp.onclick=repay;const mb=document.querySelector('#marryBtn');if(mb)mb.onclick=proposeMarriage;const cb=document.querySelector('#childBtn');if(cb)cb.onclick=haveChild;const rt=document.querySelector('#retireBtn');if(rt)rt.onclick=()=>finishRun('Bạn chủ động khép lại hành trình để xem mình đã đi được bao xa.');}
function eligibleJobs(){const v=vehicle();return JOBS.filter(j=>v.tier>=j.vehicle&&(!j.needVan||state.vehicle==='van')&&state.reputation>=(j.minRep||0));}
function refreshJobs(force=false){if(!state)return;const pool=eligibleJobs(),count=trait().mods.offers?5:4,sorted=[...pool].sort(()=>Math.random()-.5);state.jobOffers=sorted.slice(0,Math.min(count,pool.length)).map(j=>j.id);if(!state.jobOffers.length&&force)state.jobOffers=['vechai','bocHang'];}
function doJob(id){const j=JOBS.find(x=>x.id===id);if(!j)return;const energy=Math.ceil(j.energy*(trait().mods.energy||1));if(state.energy<energy)return toast('Không đủ năng lượng cho việc này.');const pay=Math.round(rnd(j.pay[0],j.pay[1])*incomeMultiplier(j)*(state.health<40?.78:1)*(state.mood<30?.85:1));state.energy=clamp(state.energy-energy,0,100);state.health=clamp(state.health-j.health,0,100);state.mood=clamp(state.mood-rnd(0,2),0,100);const rg=Math.max(0,Math.round(j.rep*(trait().mods.rep||1)));state.reputation+=rg;changeCash(pay,j.name);state.stats.earned+=pay;state.stats.jobsDone++;state.stats.daysWorked++;state.workCountToday++;state.jobOffers=state.jobOffers.filter(x=>x!==id);log(`Đi làm “${j.name}”, nhận ${fmt(pay)}.`,'good');if(Math.random()<.12){const tip=rnd(20000,120000);changeCash(tip,'Tiền bo / khách gửi thêm');state.stats.earned+=tip;news('Một khoản nhỏ vui vui',`Khách hài lòng và gửi thêm ${fmt(tip)}. Không nhiều, nhưng cảm giác làm việc hôm nay đáng công.`,'Công việc');}checkMilestones();save();renderGame();}
function eat(id){if(state.ateToday)return;const f=FOODS.find(x=>x.id===id);if(!f)return;const cost=Math.round(f.cost*livingMultiplier());if(state.cash<cost)return toast('Không đủ tiền cho lựa chọn này.');changeCash(-cost,f.name);state.stats.spent+=cost;state.health=clamp(state.health+f.health,0,100);state.mood=clamp(state.mood+f.mood,0,100);state.energy=clamp(state.energy+f.energy,0,100);state.ateToday=true;state.consecutiveNoFood=0;log(`Ăn ${f.name.toLowerCase()} (${fmt(cost)}).`);save();renderGame();}
function workout(id){if(state.workoutToday)return;const w=WORKOUTS.find(x=>x.id===id);if(!w)return;if(state.energy<w.energy)return toast('Hôm nay đã quá mệt để tập.');const cost=Math.round(w.cost*livingMultiplier());if(state.cash<cost)return toast('Không đủ tiền.');if(cost){changeCash(-cost,w.name);state.stats.spent+=cost;}state.energy-=w.energy;state.health=clamp(state.health+w.health*(trait().mods.workout||1),0,100);state.mood=clamp(state.mood+w.mood,0,100);state.workoutToday=true;log(`${w.name}: giữ sức khỏe cho đường dài.`);save();renderGame();}
function buyVehicle(id){const v=VEHICLES.find(x=>x.id===id);if(!v||v.id===state.vehicle||v.tier<vehicle().tier)return;const old=vehicle(),resale=Math.round(old.price*old.resale);if(state.cash+resale<v.price)return;if(resale>0)changeCash(resale,`Bán ${old.name}`);changeCash(-v.price,`Mua ${v.name}`);state.vehicle=v.id;state.reputation+=v.tier>=4?2:1;log(`Mua ${v.name} giá ${fmt(v.price)}.`,'good');news('Một bước tiến nhìn thấy được',`Từ hôm nay bạn đi lại bằng ${v.name}. Một số công việc mới sẽ bắt đầu xuất hiện.`,'Tài sản');if(v.tier>=2)milestone('motorbike','Chiếc xe máy đầu tiên','Không còn phải đi bộ tìm việc. Thu nhập dịch vụ bắt đầu có thể tăng rõ rệt.');refreshJobs(true);checkMilestones();save();renderGame();}
function changeHome(id){const h=HOUSING.find(x=>x.id===id);if(!h||state.housing===id)return;const cost=h.kind==='buy'?h.price:Math.round(h.monthly*1.5);if(state.cash<cost||netWorth()<h.minNet)return;if(h.kind==='buy'){changeCash(-h.price,`Mua ${h.name}`);state.housingOwned=true;milestone('home','Có nhà của mình',`Bạn đã mua ${h.name}. Từ phòng trọ đi tới đây là một đoạn đời rất dài.`);}else{changeCash(-cost,`Đặt cọc + tháng đầu ${h.name}`);state.housingOwned=false;}state.housing=id;state.nextHousingDue=state.day+MONTH_DAYS;state.mood=clamp(state.mood+8,0,100);log(`Chuyển chỗ ở: ${h.name}.`,'good');save();renderGame();}
function saturation(id){const c=state.businesses[id]||0;return Math.max(.52,1-Math.max(0,c-1)*.16);}
function buyBusiness(id){const b=BUSINESSES.find(x=>x.id===id);if(!b)return;const c=state.businesses[id]||0,setup=Math.round(b.cost*(trait().mods.setup||1));if(c>=b.max||state.reputation<b.rep||state.cash<setup)return;changeCash(-setup,`Mở ${b.name}`);state.businesses[id]=c+1;state.mood=clamp(state.mood+5,0,100);state.reputation+=2;log(`Mở ${b.name}; bắt đầu thuê ${b.staff} người vận hành.`,'good');news('Bạn bắt đầu trả lương cho người khác',`${b.name} cần ${b.staff} người. Từ đây tiền không chỉ nuôi bản thân bạn nữa; cuối mỗi 30 ngày phải có tiền lương cho đội.`,'Sự nghiệp');if(businessCount()===1)milestone('firstBiz','Cơ sở đầu tiên','Lần đầu tiên bạn dùng vốn để thuê người và tạo thu nhập không phụ thuộc hoàn toàn vào sức mình.');if(b.level>=4)milestone('company','Từ chủ nhỏ thành doanh nghiệp','Quy mô nhân sự và dòng tiền đã vượt xa những ngày tự chạy từng đơn hàng.');checkMilestones();save();renderGame();}
function datePartner(id){const a=dateActions().find(x=>x.id===id),p=partner();if(!a||!p||state.dateToday||state.cash<a.cost)return;changeCash(-a.cost,`Đi cùng ${p.name}`);state.stats.spent+=a.cost;const love=Math.round(a.love*(trait().mods.love||1)*(p.trait==='Tình cảm'?1.12:1));state.relationship.love=clamp(state.relationship.love+love,0,100);state.mood=clamp(state.mood+Math.ceil(love/2),0,100);state.dateToday=true;state.relationship.lastDateDay=state.day;log(`Dành thời gian với ${p.name}; tình cảm +${love}.`);save();renderGame();}
function proposeMarriage(){const p=partner();if(!p)return;openModal(`<div class="modal-card"><h2>Bàn chuyện kết hôn với ${p.name}</h2><p class="muted">Hai người đã đủ lâu và cuộc sống cũng có nền hơn trước. Đám cưới là một cột mốc cảm xúc nhưng đồng thời là quyết định tài chính.</p><div class="choice"><button data-wedding="60000000"><b>Đăng ký + tiệc nhỏ · 60 triệu</b><span class="mini muted">Gọn, giữ tiền cho cuộc sống sau cưới.</span></button><button data-wedding="180000000"><b>Đám cưới tiêu chuẩn · 180 triệu</b><span class="mini muted">Tăng uy tín xã hội, có tiền mừng bù lại một phần.</span></button><button data-wedding="450000000"><b>Đám cưới lớn · 450 triệu</b><span class="mini muted">Chỉ nên làm khi dòng tiền đã thật sự khỏe.</span></button></div><button class="btn" id="closeWedding" style="margin-top:10px">Để sau</button></div>`);document.querySelectorAll('[data-wedding]').forEach(b=>b.onclick=()=>wedding(Number(b.dataset.wedding)));document.querySelector('#closeWedding').onclick=closeModal;}
function wedding(cost){if(state.cash<cost)return toast('Chưa đủ tiền cho lựa chọn này.');const gift=Math.round(cost*rnd(45,75)/100);changeCash(-cost,'Chi phí đám cưới');changeCash(gift,'Tiền mừng cưới');state.relationship.status='married';state.relationship.love=clamp(state.relationship.love+12,0,100);state.reputation+=cost>=180000000?5:2;milestone('marriage','Lập gia đình',`Bạn và ${partner()?.name||'người yêu'} chính thức kết hôn. Chi ${fmt(cost)}, nhận lại khoảng ${fmt(gift)} tiền mừng.`);log(`Kết hôn. Chi phí ròng khoảng ${fmt(cost-gift)}.`,'good');closeModal();save();renderGame();}
function haveChild(){if(state.relationship.status!=='married'||state.children.length>=3)return;openModal(`<div class="modal-card"><h2>Hai người muốn có thêm một thành viên?</h2><p class="muted">Game không tự sinh con. Đây là lựa chọn của người chơi và sẽ tạo chi phí dài hạn, nhưng cũng mở một mạch đời hoàn toàn mới.</p><div class="choice"><button data-birth="28000000"><b>Sinh ở bệnh viện tiêu chuẩn · khoảng 28 triệu</b><span class="mini muted">An toàn, vừa sức với gia đình đang phát triển.</span></button><button data-birth="55000000"><b>Gói bệnh viện tư · khoảng 55 triệu</b><span class="mini muted">Tốn hơn, tinh thần gia đình tăng nhiều hơn.</span></button></div><button class="btn" id="closeBirth" style="margin-top:10px">Chưa phải lúc</button></div>`);document.querySelectorAll('[data-birth]').forEach(b=>b.onclick=()=>birth(Number(b.dataset.birth)));document.querySelector('#closeBirth').onclick=closeModal;}
function birth(cost){if(state.cash<cost)return toast('Chưa đủ tiền dự phòng.');changeCash(-cost,'Sinh con & chăm sóc ban đầu');const name=pick(RANDOM_NAMES);state.children.push({name,birthDay:state.day,school:'standard',lastStage:-1});state.relationship.love=clamp(state.relationship.love+8,0,100);state.mood=clamp(state.mood+12,0,100);milestone('child','Gia đình có thêm thành viên',`${name} chào đời. Từ hôm nay bạn không chỉ kiếm tiền cho bản thân nữa.`);log(`${name} chào đời; chi phí ban đầu ${fmt(cost)}.`,'good');closeModal();save();renderGame();}
function childStage(c){const age=childAge(c);if(age<3)return{label:'0–2 tuổi',monthly:6500000};if(age<6)return{label:'Mầm non',monthly:c.school==='premium'?15000000:9000000};if(age<18)return{label:'Đi học',monthly:c.school==='premium'?24000000:12000000};return{label:'Đại học / trưởng thành',monthly:c.school==='premium'?35000000:16000000};}
function borrow(){if(state.reputation<15)return;const amount=20000000,limit=loanLimit();if(state.debt+amount>limit)return toast('Đã gần hết hạn mức vay.');changeCash(amount,'Vay vốn');state.debt+=amount;log(`Vay thêm ${fmt(amount)} để xoay vốn.`);save();renderGame();}
function repay(){const amount=Math.min(10000000,state.debt,state.cash);if(amount<=0)return;changeCash(-amount,'Trả nợ');state.debt-=amount;log(`Trả ${fmt(amount)} nợ.`);save();renderGame();}
function loanLimit(){return state.reputation<15?0:Math.round(Math.max(30000000,netWorth()*.38+state.reputation*800000));}

function monthlyExpenseEstimate(){let total=home().monthly+vehicle().monthly;for(const b of BUSINESSES)total+=(state.businesses[b.id]||0)*b.staff*b.salary;if(state.relationship.status==='dating')total+=(partner()?.monthly||0)*.35;else if(state.relationship.status==='married')total+=(partner()?.monthly||0);for(const c of state.children)total+=childStage(c).monthly;total+=state.debt*.013;return Math.round(total*livingMultiplier());}
function processBusinessDay(){let totalGross=0,totalOp=0,detail=[];for(const b of BUSINESSES){const c=state.businesses[b.id]||0;if(!c)continue;const sat=saturation(b.id),season=1+rnd(-8,10)/100,gross=Math.round(rnd(b.gross[0],b.gross[1])*c*sat*season*(trait().mods.biz||1)),op=Math.round(gross*b.op);totalGross+=gross;totalOp+=op;detail.push(`${b.name}: ${fmt(gross-op)}`);}const net=totalGross-totalOp;if(net!==0){changeCash(net,'Lãi gộp kinh doanh trong ngày');state.stats.earned+=Math.max(0,net);state.stats.businessRevenue+=totalGross;}return{gross:totalGross,op:totalOp,net,detail};}
function processMonth(){if(state.day<state.nextHousingDue)return null;let items=[],total=0;const hCost=Math.round(home().monthly*livingMultiplier());total+=hCost;items.push(`Nhà ở ${fmt(hCost)}`);const vCost=Math.round(vehicle().monthly*livingMultiplier());total+=vCost;items.push(`Đi lại ${fmt(vCost)}`);let salary=0;for(const b of BUSINESSES)salary+=(state.businesses[b.id]||0)*b.staff*b.salary;salary=Math.round(salary*livingMultiplier());if(salary){total+=salary;items.push(`Lương ${totalStaff()} người ${fmt(salary)}`);}if(state.relationship.status==='dating'){const fam=Math.round((partner()?.monthly||0)*.35*livingMultiplier());total+=fam;items.push(`Chi tiêu chung khi hẹn hò ${fmt(fam)}`);}else if(state.relationship.status==='married'){const fam=Math.round((partner()?.monthly||0)*livingMultiplier());total+=fam;items.push(`Sinh hoạt vợ/chồng ${fmt(fam)}`);}let kids=0;for(const c of state.children)kids+=childStage(c).monthly;kids=Math.round(kids*livingMultiplier());if(kids){total+=kids;items.push(`Con cái ${fmt(kids)}`);}const interest=Math.round(state.debt*.013);if(interest){total+=interest;items.push(`Lãi vay ${fmt(interest)}`);}changeCash(-total,'Chi phí định kỳ 30 ngày');state.stats.spent+=total;state.nextHousingDue=state.day+MONTH_DAYS;news('Đến kỳ chi tiêu',`${items.join(' · ')}. Tổng ${fmt(total)}.`,'Tài chính');state.monthlyReport={day:state.day,total,items};return total;}
function sleepRecovery(){const h=home(),base=15+h.energy+(state.ateToday?5:0);state.energy=clamp(72+base,0,100);state.health=clamp(state.health+(state.ateToday?2:-6)+(state.workoutToday?1:0)+Math.floor(h.quality/2),0,100);state.mood=clamp(state.mood+(state.ateToday?1:-3)+h.mood-(state.workCountToday>=3?3:0),0,100);if(!state.ateToday)state.consecutiveNoFood++;}
function advanceDay(silent=false){if(state.events.length){showPendingEvent();return false;}const dayDone=state.day,before=state.cash,biz=processBusinessDay();processMonth();sleepRecovery();state.day++;meta.totalDays++;state.ateToday=false;state.workoutToday=false;state.workCountToday=0;state.dateToday=false;refreshJobs();checkMilestones();checkStoryBeats();maybeRandomEvent();processChildren();handleHealth();state.stats.bestCash=Math.max(state.stats.bestCash,state.cash);state.stats.maxNet=Math.max(state.stats.maxNet,netWorth());meta.bestNetWorth=Math.max(meta.bestNetWorth,netWorth());saveMeta();save();if(!silent){if(state.events.length){renderGame();showPendingEvent();}else showDaySummary(dayDone,before,biz);}return true;}
function advanceDays(n){let done=0;for(let i=0;i<n;i++){if(state.events.length)break;advanceDay(true);done++;if(state.events.length)break;}renderGame();if(state.events.length)showPendingEvent();else toast(`Đã qua ${done} ngày.`);}
function showDaySummary(dayDone,before,biz){const diff=state.cash-before;openModal(`<div class="modal-card"><div class="row between"><div><h2>Ngày ${dayDone} đã qua</h2><div class="mini muted">Cuộc sống chỉ tiến khi bạn bấm Qua ngày.</div></div><span class="tag ${diff>=0?'good':'bad'}">${diff>=0?'+':''}${fmt(diff)}</span></div><div class="brief" style="margin-top:10px"><div class="brief-item"><strong>Kinh doanh</strong><span class="mini muted">${biz.net?`Lãi gộp hôm nay ${fmt(biz.net)}`:'Chưa có cơ sở tạo tiền thụ động.'}</span></div><div class="brief-item"><strong>Sức khỏe</strong><span class="mini muted">${Math.round(state.health)}/100 · ${state.ateToday?'đã ăn':'ngày mới đang chờ bạn ăn uống'}</span></div><div class="brief-item"><strong>Việc ngày mới</strong><span class="mini muted">Có ${state.jobOffers.length} cơ hội đang chờ.</span></div></div><button class="btn primary" id="continueDay" style="margin-top:10px">Sang Ngày ${state.day}</button></div>`);document.querySelector('#continueDay').onclick=()=>{closeModal();renderGame();};}
function canFastForward(){return businessCount()>=2||netWorth()>=250000000;}
function handleHealth(){if(state.health>0)return;state.hospitalVisits++;const cost=Math.min(Math.max(3000000,Math.round(netWorth()*.015)),18000000);changeCash(-cost,'Viện phí vì kiệt sức');state.health=38;state.mood=clamp(state.mood-12,0,100);state.events.unshift({title:'Cơ thể buộc bạn dừng lại',text:`Bạn kiệt sức và phải vào viện. Viện phí khoảng ${fmt(cost)}. Tiền có thể kiếm lại, nhưng nếu cứ đổi sức khỏe lấy thu nhập, một ngày bạn sẽ trả giá đắt hơn.`,type:'Sức khỏe',choices:[{label:'Từ mai sống chậm lại một chút',effect:{health:6,mood:4}}]});}
function processChildren(){for(const c of state.children){const age=childAge(c);if(age!==c.lastStage&&(age===3||age===6||age===18)){c.lastStage=age;state.events.push({title:`${c.name} bước sang một chặng mới`,text:age===3?`${c.name} đã tới tuổi đi mầm non. Bạn bắt đầu thấy tiền học và thời gian đưa đón là một phần thật của gia đình.`:age===6?`${c.name} vào lớp 1. Từ đây chi phí học hành sẽ theo gia đình trong nhiều năm.`:`${c.name} đã 18 tuổi và đứng trước lựa chọn học đại học hay đi làm.`,type:'Gia đình',choices:[{label:'Chọn hướng vừa sức gia đình',effect:{mood:4}},{label:'Đầu tư mạnh cho việc học',cost:age===18?80000000:30000000,effect:{mood:7,rep:1},setSchool:'premium'}]});}}}
function checkMilestones(){const nw=netWorth();if(state.cash>=1000000)milestone('million','Có 1 triệu đầu tiên','Con số chưa lớn, nhưng đây là lần đầu bạn có một khoảng đệm thay vì sống từng bữa.');if(nw>=100000000)milestone('hundred','Tài sản vượt 100 triệu','Bạn đã đi qua đoạn chỉ cần xe hỏng là lao đao cả tháng.');if(nw>=1000000000)milestone('billion','Tài sản ròng vượt 1 tỷ','Lần đầu tiên chữ “tỷ” thực sự xuất hiện trong cuộc đời bạn.');}
function checkStoryBeats(){const nw=netWorth();if(!state.storyFlags.oldBike&&state.day>=5&&state.cash>=700000){state.storyFlags.oldBike=true;state.events.push({title:'Một chiếc xe đạp cũ trước cửa chợ',text:'Chú Ba ve chai nói có người quen muốn bán chiếc xe đạp cũ 900.000đ. Không bắt buộc mua, nhưng từ đây bạn hiểu rằng tài sản nhỏ có thể mở việc mới.',type:'Cơ hội',choices:[{label:'Ghi nhớ, để dành tiền',effect:{mood:1}},{label:'Mua luôn nếu đủ tiền',cost:900000,setVehicle:'bike',effect:{rep:1}}]});}
 if(!state.storyFlags.delivery&&vehicle().tier>=2&&state.stats.jobsDone>=7){state.storyFlags.delivery=true;state.events.push({title:'Cô Năm nhớ mặt bạn',text:'Sau nhiều lần giao hàng đúng giờ, cô Năm giới thiệu bạn cho vài quán khác. Từ đây những việc giao cơm, đồ ăn và ship shop xuất hiện thường hơn.',type:'Quan hệ',choices:[{label:'Cảm ơn và nhận mối',effect:{rep:3,mood:2}}]});}
 if(!state.storyFlags.love&&state.relationship.status==='single'&&state.day>=18&&state.health>=50&&state.reputation>=(trait().id==='quanHe'?5:7)&&nw>=8000000){state.storyFlags.love=true;const pool=PARTNERS.filter(p=>state.pref==='any'||p.gender===state.pref),p=pick(pool.length?pool:PARTNERS);state.events.push({title:'Một buổi sinh nhật của người quen',text:`Bạn vốn định ở nhà để tiết kiệm, nhưng cuối cùng vẫn đi. Ở đó bạn nói chuyện khá lâu với ${p.name} — ${p.trait.toLowerCase()}, ${p.desc.toLowerCase()} Không có “định mệnh”; chỉ là lần đầu sau một thời gian dài mưu sinh, bạn thấy mình có chỗ cho một người khác trong cuộc sống.`,type:'Tình cảm',partnerId:p.id,choices:[{label:'Xin số liên lạc',startDating:true,effect:{love:22,mood:5}},{label:'Làm quen chậm thôi',startDating:true,effect:{love:14,mood:3}}]});}
 if(!state.storyFlags.parents&&nw>=250000000){state.storyFlags.parents=true;state.events.push({title:'Cuộc gọi về nhà',text:'Mẹ gọi nói mái nhà ở quê bắt đầu dột. Hồi trước bạn nghe vậy chỉ biết im lặng. Bây giờ lần đầu bạn có khả năng thật sự giúp.',type:'Gia đình',choices:[{label:'Gửi 20 triệu sửa nhà',cost:20000000,effect:{mood:10,rep:2}},{label:'Gửi 8 triệu sửa phần cấp thiết',cost:8000000,effect:{mood:5}},{label:'Hẹn khi dòng tiền ổn hơn',effect:{mood:-3}}]});}
}
function maybeRandomEvent(){if(Math.random()>.30)return;const events=[
()=>({title:'Xe trục trặc giữa đường',text:'Chiếc xe có dấu hiệu hư vặt. Bạn có thể sửa ngay cho yên tâm hoặc cố chạy tiếp.',type:'Đời thường',choices:[{label:'Sửa đàng hoàng',cost:vehicle().tier>=4?3500000:650000,effect:{health:1}},{label:'Tạm chạy tiếp',effect:{mood:-2,health:-1}}]}),
()=>({title:'Khách gửi nhầm nhiều hơn',text:'Một khách cũ chuyển khoản dư 500.000đ. Không ai phát hiện ngay.',type:'Lựa chọn',choices:[{label:'Chuyển trả lại',effect:{rep:4,mood:3}},{label:'Im lặng coi như may',gain:500000,effect:{rep:-5,mood:-1}}]}),
()=>({title:'Trời mưa lớn cả ngày',text:'Việc giao hàng trả cao hơn, nhưng chạy ngoài đường sẽ mệt và nguy hiểm hơn.',type:'Thời tiết',choices:[{label:'Nhận thêm một cuốc mưa',gain:rnd(250000,650000),effect:{health:-4,mood:1}},{label:'Về sớm giữ sức',effect:{health:2,mood:2}}]}),
()=>({title:'Bạn cũ hỏi mượn tiền',text:'Một người bạn lâu năm nhắn mượn 5 triệu vì gia đình có việc gấp.',type:'Quan hệ',choices:[{label:'Cho mượn 5 triệu',cost:5000000,effect:{mood:4,rep:1}},{label:'Gửi 1 triệu coi như giúp',cost:1000000,effect:{mood:2}},{label:'Từ chối vì mình cũng đang xoay vốn',effect:{mood:-1}}]}),
()=>({title:'Video quán được chia sẻ',text:'Một khách quay clip ngắn về cơ sở của bạn và bất ngờ có nhiều người xem.',type:'Kinh doanh',onlyBiz:true,choices:[{label:'Chớp cơ hội chạy khuyến mãi',cost:3000000,gain:6500000,effect:{rep:3,mood:3}},{label:'Giữ vận hành bình thường',gain:1800000,effect:{rep:1}}]}),
()=>({title:'Một nhân viên xin nghỉ về quê',text:'Bạn có thể cho nghỉ có lương một phần hoặc giữ đúng nguyên tắc.',type:'Nhân sự',onlyBiz:true,choices:[{label:'Hỗ trợ 1 triệu',cost:1000000,effect:{rep:2,mood:2}},{label:'Xử lý theo quy định',effect:{rep:0}}]})
];let tries=0,e;do{e=pick(events)();tries++;}while(e.onlyBiz&&!businessCount()&&tries<8);if(e.onlyBiz&&!businessCount())return;state.events.push(e);}
function nextProgressGoal(){if(vehicle().tier<2)return{title:'Mua một chiếc xe máy cũ',text:'Xe máy mở nhóm việc giao hàng và xe ôm. Đừng mua nếu sau đó không còn tiền ăn, nhưng đây là mốc tăng thu nhập đầu tiên.'};if(!businessCount())return{title:'Từ tự làm sang thuê người',text:'Khi có khoảng vài triệu đến vài chục triệu, hãy mở cơ sở nhỏ. Lợi nhuận không lớn, nhưng đây là bước đầu để tiền làm việc thay bạn.'};if(state.relationship.status==='single')return{title:'Ổn định một chút rồi cuộc sống sẽ mở rộng',text:'Tình cảm sẽ xuất hiện qua sự kiện khi bạn đủ khỏe, có uy tín và không còn sống từng bữa.'};if(state.relationship.status==='dating')return{title:'Giữ cân bằng giữa làm ăn và tình cảm',text:'Kiếm tiền liên tục nhưng bỏ quên người bên cạnh sẽ khiến một phần cuộc sống đứng lại.'};if(state.relationship.status==='married'&&!state.children.length)return{title:'Gia đình là lựa chọn, không phải nghĩa vụ',text:'Bạn có thể tiếp tục hai người, hoặc chủ động có con khi nhà ở và tiền dự phòng đã phù hợp.'};if(netWorth()<1000000000)return{title:'Bước lên doanh nghiệp lớn hơn',text:'Cơ sở nhỏ sẽ bão hòa. Muốn nuôi mức sống mới, bạn cần ngành doanh thu cao hơn chứ không chỉ nhân bản quán nhỏ.'};return{title:'Từ làm giàu sang xây di sản',text:'Tiền đã lớn. Câu hỏi late game là bạn xây hệ thống nào, dành thời gian cho ai và muốn kết thúc hành trình với điều gì.'};}
function showPendingEvent(){if(!state?.events?.length)return;const ev=state.events[0];openModal(`<div class="modal-card"><span class="tag ${ev.type==='Tình cảm'?'good':ev.type==='Cơ hội'?'warn':''}">${esc(ev.type||'Sự kiện')}</span><h2 style="margin-top:8px">${esc(ev.title)}</h2><p>${esc(ev.text)}</p><div class="choice">${ev.choices.map((c,i)=>`<button data-choice="${i}"><b>${esc(c.label)}</b>${c.cost?`<span class="mini down">Chi ${fmt(c.cost)}</span>`:''}${c.gain?`<span class="mini up">Nhận ${fmt(c.gain)}</span>`:''}</button>`).join('')}</div></div>`);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>resolveEvent(Number(b.dataset.choice)));}
function resolveEvent(i){const ev=state.events[0],c=ev?.choices?.[i];if(!c)return;if(c.cost&&state.cash<c.cost){toast('Chưa đủ tiền cho lựa chọn này.');return;}if(c.cost)changeCash(-c.cost,ev.title);if(c.gain)changeCash(c.gain,ev.title);if(c.effect){if(c.effect.health)state.health=clamp(state.health+c.effect.health,0,100);if(c.effect.mood)state.mood=clamp(state.mood+c.effect.mood,0,100);if(c.effect.rep)state.reputation+=c.effect.rep;if(c.effect.love)state.relationship.love=clamp(state.relationship.love+c.effect.love,0,100);}if(c.setVehicle){state.vehicle=c.setVehicle;if(c.setVehicle==='bike')news('Có chiếc xe đầu tiên','Chiếc xe đạp cũ không sang, nhưng từ ngày mai một số việc giao gần sẽ bắt đầu xuất hiện.','Tài sản');}if(c.startDating){state.relationship.status='dating';state.relationship.partnerId=ev.partnerId;state.relationship.metDay=state.day;milestone('dating','Có người bước vào cuộc sống',`Bạn bắt đầu tìm hiểu ${partner()?.name||'một người mới'}. Từ đây tiền không còn là hệ thống duy nhất cần cân bằng.`);}if(c.setSchool&&state.children.length)state.children[state.children.length-1].school=c.setSchool;log(`${ev.title}: ${c.label}.`);state.events.shift();refreshJobs(true);save();closeModal();renderGame();if(state.events.length)setTimeout(showPendingEvent,150);}
function finishRun(reason){const scoreBase=Math.max(1,Math.floor(state.day/60)+state.milestones.length+Math.floor(Math.max(0,netWorth())/500000000)),score=Math.max(1,Math.round(scoreBase*(trait().mods.career||1)));meta.runs++;meta.careerPoints+=score;meta.history.unshift({name:state.name,day:state.day,net:netWorth(),score});meta.history=meta.history.slice(0,30);syncTraitUnlocks(meta);saveMeta();state.status='ended';save();openModal(`<div class="modal-card"><h2>Tổng kết hành trình</h2><p>${esc(reason)}</p><div class="grid3"><div class="stat"><span>Ngày</span><b>${state.day}</b></div><div class="stat"><span>Tài sản ròng</span><b>${fmt(netWorth())}</b></div><div class="stat"><span>Điểm sự nghiệp</span><b>+${score}</b></div></div><div class="goodbox">Những lối sống mới được mở bằng Điểm sự nghiệp sẽ dùng ở hành trình kế tiếp. Ô lưu này vẫn còn để bạn xem lại hoặc xóa khi muốn.</div><button class="btn primary" id="backSlots" style="margin-top:10px">Về 3 ô lưu</button></div>`);document.querySelector('#backSlots').onclick=()=>{closeModal();startScreen();};}
function openModal(html){closeModal();modal=document.createElement('div');modal.className='modal';modal.innerHTML=html;document.body.appendChild(modal);}
function closeModal(){if(modal){modal.remove();modal=null;}}
function closeGame(){save();window.parent.postMessage({type:'doi-lap-nghiep-close'},'*');}
function toast(text){let t=document.querySelector('.toast-local');if(t)t.remove();t=document.createElement('div');t.className='money-fx gain toast-local';t.style.left='50%';t.style.top='80px';t.style.transform='translateX(-50%)';t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2200);}

startScreen();
})();
