(()=>{
'use strict';
const app=document.querySelector('#app');
const META_KEY='dln_meta_v1';
const SLOT_KEY=i=>`dln_slot_${i}_v1`;
const DAYS_PER_YEAR=120;
const MONTH_DAYS=30;
const TRAITS=[
{id:'benbi',name:'Bền bỉ',unlock:0,desc:'Hợp người thích tự thân đi lên và đôi lúc phải cày đêm.',perk:'Năng lượng làm việc -12%; hao sức do làm sau 22:00 giảm khoảng 30%.',mods:{energy:.88}},
{id:'tietkiem',name:'Biết vun vén',unlock:0,desc:'Không giàu nhanh nhưng giữ tiền rất tốt.',perk:'Chi phí ăn ở và sinh hoạt -10%.',mods:{living:.90}},
{id:'kheomieng',name:'Khéo giao tiếp',unlock:0,desc:'Dễ được giới thiệu việc, làm quen và tạo uy tín.',perk:'Uy tín nhận được +50%, hẹn hò hiệu quả hơn.',mods:{rep:1.5,love:1.15}},
{id:'kyLuat',name:'Kỷ luật',unlock:2,desc:'Ăn ngủ, tập luyện đều đặn giúp đường dài bền hơn.',perk:'Tập luyện hiệu quả +40%; ngủ đủ hồi năng lượng tốt hơn khoảng 12%.',mods:{workout:1.4}},
{id:'thoNghe',name:'Có nghề trong tay',unlock:4,desc:'Giỏi các việc kỹ thuật và dịch vụ có tay nghề.',perk:'Thu nhập việc kỹ thuật +18%.',mods:{skilled:1.18}},
{id:'damLam',name:'Dám làm',unlock:6,desc:'Chấp nhận cơ hội khó để đổi lấy tốc độ tăng trưởng.',perk:'Việc rủi ro trả thêm 18%, biến cố xấu nặng hơn nhẹ.',mods:{risky:1.18}},
{id:'danBuon',name:'Máu kinh doanh',unlock:8,desc:'Nhìn thấy biên lợi nhuận và mở cơ sở nhanh hơn.',perk:'Chi phí mở kinh doanh -7%, lợi nhuận cơ sở +5%.',mods:{setup:.93,biz:1.05}},
{id:'quanHe',name:'Quan hệ rộng',unlock:11,desc:'Người quen thường mang tới mối gấp, việc ngon và cuộc gặp mới.',perk:'Mỗi ngày có thêm cơ hội; việc gấp dễ xuất hiện; hẹn hò hiệu quả hơn.',mods:{offers:1,love:1.08}},
{id:'laoDong',name:'Con nhà lao động',unlock:14,desc:'Không có vốn lớn nhưng được dạy cách sống chắc chắn.',perk:'Sức khỏe khởi đầu +10, tiền khởi đầu +200.000đ.',mods:{health:10,startCash:200000}},
{id:'tayTrang',name:'Tay trắng lì đòn',unlock:18,desc:'Khởi đầu khó nhất, dành cho hành trình thử thách.',perk:'Chỉ có 150.000đ nhưng Điểm sự nghiệp cuối hành trình +50%.',mods:{startCash:-350000,career:1.5}}
];
const FOODS=[
{id:'mi',name:'Mì + trứng ở phòng trọ',cost:18000,health:0,mood:-1,energy:12,desc:'Rẻ, đủ cầm cự nhưng không thể sống kiểu này mãi.'},
{id:'com',name:'Cơm bình dân',cost:42000,health:3,mood:1,energy:22,desc:'Lựa chọn cân bằng cho giai đoạn mưu sinh.'},
{id:'pho',name:'Phở / bún / cơm ngon',cost:75000,health:5,mood:3,energy:26,desc:'Ăn đàng hoàng, tinh thần cũng dễ chịu hơn.'},
{id:'ngon',name:'Một bữa tử tế',cost:180000,health:6,mood:8,energy:28,desc:'Không chỉ no mà còn là cảm giác cuộc sống đang khá lên.'}
];
const WORKOUTS=[
{id:'walk',name:'Đi bộ / chạy nhẹ',cost:0,health:4,mood:3,energy:12,desc:'Không tốn tiền, cần chút thời gian và kỷ luật.'},
{id:'park',name:'Tập công viên',cost:15000,health:6,mood:4,energy:16,desc:'Xà đơn, chạy bộ, vài bài thể lực cơ bản.'},
{id:'martial',name:'Đi học võ',cost:80000,health:9,mood:7,energy:22,desc:'Tốn hơn nhưng vừa khỏe vừa giải tỏa đầu óc.'},
{id:'gym',name:'Tập gym',cost:120000,health:8,mood:6,energy:20,desc:'Ổn định thể lực khi công việc bắt đầu bận.'}
];
const HOUSING=[
{id:'tro',name:'Phòng trọ 12m²',kind:'rent',price:0,monthly:900000,quality:0,mood:0,energy:0,minNet:0,desc:'Nhỏ, nóng, nhưng là chỗ để bắt đầu.'},
{id:'troTot',name:'Phòng trọ sạch sẽ',kind:'rent',price:0,monthly:2200000,quality:1,mood:2,energy:4,minNet:8000000,desc:'Có máy lạnh, bếp nhỏ, ngủ ngon hơn.'},
{id:'chungCuThue',name:'Căn hộ thuê',kind:'rent',price:0,monthly:7500000,quality:2,mood:5,energy:7,minNet:50000000,desc:'Một bước chuyển rõ rệt về chất lượng sống.'},
{id:'chungCuMua',name:'Căn hộ sở hữu',kind:'buy',price:1800000000,monthly:2500000,quality:3,mood:7,energy:8,minNet:800000000,desc:'Có chỗ ở của mình; vẫn có phí quản lý và bảo trì.'},
{id:'nhaPho',name:'Nhà phố',kind:'buy',price:5500000000,monthly:4500000,quality:4,mood:10,energy:9,minNet:2500000000,desc:'Ổn định cho gia đình và mở nhiều lựa chọn xã hội.'},
{id:'bietThu',name:'Biệt thự',kind:'buy',price:18000000000,monthly:12000000,quality:5,mood:14,energy:10,minNet:9000000000,desc:'Không làm bạn thắng game, nhưng cho thấy bạn đã bước sang một tầng đời khác.'}
];
const VEHICLES=[
{id:'none',name:'Đi bộ / xe buýt',price:0,monthly:120000,resale:.0,tier:0,desc:'Chậm nhưng chưa tạo gánh nặng.'},
{id:'bike',name:'Xe đạp cũ',price:900000,monthly:50000,resale:.35,tier:1,desc:'Mở thêm vài việc giao hàng gần.'},
{id:'motorOld',name:'Xe máy cũ',price:5500000,monthly:450000,resale:.55,tier:2,desc:'Mốc đời quan trọng: bắt đầu chạy dịch vụ nghiêm túc.'},
{id:'motor',name:'Xe máy tốt',price:28000000,monthly:850000,resale:.62,tier:3,desc:'Ít hư, uy tín dịch vụ tốt hơn.'},
{id:'carOld',name:'Ô tô cũ',price:320000000,monthly:5500000,resale:.58,tier:4,desc:'Mở một số cơ hội khách hàng và đời sống mới.'},
{id:'car',name:'Ô tô gia đình',price:850000000,monthly:9000000,resale:.62,tier:5,desc:'Tốt cho gia đình, gặp khách và vị thế xã hội.'},
{id:'van',name:'Xe tải van',price:520000000,monthly:11000000,resale:.60,tier:5,desc:'Tài sản làm ăn, mở việc vận chuyển hàng nhỏ.'}
];
const JOBS=[
{id:'vechai',name:'Nhặt ve chai cuối buổi chợ',pay:[90000,170000],energy:24,health:2,rep:0,tier:0,vehicle:0,kind:'basic',desc:'Giấy carton, lon, nhựa. Ít vốn, đổi sức lấy tiền.'},
{id:'bocHang',name:'Bốc hàng chợ đầu mối',pay:[170000,300000],energy:34,health:4,rep:1,tier:0,vehicle:0,kind:'risky',desc:'Nặng nhưng trả ngay trong ngày.'},
{id:'ruaXe',name:'Phụ rửa xe',pay:[140000,250000],energy:26,health:2,rep:1,tier:0,vehicle:0,kind:'basic',desc:'Chủ tiệm đang thiếu người một ca.'},
{id:'chayBan',name:'Chạy bàn tiệc cưới',pay:[180000,320000],energy:30,health:2,rep:1,tier:0,vehicle:0,kind:'basic',desc:'Ca tối, đông nhưng thường có thêm tiền bo.'},
{id:'giaoPho',name:'Giao phở buổi sáng',pay:[180000,330000],energy:25,health:1,rep:1,tier:1,vehicle:1,kind:'basic',desc:'Quán cô Năm cần giao vài chục tô quanh khu.'},
{id:'shipShop',name:'Ship đơn shop quần áo',pay:[260000,480000],energy:29,health:2,rep:2,tier:1,vehicle:2,kind:'basic',desc:'Đi nhiều điểm, tiền khá hơn nếu chạy gọn.'},
{id:'giaoCom',name:'Giao cơm văn phòng',pay:[280000,520000],energy:30,health:2,rep:2,tier:1,vehicle:2,kind:'basic',desc:'Khung giờ gắt nhưng đơn đều.'},
{id:'gaRan',name:'Giao gà rán & đồ ăn tối',pay:[300000,560000],energy:31,health:2,rep:2,tier:1,vehicle:2,kind:'basic',desc:'Đông nhất khi trời mưa hoặc cuối tuần.'},
{id:'xeOm',name:'Chạy xe ôm ứng dụng',pay:[320000,620000],energy:35,health:3,rep:2,tier:1,vehicle:2,kind:'risky',desc:'Thu nhập tốt hơn, đổi lại chạy đường nhiều.'},
{id:'binhNuoc',name:'Chở bình nước cho đại lý',pay:[360000,680000],energy:35,health:4,rep:2,tier:2,vehicle:2,kind:'risky',desc:'Nặng, đều tiền, quen được nhiều chủ cửa hàng.'},
{id:'dienMay',name:'Phụ lắp điện máy',pay:[420000,760000],energy:30,health:2,rep:3,tier:2,vehicle:2,kind:'skilled',minRep:8,desc:'Cần biết việc và giữ lời hẹn với khách.'},
{id:'chuyenNha',name:'Phụ chuyển nhà',pay:[500000,900000],energy:40,health:5,rep:3,tier:2,vehicle:2,kind:'risky',minRep:10,desc:'Một ngày mệt nhưng thu nhập đã khác trước.'},
{id:'giaoHangVan',name:'Nhận tuyến giao hàng bằng van',pay:[750000,1350000],energy:34,health:2,rep:4,tier:3,vehicle:5,kind:'skilled',minRep:22,needVan:true,desc:'Khách doanh nghiệp nhỏ trả theo tuyến.'}
];
const BUSINESSES=[
{id:'toThuGom',name:'Tổ thu gom ve chai',cost:4500000,rep:3,level:1,gross:[450000,750000],op:.36,staff:1,salary:5500000,max:3,desc:'Thuê 1 người đi gom, bạn lo đầu mối và bán lại.'},
{id:'banhMi',name:'Xe bánh mì',cost:14000000,rep:6,level:1,gross:[700000,1250000],op:.55,staff:1,salary:6500000,max:4,desc:'Đồ ăn sáng rất đời; lời vừa phải và sớm bão hòa.'},
{id:'caPhe',name:'Xe cà phê mang đi',cost:19000000,rep:7,level:1,gross:[850000,1450000],op:.57,staff:1,salary:6500000,max:4,desc:'Đẹp vị trí thì bán tốt, nhưng cạnh tranh dày.'},
{id:'daiLyNuoc',name:'Đại lý nước uống nhỏ',cost:38000000,rep:10,level:2,gross:[1400000,2400000],op:.60,staff:2,salary:7000000,max:3,desc:'Có khách lẻ và khách văn phòng; xe máy tốt giúp vận hành.'},
{id:'doiGiaoHang',name:'Đội giao hàng nội quận',cost:52000000,rep:12,level:2,gross:[1900000,3300000],op:.54,staff:4,salary:7200000,max:3,desc:'Bạn bắt đầu kiếm tiền bằng tổ chức người khác chạy.'},
{id:'ruaXeBiz',name:'Tiệm rửa xe',cost:70000000,rep:14,level:2,gross:[2100000,3600000],op:.50,staff:3,salary:7500000,max:2,desc:'Dòng tiền khá đều, khó tăng quá lớn nếu chỉ một điểm.'},
{id:'bepCom',name:'Bếp cơm văn phòng',cost:145000000,rep:18,level:3,gross:[5200000,8200000],op:.66,staff:6,salary:7800000,max:2,desc:'Hợp đồng suất ăn đưa bạn sang kinh doanh có hệ thống.'},
{id:'gara',name:'Gara xe máy',cost:210000000,rep:22,level:3,gross:[6500000,10500000],op:.60,staff:7,salary:8500000,max:2,desc:'Tay nghề, phụ tùng và uy tín quyết định khách quay lại.'},
{id:'khoThucPham',name:'Kho thực phẩm & phân phối',cost:360000000,rep:28,level:4,gross:[10000000,17000000],op:.70,staff:9,salary:9000000,max:2,desc:'Biên không quá dày nhưng doanh thu lớn hơn rõ rệt.'},
{id:'logistics',name:'Công ty giao nhận nội thành',cost:720000000,rep:35,level:4,gross:[21000000,36000000],op:.73,staff:18,salary:10500000,max:2,desc:'Không còn chạy từng đơn; bạn quản đội xe, khách và dòng tiền.'},
{id:'chuoiDoAn',name:'Chuỗi đồ ăn nhanh Việt',cost:1800000000,rep:48,level:5,gross:[55000000,90000000],op:.77,staff:42,salary:11000000,max:2,desc:'Bánh mì, cơm, bún, đồ uống thành một chuỗi vận hành thật.'},
{id:'phanPhoi',name:'Công ty phân phối hàng tiêu dùng',cost:4200000000,rep:62,level:6,gross:[130000000,210000000],op:.81,staff:85,salary:12500000,max:2,desc:'Doanh thu rất lớn nhưng lợi nhuận biên vẫn không vô hạn.'},
{id:'tapDoan',name:'Hệ sinh thái logistics & bán lẻ',cost:12000000000,rep:78,level:7,gross:[380000000,620000000],op:.85,staff:220,salary:14500000,max:1,desc:'Late game: nhiều tiền hơn nhưng trách nhiệm và chi phí cũng ở quy mô khác.'}
];
const PARTNERS=[
{id:'mai',gender:'female',name:'Mai',trait:'Thực tế',monthly:3500000,desc:'Không đòi hỏi hào nhoáng, nhưng rất coi trọng sự ổn định và kế hoạch tương lai.'},
{id:'lan',gender:'female',name:'Lan',trait:'Tham vọng',monthly:5200000,desc:'Thích người có chí làm ăn; đôi khi mở ra cơ hội kinh doanh mới.'},
{id:'vy',gender:'female',name:'Vy',trait:'Tình cảm',monthly:3000000,desc:'Cần thời gian bên nhau hơn là quà đắt tiền.'},
{id:'minh',gender:'male',name:'Minh',trait:'Điềm đạm',monthly:3600000,desc:'Sống có kế hoạch, coi trọng sức khỏe và gia đình.'},
{id:'khoa',gender:'male',name:'Khoa',trait:'Năng động',monthly:4800000,desc:'Thích trải nghiệm, du lịch và những quyết định táo bạo.'},
{id:'nam',gender:'male',name:'Nam',trait:'Thực tế',monthly:3200000,desc:'Ưu tiên nền tảng tài chính chắc và cuộc sống gọn gàng.'}
];
const RANDOM_NAMES=['An','Bình','Chi','Duy','Hân','Hải','Khang','Linh','Minh','My','Nam','Ngân','Phúc','Quân','Thảo','Vy'];
const TABS=[['tongquan','Tổng quan'],['vieclam','Việc làm'],['doisong','Đời sống'],['sunghiep','Sự nghiệp'],['tinhcam','Tình cảm'],['taisan','Tài sản'],['nhatky','Nhật ký']];
const GAME_VERSION=2;
let state=null,meta=loadMeta(),slot=1,tab='tongquan',modal=null,cashFxQueue=[];
const DAY_BOUNDARY=1500; // 01:00 sáng hôm sau. Một "ngày chơi" kết thúc tại mốc này.
const DEFAULT_WAKE=330; // 05:30
const WEEKDAYS=['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ Nhật'];
const FOOD_TIME={mi:15,com:25,pho:35,ngon:60};
const WORKOUT_TIME={walk:45,park:60,martial:90,gym:75};
const WEATHER=[
 {id:'clear',name:'Trời dịu',icon:'☀',desc:'Đi lại bình thường.',travel:1,pay:1,health:1},
 {id:'hot',name:'Nắng nóng',icon:'☀',desc:'Làm ngoài đường mệt hơn một chút.',travel:1.03,pay:1,health:1.15},
 {id:'rain',name:'Mưa',icon:'☂',desc:'Đơn giao hàng trả tốt hơn nhưng đi chậm hơn.',travel:1.12,pay:1.15,health:1.25},
 {id:'storm',name:'Mưa lớn',icon:'☔',desc:'Đơn giao hàng rất có giá, đổi lại sức khỏe hao nhanh.',travel:1.22,pay:1.28,health:1.55}
];
const AREAS={
 tro:'Khu trọ',cho:'Chợ đầu mối',danCu:'Khu dân cư',vanPhong:'Khu văn phòng',trungTam:'Trung tâm',benXe:'Bến xe',kcn:'Khu công nghiệp',ngoaiThanh:'Ngoại thành'
};
const JOB_TIME={
 vechai:{windows:[[480,1110]],duration:[80,145],area:'cho',travel:.25,tag:'Linh hoạt'},
 bocHang:{windows:[[270,510],[1260,1490]],duration:[120,210],area:'cho',travel:.15,tag:'Ca nặng'},
 ruaXe:{windows:[[480,1080]],duration:[180,300],area:'danCu',travel:.15,tag:'Theo ca'},
 chayBan:{windows:[[960,1320]],duration:[240,360],area:'trungTam',travel:.18,tag:'Ca tối'},
 giaoPho:{windows:[[300,535]],duration:[40,65],area:'danCu',travel:.72,tag:'Buổi sáng',delivery:true},
 shipShop:{windows:[[540,1140]],duration:[90,175],area:'trungTam',travel:.78,tag:'Nhiều điểm',delivery:true},
 giaoCom:{windows:[[600,780]],duration:[60,105],area:'vanPhong',travel:.82,tag:'Giờ trưa',delivery:true},
 gaRan:{windows:[[1020,1410]],duration:[80,155],area:'danCu',travel:.80,tag:'Buổi tối',delivery:true},
 xeOm:{windows:[[360,1425],[60,180]],duration:[60,180],area:'trungTam',travel:.88,tag:'Linh hoạt',delivery:true},
 binhNuoc:{windows:[[420,1020]],duration:[120,210],area:'danCu',travel:.55,tag:'Hàng nặng'},
 dienMay:{windows:[[480,1020]],duration:[100,195],area:'danCu',travel:.42,tag:'Có tay nghề'},
 chuyenNha:{windows:[[420,960]],duration:[180,330],area:'ngoaiThanh',travel:.35,tag:'Theo chuyến'},
 giaoHangVan:{windows:[[480,1080]],duration:[180,285],area:'kcn',travel:.68,tag:'Tuyến doanh nghiệp',delivery:true},
 hoSoGap:{windows:[[480,960]],duration:[35,55],area:'vanPhong',travel:.84,tag:'Việc gấp',delivery:true},
 giaoChaoDem:{windows:[[1320,1480]],duration:[45,70],area:'danCu',travel:.82,tag:'Ca đêm',delivery:true,night:true},
 benXeDem:{windows:[[1260,1470]],duration:[75,110],area:'benXe',travel:.92,tag:'Cuốc đêm',delivery:true,night:true},
 bocRauSom:{windows:[[270,420]],duration:[120,170],area:'cho',travel:.10,tag:'Chợ sớm'}
};
const EXTRA_JOBS=[
 {id:'hoSoGap',name:'Giao hồ sơ gấp cho công ty',pay:[180000,420000],energy:15,health:1,rep:2,tier:1,vehicle:2,kind:'skilled',minRep:4,desc:'Chuyến ngắn nhưng khách trả cho độ gấp và đúng giờ, không phải cho số phút.'},
 {id:'giaoChaoDem',name:'Giao cháo & đồ ăn khuya',pay:[150000,330000],energy:18,health:2,rep:1,tier:1,vehicle:2,kind:'basic',desc:'Đêm muộn ít đơn nhưng phụ phí khá. Cày thêm thì có tiền, đổi lại cơ thể phải trả giá.'},
 {id:'benXeDem',name:'Chở khách ra bến xe đêm',pay:[280000,650000],energy:24,health:3,rep:2,tier:2,vehicle:2,kind:'risky',minRep:6,desc:'Không lâu bằng một ca làm, nhưng giờ xấu nên thu nhập có thể rất khá.'},
 {id:'bocRauSom',name:'Bốc rau chuyến chợ sớm',pay:[220000,380000],energy:31,health:4,rep:1,tier:0,vehicle:0,kind:'risky',desc:'Việc bắt đầu rất sớm; ai dậy đúng giờ mới có phần.'}
];
const ALL_JOBS=[...JOBS,...EXTRA_JOBS];

function defaultMeta(){return{version:GAME_VERSION,runs:0,totalDays:0,careerPoints:0,bestNetWorth:0,milestones:[],history:[],unlockedTraits:['benbi','tietkiem','kheomieng']};}
function loadMeta(){try{const d=defaultMeta(),x=Object.assign(d,JSON.parse(localStorage.getItem(META_KEY)||'{}'));x.unlockedTraits=x.unlockedTraits||d.unlockedTraits;x.milestones=x.milestones||[];syncTraitUnlocks(x);return x;}catch{return defaultMeta();}}
function saveMeta(){localStorage.setItem(META_KEY,JSON.stringify(meta));}
function loadSlot(i){try{return JSON.parse(localStorage.getItem(SLOT_KEY(i)));}catch{return null;}}
function save(){if(!state)return;state.updatedAt=Date.now();localStorage.setItem(SLOT_KEY(slot),JSON.stringify(state));}
function eraseSlot(i){localStorage.removeItem(SLOT_KEY(i));}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a;}
function pick(a){return a[Math.floor(Math.random()*a.length)];}
function fmt(v){const n=Math.abs(Math.round(v)),sign=v<0?'-':'';if(n>=1000000000)return sign+(n/1000000000).toLocaleString('vi-VN',{maximumFractionDigits:2})+' tỷ';if(n>=1000000)return sign+(n/1000000).toLocaleString('vi-VN',{maximumFractionDigits:1})+' tr';if(n>=1000)return sign+Math.round(n/1000).toLocaleString('vi-VN')+'k';return sign+n.toLocaleString('vi-VN')+'đ';}
function fmtDuration(m){m=Math.max(0,Math.round(m));const h=Math.floor(m/60),r=m%60;if(!h)return `${r} phút`;if(!r)return `${h} giờ`;return `${h}g ${r}p`;}
function timeLabel(m=state?.clock||DEFAULT_WAKE){const x=((Math.round(m)%1440)+1440)%1440;return `${String(Math.floor(x/60)).padStart(2,'0')}:${String(x%60).padStart(2,'0')}`;}
function weekday(day=state?.day||1){return WEEKDAYS[(day-1)%7];}
function trait(){return TRAITS.find(x=>x.id===state?.trait)||TRAITS[0];}
function vehicle(){return VEHICLES.find(x=>x.id===state?.vehicle)||VEHICLES[0];}
function home(){return HOUSING.find(x=>x.id===state?.housing)||HOUSING[0];}
function partner(){return PARTNERS.find(x=>x.id===state?.relationship?.partnerId)||null;}
function playerAge(s=state){return 20+Math.floor(((s?.day||1)-1)/DAYS_PER_YEAR);}
function childAge(c){return Math.max(0,Math.floor((state.day-c.birthDay)/DAYS_PER_YEAR));}
function businessCount(){return Object.values(state?.businesses||{}).reduce((a,b)=>a+b,0);}
function totalStaff(){let n=0;for(const b of BUSINESSES)n+=(state?.businesses?.[b.id]||0)*b.staff;return n;}
function netWorth(s=state){if(!s)return 0;let n=s.cash-(s.debt||0);const v=VEHICLES.find(x=>x.id===s.vehicle);if(v)n+=v.price*v.resale;const h=HOUSING.find(x=>x.id===s.housing);if(h?.kind==='buy')n+=h.price*.82;for(const b of BUSINESSES)n+=(s.businesses?.[b.id]||0)*b.cost*.60;return Math.round(n);}
function livingMultiplier(){return trait().mods.living||1;}
function incomeMultiplier(job){let m=1;if(job.kind==='skilled')m*=trait().mods.skilled||1;if(job.kind==='risky')m*=trait().mods.risky||1;return m;}
function weather(){return WEATHER.find(w=>w.id===state?.weather)||WEATHER[0];}
function changeCash(delta,label='Giao dịch',animate=true){if(!state||!Number.isFinite(delta)||!delta)return;state.cash+=Math.round(delta);if(delta>0)state.stats.earned+=Math.round(delta);else state.stats.spent+=Math.abs(Math.round(delta));if(animate)cashFxQueue.push({delta:Math.round(delta),label});}
function flushCashFx(){if(!cashFxQueue.length)return;const anchor=document.querySelector('[data-cash-anchor]');if(!anchor){cashFxQueue=[];return;}const r=anchor.getBoundingClientRect();cashFxQueue.splice(0,8).forEach((fx,i)=>setTimeout(()=>{const el=document.createElement('div');el.className=`money-fx ${fx.delta>0?'gain':'loss'}`;el.innerHTML=`${fx.delta>0?'+':'−'}${fmt(Math.abs(fx.delta))}<small>${esc(fx.label)}</small>`;el.style.left=`${Math.max(8,Math.min(window.innerWidth-180,r.left+r.width/2-60+(i%3-1)*18))}px`;el.style.top=`${Math.max(74,r.bottom+4)}px`;document.body.appendChild(el);setTimeout(()=>el.remove(),2550);},i*170));}
function log(text,type='normal'){if(!state)return;state.journal.unshift({day:state.day,time:timeLabel(),text,type});state.journal=state.journal.slice(0,220);}
function news(title,text,type='Đời sống'){state.news.unshift({day:state.day,time:timeLabel(),title,text,type});state.news=state.news.slice(0,40);}
function syncTraitUnlocks(m=meta){for(const t of TRAITS)if((m.careerPoints||0)>=t.unlock&&!m.unlockedTraits.includes(t.id))m.unlockedTraits.push(t.id);}
function careerPoint(key,label){if(meta.milestones.includes(key))return;meta.milestones.push(key);meta.careerPoints++;syncTraitUnlocks(meta);saveMeta();news('Điểm sự nghiệp',`${label}. Bạn nhận +1 Điểm sự nghiệp dùng để mở lối sống cho các hành trình sau.`,'Roguelite');}
function milestone(key,title,text){if(state.milestones.includes(key))return false;state.milestones.push(key);state.storyFlags[key]=true;news(title,text,'Cột mốc');log(`${title}: ${text}`,'good');careerPoint(key,title);return true;}
function randomWeather(){const roll=Math.random();return roll<.53?'clear':roll<.70?'hot':roll<.92?'rain':'storm';}

function createState(name,gender,pref,traitId){
 const t=TRAITS.find(x=>x.id===traitId)||TRAITS[0],start=500000+(t.mods.startCash||0);
 const s={version:GAME_VERSION,status:'playing',name:name||'Linh',gender,pref,trait:t.id,day:1,clock:360,cash:Math.max(150000,start),debt:0,
 health:clamp(86+(t.mods.health||0),1,100),mood:72,energy:92,reputation:0,vehicle:'none',housing:'tro',housingOwned:false,nextHousingDue:15,
 ateToday:false,mealsToday:0,workoutToday:false,workCountToday:0,dateToday:false,familyToday:false,managementToday:false,managementBonus:0,awakeMinutes:30,lastSleepHours:7.5,sleepDebt:0,lateWorkStreak:0,
 businesses:{},jobOffers:[],relationship:{status:'single',partnerId:null,love:0,metDay:null,lastDateDay:-99},children:[],events:[],news:[],journal:[],milestones:[],storyFlags:{},
 stats:{earned:0,spent:0,jobsDone:0,businessRevenue:0,bestCash:start,maxNet:0,daysWorked:0,lateJobs:0,hoursWorked:0,hoursSlept:0},
 weather:randomWeather(),createdAt:Date.now(),updatedAt:Date.now(),monthlyReport:null,consecutiveNoFood:0,hospitalVisits:0,lastDayResult:null};
 state=s;refreshJobs(true);
 s.events.push({title:'Ngày đầu ở thành phố',text:`06:00. Bạn kéo chiếc ba lô vào phòng trọ 12m². Trong túi có ${fmt(s.cash)}. Cô Út chủ trọ cho khất tiền phòng tới Ngày 15. Thành phố không chờ ai: chợ đã mở từ sáng sớm, quán phở đang thiếu người giao, nhưng 24 giờ của bạn cũng chỉ có từng ấy.`,type:'Mở đầu',choices:[{label:'Ra ngoài xem việc đang mở',effect:{mood:2}},{label:'Ăn nhẹ rồi tính đường dài',effect:{health:1}}]});
 return s;
}
function migrateState(s){
 if(!s)return null;
 s.version=GAME_VERSION;s.clock=Number.isFinite(s.clock)?s.clock:360;s.debt=s.debt||0;s.businesses=s.businesses||{};s.children=s.children||[];s.news=s.news||[];s.journal=s.journal||[];s.events=s.events||[];s.milestones=s.milestones||[];s.storyFlags=s.storyFlags||{};
 s.relationship=s.relationship||{status:'single',partnerId:null,love:0,metDay:null,lastDateDay:-99};s.stats=Object.assign({earned:0,spent:0,jobsDone:0,businessRevenue:0,bestCash:s.cash||0,maxNet:0,daysWorked:0,lateJobs:0,hoursWorked:0,hoursSlept:0},s.stats||{});
 s.jobOffers=s.jobOffers||[];s.nextHousingDue=s.nextHousingDue||s.day+15;s.weather=s.weather||randomWeather();s.mealsToday=s.mealsToday??(s.ateToday?1:0);s.familyToday=!!s.familyToday;s.managementToday=!!s.managementToday;s.managementBonus=s.managementBonus||0;s.awakeMinutes=s.awakeMinutes||60;s.lastSleepHours=s.lastSleepHours||7;s.sleepDebt=s.sleepDebt||0;s.lateWorkStreak=s.lateWorkStreak||0;
 return s;
}

function startScreen(){
 state=null;const slots=[1,2,3].map(i=>({i,s:migrateState(loadSlot(i))}));
 app.innerHTML=`<div class="shell"><div class="slot-wrap"><div class="row" style="justify-content:flex-end"><button class="btn" id="guideBtn">Cách chơi & cơ chế</button><button class="btn" id="exitGameBtn">Đóng game</button></div>
 <div class="hero"><div class="brand-mark" style="margin:auto">ĐỜI</div><h1>Đời Lập Nghiệp</h1><p>Game số liệu về một cuộc đời Việt Nam: bạn không chỉ kiếm tiền, mà phải quyết định dùng thời gian để kiếm tiền, giữ sức, yêu, nuôi gia đình và dần mua lại chính thời gian của mình.</p><div class="row hero-tags"><span class="tag good">Đồng hồ 24 giờ</span><span class="tag">3 ô lưu</span><span class="tag">10 lối sống Roguelite</span><span class="tag">Mobile friendly</span></div></div>
 <div class="grid"><div class="card"><h2>Vòng chơi cốt lõi</h2><div class="brief"><div class="brief-item"><strong>1. Mỗi việc lấy đi thời gian thật</strong><span class="muted mini">Giao phở có thể mất 45–60 phút, chạy bàn mất cả buổi. Việc ngắn không đồng nghĩa lương thấp.</span></div><div class="brief-item"><strong>2. 22:00 trở đi là quyết định</strong><span class="muted mini">Bạn vẫn được cày đêm để kiếm thêm, nhưng sức khỏe và giấc ngủ sẽ trả giá. 01:00 game tự sang ngày mới nếu vẫn thức.</span></div><div class="brief-item"><strong>3. Ngủ là cách chủ động kết thúc ngày</strong><span class="muted mini">Ngủ sớm thường dậy 05:30–06:00; ngủ quá khuya thì hôm sau dậy muộn và bỏ lỡ việc sáng.</span></div><div class="brief-item"><strong>4. Tiền mở cuộc sống, cuộc sống lấy lại tiền & giờ</strong><span class="muted mini">Xe, nhà, tình yêu, cưới, con cái và doanh nghiệp chỉ mở dần khi bạn đủ khả năng gánh.</span></div></div></div>
 <div class="card"><h2>Roguelite nhẹ</h2><p class="mini muted">Mỗi hành trình chọn một lối sống. Cột mốc tạo Điểm sự nghiệp để mở thêm tính cách cho ván sau; không có chuyện cộng sẵn hàng đống tiền khiến mất cảm giác đi lên.</p><div class="row"><span class="tag">${meta.unlockedTraits.length}/10 đã mở</span><span class="tag">${meta.careerPoints} Điểm sự nghiệp</span></div><button class="btn guide-inline" id="guideBtn2">Xem toàn bộ cơ chế cơ bản</button></div></div>
 <div class="career"><div class="card"><span class="mini muted">Hành trình</span><div class="kpi">${meta.runs}</div></div><div class="card"><span class="mini muted">Ngày đã sống</span><div class="kpi">${meta.totalDays}</div></div><div class="card"><span class="mini muted">Điểm sự nghiệp</span><div class="kpi">${meta.careerPoints}</div></div><div class="card"><span class="mini muted">Tài sản kỷ lục</span><div class="kpi">${fmt(meta.bestNetWorth)}</div></div></div>
 <h2>3 ô lưu</h2><div class="grid3">${slots.map(x=>slotCard(x.i,x.s)).join('')}</div>
 <div class="card" style="margin-top:10px"><h2>10 lối sống</h2><div class="row">${TRAITS.map(t=>`<span class="tag ${meta.unlockedTraits.includes(t.id)?'good':'warn'}" title="${esc(t.perk)}">${meta.unlockedTraits.includes(t.id)?'✓':'🔒'} ${t.name}</span>`).join('')}</div></div><div class="footer-note">Dữ liệu game lưu riêng trong trình duyệt, không ảnh hưởng KanBan hoặc Thương Lộ Việt.</div></div></div>`;
 bindStart();
}
function slotCard(i,s){if(!s)return `<div class="card slot empty"><div><span class="tag">Ô ${i}</span><h3>Chưa có cuộc đời</h3><p class="muted mini">Bắt đầu lúc 06:00 với phòng trọ và số vốn rất nhỏ.</p></div><button class="btn primary" data-new="${i}">Bắt đầu</button></div>`;return `<div class="card slot"><div><div class="row between"><span class="tag">Ô ${i}</span><span class="time-chip">${timeLabel(s.clock||360)}</span></div><h3>${esc(s.name)}</h3><div class="big">${fmt(netWorth(s))}</div><div class="mini muted">Ngày ${s.day} · ${playerAge(s)} tuổi · ${TRAITS.find(t=>t.id===s.trait)?.name||''}</div><div class="mini muted">${s.status==='playing'?'Đang sống hành trình':'Đã kết thúc'}</div></div><div class="slot-actions"><button class="btn primary" data-load="${i}">Tiếp tục</button><button class="btn danger" data-delete="${i}">Xóa</button></div></div>`;}
function bindStart(){document.querySelector('#exitGameBtn')?.addEventListener('click',closeGame);document.querySelector('#guideBtn')?.addEventListener('click',showGuide);document.querySelector('#guideBtn2')?.addEventListener('click',showGuide);document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>openNew(Number(b.dataset.new)));document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>openSlot(Number(b.dataset.load)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Xóa hẳn ô lưu này?')){eraseSlot(Number(b.dataset.delete));startScreen();}});}
function showGuide(){openModal(`<div class="modal-card guide-modal"><div class="row between"><div><span class="tag good">Cơ chế cơ bản</span><h2 style="margin-top:8px">Cách sống một ngày trong Đời Lập Nghiệp</h2></div><button class="btn" id="closeGuide">Đóng</button></div><div class="guide-grid">
 <div class="guide-step"><b>⏱ 1. Đồng hồ là tài nguyên</b><span>Mỗi việc, bữa ăn, buổi tập hay cuộc hẹn đều trừ phút. Hành động nhảy thời gian ngay, không bắt bạn ngồi chờ.</span></div>
 <div class="guide-step"><b>💼 2. Việc có giờ mở</b><span>Phở buổi sáng, cơm văn phòng buổi trưa, tiệc cưới buổi tối, cuốc đêm sau 22:00. Trễ giờ là mất cơ hội hôm đó.</span></div>
 <div class="guide-step"><b>🌙 3. Có thể cày sau 22:00</b><span>Game không cấm. Việc đêm thường có phụ phí, nhưng hao sức và tạo thiếu ngủ. Nếu vẫn thức tới 01:00, ngày mới tự bắt đầu.</span></div>
 <div class="guide-step"><b>🛏 4. Về nghỉ</b><span>Bấm Về nghỉ để ngủ thẳng tới sáng. Ngủ càng trễ càng dậy muộn; ngủ đủ hồi sức tốt và giữ nhịp dài hạn.</span></div>
 <div class="guide-step"><b>🛵 5. Tài sản mua lại thời gian</b><span>Xe tốt rút ngắn phần di chuyển của công việc. Ô tô không phải lúc nào nhanh hơn xe máy vì kẹt xe/đậu xe; xe tải mở việc riêng.</span></div>
 <div class="guide-step"><b>☔ 6. Thời tiết & ngày trong tuần</b><span>Mưa làm đơn giao hàng trả cao hơn nhưng lâu và mệt hơn. Cuối tuần thiên về ăn uống/tiệc; ngày thường thiên về văn phòng.</span></div>
 <div class="guide-step"><b>❤️ 7. Cuộc sống mở dần</b><span>Tình yêu chỉ xuất hiện khi bạn đã có nền. Hẹn hò, cưới và con cái lấy cả tiền lẫn thời gian, nhưng không bị ép mở sớm.</span></div>
 <div class="guide-step"><b>🏪 8. Từ bán giờ sang mua giờ</b><span>Đầu game bạn bán sức và thời gian. Giữa game thuê người. Cuối game doanh nghiệp tự tạo tiền, còn bạn chọn gặp khách, chăm gia đình hay mở ngành mới.</span></div>
 <div class="guide-step"><b>🧬 9. 10 lối sống Roguelite</b><span>Mỗi lối sống đổi cách đi đường dài. Hoàn thành cột mốc cho Điểm sự nghiệp để mở thêm lựa chọn ở hành trình mới.</span></div>
 <div class="guide-step"><b>💾 10. 3 ô lưu độc lập</b><span>Mỗi ô là một cuộc đời riêng. Save tự động sau hành động; xóa dữ liệu trình duyệt sẽ xóa save.</span></div></div></div>`);document.querySelector('#closeGuide').onclick=closeModal;}
function openNew(i){slot=i;const traitCards=TRAITS.map(t=>`<button type="button" class="trait ${meta.unlockedTraits.includes(t.id)?'':'locked'}" data-trait="${t.id}" ${meta.unlockedTraits.includes(t.id)?'':`title="Cần ${t.unlock} Điểm sự nghiệp"`}><b>${meta.unlockedTraits.includes(t.id)?'':'🔒 '}${t.name}</b><span class="mini muted">${t.desc}</span><span class="mini"><b>Lợi thế:</b> ${t.perk}</span>${meta.unlockedTraits.includes(t.id)?'':`<span class="mini muted">Mở ở ${t.unlock} điểm · hiện có ${meta.careerPoints}</span>`}</button>`).join('');openModal(`<div class="modal-card"><h2>Tạo cuộc đời mới · Ô ${i}</h2><div class="form-grid"><label>Tên nhân vật<input id="playerName" value="Linh" maxlength="24"></label><label>Giới tính<select id="playerGender"><option value="male">Nam</option><option value="female">Nữ</option><option value="other">Khác / không đặt nặng</option></select></label><label>Muốn hẹn hò với<select id="pref"><option value="female">Nữ</option><option value="male">Nam</option><option value="any">Bất kỳ</option></select></label><label>Nhịp đời<div class="brief-item" style="margin-top:4px">120 ngày game ≈ 1 tuổi</div></label></div><h3 style="margin-top:14px">Chọn 1 lối sống cho hành trình này</h3><div class="trait-grid">${traitCards}</div><div class="row" style="margin-top:12px"><button class="btn" id="cancelNew">Hủy</button><button class="btn primary" id="createNew">Bắt đầu lúc 06:00</button></div></div>`);let chosen=meta.unlockedTraits[0]||'benbi';const setChoice=id=>{chosen=id;document.querySelectorAll('.trait').forEach(x=>x.classList.toggle('selected',x.dataset.trait===id));};setChoice(chosen);document.querySelectorAll('.trait:not(.locked)').forEach(b=>b.onclick=()=>setChoice(b.dataset.trait));document.querySelector('#cancelNew').onclick=closeModal;document.querySelector('#createNew').onclick=()=>{state=createState(document.querySelector('#playerName').value.trim()||'Linh',document.querySelector('#playerGender').value,document.querySelector('#pref').value,chosen);tab='tongquan';save();closeModal();renderGame();showPendingEvent();};}
function openSlot(i){const s=migrateState(loadSlot(i));if(!s)return;slot=i;state=s;tab='tongquan';if(!state.jobOffers.length)refreshJobs(true);renderGame();if(state.events.length)showPendingEvent();}

function renderGame(){
 if(!state)return startScreen();
 const p=partner(),rel=state.relationship.status==='single'?'Độc thân':state.relationship.status==='dating'?`Đang yêu ${p?.name||''}`:state.relationship.status==='married'?`Đã kết hôn · ${p?.name||''}`:'Đang tìm hiểu',n=netWorth(),w=weather();
 state.stats.maxNet=Math.max(state.stats.maxNet||0,n);meta.bestNetWorth=Math.max(meta.bestNetWorth||0,n);saveMeta();
 const late=isLateTime();
 app.innerHTML=`<div class="shell"><div class="top"><div class="content"><div class="top-row"><div class="brand"><div class="brand-mark">ĐỜI</div><div><h1>${esc(state.name)}</h1><small>${trait().name} · ${rel}</small></div></div><div class="top-actions"><div class="clock-card ${late?'late':''}"><b>${timeLabel()}</b><span>Ngày ${state.day} · ${weekday()}</span></div><span class="weather-pill" title="${esc(w.desc)}">${w.icon} ${w.name}</span><button class="btn ghost" id="homeBtn">Ô lưu</button><button class="btn ghost" id="guideGameBtn">?</button><button class="btn primary next-btn" id="sleepBtn">Về nghỉ</button></div></div>
 <div class="stats"><div class="stat" data-cash-anchor><span>Tiền mặt</span><b>${fmt(state.cash)}</b></div><div class="stat"><span>Tài sản ròng</span><b>${fmt(n)}</b></div><div class="stat"><span>Sức khỏe</span><b>${Math.round(state.health)}/100</b><div class="progress ${state.health<35?'bad':''}"><i style="width:${clamp(state.health,0,100)}%"></i></div></div><div class="stat"><span>Tinh thần</span><b>${Math.round(state.mood)}/100</b><div class="progress"><i style="width:${clamp(state.mood,0,100)}%"></i></div></div><div class="stat"><span>Năng lượng</span><b>${Math.round(state.energy)}/100</b><div class="progress"><i style="width:${clamp(state.energy,0,100)}%"></i></div></div><div class="stat"><span>Thiếu ngủ</span><b>${state.sleepDebt?fmtDuration(state.sleepDebt):'Không'}</b><div class="progress ${state.sleepDebt>180?'bad':''}"><i style="width:${clamp(state.sleepDebt/360*100,0,100)}%"></i></div></div></div>
 ${late?`<div class="late-banner"><b>${state.clock>=1440||state.clock<300?'Đã qua nửa đêm':'Đã sau 22:00'}.</b> Bạn vẫn có thể làm việc. Thu nhập đêm có thể tốt, nhưng sức khỏe và giờ dậy sáng mai sẽ chịu tác động.</div>`:''}
 <div class="nav">${TABS.map(([id,label])=>`<button data-tab="${id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</div></div></div><div class="content">${viewForTab()}<div class="footer-note">Ngày chơi kết thúc lúc 01:00. Nếu chưa ngủ, game tự sang ngày mới nhưng cơ thể vẫn đang thức.</div></div><div class="mobile-dock"><button class="btn" id="mobileJobs">Việc làm</button><div class="dock-time"><b>${timeLabel()}</b><span>${weekday()}</span></div><button class="btn primary" id="mobileSleep">Về nghỉ</button></div></div>`;
 bindGame();setTimeout(flushCashFx,80);
}
function viewForTab(){return tab==='vieclam'?jobsView():tab==='doisong'?lifeView():tab==='sunghiep'?careerView():tab==='tinhcam'?relationshipView():tab==='taisan'?assetsView():tab==='nhatky'?journalView():overviewView();}
function overviewView(){const p=partner(),monthly=monthlyExpenseEstimate(),nextGoal=nextProgressGoal(),open=state.jobOffers.map(jobById).filter(Boolean).filter(j=>jobAvailability(j).state==='open').slice(0,3);return `<div class="grid"><div><div class="card"><div class="screen-title"><div><h2>${timeOfDayTitle()}</h2><div class="mini muted">${timeContextText()}</div></div><span class="tag">${timeLabel()} · ${weather().icon} ${weather().name}</span></div>${open.length?`<div class="grid3">${open.map(jobCard).join('')}</div>`:`<div class="empty-state">Không còn việc nào đang mở ngay lúc này. Bạn có thể xem việc sắp mở, ăn/tập, dành thời gian cho người thân hoặc về nghỉ.</div>`}</div><div class="card" style="margin-top:10px"><h2>Chặng đời tiếp theo</h2><div class="story hot"><div class="story-title">${esc(nextGoal.title)}</div><div class="mini muted">${esc(nextGoal.text)}</div></div></div></div><div><div class="card"><h2>Cuộc sống hiện tại</h2><div class="brief"><div class="brief-item"><strong>Nhà ở</strong><span class="muted mini">${home().name} · khoảng ${fmt(home().monthly*livingMultiplier())}/30 ngày</span></div><div class="brief-item"><strong>Đi lại</strong><span class="muted mini">${vehicle().name} · phương tiện tốt rút ngắn phần di chuyển của việc phù hợp</span></div><div class="brief-item"><strong>Gia đình</strong><span class="muted mini">${state.relationship.status==='single'?'Chưa có người yêu':`${p?.name||'Người yêu'} · tình cảm ${Math.round(state.relationship.love)}/100`}${state.children.length?` · ${state.children.length} con`:''}</span></div><div class="brief-item"><strong>Chi phí cố định ước tính</strong><span class="muted mini">${fmt(monthly)}/30 ngày, chưa gồm ăn uống tự chọn</span></div><div class="brief-item"><strong>Giấc ngủ gần nhất</strong><span class="muted mini">${(state.lastSleepHours||0).toFixed(1)} giờ · thiếu ngủ ${state.sleepDebt?fmtDuration(state.sleepDebt):'0 phút'}</span></div></div></div>${phoneView()}</div></div>`;}
function phoneView(){const items=state.news.slice(0,4);return `<div class="card" style="margin-top:10px"><div class="screen-title"><div><h2>Điện thoại</h2><div class="mini muted">Tin từ cuộc sống, khách hàng và các cột mốc.</div></div><span class="tag">${items.length} mới</span></div>${items.length?`<div class="brief">${items.map(n=>`<div class="brief-item"><strong>${esc(n.title)}</strong><span class="mini muted">Ngày ${n.day} · ${n.time||''} · ${esc(n.text)}</span></div>`).join('')}</div>`:'<div class="empty-state">Chưa có tin mới.</div>'}</div>`;}
function jobsView(){const cards=state.jobOffers.map(jobById).filter(Boolean);const open=cards.filter(j=>jobAvailability(j).state==='open'),upcoming=cards.filter(j=>jobAvailability(j).state==='upcoming'),closed=cards.filter(j=>jobAvailability(j).state==='closed');return `<div class="card"><div class="screen-title"><div><h2>Việc hôm nay</h2><div class="mini muted">Mỗi việc có giờ nhận, thời lượng và khu vực riêng. Lương không tính máy móc theo số phút.</div></div><span class="tag ${isLateTime()?'warn':'good'}">${timeLabel()} · ${weekday()}</span></div><div class="timeline-strip"><span>05:00 Chợ sớm</span><span>11:00 Cơm VP</span><span>18:00 Đồ ăn tối</span><span>22:00 Ca đêm</span><span>01:00 Sang ngày</span></div>${open.length?`<h3>Đang nhận được</h3><div class="grid3">${open.map(jobCard).join('')}</div>`:''}${upcoming.length?`<h3 style="margin-top:14px">Sắp mở</h3><div class="grid3">${upcoming.map(jobCard).join('')}</div>`:''}${closed.length?`<details class="closed-jobs"><summary>Đã lỡ ${closed.length} việc hôm nay</summary><div class="grid3" style="margin-top:8px">${closed.map(jobCard).join('')}</div></details>`:''}${!cards.length?'<div class="empty-state">Chưa có việc phù hợp. Hãy mua phương tiện, tăng uy tín hoặc sang ngày mới.</div>':''}</div>`;}
function jobCard(j){const av=jobAvailability(j),s=JOB_TIME[j.id],d=estimatedDurationRange(j),window=bestWindowText(j),disabled=av.state!=='open'||state.energy<Math.ceil(j.energy*(trait().mods.energy||1));const cls=av.state==='closed'?'done':'';return `<div class="job ${cls}"><div class="job-top"><div><b>${esc(j.name)}</b><div class="mini muted">${esc(j.desc)}</div></div><span class="tag ${av.state==='open'?'good':av.state==='upcoming'?'warn':'bad'}">${av.label}</span></div><div class="job-meta"><span>⏱ ${fmtDuration(d[0])}–${fmtDuration(d[1])}</span><span>🕒 ${window}</span><span>📍 ${AREAS[s?.area]||'Nội thành'}</span><span>💵 ${fmt(j.pay[0])}–${fmt(j.pay[1])}</span></div>${weatherJobNote(j)}<button class="btn ${av.state==='open'?'primary':''}" data-job="${j.id}" ${disabled?'disabled':''}>${av.state==='open'?'Nhận việc ngay':av.state==='upcoming'?`Mở lúc ${av.next}`:'Đã hết giờ'}</button></div>`;}
function weatherJobNote(j){const s=JOB_TIME[j.id],w=weather();if(!s?.delivery||w.id==='clear')return '';return `<div class="mini ${w.id==='storm'?'down':'muted'}" style="margin-top:6px">${w.icon} ${w.name}: đơn giao hàng hôm nay có thể trả cao hơn, nhưng thời gian di chuyển tăng.</div>`;}
function lifeView(){return `<div class="grid"><div class="card"><h2>Ăn uống</h2><p class="mini muted">Bữa ăn cũng lấy thời gian. Game chỉ cho một bữa chính có tác động mạnh mỗi ngày để tránh thành simulator ăn uống.</p><div class="grid4">${FOODS.map(f=>`<div class="life-action"><b>${f.name}</b><div class="mini muted">${f.desc}</div><div class="mini">${fmt(Math.round(f.cost*livingMultiplier()))} · ⏱ ${fmtDuration(FOOD_TIME[f.id]||25)}</div><button class="btn" data-food="${f.id}" ${state.ateToday||state.cash<Math.round(f.cost*livingMultiplier())?'disabled':''}>${state.ateToday?'Đã ăn':'Ăn'}</button></div>`).join('')}</div></div><div class="card"><h2>Giữ sức khỏe</h2><p class="mini muted">Tập luyện lấy giờ hôm nay để mua sức bền cho những ngày sau.</p><div class="grid4">${WORKOUTS.map(w=>`<div class="life-action"><b>${w.name}</b><div class="mini muted">${w.desc}</div><div class="mini">${fmt(Math.round(w.cost*livingMultiplier()))} · ⏱ ${fmtDuration(WORKOUT_TIME[w.id]||60)}</div><button class="btn" data-workout="${w.id}" ${state.workoutToday||state.energy<w.energy||state.cash<Math.round(w.cost*livingMultiplier())?'disabled':''}>${state.workoutToday?'Đã tập':'Đi tập'}</button></div>`).join('')}</div></div></div><div class="card" style="margin-top:10px"><div class="screen-title"><div><h2>Giấc ngủ</h2><div class="mini muted">Về nghỉ kết thúc nhịp lao động. Ngủ trễ khiến giờ dậy trễ chứ không bị game phạt kiểu cấm làm.</div></div><span class="tag">Dự kiến dậy ${timeLabel(sleepPlan().wake)}</span></div><div class="split"><div class="brief-item"><strong>Nếu ngủ bây giờ</strong><span class="mini muted">Ngủ khoảng ${(sleepPlan().minutes/60).toFixed(1)} giờ, dậy ${timeLabel(sleepPlan().wake)}. ${sleepPlan().note}</span></div><div class="brief-item"><strong>Nếu tiếp tục cày</strong><span class="mini muted">Sau 22:00 sức khỏe hao nhanh hơn. Sau 01:00 ngày mới tự sang, nhưng bạn không được hồi sức vì chưa ngủ.</span></div></div><button class="btn primary" id="sleepLifeBtn" style="margin-top:10px">Về nghỉ ngay</button></div>`;}
function careerView(){const owned=BUSINESSES.filter(b=>state.businesses[b.id]);return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>Cơ sở & doanh nghiệp</h2><div class="mini muted">Đây là bước chuyển từ bán thời gian của mình sang thuê người khác vận hành.</div></div><span class="tag">${businessCount()} cơ sở · ${totalStaff()} người</span></div>${owned.length?`<div class="brief">${owned.map(b=>{const c=state.businesses[b.id],sat=saturation(b.id);return `<div class="business"><div class="business-top"><div><b>${b.name} ×${c}</b><span class="mini muted">${b.desc}</span></div><span class="tag ${sat<.75?'warn':'good'}">Hiệu quả ${Math.round(sat*100)}%</span></div><div class="mini">Nhân sự ${b.staff*c} · lương cơ bản ${fmt(b.salary)}/người/30 ngày</div></div>`;}).join('')}</div>`:'<div class="empty-state">Chưa có cơ sở. Đầu game bạn phải tự làm để tích vốn.</div>'}</div><div class="card"><h2>Dòng tiền & vay vốn</h2><div class="brief"><div class="brief-item"><strong>Nợ hiện tại</strong><span class="mini muted">${fmt(state.debt)} · hạn mức khoảng ${fmt(loanLimit())}</span></div><div class="brief-item"><strong>Chi cố định ước tính</strong><span class="mini muted">${fmt(monthlyExpenseEstimate())}/30 ngày</span></div></div><div class="row" style="margin-top:10px"><button class="btn" id="borrowBtn" ${state.reputation<15||state.debt+20000000>loanLimit()?'disabled':''}>Vay 20 triệu</button><button class="btn" id="repayBtn" ${state.debt<=0||state.cash<=0?'disabled':''}>Trả tối đa 10 triệu</button></div>${businessCount()?managementPanel():''}</div></div><div class="card" style="margin-top:10px"><h2>Cơ hội mở ngành</h2><div class="grid3">${BUSINESSES.map(b=>businessCard(b)).join('')}</div></div>`;}
function businessCard(b){const c=state.businesses[b.id]||0,setup=Math.round(b.cost*(trait().mods.setup||1)),locked=state.reputation<b.rep||c>=b.max||state.cash<setup;return `<div class="business ${state.reputation<b.rep?'locked':''}"><div class="business-top"><div><b>${b.name}</b><div class="mini muted">${b.desc}</div></div><span class="tag">Uy tín ${b.rep}</span></div><div class="mini">Vốn ${fmt(setup)} · ${b.staff} người/cơ sở · tối đa ${b.max}</div><button class="btn" data-biz="${b.id}" ${locked?'disabled':''}>${c>=b.max?'Đã bão hòa':`Mở cơ sở ${c+1}`}</button></div>`;}
function relationshipView(){const p=partner();if(state.relationship.status==='single')return `<div class="card"><h2>Tình cảm chưa mở</h2><p class="muted">Game không ném người yêu vào lúc bạn còn đang lo từng bữa. Khi cuộc sống có chút nền, một cuộc gặp sẽ đến qua sự kiện.</p><div class="notice"><b>Điều kiện mềm:</b> khoảng Ngày 18+, uy tín 6–8+, sức khỏe trên 50 và tài sản ròng đủ để không còn sống từng ngày.</div></div>`;const status=state.relationship.status==='married'?'Vợ/chồng':'Người yêu';return `<div class="grid"><div class="card"><div class="screen-title"><div><h2>${status}: ${p?.name||''}</h2><div class="mini muted">${p?.trait||''} · ${p?.desc||''}</div></div><span class="tag good">Tình cảm ${Math.round(state.relationship.love)}/100</span></div><div class="progress"><i style="width:${clamp(state.relationship.love,0,100)}%"></i></div><h3 style="margin-top:14px">Dành thời gian cho nhau</h3><div class="grid3">${dateActions().map(a=>`<div class="life-action"><b>${a.name}</b><div class="mini muted">${a.desc}</div><div class="mini">${fmt(a.cost)} · ⏱ ${fmtDuration(a.minutes)} · tình cảm +${a.love}</div><button class="btn" data-date="${a.id}" ${state.dateToday||state.cash<a.cost?'disabled':''}>Đi cùng nhau</button></div>`).join('')}</div>${state.relationship.status==='dating'?marriageBox():childBox()}</div><div class="card"><h2>Gia đình</h2>${familyView()}</div></div>`;}
function dateActions(){return[{id:'coffee',name:'Cà phê & đi dạo',cost:180000,love:5,minutes:90,desc:'Không đắt nhưng phải thật sự dành thời gian.'},{id:'food',name:'Ăn một bữa ngon',cost:650000,love:8,minutes:120,desc:'Hai tiếng không kiếm tiền, đổi lại một mối quan hệ được nuôi.'},{id:'movie',name:'Xem phim + ăn tối',cost:1100000,love:10,minutes:210,desc:'Một buổi hẹn đúng nghĩa, thường chiếm gần hết buổi tối.'},{id:'trip',name:'Đi chơi cuối tuần',cost:4200000,love:15,minutes:420,desc:'Tốn cả tiền lẫn gần một ngày, nhưng kỷ niệm tăng mạnh.'}];}
function marriageBox(){const ok=state.relationship.love>=78&&netWorth()>=120000000&&state.day-state.relationship.metDay>=20;return `<div class="notice"><b>Kết hôn:</b> cần tình cảm khoảng 78+, đã quen đủ lâu và tài chính có nền. ${ok?'<button class="btn primary" id="marryBtn" style="margin-top:8px">Bàn chuyện cưới</button>':'Hiện tại hai người chưa đủ điều kiện mềm.'}</div>`;}
function childBox(){if(state.relationship.status!=='married')return '';const max=state.children.length>=3;return `<div class="notice"><b>Con cái là lựa chọn.</b> Không tự động sinh. ${max?'Gia đình hiện đã có 3 con.':`Khi muốn, bạn có thể chủ động mở mạch này. <button class="btn" id="childBtn" style="margin-top:8px">Bàn chuyện có con</button>`}</div>`;}
function familyView(){const p=partner();let html=`<div class="brief"><div class="brief-item"><strong>${state.relationship.status==='married'?'Bạn đời':'Người đang tìm hiểu'}</strong><span class="mini muted">${p?.name||'Chưa có'}${p?` · ${p.trait}`:''}</span></div>`;if(!state.children.length)html+=`<div class="brief-item"><strong>Con cái</strong><span class="mini muted">Chưa có. Game không xem đây là nghĩa vụ bắt buộc.</span></div>`;else for(const c of state.children){const st=childStage(c);html+=`<div class="brief-item"><strong>${c.name} · ${childAge(c)} tuổi</strong><span class="mini muted">${st.label} · khoảng ${fmt(st.monthly)}/30 ngày</span></div>`;}html+='</div>';if(state.children.length)html+=`<h3 style="margin-top:12px">Dành thời gian cho con</h3><div class="choice compact-choice">${familyActions().map(a=>`<button data-family="${a.id}" ${state.familyToday||state.cash<a.cost?'disabled':''}><b>${a.name}</b><span class="mini muted">${fmt(a.cost)} · ⏱ ${fmtDuration(a.minutes)} · ${a.desc}</span></button>`).join('')}</div>`;return html;}
function familyActions(){return[
 {id:'parkKids',name:'Đưa con đi công viên / ăn sáng',cost:350000,minutes:120,mood:5,love:3,desc:'Hai tiếng không tạo doanh thu nhưng tạo ký ức gia đình.'},
 {id:'familyDay',name:'Một buổi cho gia đình',cost:1200000,minutes:240,mood:9,love:5,desc:'Gần nửa ngày dành cho nhau; late game đây là chi phí cơ hội thật.'},
 {id:'outing',name:'Đi chơi cả nhà',cost:3500000,minutes:420,mood:14,love:7,desc:'Gần trọn ngày, phù hợp khi bạn đã có hệ thống kiếm tiền thay mình.'}
];}
function doFamilyAction(id){const a=familyActions().find(x=>x.id===id);if(!a||!state.children.length||state.familyToday||state.cash<a.cost)return;changeCash(-a.cost,a.name);state.mood=clamp(state.mood+a.mood,0,100);if(state.relationship.status!=='single')state.relationship.love=clamp(state.relationship.love+a.love,0,100);state.familyToday=true;const start=timeLabel();advanceClock(a.minutes,{awake:true,source:a.name});log(`${a.name} từ ${start} đến ${timeLabel()}; ${fmtDuration(a.minutes)} dành cho gia đình.`,'good');save();renderGame();if(state.events.length)setTimeout(showPendingEvent,120);}
function managementActions(){return[
 {id:'brief',name:'Họp nhanh với quản lý',minutes:60,energy:8,bonus:.04,rep:1,desc:'Một giờ rà vận hành; lợi nhuận cơ sở ngày này tăng nhẹ.'},
 {id:'client',name:'Gặp khách hàng lớn',minutes:120,energy:13,bonus:.07,rep:2,desc:'Tốn hai giờ nhưng có thể kéo hợp đồng và cải thiện doanh thu.'},
 {id:'field',name:'Đi thị trường / khảo sát điểm bán',minutes:180,energy:16,bonus:.10,rep:2,desc:'Ba giờ rời bàn làm việc để hiểu thị trường; hiệu quả ngày tăng rõ hơn.'}
];}
function managementPanel(){return `<div class="management-panel"><h3>Thời gian của người chủ</h3><p class="mini muted">Khi đã có cơ sở, bạn không còn phải tự giao từng đơn. Nhưng muốn hệ thống chạy tốt, đôi lúc vẫn phải dành giờ cho quản trị.</p><div class="choice compact-choice">${managementActions().map(a=>`<button data-manage="${a.id}" ${state.managementToday||state.energy<a.energy?'disabled':''}><b>${a.name}</b><span class="mini muted">⏱ ${fmtDuration(a.minutes)} · năng lượng -${a.energy} · hiệu quả kinh doanh ngày +${Math.round(a.bonus*100)}%</span></button>`).join('')}</div></div>`;}
function doManagementAction(id){const a=managementActions().find(x=>x.id===id);if(!a||!businessCount()||state.managementToday||state.energy<a.energy)return;state.energy=clamp(state.energy-a.energy,0,100);state.reputation+=a.rep;state.managementBonus=Math.max(state.managementBonus||0,a.bonus);state.managementToday=true;const start=timeLabel();advanceClock(a.minutes,{awake:true,source:a.name});if(id==='client'&&Math.random()<.45){const deal=Math.round(rnd(350000,1200000)*Math.max(1,Math.sqrt(businessCount())));changeCash(deal,'Khách đặt cọc / hợp đồng mới');news('Một cuộc gặp đáng thời gian',`Buổi gặp tạo thêm ${fmt(deal)} tiền đặt cọc/hợp đồng. Không phải ngày nào họp cũng ra tiền, nhưng hôm nay có kết quả.`,'Kinh doanh');}log(`${a.name} từ ${start} đến ${timeLabel()}; dành ${fmtDuration(a.minutes)} để hệ thống chạy tốt hơn.`);save();renderGame();if(state.events.length)setTimeout(showPendingEvent,120);}
function processRelationshipDay(){if(state.relationship.status==='single')return;const gap=state.day-(state.relationship.lastDateDay??state.relationship.metDay??state.day);if(gap>=6&&state.day%3===0){const loss=state.relationship.status==='married'?1:2;state.relationship.love=clamp(state.relationship.love-loss,0,100);state.mood=clamp(state.mood-1,0,100);if(gap===6||gap===9)news(partner()?.name||'Người thân',`“Dạo này mình ít có thời gian cho nhau quá.” Không cần ngày nào cũng hẹn hò, nhưng để quá lâu thì khoảng cách sẽ xuất hiện.`,'Tình cảm');}}
function assetsView(){return `<div class="grid"><div class="card"><h2>Phương tiện</h2><p class="mini muted">Xe chủ yếu mở việc và rút ngắn phần di chuyển. Nó không phải nút +% tiền vô điều kiện.</p><div class="brief">${VEHICLES.map(v=>`<div class="asset ${v.id===state.vehicle?'selected-asset':''}"><div class="asset-top"><div><b>${v.name}</b><span class="mini muted">${v.desc}</span></div>${v.id===state.vehicle?'<span class="tag good">Đang dùng</span>':`<span class="tag">${fmt(v.price)}</span>`}</div>${v.id!==state.vehicle&&v.tier>vehicle().tier?`<button class="btn" data-vehicle="${v.id}" ${state.cash+Math.round(vehicle().price*vehicle().resale)<v.price?'disabled':''}>Đổi xe</button>`:''}</div>`).join('')}</div></div><div class="card"><h2>Nhà ở</h2><p class="mini muted">Nhà tốt tăng khả năng hồi phục và mở cảm giác ổn định cho gia đình.</p><div class="brief">${HOUSING.map(h=>`<div class="asset ${h.id===state.housing?'selected-asset':''}"><div class="asset-top"><div><b>${h.name}</b><span class="mini muted">${h.desc}</span></div>${h.id===state.housing?'<span class="tag good">Đang ở</span>':`<span class="tag">${h.kind==='buy'?fmt(h.price):fmt(h.monthly)+'/30 ngày'}</span>`}</div>${h.id!==state.housing&&h.quality>home().quality?`<button class="btn" data-home="${h.id}" ${state.cash<(h.kind==='buy'?h.price:Math.round(h.monthly*1.5))||netWorth()<h.minNet?'disabled':''}>${h.kind==='buy'?'Mua':'Chuyển tới'}</button>`:''}</div>`).join('')}</div></div></div>`;}
function journalView(){return `<div class="grid"><div class="card"><h2>Nhật ký cuộc đời</h2><div class="log">${state.journal.length?state.journal.map(x=>`<div class="log-item"><span class="tag">Ngày ${x.day} · ${x.time||''}</span><div class="${x.type==='good'?'up':x.type==='bad'?'down':''}">${esc(x.text)}</div></div>`).join(''):'<div class="empty-state">Nhật ký sẽ tự ghi các quyết định đáng nhớ.</div>'}</div></div><div><div class="card"><h2>Cột mốc</h2>${state.news.filter(x=>x.type==='Cột mốc'||x.type==='Roguelite').slice(0,12).map(x=>`<div class="story"><div class="story-title">${esc(x.title)}</div><div class="mini muted">Ngày ${x.day} · ${x.time||''} · ${esc(x.text)}</div></div>`).join('')||'<div class="empty-state">Chưa có cột mốc.</div>'}</div><div class="card" style="margin-top:10px"><h2>Thống kê đời sống</h2><div class="brief"><div class="brief-item"><strong>Giờ đã tự làm</strong><span class="mini muted">${(state.stats.hoursWorked||0).toFixed(1)} giờ</span></div><div class="brief-item"><strong>Việc làm đêm</strong><span class="mini muted">${state.stats.lateJobs||0} lần</span></div><div class="brief-item"><strong>Giờ đã ngủ</strong><span class="mini muted">${(state.stats.hoursSlept||0).toFixed(1)} giờ</span></div></div><button class="btn danger" id="retireBtn" style="margin-top:10px">Khép lại hành trình</button></div></div></div>`;}

function bindGame(){
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderGame();});
 document.querySelector('#homeBtn')?.addEventListener('click',()=>{save();startScreen();});document.querySelector('#guideGameBtn')?.addEventListener('click',showGuide);
 document.querySelector('#sleepBtn')?.addEventListener('click',sleepNow);document.querySelector('#mobileSleep')?.addEventListener('click',sleepNow);document.querySelector('#sleepLifeBtn')?.addEventListener('click',sleepNow);
 document.querySelector('#mobileJobs')?.addEventListener('click',()=>{tab='vieclam';renderGame();});
 document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>doJob(b.dataset.job));document.querySelectorAll('[data-food]').forEach(b=>b.onclick=()=>eat(b.dataset.food));document.querySelectorAll('[data-workout]').forEach(b=>b.onclick=()=>workout(b.dataset.workout));document.querySelectorAll('[data-vehicle]').forEach(b=>b.onclick=()=>buyVehicle(b.dataset.vehicle));document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>changeHome(b.dataset.home));document.querySelectorAll('[data-biz]').forEach(b=>b.onclick=()=>buyBusiness(b.dataset.biz));document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>datePartner(b.dataset.date));document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>doFamilyAction(b.dataset.family));document.querySelectorAll('[data-manage]').forEach(b=>b.onclick=()=>doManagementAction(b.dataset.manage));
 document.querySelector('#borrowBtn')?.addEventListener('click',borrow);document.querySelector('#repayBtn')?.addEventListener('click',repay);document.querySelector('#marryBtn')?.addEventListener('click',proposeMarriage);document.querySelector('#childBtn')?.addEventListener('click',haveChild);document.querySelector('#retireBtn')?.addEventListener('click',()=>finishRun('Bạn chủ động khép lại hành trình để xem mình đã đi được bao xa.'));
}

function jobById(id){return ALL_JOBS.find(j=>j.id===id);}
function eligibleJobs(){const v=vehicle();return ALL_JOBS.filter(j=>v.tier>=j.vehicle&&(!j.needVan||state.vehicle==='van')&&state.reputation>=(j.minRep||0));}
function jobAvailability(j){const s=JOB_TIME[j.id]||{windows:[[300,1320]]},now=state.clock;let next=null;for(const [a,b] of s.windows){if(now>=a&&now<=b)return{state:'open',label:'Đang mở',next:timeLabel(a)};if(a>now&&(next===null||a<next))next=a;}if(next!==null)return{state:'upcoming',label:`Mở ${timeLabel(next)}`,next:timeLabel(next)};return{state:'closed',label:'Đã hết giờ',next:null};}
function bestWindowText(j){const s=JOB_TIME[j.id]||{windows:[[300,1320]]};return s.windows.map(([a,b])=>`${timeLabel(a)}–${timeLabel(b)}`).join(' / ');}
function refreshJobs(force=false){if(!state)return;const pool=eligibleJobs(),now=state.clock;let scored=pool.map(j=>{const av=jobAvailability(j),s=JOB_TIME[j.id]||{},weekend=(weekday()==='Thứ Bảy'||weekday()==='Chủ Nhật'),score=(av.state==='open'?8:av.state==='upcoming'?3:0)+Math.random()*3;if(weekend&&(j.id==='chayBan'||j.id==='gaRan'||j.id==='xeOm'))score+=3;if(!weekend&&(j.id==='giaoCom'||j.id==='hoSoGap'))score+=2;if(trait().mods.offers&&(j.id==='hoSoGap'||s.night))score+=2;return{j,score};}).sort((a,b)=>b.score-a.score);const count=trait().mods.offers?6:5;state.jobOffers=scored.slice(0,Math.min(count,scored.length)).map(x=>x.j.id);const openPool=pool.filter(j=>jobAvailability(j).state==='open');if(openPool.length&&!state.jobOffers.some(id=>jobAvailability(jobById(id)).state==='open'))state.jobOffers[0]=pick(openPool).id;if(!state.jobOffers.length&&force)state.jobOffers=['vechai','bocHang'];}
function estimatedDurationRange(j){const s=JOB_TIME[j.id]||{duration:[60,120],travel:.3},w=weather(),veh=vehicle();const speedGain=Math.min(.20,Math.max(0,veh.tier-0)*.035)*(s.travel||0),weatherFactor=s.delivery?w.travel:1,carPenalty=(veh.tier>=4&&['trungTam','vanPhong'].includes(s.area))?1.05:1,factor=(1-speedGain)*weatherFactor*carPenalty;return s.duration.map(x=>Math.max(20,Math.round(x*factor/5)*5));}
function rolledDuration(j){const range=estimatedDurationRange(j);return rnd(range[0],range[1]);}
function jobPay(j){const s=JOB_TIME[j.id]||{},w=weather(),weekend=(weekday()==='Thứ Bảy'||weekday()==='Chủ Nhật');let m=incomeMultiplier(j)*(state.health<40?.78:1)*(state.mood<30?.85:1);if(s.delivery)m*=w.pay;if(weekend&&(j.id==='chayBan'||j.id==='gaRan'||j.id==='xeOm'))m*=1.08;if(s.night)m*=1.08;return Math.round(rnd(j.pay[0],j.pay[1])*m);}
function doJob(id){const j=jobById(id);if(!j)return;const av=jobAvailability(j);if(av.state!=='open')return toast(av.state==='upcoming'?`Việc này mở lúc ${av.next}.`:'Đã lỡ khung giờ của việc này hôm nay.');const energy=Math.ceil(j.energy*(trait().mods.energy||1));if(state.energy<energy)return toast('Không đủ năng lượng cho việc này. Hãy ăn, nghỉ hoặc chọn việc nhẹ hơn.');const startClock=state.clock,duration=rolledDuration(j),pay=jobPay(j);state.jobOffers=state.jobOffers.filter(x=>x!==id);state.energy=clamp(state.energy-energy,0,100);state.health=clamp(state.health-j.health*(weather().health||1),0,100);state.mood=clamp(state.mood-rnd(0,2),0,100);state.reputation+=Math.max(0,Math.round(j.rep*(trait().mods.rep||1)));changeCash(pay,j.name);state.stats.jobsDone++;state.stats.daysWorked++;state.stats.hoursWorked+=(duration/60);state.workCountToday++;advanceClock(duration,{awake:true,source:j.name});const latePenalty=applyLateWorkPenalty(startClock,duration,j);log(`Làm “${j.name}” từ ${timeLabel(startClock)} đến ${timeLabel()}; mất ${fmtDuration(duration)}, nhận ${fmt(pay)}${latePenalty?`, làm khuya hao sức ${latePenalty}`:''}.`,'good');if(Math.random()<.11){const tip=rnd(20000,140000);changeCash(tip,'Tiền bo / khách gửi thêm');news('Một khoản nhỏ vui vui',`Khách hài lòng và gửi thêm ${fmt(tip)}. Việc ngắn đôi khi vẫn đáng giá vì đúng người, đúng lúc.`,'Công việc');}checkMilestones();checkStoryBeats();handleHealth();save();renderGame();if(state.events.length)setTimeout(showPendingEvent,120);}
function applyLateWorkPenalty(start,duration,j){const end=start+duration,night=start>=1320||start<300||end>1320,s=JOB_TIME[j.id]||{};if(!night)return 0;state.stats.lateJobs++;state.lateWorkStreak=(state.lateWorkStreak||0)+1;let hp=Math.max(1,Math.ceil(duration/90));if(s.night)hp+=1;if(trait().id==='benbi')hp=Math.max(1,Math.ceil(hp*.7));state.health=clamp(state.health-hp,0,100);state.sleepDebt=clamp((state.sleepDebt||0)+Math.round(duration*.35),0,720);if(state.lateWorkStreak>=3)state.mood=clamp(state.mood-2,0,100);return hp;}

function advanceClock(minutes,{awake=false,source=''}={}){let remaining=Math.max(0,Math.round(minutes));if(awake)state.awakeMinutes=(state.awakeMinutes||0)+remaining;while(remaining>0){const untilBoundary=DAY_BOUNDARY-state.clock;if(remaining<untilBoundary){state.clock+=remaining;remaining=0;}else{state.clock=DAY_BOUNDARY;remaining-=untilBoundary;processDayBoundary({awake,source});}}}
function processDayBoundary({awake=false,source=''}={}){const dayDone=state.day,before=state.cash,biz=processBusinessDay();processMonth();state.lastDayAte=!!state.ateToday;state.day++;meta.totalDays++;state.clock=60;state.ateToday=false;state.mealsToday=0;state.workoutToday=false;state.workCountToday=0;state.dateToday=false;state.familyToday=false;state.managementToday=false;state.weather=randomWeather();refreshJobs(true);processRelationshipDay();processChildren();checkMilestones();checkStoryBeats();maybeRandomEvent();state.stats.bestCash=Math.max(state.stats.bestCash,state.cash);state.stats.maxNet=Math.max(state.stats.maxNet,netWorth());meta.bestNetWorth=Math.max(meta.bestNetWorth,netWorth());state.lastDayResult={dayDone,before,after:state.cash,biz};if(awake){state.sleepDebt=clamp((state.sleepDebt||0)+45,0,720);news('01:00 — ngày mới đã bắt đầu',`Bạn vẫn chưa ngủ${source?` sau “${source}”`:''}. Công việc và thời tiết đã sang Ngày ${state.day}, nhưng cơ thể không được hồi năng lượng.`,'Sức khỏe');}saveMeta();}
function sleepPlan(){const c=state.clock;let wake,note;if(c>=1260&&c<1380){wake=330;note='Ngủ khá sớm, sáng mai còn nguyên khung việc chợ và đồ ăn sáng.';}else if(c>=1380&&c<1440){wake=360;note='Ngủ hơi muộn nhưng vẫn kịp phần lớn việc buổi sáng.';}else if(c>=1440||c<120){wake=450;note='Đã qua nửa đêm, sáng mai bạn sẽ dậy muộn hơn.';}else if(c<300){wake=540;note='Bạn đã thức sâu sang ngày mới; cơ thể cần ngủ bù.';}else if(c<900){wake=360;note='Bạn đang bỏ phần còn lại của ngày để hồi sức; chỉ nên làm khi thật sự mệt.';}else{wake=330;note='Kết thúc ngày sớm để giữ sức cho sáng mai.';}let minutes;if(c<wake&&c<300)minutes=wake-c;else if(c>=DAY_BOUNDARY)minutes=(DAY_BOUNDARY-c)+(wake-60);else minutes=(DAY_BOUNDARY-c)+(wake-60);if(minutes<=0)minutes=420;return{wake,minutes,note};}
function sleepNow(){if(state.events.length){showPendingEvent();return;}const plan=sleepPlan(),startDay=state.day,start=timeLabel(),hours=plan.minutes/60,ateBefore=!!state.ateToday||(state.clock<300&&!!state.lastDayAte);advanceClock(plan.minutes,{awake:false,source:'Ngủ'});state.stats.hoursSlept+=hours;applySleepRecovery(hours,ateBefore);state.clock=plan.wake;state.awakeMinutes=0;state.lateWorkStreak=0;log(`Ngủ từ ${start} đến ${timeLabel()} (${hours.toFixed(1)} giờ).`,'good');handleHealth();save();renderGame();showSleepSummary(startDay,start,hours);}
function applySleepRecovery(hours,ateBefore=false){const h=home(),sleepBonus=trait().id==='kyLuat'?1.12:1,quality=hours>=7?1:hours>=5?.72:hours>=3?.42:.2;state.lastSleepHours=hours;state.energy=clamp(Math.round((48+45*quality+h.energy)*sleepBonus),0,100);let hp=hours>=7?4:hours>=5?1:hours>=3?-2:-6;hp+=(ateBefore?2:-3)+Math.floor(h.quality/2);state.health=clamp(state.health+hp,0,100);state.mood=clamp(state.mood+(hours>=7?4:hours>=5?1:-4)+h.mood+(ateBefore?1:-2),0,100);const target=420,short=Math.max(0,target-Math.round(hours*60)),paid=Math.min(state.sleepDebt||0,Math.max(0,Math.round(hours*60)-target));state.sleepDebt=clamp((state.sleepDebt||0)+short-paid,0,720);if(!ateBefore)state.consecutiveNoFood=(state.consecutiveNoFood||0)+1;else state.consecutiveNoFood=0;}
function showSleepSummary(startDay,start,hours){const missed=state.jobOffers.map(jobById).filter(Boolean).filter(j=>jobAvailability(j).state==='closed').length;openModal(`<div class="modal-card"><div class="row between"><div><span class="tag good">Đã nghỉ</span><h2 style="margin-top:8px">${timeLabel()} · Ngày ${state.day} · ${weekday()}</h2></div><span class="tag">Ngủ ${hours.toFixed(1)} giờ</span></div><div class="brief"><div class="brief-item"><strong>Bắt đầu ngủ</strong><span class="mini muted">${start} · Ngày ${startDay}</span></div><div class="brief-item"><strong>Sức khỏe / năng lượng</strong><span class="mini muted">${Math.round(state.health)}/100 · ${Math.round(state.energy)}/100</span></div><div class="brief-item"><strong>Việc sáng</strong><span class="mini muted">${missed?`Có ${missed} việc đã trôi qua theo giờ hiện tại.`:'Bạn vẫn còn kịp những cơ hội đang mở.'}</span></div></div><button class="btn primary" id="wakeBtn" style="margin-top:10px">Bắt đầu ngày</button></div>`);document.querySelector('#wakeBtn').onclick=()=>{closeModal();renderGame();if(state.events.length)showPendingEvent();};}
function isLateTime(){return state.clock>=1320||state.clock<300;}
function timeOfDayTitle(){const c=state.clock;if(c<300)return 'Đêm rất khuya';if(c<660)return 'Buổi sáng';if(c<840)return 'Buổi trưa';if(c<1080)return 'Buổi chiều';if(c<1320)return 'Buổi tối';return 'Đã khuya';}
function timeContextText(){const c=state.clock;if(c<300)return 'Ngày mới đã sang nhưng bạn vẫn đang thức. Việc đêm còn lại rất ít; giấc ngủ lúc này đáng giá hơn bình thường.';if(c<540)return 'Chợ, phở, hàng sáng đang là cơ hội tốt. Ngủ dậy muộn sẽ lỡ một phần nhịp này.';if(c<780)return 'Việc văn phòng, giao cơm và dịch vụ ban ngày bắt đầu đông.';if(c<1020)return 'Buổi chiều linh hoạt để làm việc dài, tập luyện hoặc xử lý tài sản.';if(c<1320)return 'Đồ ăn tối, tiệc và hẹn hò cạnh tranh trực tiếp với giờ kiếm tiền.';return 'Từ 22:00, cày thêm vẫn hợp lệ nhưng sức khỏe và giờ dậy sáng mai sẽ chịu tác động.';}

function eat(id){if(state.ateToday)return toast('Hôm nay bạn đã có một bữa chính đủ tác động.');const f=FOODS.find(x=>x.id===id);if(!f)return;const cost=Math.round(f.cost*livingMultiplier()),mins=FOOD_TIME[id]||25;if(state.cash<cost)return toast('Không đủ tiền cho lựa chọn này.');changeCash(-cost,f.name);state.health=clamp(state.health+f.health,0,100);state.mood=clamp(state.mood+f.mood,0,100);state.energy=clamp(state.energy+f.energy,0,100);state.ateToday=true;state.mealsToday=(state.mealsToday||0)+1;state.consecutiveNoFood=0;const start=timeLabel();advanceClock(mins,{awake:true,source:f.name});log(`Ăn ${f.name.toLowerCase()} từ ${start} đến ${timeLabel()}; mất ${fmtDuration(mins)}.`);save();renderGame();if(state.events.length)setTimeout(showPendingEvent,120);}
function workout(id){if(state.workoutToday)return toast('Hôm nay đã tập rồi.');const w=WORKOUTS.find(x=>x.id===id);if(!w)return;if(state.energy<w.energy)return toast('Hôm nay đã quá mệt để tập.');const cost=Math.round(w.cost*livingMultiplier()),mins=WORKOUT_TIME[id]||60;if(state.cash<cost)return toast('Không đủ tiền.');if(cost)changeCash(-cost,w.name);state.energy=clamp(state.energy-w.energy,0,100);state.health=clamp(state.health+w.health*(trait().mods.workout||1),0,100);state.mood=clamp(state.mood+w.mood,0,100);state.workoutToday=true;const start=timeLabel();advanceClock(mins,{awake:true,source:w.name});log(`${w.name} từ ${start} đến ${timeLabel()}; mất ${fmtDuration(mins)} để giữ sức đường dài.`);save();renderGame();if(state.events.length)setTimeout(showPendingEvent,120);}
function buyVehicle(id){const v=VEHICLES.find(x=>x.id===id);if(!v||v.id===state.vehicle||v.tier<vehicle().tier)return;const old=vehicle(),resale=Math.round(old.price*old.resale);if(state.cash+resale<v.price)return;if(resale>0)changeCash(resale,`Bán ${old.name}`);changeCash(-v.price,`Mua ${v.name}`);state.vehicle=v.id;state.reputation+=v.tier>=4?2:1;advanceClock(v.tier>=4?120:60,{awake:true,source:'Mua xe'});log(`Mua ${v.name} giá ${fmt(v.price)}; mất thời gian xem xe và giấy tờ.`,'good');news('Một bước tiến nhìn thấy được',`Từ hôm nay bạn đi lại bằng ${v.name}. Một số việc mới mở và thời gian di chuyển của nhiều việc sẽ giảm.`,'Tài sản');if(v.tier>=2)milestone('motorbike','Chiếc xe máy đầu tiên','Không còn phải đi bộ tìm việc. Tài sản đầu tiên đã bắt đầu mua lại thời gian của bạn.');refreshJobs(true);checkMilestones();save();renderGame();}
function changeHome(id){const h=HOUSING.find(x=>x.id===id);if(!h||state.housing===id)return;const cost=h.kind==='buy'?h.price:Math.round(h.monthly*1.5);if(state.cash<cost||netWorth()<h.minNet)return;if(h.kind==='buy'){changeCash(-h.price,`Mua ${h.name}`);state.housingOwned=true;milestone('home','Có nhà của mình',`Bạn đã mua ${h.name}. Từ phòng trọ đi tới đây là một đoạn đời rất dài.`);}else{changeCash(-cost,`Đặt cọc + tháng đầu ${h.name}`);state.housingOwned=false;}state.housing=id;state.nextHousingDue=state.day+MONTH_DAYS;state.mood=clamp(state.mood+8,0,100);advanceClock(150,{awake:true,source:'Chuyển nhà'});log(`Chuyển chỗ ở: ${h.name}. Mất một phần ngày cho hợp đồng và dọn đồ.`,'good');save();renderGame();}
function saturation(id){const c=state.businesses[id]||0;return Math.max(.52,1-Math.max(0,c-1)*.16);}
function buyBusiness(id){const b=BUSINESSES.find(x=>x.id===id);if(!b)return;const c=state.businesses[id]||0,setup=Math.round(b.cost*(trait().mods.setup||1));if(c>=b.max||state.reputation<b.rep||state.cash<setup)return;changeCash(-setup,`Mở ${b.name}`);state.businesses[id]=c+1;state.mood=clamp(state.mood+5,0,100);state.reputation+=2;advanceClock(Math.min(240,90+b.level*20),{awake:true,source:`Mở ${b.name}`});log(`Mở ${b.name}; bắt đầu thuê ${b.staff} người vận hành.`,'good');news('Bạn bắt đầu trả lương cho người khác',`${b.name} cần ${b.staff} người. Từ đây tiền mua lại thời gian của bạn, nhưng cuối mỗi 30 ngày phải có tiền lương cho đội.`,'Sự nghiệp');if(businessCount()===1)milestone('firstBiz','Cơ sở đầu tiên','Lần đầu bạn dùng vốn để thuê người và tạo thu nhập không phụ thuộc hoàn toàn vào sức mình.');if(b.level>=4)milestone('company','Từ chủ nhỏ thành doanh nghiệp','Quy mô nhân sự và dòng tiền đã vượt xa những ngày tự chạy từng đơn hàng.');checkMilestones();save();renderGame();}
function datePartner(id){const a=dateActions().find(x=>x.id===id),p=partner();if(!a||!p||state.dateToday||state.cash<a.cost)return;changeCash(-a.cost,`Đi cùng ${p.name}`);const love=Math.round(a.love*(trait().mods.love||1)*(p.trait==='Tình cảm'?1.12:1));state.relationship.love=clamp(state.relationship.love+love,0,100);state.mood=clamp(state.mood+Math.ceil(love/2),0,100);state.dateToday=true;state.relationship.lastDateDay=state.day;const start=timeLabel();advanceClock(a.minutes,{awake:true,source:`Hẹn ${p.name}`});log(`Dành thời gian với ${p.name} từ ${start} đến ${timeLabel()}; tình cảm +${love}, mất ${fmtDuration(a.minutes)}.`);save();renderGame();if(state.events.length)setTimeout(showPendingEvent,120);}
function proposeMarriage(){const p=partner();if(!p)return;openModal(`<div class="modal-card"><h2>Bàn chuyện kết hôn với ${p.name}</h2><p class="muted">Đám cưới là một cột mốc cảm xúc và tài chính. Ngoài tiền, bạn cũng sẽ mất gần trọn một ngày cho ngày cưới.</p><div class="choice"><button data-wedding="60000000"><b>Đăng ký + tiệc nhỏ · 60 triệu</b><span class="mini muted">Gọn, giữ tiền cho cuộc sống sau cưới.</span></button><button data-wedding="180000000"><b>Đám cưới tiêu chuẩn · 180 triệu</b><span class="mini muted">Tăng uy tín xã hội, tiền mừng bù một phần.</span></button><button data-wedding="450000000"><b>Đám cưới lớn · 450 triệu</b><span class="mini muted">Chỉ hợp khi dòng tiền thật khỏe.</span></button></div><button class="btn" id="closeWedding" style="margin-top:10px">Để sau</button></div>`);document.querySelectorAll('[data-wedding]').forEach(b=>b.onclick=()=>wedding(Number(b.dataset.wedding)));document.querySelector('#closeWedding').onclick=closeModal;}
function wedding(cost){if(state.cash<cost)return toast('Chưa đủ tiền cho lựa chọn này.');const gift=Math.round(cost*rnd(45,75)/100);changeCash(-cost,'Chi phí đám cưới');changeCash(gift,'Tiền mừng cưới');state.relationship.status='married';state.relationship.love=clamp(state.relationship.love+12,0,100);state.reputation+=cost>=180000000?5:2;advanceClock(600,{awake:true,source:'Đám cưới'});milestone('marriage','Lập gia đình',`Bạn và ${partner()?.name||'người yêu'} chính thức kết hôn. Chi ${fmt(cost)}, nhận khoảng ${fmt(gift)} tiền mừng.`);log(`Kết hôn. Chi phí ròng khoảng ${fmt(cost-gift)}.`,'good');closeModal();save();renderGame();}
function haveChild(){if(state.relationship.status!=='married'||state.children.length>=3)return;openModal(`<div class="modal-card"><h2>Hai người muốn có thêm một thành viên?</h2><p class="muted">Game không tự sinh con. Đây là lựa chọn mở một mạch đời mới: viện phí, chi phí dài hạn và cả thời gian dành cho gia đình.</p><div class="choice"><button data-birth="28000000"><b>Bệnh viện tiêu chuẩn · khoảng 28 triệu</b></button><button data-birth="55000000"><b>Gói bệnh viện tư · khoảng 55 triệu</b></button></div><button class="btn" id="closeBirth" style="margin-top:10px">Chưa phải lúc</button></div>`);document.querySelectorAll('[data-birth]').forEach(b=>b.onclick=()=>birth(Number(b.dataset.birth)));document.querySelector('#closeBirth').onclick=closeModal;}
function birth(cost){if(state.cash<cost)return toast('Chưa đủ tiền dự phòng.');changeCash(-cost,'Sinh con & chăm sóc ban đầu');const name=pick(RANDOM_NAMES);state.children.push({name,birthDay:state.day,school:'standard',lastStage:-1});state.relationship.love=clamp(state.relationship.love+8,0,100);state.mood=clamp(state.mood+12,0,100);advanceClock(420,{awake:true,source:'Gia đình đón em bé'});milestone('child','Gia đình có thêm thành viên',`${name} chào đời. Từ hôm nay bạn không chỉ kiếm tiền cho bản thân nữa.`);log(`${name} chào đời; chi phí ban đầu ${fmt(cost)}.`,'good');closeModal();save();renderGame();}
function childStage(c){const age=childAge(c);if(age<3)return{label:'0–2 tuổi',monthly:6500000};if(age<6)return{label:'Mầm non',monthly:c.school==='premium'?15000000:9000000};if(age<18)return{label:'Đi học',monthly:c.school==='premium'?24000000:12000000};return{label:'Đại học / trưởng thành',monthly:c.school==='premium'?35000000:16000000};}
function borrow(){if(state.reputation<15)return;const amount=20000000,limit=loanLimit();if(state.debt+amount>limit)return toast('Đã gần hết hạn mức vay.');changeCash(amount,'Vay vốn');state.debt+=amount;advanceClock(45,{awake:true,source:'Làm hồ sơ vay'});log(`Vay thêm ${fmt(amount)} để xoay vốn.`);save();renderGame();}
function repay(){const amount=Math.min(10000000,state.debt,state.cash);if(amount<=0)return;changeCash(-amount,'Trả nợ');state.debt-=amount;advanceClock(15,{awake:true,source:'Trả nợ'});log(`Trả ${fmt(amount)} nợ.`);save();renderGame();}
function loanLimit(){return state.reputation<15?0:Math.round(Math.max(30000000,netWorth()*.38+state.reputation*800000));}

function monthlyExpenseEstimate(){let total=home().monthly+vehicle().monthly;for(const b of BUSINESSES)total+=(state.businesses[b.id]||0)*b.staff*b.salary;if(state.relationship.status==='dating')total+=(partner()?.monthly||0)*.35;else if(state.relationship.status==='married')total+=(partner()?.monthly||0);for(const c of state.children)total+=childStage(c).monthly;total+=state.debt*.013;return Math.round(total*livingMultiplier());}
function processBusinessDay(){let totalGross=0,totalOp=0,detail=[];for(const b of BUSINESSES){const c=state.businesses[b.id]||0;if(!c)continue;const sat=saturation(b.id),season=1+rnd(-8,10)/100,gross=Math.round(rnd(b.gross[0],b.gross[1])*c*sat*season*(trait().mods.biz||1)*(1+(state.managementBonus||0))),op=Math.round(gross*b.op);totalGross+=gross;totalOp+=op;detail.push(`${b.name}: ${fmt(gross-op)}`);}const net=totalGross-totalOp;if(net!==0){changeCash(net,'Lãi gộp kinh doanh trong ngày');state.stats.businessRevenue+=totalGross;}state.managementBonus=0;return{gross:totalGross,op:totalOp,net,detail};}
function processMonth(){if(state.day<state.nextHousingDue)return null;let items=[],total=0;const hCost=Math.round(home().monthly*livingMultiplier());total+=hCost;items.push(`Nhà ở ${fmt(hCost)}`);const vCost=Math.round(vehicle().monthly*livingMultiplier());total+=vCost;items.push(`Đi lại ${fmt(vCost)}`);let salary=0;for(const b of BUSINESSES)salary+=(state.businesses[b.id]||0)*b.staff*b.salary;salary=Math.round(salary*livingMultiplier());if(salary){total+=salary;items.push(`Lương ${totalStaff()} người ${fmt(salary)}`);}if(state.relationship.status==='dating'){const fam=Math.round((partner()?.monthly||0)*.35*livingMultiplier());total+=fam;items.push(`Chi tiêu chung khi hẹn hò ${fmt(fam)}`);}else if(state.relationship.status==='married'){const fam=Math.round((partner()?.monthly||0)*livingMultiplier());total+=fam;items.push(`Sinh hoạt vợ/chồng ${fmt(fam)}`);}let kids=0;for(const c of state.children)kids+=childStage(c).monthly;kids=Math.round(kids*livingMultiplier());if(kids){total+=kids;items.push(`Con cái ${fmt(kids)}`);}const interest=Math.round(state.debt*.013);if(interest){total+=interest;items.push(`Lãi vay ${fmt(interest)}`);}changeCash(-total,'Chi phí định kỳ 30 ngày');state.nextHousingDue=state.day+MONTH_DAYS;news('Đến kỳ chi tiêu',`${items.join(' · ')}. Tổng ${fmt(total)}.`,'Tài chính');state.monthlyReport={day:state.day,total,items};return total;}
function handleHealth(){if(state.health>0)return;state.hospitalVisits++;const cost=Math.min(Math.max(3000000,Math.round(Math.max(0,netWorth())*.015)),18000000);changeCash(-cost,'Viện phí vì kiệt sức');state.health=38;state.mood=clamp(state.mood-12,0,100);state.events.unshift({title:'Cơ thể buộc bạn dừng lại',text:`Bạn kiệt sức và phải vào viện. Viện phí khoảng ${fmt(cost)}. Game không cấm cày đêm, nhưng cơ thể sẽ có giới hạn.`,type:'Sức khỏe',choices:[{label:'Từ mai sống chậm lại một chút',effect:{health:6,mood:4}}]});}
function processChildren(){for(const c of state.children){const age=childAge(c);if(age!==c.lastStage&&(age===3||age===6||age===18)){c.lastStage=age;state.events.push({title:`${c.name} bước sang một chặng mới`,text:age===3?`${c.name} đã tới tuổi mầm non. Tiền học và thời gian đưa đón bắt đầu thành một phần thật của gia đình.`:age===6?`${c.name} vào lớp 1. Từ đây chi phí học hành theo gia đình trong nhiều năm.`:`${c.name} đã 18 tuổi và đứng trước lựa chọn học đại học hay đi làm.`,type:'Gia đình',choices:[{label:'Chọn hướng vừa sức gia đình',effect:{mood:4}},{label:'Đầu tư mạnh cho việc học',cost:age===18?80000000:30000000,effect:{mood:7,rep:1},setSchool:'premium'}]});}}}
function checkMilestones(){const nw=netWorth();if(state.cash>=1000000)milestone('million','Có 1 triệu đầu tiên','Lần đầu bạn có một khoảng đệm thay vì sống từng bữa.');if(nw>=100000000)milestone('hundred','Tài sản vượt 100 triệu','Bạn đã đi qua đoạn chỉ cần xe hỏng là lao đao cả tháng.');if(nw>=1000000000)milestone('billion','Tài sản ròng vượt 1 tỷ','Lần đầu chữ “tỷ” thực sự xuất hiện trong cuộc đời bạn.');if((state.stats.hoursWorked||0)>=100)milestone('hundredHours','100 giờ tự thân lao động','Bạn đã bán hơn 100 giờ đời mình để xây nền. Từ đây câu hỏi lớn dần là làm sao mua lại thời gian.');}
function checkStoryBeats(){const nw=netWorth();if(!state.storyFlags.oldBike&&state.day>=5&&state.cash>=700000){state.storyFlags.oldBike=true;state.events.push({title:'Một chiếc xe đạp cũ trước cửa chợ',text:'Chú Ba ve chai nói có người quen bán chiếc xe đạp cũ 900.000đ. Không bắt buộc mua, nhưng đây là lúc bạn hiểu tài sản nhỏ có thể đổi cả cách dùng thời gian.',type:'Cơ hội',choices:[{label:'Ghi nhớ, để dành tiền',effect:{mood:1}},{label:'Mua luôn nếu đủ tiền',cost:900000,setVehicle:'bike',effect:{rep:1}}]});}
 if(!state.storyFlags.delivery&&vehicle().tier>=2&&state.stats.jobsDone>=7){state.storyFlags.delivery=true;state.events.push({title:'Cô Năm nhớ mặt bạn',text:'Sau nhiều lần đúng giờ, cô Năm giới thiệu bạn cho vài quán khác. Từ đây việc giao cơm, ship shop và các đơn gấp xuất hiện thường hơn.',type:'Quan hệ',choices:[{label:'Cảm ơn và nhận mối',effect:{rep:3,mood:2}}]});}
 if(!state.storyFlags.love&&state.relationship.status==='single'&&state.day>=18&&state.health>=50&&state.reputation>=(trait().id==='quanHe'?5:7)&&nw>=8000000){state.storyFlags.love=true;const pool=PARTNERS.filter(p=>state.pref==='any'||p.gender===state.pref),p=pick(pool.length?pool:PARTNERS);state.events.push({title:'Một buổi sinh nhật của người quen',text:`Bạn vốn định ở nhà để tiết kiệm, nhưng cuối cùng vẫn đi. Ở đó bạn nói chuyện khá lâu với ${p.name} — ${p.trait.toLowerCase()}, ${p.desc.toLowerCase()} Không có định mệnh; chỉ là lần đầu sau một thời gian mưu sinh, bạn thấy mình có chỗ trong lịch cho một người khác.`,type:'Tình cảm',partnerId:p.id,choices:[{label:'Xin số liên lạc',startDating:true,effect:{love:22,mood:5}},{label:'Làm quen chậm thôi',startDating:true,effect:{love:14,mood:3}}]});}
 if(!state.storyFlags.parents&&nw>=250000000){state.storyFlags.parents=true;state.events.push({title:'Cuộc gọi về nhà',text:'Mẹ gọi nói mái nhà ở quê bắt đầu dột. Hồi trước bạn chỉ biết im lặng. Bây giờ lần đầu bạn có khả năng thật sự giúp.',type:'Gia đình',choices:[{label:'Gửi 20 triệu sửa nhà',cost:20000000,effect:{mood:10,rep:2}},{label:'Gửi 8 triệu sửa phần cấp thiết',cost:8000000,effect:{mood:5}},{label:'Hẹn khi dòng tiền ổn hơn',effect:{mood:-3}}]});}}
function maybeRandomEvent(){if(Math.random()>.26)return;const events=[
 ()=>({title:'Xe trục trặc giữa đường',text:'Chiếc xe có dấu hiệu hư vặt. Sửa ngay mất tiền và một ít thời gian; để lại thì tinh thần không yên.',type:'Đời thường',choices:[{label:'Sửa đàng hoàng',cost:vehicle().tier>=4?3500000:650000,time:90,effect:{health:1}},{label:'Tạm chạy tiếp',effect:{mood:-2,health:-1}}]}),
 ()=>({title:'Khách chuyển khoản dư',text:'Một khách cũ chuyển dư 500.000đ. Không ai phát hiện ngay.',type:'Lựa chọn',choices:[{label:'Chuyển trả lại',time:10,effect:{rep:4,mood:3}},{label:'Im lặng coi như may',gain:500000,effect:{rep:-5,mood:-1}}]}),
 ()=>({title:'Một mối giao hàng bất ngờ',text:'Người quen gọi hỏi bạn có thể giao gấp một bộ hồ sơ trước giờ nghỉ trưa. Đây là dạng việc trả cho độ gấp chứ không cho số giờ.',type:'Cơ hội',choices:[{label:'Nhận mối và dành 45 phút xử lý',gain:rnd(220000,480000),time:45,effect:{rep:2,health:-1}},{label:'Từ chối vì lịch đã kín',effect:{mood:1}}]}),
 ()=>({title:'Bạn cũ hỏi mượn tiền',text:'Một người bạn lâu năm nhắn mượn 5 triệu vì gia đình có việc gấp.',type:'Quan hệ',choices:[{label:'Cho mượn 5 triệu',cost:5000000,time:20,effect:{mood:4,rep:1}},{label:'Gửi 1 triệu coi như giúp',cost:1000000,time:10,effect:{mood:2}},{label:'Từ chối vì mình cũng đang xoay vốn',effect:{mood:-1}}]}),
 ()=>({title:'Video quán được chia sẻ',text:'Một khách quay clip ngắn về cơ sở của bạn và bất ngờ có nhiều người xem.',type:'Kinh doanh',onlyBiz:true,choices:[{label:'Dành 2 giờ chớp cơ hội khuyến mãi',cost:3000000,gain:6500000,time:120,effect:{rep:3,mood:3}},{label:'Giữ vận hành bình thường',gain:1800000,effect:{rep:1}}]}),
 ()=>({title:'Nhân viên xin nghỉ về quê',text:'Bạn có thể cho nghỉ có lương một phần hoặc giữ đúng nguyên tắc.',type:'Nhân sự',onlyBiz:true,choices:[{label:'Hỗ trợ 1 triệu',cost:1000000,time:15,effect:{rep:2,mood:2}},{label:'Xử lý theo quy định',time:10,effect:{rep:0}}]})
 ];let tries=0,e;do{e=pick(events)();tries++;}while(e.onlyBiz&&!businessCount()&&tries<8);if(e.onlyBiz&&!businessCount())return;state.events.push(e);}
function nextProgressGoal(){if(vehicle().tier<2)return{title:'Mua chiếc xe máy đầu tiên',text:'Xe máy không chỉ mở việc giao hàng; nó còn rút ngắn phần di chuyển, tức là bạn bắt đầu mua lại từng phút của ngày.'};if(!businessCount())return{title:'Từ tự làm sang thuê người',text:'Khi có vốn, mở cơ sở nhỏ để tiền bắt đầu chạy dù bạn đang ăn, tập hoặc hẹn hò.'};if(state.relationship.status==='single')return{title:'Ổn định rồi cuộc sống mới mở rộng',text:'Tình cảm sẽ đến qua sự kiện khi bạn đủ khỏe, có uy tín và đã thoát cảnh sống từng bữa.'};if(state.relationship.status==='dating')return{title:'Tiền và thời gian bắt đầu cạnh tranh',text:'Một đơn lời 1 triệu lúc 18:00 có thể trùng đúng giờ hẹn. Game không có đáp án đúng.'};if(state.relationship.status==='married'&&!state.children.length)return{title:'Gia đình là lựa chọn, không phải nghĩa vụ',text:'Bạn có thể sống hai người, hoặc chủ động có con khi nhà ở và dòng tiền phù hợp.'};if(netWorth()<1000000000)return{title:'Bước lên ngành doanh thu cao hơn',text:'Cơ sở nhỏ sẽ bão hòa. Muốn nuôi mức sống mới, bạn phải đổi cấp ngành chứ không nhân bản vô hạn.'};return{title:'Từ làm giàu sang mua lại cuộc đời',text:'Tiền đã lớn. Late game là chọn hệ thống nào chạy thay bạn và bạn muốn dành thời gian cho ai.'};}
function showPendingEvent(){if(!state?.events?.length)return;const ev=state.events[0];openModal(`<div class="modal-card"><span class="tag ${ev.type==='Tình cảm'?'good':ev.type==='Cơ hội'?'warn':''}">${esc(ev.type||'Sự kiện')}</span><h2 style="margin-top:8px">${esc(ev.title)}</h2><p>${esc(ev.text)}</p><div class="choice">${ev.choices.map((c,i)=>`<button data-choice="${i}"><b>${esc(c.label)}</b><span class="mini">${c.cost?`Chi ${fmt(c.cost)} · `:''}${c.gain?`Nhận ${fmt(c.gain)} · `:''}${c.time?`⏱ ${fmtDuration(c.time)}`:''}</span></button>`).join('')}</div></div>`);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>resolveEvent(Number(b.dataset.choice)));}
function resolveEvent(i){const ev=state.events[0],c=ev?.choices?.[i];if(!c)return;if(c.cost&&state.cash<c.cost){toast('Chưa đủ tiền cho lựa chọn này.');return;}if(c.cost)changeCash(-c.cost,ev.title);if(c.gain)changeCash(c.gain,ev.title);if(c.effect){if(c.effect.health)state.health=clamp(state.health+c.effect.health,0,100);if(c.effect.mood)state.mood=clamp(state.mood+c.effect.mood,0,100);if(c.effect.rep)state.reputation+=c.effect.rep;if(c.effect.love)state.relationship.love=clamp(state.relationship.love+c.effect.love,0,100);}if(c.time)advanceClock(c.time,{awake:true,source:ev.title});if(c.setVehicle){state.vehicle=c.setVehicle;if(c.setVehicle==='bike')news('Có chiếc xe đầu tiên','Chiếc xe đạp cũ không sang, nhưng từ đây một số việc giao gần sẽ bắt đầu xuất hiện.','Tài sản');}if(c.startDating){state.relationship.status='dating';state.relationship.partnerId=ev.partnerId;state.relationship.metDay=state.day;milestone('dating','Có người bước vào cuộc sống',`Bạn bắt đầu tìm hiểu ${partner()?.name||'một người mới'}. Từ đây tiền không còn là tài nguyên duy nhất; lịch của bạn cũng phải có chỗ cho một người khác.`);}if(c.setSchool&&state.children.length)state.children[state.children.length-1].school=c.setSchool;log(`${ev.title}: ${c.label}.`);state.events.shift();refreshJobs(true);save();closeModal();renderGame();if(state.events.length)setTimeout(showPendingEvent,150);}
function finishRun(reason){const scoreBase=Math.max(1,Math.floor(state.day/60)+state.milestones.length+Math.floor(Math.max(0,netWorth())/500000000)),score=Math.max(1,Math.round(scoreBase*(trait().mods.career||1)));meta.runs++;meta.careerPoints+=score;meta.history.unshift({name:state.name,day:state.day,net:netWorth(),score});meta.history=meta.history.slice(0,30);syncTraitUnlocks(meta);saveMeta();state.status='ended';save();openModal(`<div class="modal-card"><h2>Tổng kết hành trình</h2><p>${esc(reason)}</p><div class="grid3"><div class="stat"><span>Ngày</span><b>${state.day}</b></div><div class="stat"><span>Tài sản ròng</span><b>${fmt(netWorth())}</b></div><div class="stat"><span>Điểm sự nghiệp</span><b>+${score}</b></div></div><div class="goodbox">Những lối sống mới mở bằng Điểm sự nghiệp dùng ở hành trình kế tiếp. Ô lưu này vẫn còn để xem lại hoặc xóa.</div><button class="btn primary" id="backSlots" style="margin-top:10px">Về 3 ô lưu</button></div>`);document.querySelector('#backSlots').onclick=()=>{closeModal();startScreen();};}
function openModal(html){closeModal();modal=document.createElement('div');modal.className='modal';modal.innerHTML=html;document.body.appendChild(modal);}
function closeModal(){if(modal){modal.remove();modal=null;}}
function closeGame(){save();window.parent.postMessage({type:'doi-lap-nghiep-close'},'*');}
function toast(text){document.querySelector('.toast-local')?.remove();const t=document.createElement('div');t.className='toast-local';t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2400);}

startScreen();
})();
